datacommonsorg/website

static/css/draw.css, static/js/chart/draw.ts
* added tick formatting
* add dots for smaller datasets
* zero-index the y-axis. I find this gives a better sense of scale.
=> Add more styling to line charts

static/css/draw.css, static/js/chart/draw.ts, static/js/dev.js, static/js/place_overview.jsx, static/tsconfig.json
demo link: https://screenshot.googleplex.com/jEek0HQ2Ga4
=> Use d3 for group bar chart

static/js/chart/draw.ts
demo: https://screenshot.googleplex.com/UnqD8sJbFpm
=> Remove unused functions; Use new legend creation for line chart

static/js/chart/draw.ts, static/js/dev.js
Also:
-  Update getColorFn take the domain list
-  Remove deprecated functions
demo: https://screenshot.googleplex.com/EOnWvXYhEF3
=> Use d3 for stack bar chart

static/js/chart/draw.test.ts, static/js/chart/draw.ts, static/js/dev.js
demo: https://screenshot.googleplex.com/6XcyoEtz9Rp
=> Use d3 for single bar chart

tools/pv_tree_generator/dc_request.py
Fix the problem in get_triples function in dc_request that sometimes only part of the triples are read.
=> fix the problem of partly read triples

static/css/draw.css, static/css/place_overview.css, static/js/chart/draw.ts, static/js/place_overview.jsx
- Update axes styles to follow the line chart styling
- Add padding before the left hand bar charts (paddingOuter)
- Update chart colors to use `[Spectral](https://github.com/d3/d3-scale-chromatic#schemeSpectral)`
Remove red borders around charts since they're not click targets
Screenshot: https://screenshot.googleplex.com/qmDOVbv3rri
=> Chart styling updates

cloudbuild.py.yaml
This has the benefit of triggering only on python file changes
=> Use clodubuild instead of Dockerfile for presubmit test

static/css/draw.css, static/css/place_overview.css, static/js/chart/draw.test.ts, static/js/chart/draw.ts, static/js/dev.js, static/js/place_overview.jsx, static/package-lock.json, static/package.json, static/tsconfig.json, templates/dev.html
A set of changes to update chart drawing to use the d3 library
=> Merge d3 into master

static/js/chart/draw.ts
Loosely based on spectral, but with some light colors removed and with a
fix for 1 or 2 categories.
=> Update chart colors

server/main.py, server/templates/base.html, server/templates/search.html, static/css/base.css, static/css/search.css, static/js/kg.js
Only added to browser pages. Will add the searchbox on the factcheck pages when we redo the headers there.
Demo: https://screenshot.googleplex.com/uOzKxx6NAbu
=> Replace search box with CSE based search

server/__init__.py, server/configmodule.py, server/routes/api/__init__.py, server/routes/api/place.py, server/routes/sitemap.py, server/services/datacommons.py, server/templates/sitemap.html, server/tests/sitemap_test.py
demo: https://41881275dbea.ngrok.io/sitemap
https://41881275dbea.ngrok.io/sitemap/country/USA
=> Add sitemap

server/main.py, server/routes/api/place.py, server/templates/place_overview.html, server/tests/api/place_test.py, static/js/place_overview.js, static/js/place_overview.jsx
This also
- deprecate the old child places api which only returns dcid.
- fix the containing place charts due to place type mismatch.
- add unittest for api.
=> Add child places in place overview page

server/__init__.py, server/routes/redirects.py, server/routes/tools.py, server/templates/tools/base.html, server/templates/tools/download.html, server/templates/tools/download_bulk.html, server/templates/tools/explore.html, server/templates/tools/scatter.html, server/tests/gni_test.py, static/js/download.js, static/js/gni.js, static/js/menu.js
Moves
gni -> /tools/timeline
scatter -> /tools/scatter
=> Add redirects for tool pages

server/__init__.py, server/routes/redirects.py, server/routes/tools.py, server/templates/tools/base.html, server/templates/tools/download.html, server/templates/tools/download_bulk.html, server/templates/tools/explore.html, server/templates/tools/scatter.html, server/tests/redirects_test.py, server/tests/tools_test.py, static/js/download.js, static/js/gni.js, static/js/menu.js
browser.dc.org/gni -> dc.org/tools/timeline
browser.dc.org/scatter -> dc.org/tools/scatter
=> Add redirects for tools

server/templates/dev.html, static/css/gni.css, static/js/dev.ts, static/js/pv_tree.tsx, static/js/util.js, static/js/util.test.js, static/webpack.config.js
- build the gni menu using react js
- add the function of updating the url once the statvar is selected
=> build the menu, update url upon click

server/templates/base.html, server/templates/tools/scatter.html, server/tests/redirects_test.py, server/tests/tools_test.py, static/css/base.scss, static/css/base_tools.scss, static/css/scatter.scss, static/js/scatter.js, static/webpack.config.js
* Migrate from jquery 1.11 to the base version from base.html (3.5.1)
* Remove jquery.ui
* Cleaned up the plot selection form
* Cleaned up dialog
* Added welcome message
=> Update styling on the scatter tool

server/chart_config.json, server/routes/api/chart.py, static/js/place_template.tsx, static/js/stats_var.ts
=> Add some sample international data to show case the effect

server/templates/dev_menu.html, static/css/dev_menu.scss, static/js/tools/dev_menu.ts, static/js/tools/timeline_chart.tsx, static/js/tools/timeline_page.tsx
Also fix various type and lint errors
=> Fix and re-organize timeline Page component

static/js/tools/timeline_chart.tsx, static/js/tools/timeline_page.tsx, static/js/tools/timeline_util.js
- pass perCapita to ChartRegion
- add the deleteStatVar function of ChartRegion
- resolve the issue that the last place chip cannot be deleted
=> Complete event propagation from Page to ChartRegion

static/js/tools/timeline_util.js, static/js/tools/timeline_util.test.ts
=> set default statvar = Count_Person when place is defined but statvar is empty

static/js/tools/statsvar_menu.tsx, static/js/tools/timeline_info.tsx, static/js/tools/timeline_page.tsx, static/js/tools/timeline_util.js, static/js/tools/timeline_util.test.ts
- add the static component when the page loads, replace the old url with the new ones.
- in the url, join the node path by " ' " instead of " , " , because " , " is used in the income range such as "Less than 9,999 $"
=> add static component when the page loads

static/js/chart/draw.ts
=> Revert the line chart y axis tick and line styling

server/main.py, server/routes/api/place.py, server/tests/api/place_test.py, static/css/place/place.scss, static/js/place.ts, static/js/place_template.tsx
- Do not add link to continent.
- Do not show map and ranking for non-US places.
- Do not include ranking for continent.
=> Update UI for ranking and continent

server/main.py, server/templates/search_dc.html
Revert some changes from #31 to alleviate searching while we get CSE to completely index our pages.
Helps with bug #92
=> Add back old search functionality

static/js/chart/draw.ts, static/js/dev.ts
=> Wrap text for gni in-chart legend

cloudbuild.deploy.yaml, cloudbuild.npm.yaml, cloudbuild.py.yaml, run_test.sh
* add cmd flags to to support the various options
No rush on this, Bo. Just wanted to get this out, but can merge when we have more time to triage issues that come up.
Also, how can I test the cloudbuild yamls?
=> Consolidate commands to run tests into the script

static/js/place/place_template.tsx
=> Place page: do not show topic on menu if there are no sub-topic charts

static/js/place/place_template.tsx, static/js/shared/data_fetcher.ts
- When there is no data for containing or contained places, use similar places chart.
=> [Place Page] handle various missing data scenarios

static/js/tools/statsvar_menu.tsx, static/js/tools/timeline_info.tsx, static/js/tools/timeline_util.ts
Do not render if the node is an invalid value node, even if it can be expanded
=> fix the PVtree node filtering logic

static/js/chart/draw.ts, static/js/shared/data_fetcher.test.ts, static/js/shared/data_fetcher.ts, static/js/tools/timeline_chart.tsx
=> add source info to the chart

server/__init__.py, server/tests/browser_test.py, server/tests/redirects_test.py
Should not access real GCS in the tests. This allows to add selenium test
=> Use mock placeid2dcid config in TEST env

server/templates/tools/choropleth.html, static/css/tools/choropleth.scss, static/js/tools/choropleth/choropleth.ts, static/js/tools/choropleth/choropleth_template.tsx, static/package.json, static/webpack.config.js
No nice formatting, but includes working E2E integration.
=> Initial commit to power Choropleth Client. 

tools/geojson_simplifier/plotter.py
Script to plot a comparison between the data downloaded by script in #192  and simplified in #194 .
=> Added plotting tool to visualize changes.

static/js/chart/draw.ts, static/js/shared/data_fetcher.ts, static/js/tools/timeline_util.ts
- fix the problem when two time series has no intersection, the returned dataset would be empty
=> use union of dates instead of intersection when multiple statsVars are selected

static/index.d.ts, static/jest.config.js, static/js/chart/base.ts, static/js/chart/draw.test.ts, static/js/chart/draw.ts, static/js/dev.ts, static/js/tools/timeline_chart.tsx, static/js/tools/timeline_chart_region.tsx, static/js/tools/timeline_page.test.tsx, static/js/tools/timeline_page.tsx, static/js/tools/timeline_search.tsx, static/package-lock.json, static/package.json, static/setup.js
- factored out non draw chart functions to base module
- make jest config file
=> Add e2e react test to verify chart is rendered.

static/js/tools/commons.ts, static/js/tools/statsvar_menu.test.js, static/js/tools/statsvar_menu.tsx, static/js/tools/timeline_info.tsx, static/js/tools/timeline_page.test.tsx, static/js/tools/timeline_page.tsx, static/js/tools/timeline_util.test.ts, static/js/tools/timeline_util.ts
- add the StatsVarFilterInterface for filtering the statsVar
- add the class UrlTimeline for keeping and updating information about statsVar, placeId, perCapita etc
- rename function handleHashChange to OnUpdate
- simplify the logic of finding the selected nodes in the pv-tree
- add licences
=> add interface and classes for refactoring statsVar menu

static/js/tools/statsvar_menu.test.js, static/js/tools/statsvar_menu.tsx, static/js/tools/timeline_chart.tsx, static/js/tools/timeline_chart_region.tsx, static/js/tools/timeline_page.test.tsx, static/js/tools/timeline_page.tsx, static/js/tools/timeline_search.tsx, static/js/tools/timeline_util.test.ts, static/js/tools/timeline_util.ts
- remove onHashChange in page component
- remove update url related functions in statsVar menu
- pass functions for adding/removing statsVar from page to statsVar menu
I'll remove url related function in searchBar and chart in the next PR.
=> remove onHashChange in timeline page component

static/js/tools/choropleth/choropleth.ts
This is an experimental PR that makes a small fix by addressing a TODO. @beets
=> Addressed TODO to make paths relative.

webdriver-chrome/Dockerfile, webdriver-chrome/README.md, webdriver-chrome/cloudbuild.yaml
This PR is building a docker image based on python;3.7-slim, but with chrome and chromedriver preinstalled.
=> Add couldbuild file for webdriver-chrome

static/js/tools/choropleth/choropleth.tsx, static/webpack.config.js
For review @beets @IanCostello @jeffreyoldham .
=> Added better USA projection and debugged references

static/js/tools/timeline_util.test.ts, static/js/tools/timeline_util.ts
These functions are not used anymore after refactoring.
=> remove url related functions in Timeline tool

README.md
Add instructions to setup web browser and webdriver in README.
=> Add webdriver info in README

server/routes/api/choropleth.py
@beets fixed according to your request.
=> Fixed issue with reversed() function on server.

.gitignore, cloudbuild.screenshot.yaml, server/routes/place.py
This somehow changes the placeid2dcid search url to:  /place/api/placeid2dcid/<placeid>, which has an additional /place prefix. The actual endpoint should be /api/placeid2dcid/<placeid>
=> Remove trailing slash for place page; Fix issue for screenshot notifier.

cloudbuild.screenshot.yaml, static/css/kg.scss
Should write env variable to /workspace/*.txt instead of set it as env variable.
=> fix cloudbuild screenshot yaml error

server/webdriver_tests/place_explorer_test.py, server/webdriver_tests/scatter_test.py, server/webdriver_tests/screenshot/screenshot_test.py
* Add scatter tool test
* Move place explorer on top of the screenshot part.
=> Add scatter tool test

static/js/tools/__snapshots__/statsvar_menu.test.tsx.snap, static/js/tools/__snapshots__/timeline_page.test.tsx.snap, static/js/tools/statsvar_menu.tsx
move the onClick function to the statsVar label + right caret
=> Fix #247, Expand menu when the text in the statsVar menu is clicked

cloudbuild.deploy.yaml
Need to extend timeout for cloudbuild as well
=> Add timeout option to cloudbuild

static/js/chart/draw.ts
set the format the y-axis tick label when the number is negative
=> fix y-axis tick label format

server/routes/api/place.py, server/routes/api/stats.py, server/routes/place.py, static/js/place/place_template.tsx
* Update ranking labels so the rank direction is clearer
* use geoOverlaps for child places, to get some zip codes which might go outside of the containing place's bounds
=> Place page small fixes

server/routes/api/place.py, static/js/place/place_template.tsx
=> Add current place to nearby place list and filter/sort nearby places

server/routes/api/place.py, server/webdriver_tests/place_explorer_test.py
=> Use Response for api handlers in place.py, and use helpers for other

static/js/shared/data_fetcher.test.ts, static/js/shared/data_fetcher.ts
Set value to 0 when there is missing data when getting time groups data
=> handle missing data when getting time groups

server/chart_config.json
Move the inequality charts to be below health
=> move inequality charts below health

static/css/draw.scss, static/js/chart/base.ts, static/js/chart/draw.ts, static/js/place/place_template.tsx, static/js/shared/data_fetcher.ts
=> Add link to group bar chart x tick when it is a place

server/routes/api/chart.py, server/tests/chart_test.py, static/js/shared/data_fetcher.test.ts, static/js/shared/data_fetcher.ts
When getting data for a chart, get it for the latest date for which there is data for all the stat vars in the chart. If there is no such date, choose the latest date.
=> data for latest data with all data

server/__init__.py, server/routes/api/place.py, server/routes/api/ranking.py, server/routes/ranking.py, server/templates/ranking.html, server/webdriver_tests/screenshot/screenshot_test.py, static/css/ranking.scss, static/js/place/place_template.tsx, static/js/ranking/ranking.ts, static/js/ranking/ranking_page.tsx, static/js/ranking/ranking_table.tsx, static/js/shared/stats_var_titles.ts, static/js/shared/util.js
* Removed support for multiple stat var (since it's not used at the moment)
* Fully specify params in the url path (changed the URL pattern as well)
* Cleaned up some unused functions
* Added error handling
* Move some static page rendering to the client
=> Add links to ranking pages from place overview table

server/webdriver_tests/place_explorer_test.py, static/css/place/place.scss, static/js/place/place_template.tsx
If the chart is not a line chart and does not have time as its axis, put in brackets in the title what date the data in the chart is from
=> Add date of observations to charts

static/js/place/place_template.tsx
screenshot: https://staging.datacommons.org/dev/screenshot/8defc14
=> Use provenance domain from data in place page source footer

server/chart_config.json, static/js/place/place.ts, static/js/place/place_template.tsx, static/js/shared/data_fetcher.test.ts, static/js/shared/data_fetcher.ts
Remove continent from parent places.
Remove null data from bar chart.
Add % as unit for unemployment rate.
=> Fix some missing data issue

server/chart_config.json, server/webdriver_tests/screenshot/screenshot_test.py, static/js/chart/draw.ts, static/js/dev.ts, static/js/place/place_template.tsx
* fixes layout for missing charts (all charts in a section should flow together)
* fix overflowing x-axis tick labels when there are long place names which are hyphenated
* drop line charts if there is only a single data point
* rename population density
=> [place page] a bunch of small fixes

server/chart_config.json, static/js/place/place_template.tsx
relatedChart field contains the information for derived chart. It contains "scale" and "denominator" fields to indicate how scaling should be done
=> Add relatedChart field in chart config to indicate whether related chart can be scaled

server/routes/api/chart.py, server/tests/chart_test.py
added new endpoint api/chart/geojson/<path:dcid> which:
- takes the given dcid and gets the geojson for the list of places that are one level down from it
=> add endpoint for getting geojson for charts

server/routes/api/place.py, static/js/place/place.ts
=> Use cohort city and county for US city county similar places

server/templates/place.html, static/css/place/place.scss, static/js/chart/base.ts, static/js/place/chart.tsx, static/js/place/chart_embed.tsx, static/js/shared/util.js, static/js/tools/timeline_chart_region.tsx, static/js/tools/timeline_util.ts, static/package-lock.json, static/package.json
Creates a new component for showing a modal with instructions to embed charts / download data. This is attached to each Chart component, but only updated with data when the embed link is clicked.
Sending this sooner for early feedback / testing.
TODOs:
* add tests (unit tests for data group -> csv, screenshot + webdriver test for modal)
* complete implementation of csv for datapoints
* add svg as an image (convert to data URI)
* include title, legend as part of svg
=> [place] V1 of Chart Embed

server/routes/api/chart.py, server/tests/chart_test.py
add another property in the returned object from api/chart/choroplethdata/<path:dcid> to return the number of data points we have for a specific statvar/denom combination
=> add num data points to endpoint

server/chart_config.json, server/webdriver_tests/place_explorer_test.py, static/js/chart/draw.ts, static/js/place/chart_block.tsx, static/js/place/types.ts
* Updated titles of the charts based on our discussion today
* Added explicit unit / scaling factor for related charts
* Added support for "grams" as a unit
=> [place] chart title updates

server/chart_config.json, server/webdriver_tests/place_explorer_test.py
Local screenshot: 
I noticed current staging/prod does not have years for median age so I did the same: 
Question: I had some changes to static/package.*json from just running `./run_npm.sh`. Is the correct thing to do: do not commit these changes unless you know what you are doing?
=> Add chart config for life expectancy.

server/routes/api/landing_page.py
=> Use early year data for denominator; Only overview page when there are few charts

server/routes/api/landing_page.py, static/js/place/chart_block.tsx, static/js/place/main.tsx
- Do not add related chart for non-US places.
- Do not have topic page link when there is no topic page.
=> Various fix for page with only overview category

server/routes/api/landing_page.py, server/templates/base.html, server/templates/place.html, static/css/place/place.scss, static/js/place/place.ts, static/js/place/place_highlight.tsx, static/js/place/types.ts
=> Add population as a subheading of the page

server/templates/base.html, server/templates/browser/kg_main.html, server/templates/static/about.html, server/templates/static/datasets.html, static/js/tools/timeline_info.tsx
Changes to datasets doc, about doc
=> documentation changes

server/templates/dev/dev.html, server/webdriver_tests/screenshot/screenshot_test.py, static/js/dev.ts
fixed ordering of screenshots (we have more than 9 now)
made dev charts more compact
=> fix screenshot tests

server/routes/api/place.py, server/services/datacommons.py
Note this has to be released together with: https://github.com/datacommonsorg/mixer/pull/328
=> Use related place api that now only supports same place type

server/routes/api/landing_page.py, static/js/place/chart_block.tsx
=> Allow similar place chart in USA page

server/routes/api/place.py, server/templates/place_landing.html, static/js/ranking/ranking_page.tsx, static/js/ranking/ranking_table.tsx
- Better message on pages with missing ranking data
- Add highlights to ranking from overview table
- Better precision handling for tables
- Add missing unit for income ranking links from place landing
=> Ranking page fixes

server/chart_config.json, static/js/shared/data_fetcher.test.ts, static/js/shared/stats_var_labels.ts, static/js/shared/stats_var_titles.ts
=> Create housing category and add housing unit (by race) charts

server/chart_config.json, server/lib/range.py, server/routes/api/landing_page.py, server/tests/chart_config_test.py, server/tests/range_test.py, static/js/shared/stats_var_labels.test.ts, static/js/shared/stats_var_labels.ts, static/js/shared/stats_var_titles.test.ts, static/js/shared/stats_var_titles.ts
Also make the aggregation function general.
=> Add housing unit by value chart

server/routes/api/landing_page.py, static/js/place/chart_block.tsx, static/js/place/ranking.tsx
=> Revive related charts for i18n places now we have similar place cohort

server/chart_config.json, static/js/shared/stats_var_labels.ts, static/js/shared/stats_var_titles.ts
=> Add housing unit by rental status chart

server/chart_config.json, static/js/shared/stats_var_labels.ts, static/js/shared/stats_var_titles.ts
Luckily this one won't need aggregation
=> Add housing unit by date built chart

static/js/tools/choropleth/choropleth.tsx
I have done some testing, and nothing seems to have broken.
Removing **shouldComponentUpdate => false** and deleting any this.forceUpdate() after this.setState().
=> Resolves issue where setState was not updating

tools/pv_tree_generator/build_tree.py
Besides "count", StatVars with mprop "incrementalCount" and "cumulativeCount" can also be used as denominators.
Thanks for reviewing.
=> [PV Tree Generator] allow incrementalCount and cumulativeCount

server/templates/place_landing.html, server/templates/static/about.html, server/templates/static/faq.html, server/webdriver_tests/place_explorer_test.py, static/css/base.scss, static/css/place/place.scss, static/js/place/chart.tsx, static/js/place/chart_embed.tsx, static/js/place/main.tsx, static/js/place/topic_menu.tsx, static/js/tools/__snapshots__/timeline_page.test.tsx.snap, static/js/tools/timeline_chart.tsx, static/js/tools/timeline_page.test.tsx
* fix modal dialog overflow issues for wide charts 
* added xl grid breakpoint for super wide windows, introduce 3rd column of charts then
* fix missing csv for choropleths
* fix sometimes missing source / date string
* hide explore more link at narrow widths
=> Small fixes

static/js/place/chart_block.tsx, static/js/place/main.tsx, static/js/place/place.ts
link to the right country for intl places
=> Fix intl ranking bug

server/cache.py, tools/clicker/main.py
It's tedious to clear the cache for every code commit.
=> Do not use redis cache for staging website

static/js/place/place_highlight.tsx
this was the original problem:
=> Handle place highlight undefined object error

server/templates/base.html, server/templates/static/homepage.html, static/css/static.scss
See:
https://github.com/datacommonsorg/docsite/pull/85
=> add link to blog

static/js/place/chart.tsx, static/js/place/chart_block.tsx, static/js/place/main.tsx, static/js/place/place.ts, static/js/place/types.ts
-  for geoJsonData props, replace type of unknown with newly created type of GeoJsonData
=> Update type for geojson data

Dockerfile, cloudbuild.py.yaml, cloudbuild.screenshot.yaml, run_server.sh, run_test.sh, server/__init__.py, server/main.py, server/requirements-core.txt, server/requirements-gcp.txt, server/requirements.txt
Instruction: https://cloud.google.com/profiler/docs/profiling-python#flexible-environment.
pip install google-cloud-profiler is very cubesome: https://cloud.google.com/profiler/docs/profiling-python#running_with_linux_alpine. Splitting the requirements.txt so non gcp env won't need to install it.
=> Try to add cloud profiler to website

cloudbuild.deploy.yaml, cloudbuild.py.yaml, cloudbuild.screenshot.yaml, run_test.sh, server/webdriver_tests/screenshot/screenshot_test.py, static/package-lock.json
Also "set -e" to exit immediately
=> Fix deploy error: need 'cd server' so requirements-core.txt can be found

static/js/place/chart_block.tsx
- On the overview page, replace the related place chart with choropleth chart if possible
=> add choropleth to overview

server/__init__.py, server/requirements.txt
Follow the instruction at: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/trace/cloud-trace-demo-app/app/app.py
Need to deploy to staging and verify
=> Add google cloud trace to website flask app

server/routes/api/landing_page.py
get_year() function takes a substantial portion of cpu time:
=> Get year in a faster way

server/lib/range.py, server/tests/range_test.py
Not necessary for actual logic but ensure tests always pass
=> sort range aggregration list for consistent result

server/app_prod.yaml
Have seen large latency when qps reaches above 50+, so increase the instance from 20 to 50.
=> Increase production to 50 instances

server/templates/place.html, server/templates/place_landing.html, server/templates/tools/scatter2.html, server/templates/tools/timeline.html
IMPORTANT:
- Submit this PR first to fix broken prod
- Remove https://screenshot.googleplex.com/6u7tnkaGARh8NDc from prod API key
- Make second API key for local dev, remove website restriction but create a request limit (or find a better way)
prod:
local (a bit flaky, had to add [localhost](https://screenshot.googleplex.com/6u7tnkaGARh8NDc) but still occasionally says IP not allowed to use the API key):
=> New API key

server/__init__.py, server/configmodule.py, server/routes/api/chart.py, server/routes/api/landing_page.py, server/routes/api/place.py, server/routes/dev.py, server/routes/factcheck.py, server/routes/place.py, server/routes/tools.py, server/services/datacommons.py, server/templates/place.html, server/templates/place_landing.html, server/templates/tools/scatter2.html, server/templates/tools/timeline.html, server/webdriver_tests/base_test.py
Local development will read maps api key from GCS secret manager in project: datcom-browser-staging. The developer need to have access.
Also remove some unused imports
=> Use dev maps api key for localhost

static/css/tools/choropleth.scss, static/js/tools/choropleth/choropleth.tsx, static/js/tools/choropleth/choropleth_template.tsx
- Few simple changes to make title a little more readable: remove underscore, few replacements in the words in the title. More efforts will be needed to make title readable
- Show the selected stat var in the menu when loading the choropleth tool for the first time
- keep the stat var menu open and keep the current option selected when navigating to different place (ie. when clicking on a region in the choropleth or when clicking a breadcrumb)
=> Choropleth Tool Improvements

server/cache.py, server/configmodule.py, server/services/datacommons.py
This version was deployed to factcheck-sandbox last night to mitigate the outage. Checking it in for record keeping.
=> remove secret key, update to redis for factcheck-sandbox

localization.md, static/js/i18n/compiled-lang/en.json, static/js/i18n/place.json, static/js/place/chart.tsx, static/js/place/chart_block.tsx, static/js/place/chart_embed.tsx, static/js/place/page_subtitle.tsx, static/js/place/parent_breadcrumbs.tsx, static/js/place/ranking.tsx, static/js/place/util.ts
- tighten descriptions
- update some id's
- small refactors so entire strings can be sent for translations as a unit
=> Small updates to place UI strings

static/js/browser/kg.js, static/js/shared/util.js
=> Remove deprecated/initial implementation of place page in graph browser

server/__init__.py, server/routes/api/browser.py, server/services/datacommons.py, static/js/browser/kg.js, static/js/shared/util.js, static/package-lock.json, static/package.json, static/webpack.config.js, tools/pv_tree_generator/util.py
This is to align the behavior with place and timeline tools. It also prepares isolated mixer for website setup, so a website server uses a dedicated mixer server. 
Tested locally and do not see performance degradation. Will verify after staging push.
=> Move all the client side api call to server side

.gitmodules, README.md
This will make it easy to build and deploy website and mixer together.
This is a good read: https://gist.github.com/gitaarik/8735255#file-git_submodules-md
=> Add mixer repo as a submodule of website repo

deployment/website.yaml.tmpl, server/main.py
GKE use readiness check to to pod management and load balancing:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
=> website app /healthz endpoints used for kubernetes health check

deployment/gke/README.md, deployment/gke/create_cluster.sh, deployment/gke/create_robot_account.sh, deployment/gke/download_robot_key.sh, deployment/gke/first_time_setup.sh, deployment/gke/setup_config_cluster.sh
Need to make sure project and cluster are correct.
Need to make sure the local robot keys are correct.
Need to update the yaml files before a new deployment.
=> Fix the steps for create standalone cluster

babel-mapping.ini, localization.md, server/l10n/messages.pot, server/routes/api/place.py, server/templates/ranking.html, static/js/chart/draw.ts, static/js/i18n/compiled-lang/en/place.json, static/js/i18n/strings/en/place.json, static/js/place/page_subtitle.tsx, static/js/ranking/ranking_page.tsx, static/js/ranking/ranking_table.tsx
also adds a few straggler strings on the place pages
=> [i18n] Markup and extract strings for place ranking pages

gke/setup_esp.sh, script/deploy_gke.sh
This is a follow up with https://github.com/datacommonsorg/mixer/pull/448
=> Update mixer grpc descriptor download path

.gitignore, build/ci/cloudbuild.deploy.yaml, deploy/gke/autopush.yaml, deploy/overlays/autopush/kustomization.yaml, gke/README.md, script/deploy_gke.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/website/780)
=> Add config for autopush and add it as a website deploy step

build/webdriver-chrome/README.md, build/webdriver-chrome/cloudbuild.yaml, deploy/base/deployment.yaml, deploy/base/kustomization.yaml, deploy/gke/prod.yaml, deploy/overlays/dev/patch_args.yaml, developer_guide.md, gke/README.md, gke/setup_robot_account.sh, gke/setup_ssl.sh, run_server.sh, run_test.sh, script/deploy_gke.sh, static/js/shared/util.js
- Move schema mapping as config
- Use branch BT table
- grpc descriptor path change
- Reduce Memory/CPU change request size based on monitoring, this prepares for auto-scaling
- New cluster deploy script
- SSL domain includes all sub-domains
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/website/777)
=> Various updates based on recent mixer change

build/Dockerfile, deploy/base/deployment.yaml, deploy/git/kustomization.yaml, deploy/overlays/dev/patch_deployment.yaml, scripts/deploy_gke.sh, server/main.py, server/templates/version.html
=> Add an endpoint to check the version

server/routes/api/stats.py, server/routes/tools.py, server/services/datacommons.py, server/templates/tools/timeline.html, server/templates/tools/timeline_bulk_download.html, static/js/tools/timeline_bulk_download.ts, static/js/tools/timeline_chart_region.tsx, static/js/tools/timeline_page.test.tsx, static/webpack.config.js
It's much simplified - uses /stat/set to get the latest values, and only for states and counties in the US. Also doesn't look the best...
=> Resurrect bulk download tool for UCSB's data science course

server/main.py, server/services/datacommons.py
* Remove DEBUG message!
* Let mixer error message show up..
=> Improve flask logging message

static/js/browser2/observation_chart.tsx, static/js/chart/draw.ts, static/js/chart/types.ts, static/js/dev_page.tsx, static/js/place/chart.tsx
Changes:
- update the function drawLineChart to take in handler function for dots being clicked and change the data format of the dots
- update the observationChart component to use drawLineChart function.
=> [Graph Browser 2] use drawLineChart function for observationChart

server/requirements.txt, tools/geojson_simplifier/plotter.py
pin yapf version number to requirements.txt
=> Pin Yapf version number

README.md
=> Fix developer_guide.md link

static/js/browser2/out_arc_section.tsx
=> Website release

static/js/browser2/arc_section.tsx, static/js/browser2/browser.ts, static/js/browser2/browser_page.tsx
- Update title to STAT_VAR - PLACE_NAME - Graph Browser - Data Commons
- Update properties header to "Statistical Variable Properties"
- Update observations header to "Observations for PLACE_NAME"
=> [Graph Browser 2] Place stat var ui updates

build/ci/cloudbuild.npm.yaml, build/ci/cloudbuild.webdriver.yaml, build/node/README.md, build/node/cloudbuild.yaml, build/webdriver-chrome/README.md, build/webdriver-chrome/cloudbuild.yaml
This should speed up the testing and binary push in cloudbuild
=> Update deploy docker images and webdriver tests configuration

server/routes/api/stats.py, server/services/datacommons.py, server/tests/api_stats_test.py, static/js/tools/scatter2/app.test.tsx, static/js/tools/scatter2/chart_loader.tsx, static/js/tools/scatter2/util.ts
- mixer /stat/collection was updated to stat/set/within-place so make the corresponding changes on flask and client
=> API update for scatter tool

server/routes/api/stats.py, server/services/datacommons.py, server/tests/api_stats_test.py, static/js/tools/scatter2/app.test.tsx, static/js/tools/scatter2/chart_loader.tsx, static/js/tools/scatter2/util.ts
- use post instead of get to get population data 
- use post instead of get to get stat-set-within-place
=> scatter2 updates to api calls

deploy/base/deployment.yaml, deploy/overlays/local/patch_deployment.yaml
More background see this PR [description](https://github.com/datacommonsorg/mixer/pull/515#issue-631595221).
=> Turn off GKE cpu and memory usage limit

server/lib/statvar_hierarchy_search.py, server/routes/api/browser.py, server/services/datacommons.py, static/js/browser2/statvar_group_node.tsx, static/js/browser2/statvar_hierarchy.tsx
This is a follow up of https://github.com/datacommonsorg/mixer/pull/519.
Also did some format update.
=> Update get_statvar_groups() to take multiple places

static/css/timeline.scss, static/css/tools/scatter.scss, static/js/tools/scatter2/app.test.tsx, static/js/tools/scatter2/place_options.tsx, static/js/tools/scatter2/statvar.tsx, static/js/tools/timeline/search.tsx
- update the modal that pops up when user picks three variable. The new modal shows the user the third variable they picked and then forces them to keep one of the other two variables. if user closes the modal, no change.
- update the place options to look better on small screens
dev instance has been updated
=> [scatter] more nice to haves

static/js/chart/draw_choropleth.ts, static/js/tools/map/app.tsx, static/js/tools/map/info.tsx
=> [map] Add info page and handle window resize

deploy/overlays/local/patch_deployment.yaml, docs/developer_guide.md
Reduce the memory and cpu usage in local development. The default one takes 10+ memory.
=> Update local development configuration and documentation

static/css/tools/map.scss, static/js/chart/draw_choropleth.ts, static/js/place/chart.tsx, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/chart_options.tsx
- Updated tooltip to include the date and sources of the data point
dev updated (http://dev.datacommons.org/tools/map#%26sv%3DCumulativeCount_MedicalConditionIncident_COVID_19_PatientDeceased%26pc%3D1))
=> [map] Updated Tooltip

static/css/tools/map.scss, static/js/chart/draw_choropleth.ts, static/js/tools/map/chart.tsx
-added ability to zoom and pan. To zoom in and out, can use buttons or mouse wheel
dev updated (http://dev.datacommons.org/tools/map#%26sv%3DCumulativeCount_MedicalConditionIncident_COVID_19_PatientDeceased%26pc%3D1)
=> [map] zoom in on map

static/js/browser/statvar_checkbox.tsx
Also pull in latest mixer change to sync with latest stat var group change there.
=> Update checkbox logic so it's updated when chart chip is deslected

static/css/browser.scss, static/css/stat_var_hierarchy.scss, static/css/timeline.scss, static/css/tools/map.scss, static/css/tools/stat_var_widget.scss, static/css/tools/statvar_menu.scss, static/js/browser/browser_page.tsx, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/tools/map/stat_var_chooser.tsx, static/js/tools/timeline/page.tsx
small scss refactoring
- /stat_var_hieararchy.scss contains base styles for the menu
- /tools/stat_var_widget.scss contains modifications used for all three tools
made very basic fixes to maintain the look and feel for our old menu:
=> [sv widget] factor out styles for the stat var hierarchy

static/css/stat_var_hierarchy.scss, static/css/tools/stat_var_widget.scss
=> Make stat var hierarchy widget scroll on x overflow

static/css/tools/scatter.scss, static/js/shared/types.ts, static/js/stat_var_hierarchy/node_header.tsx, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/stat_var_hierarchy/stat_var_section_input.tsx, static/js/tools/scatter/app.test.tsx, static/js/tools/scatter/app.tsx, static/js/tools/scatter/chart_loader.tsx, static/js/tools/scatter/context.ts, static/js/tools/scatter/statvar.tsx, static/js/tools/scatter/util.test.ts, static/js/tools/scatter/util.ts, static/js/tools/timeline/__snapshots__/page.test.tsx.snap
dev updated (https://dev.datacommons.org/tools/scatter)
=> [scatter] incorporate tree widget into scatter tool

server/routes/api/stats.py, server/templates/tools/map.html, static/css/tools/map.scss, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/chart_options.tsx, static/js/tools/map/info.tsx, static/js/tools/map/stat_var_chooser.tsx, static/js/tools/statvar_menu/util.tsx
- add examples to the landing page
- add a tooltip beside the title explaining the date range
- disable per capita checkbox for medianValue stat vars
dev instance updated (https://dev.datacommons.org/tools/map)
=> [map] Few updates

static/js/chart/draw.ts
=> [timeline ]show display name of stat var in legend

server/routes/api/stats.py, static/js/stat_var_hierarchy/stat_var_section_input.tsx
Update the tooltip content for when there is no stat var summary for a stat var.
=> [tree widget] update tooltip

server/configmodule.py, server/routes/api/browser.py, server/services/datacommons.py, server/tests/api_browser_test.py
added mechanism to blocklist svgs for prod
=> [tree widget] add mechanism for blocklisting svg

server/requirements.txt
Plan to clean up package.json and anchor requirements.txt in a follow up PR
=> Fix a server crash due to library update

server/chart_config.json, server/configmodule.py, static/js/i18n/compiled-lang/en/stats_var_labels.json, static/js/i18n/compiled-lang/en/stats_var_titles.json, static/js/i18n/i18n.tsx
This includes the following charts:
Wages
(a) Total
* Mean_WagesMonthly_Worker
(b) Urban vs. Rural
* Mean_WagesMonthly_Worker_Urban
* Mean_WagesMonthly_Worker_Rural
(c) Gender
* Mean_WagesMonthly_Worker_Female
* Mean_WagesMonthly_Worker_Male
Religion
* indianCensus/Count_Person_Religion_Buddhist
* indianCensus/Count_Person_Religion_Christian
* indianCensus/Count_Person_Religion_Hindu
* indianCensus/Count_Person_Religion_Jain
* indianCensus/Count_Person_Religion_Muslim
* indianCensus/Count_Person_Religion_OtherReligionsAndPersuasions
* indianCensus/Count_Person_Religion_ReligionNotStated
* indianCensus/Count_Person_Religion_Sikh
Unemployment Rate (time-series)
* UnemploymentRate_Person_Rural
* UnemploymentRate_Person_Urban
=> Add more charts to place page

static/js/place/chart_block.tsx, static/js/place/main.tsx
=> [Place Page] Each topic show start a new chart block row

static/css/tools/stat_var_widget.scss, static/js/stat_var_hierarchy/stat_var_group_node.tsx, static/js/stat_var_hierarchy/stat_var_group_section.tsx, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/stat_var_hierarchy/stat_var_search.tsx, static/js/tools/map/stat_var_chooser.tsx, static/js/tools/scatter/statvar.tsx, static/js/tools/timeline/page.tsx, static/package-lock.json
=> [tree widget] Add toggle for hiding unavailable stat vars

server/routes/api/protein.py, static/js/protein/page.tsx, static/js/shared/types.ts
This gets the page working e2e. Next step is to use d3 to draw charts instead of showing plain text
=> Pipe in real data for protein page

static/js/protein/chart.ts, static/js/protein/page.tsx
Next step is to use the d3 code in observable and draw the real chart
=> Use a dummy chart for bio protein page

static/js/tools/scatter/chart.tsx
=> [scatter] add text wrap for title and axis

server/routes/dev.py
This is due to the upgrade of google-cloud-secret-manager library
=> Fix clear cache secret API func call issue

server/main.py, server/webdriver_tests/browser_test.py, static/js/browser/types.ts, static/js/browser/weather_chart_section.tsx
=> Display both daily and monthly weather in browser

static/css/tools/map.scss, static/js/tools/map/chart.tsx
=> Display unit in map tool legend

static/js/tools/map/chart_options.tsx
=> [map] add units to breadcrumbs

.gitignore, deploy/gke/private.yaml, deploy/overlays/private/kustomization.yaml, deploy/overlays/private/patch.yaml, gke/setup_config_cluster.sh, gke/setup_robot_account.sh, run_server.sh, scripts/deploy_gke.sh, server/__init__.py, server/configmodule.py, server/lib/config.py, server/main.py, server/templates/base.html, server/webdriver_tests/base_test.py, static/css/base.scss, static/css/browser.scss, static/css/place/place.scss, static/css/tools/base_tools.scss, static/css/tools/scatter.scss, static/js/shared/util.ts, static/js/tools/timeline/page.tsx, static/package-lock.json
- There is no provenance from TMCF+CSV, may need to enforce a manifest for each import.
- Color change is not reflected in this PR. Will do a separate one for color and homepage change.
=> [Private DC] GKE deployment config and util functions update to make it run

server/configmodule.py, server/main.py, server/routes/static.py, server/templates/base.html, server/templates/static/private.html
=> Homepage update for private DC

static/js/tools/scatter/statvar.tsx
- fix for [issue #1103](https://github.com/datacommonsorg/website/issues/1103)
=> [scatter] keep axis for existing var when a third is added

server/routes/api/choropleth.py, static/css/tools/map.scss, static/js/chart/draw_choropleth.ts, static/js/chart/types.ts, static/js/tools/map/chart.test.ts, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/chart_options.tsx, static/js/tools/map/context.ts, static/js/tools/map/util.test.ts, static/js/tools/map/util.ts
- add functionality where if the url contains &ppt=<placeType>, we will plot points for places of that type that are contained within the current map
dev updated (eg. https://dev.datacommons.org/tools/map#%26sv%3DMedian_Age_Person%26pc%3D0%26pd%3DgeoId%2F06027%26pn%3DInyo%20County%2C%20CA%26pt%3DCounty%26ept%3DCounty%26ppt%3DCity)
=> [map] add points on top of map

static/js/tools/scatter/app.tsx, static/js/tools/scatter/chart_loader.tsx, static/js/tools/scatter/place_options.tsx, static/js/tools/scatter/util.ts
- allow placetype of country to be selected and when country is selected, show place as Earth
- programmed together with Bo
dev updated (go to https://dev.datacommons.org/tools/scatter and choose country from the place type dropdown)
=> [scatter] support country

server/routes/api/stats.py, static/js/tools/map/chart_loader.tsx
- stats/within-place throws KeyError when there is no data. Handle this error.
=> Handle when getting stats within a place and there is no data

scripts/autopush.sh, static/css/base.scss
- Autopush to private website instance
- Fix header dropdown item active state color.
=> [Private DC] some minor update

static/css/tools/map.scss, static/js/chart/draw_choropleth.ts, static/js/tools/map/chart.tsx
- if a place has no data, make the dot grey. I'm not sure how I feel about the fact that these grey dots look very similar to the hover state, what are your thoughts @beets @shifucun
=> [map] Grey out dots for places that have no data

server/templates/base.html, server/templates/static/private.html, static/js/stat_var_hierarchy/stat_var_group_node.tsx
- remove footer
- do not use "private"
=> Update on IEA DC

static/js/chart/draw_choropleth.ts, static/js/tools/map/chart.tsx, static/js/tools/map/chart_options.tsx, static/js/tools/map/info.tsx
=> [map] add links for greenhouse gas emissions plots

docs/developer_guide.md, docs/localization.md, server/routes/static.py, server/templates/static/faq.html, static/css/static.scss
=> Add citation info to faq

server/__init__.py, server/configmodule.py, server/main.py, server/requirements.txt, server/routes/auth.py, server/routes/user.py
Only allow google.com users to login to non-prod instances
=> Add website login and require login for non-(prod/local) instances

static/js/shared/constants.ts, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/place_details.tsx, static/js/tools/map/place_options.tsx, static/js/tools/map/util.ts
=> [map] Enable IPCC_50 for countries

static/css/draw_choropleth.scss, static/css/tools/map.scss, static/js/chart/draw.ts, static/js/chart/draw_choropleth.ts, static/js/tools/map/chart.tsx, static/js/tools/map/place_details.tsx, static/js/tools/scatter/chart.tsx, static/js/tools/shared_util.ts
- added missing replot on prop update
- fix domain / color for wet bulb temp
small bugfix in timeline:
- removed empty measurement method in the provenance
=> [map] a few small fixes

static/js/chart/draw_choropleth.ts
=> [release] update mixer & wet bulb color 

static/js/i18n/compiled-lang/de/stats_var_titles.json, static/js/i18n/compiled-lang/en/stats_var_titles.json, static/js/i18n/compiled-lang/es/stats_var_titles.json, static/js/i18n/compiled-lang/fr/stats_var_titles.json, static/js/i18n/compiled-lang/hi/stats_var_titles.json, static/js/i18n/compiled-lang/it/stats_var_titles.json, static/js/i18n/compiled-lang/ja/stats_var_titles.json, static/js/i18n/compiled-lang/ko/stats_var_titles.json, static/js/i18n/compiled-lang/ru/stats_var_titles.json, static/js/i18n/strings/de/stats_var_titles.json, static/js/i18n/strings/en/stats_var_titles.json, static/js/i18n/strings/es/stats_var_titles.json, static/js/i18n/strings/fr/stats_var_titles.json, static/js/i18n/strings/hi/stats_var_titles.json, static/js/i18n/strings/it/stats_var_titles.json, static/js/i18n/strings/ja/stats_var_titles.json, static/js/i18n/strings/ko/stats_var_titles.json, static/js/i18n/strings/ru/stats_var_titles.json, static/js/tools/timeline/info.tsx
- s/Facilitys/Facilities
- Broken poverty link on Timeline info page
=> small typo fixes

static/js/tools/map/chart_loader.tsx
original: https://screenshot.googleplex.com/7gk3VzKPvdRnLeb
fixed: https://screenshot.googleplex.com/9Kjuiy8Yhz3uajq
=> [map] fix map bug for leaf page for stat var with capped date 

static/js/stat_var_hierarchy/node_header.tsx, static/js/stat_var_hierarchy/stat_var_group_node.tsx, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/stat_var_chooser.tsx, static/js/tools/map/util.ts
addresses [issue #1284](https://github.com/datacommonsorg/website/issues/1284)
=> [map] don't clear stat var if unavailable for a selected place type

static/css/tools/scatter.scss, static/js/tools/scatter/context.ts, static/js/tools/scatter/place_and_type_options.tsx
- also populate place type options after place has been selected
For now, the place type options are general to the selected place type which means some of these options may not be real options for the selected place. 
eg.
=> [scatter] allow select country for Europe

server/templates/static/homepage.html, static/js/place/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/place_options.tsx, static/js/tools/map/util.ts, static/js/tools/scatter/chart.tsx, static/js/tools/scatter/place_and_type_options.tsx
- Add IPCCPlace_50 to dropdown for continents
- fix [issue #1306 ](https://github.com/datacommonsorg/website/issues/1306)
- fix [issue #1300](https://github.com/datacommonsorg/website/issues/1300)
- fix [issue #1310](https://github.com/datacommonsorg/website/issues/1310)
=> [map] Add IPCCPlace_50 to dropdown for continents & small bug fixes

static/js/tools/scatter/chart_loader.tsx, static/js/tools/scatter/plot_options.tsx
- fix [issue #1265](https://github.com/datacommonsorg/website/issues/1265)
- fix [issue #1312](https://github.com/datacommonsorg/website/issues/1312)
- Problem here was empty population data. I also disabled per capita option for axes where there's no population data because nothing happens when user chooses per capita for axes without population data
=> [scatter] few more fixes

server/webdriver_tests/map_test.py, server/webdriver_tests/scatter_test.py, server/webdriver_tests/shared.py
- fix broken map webdriver test
- add shared function that should be able to help with flaky tests
=> [map] fix webdriver tests

deploy/gke/private.yaml
Guha suggested to use this domain to map the content
=> Update private website domain

server/routes/api/stats.py, server/services/datacommons.py, static/css/tools/map.scss, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/scatter/chart_loader.tsx, static/js/tools/shared_util.ts
- Fetch all the stat set series data in the initial load.
- Add a picker to pick the source and reload chart with corresponding data.
UI is very basic, we could visit other options later.
=> Add source selector in map tool

server/templates/static/homepage.html, static/css/static.scss
Text updates for the homepage.
Also added indicators for external links, and slowed down the map animation (as well as a missing frame!)
Changes are staged on dev.datacommons.org
=> homepage updates

server/templates/static/homepage.html
Add missing external icon to CDC study page
=> Small homepage update

server/routes/api/choropleth.py, server/tests/choropleth_test.py
fixes [issue #1353](https://github.com/datacommonsorg/website/issues/1353)
=> [place] fix choropleth missing data source attribution

server/topic_page_pb2.py, static/js/topic_page/line_tile.tsx, static/js/topic_page/main_pane.tsx, static/js/topic_page/map_tile.tsx
- Use statVarMetadata as Component prop field.
- Move helper functions into the Component scope.
- Consolidate prop naming
- Set "isUSAPlace" to true always
=> Align the Component style for line and map tile

static/js/topic_page/line_tile.tsx, static/js/topic_page/map_tile.tsx, static/js/topic_page/ranking_tile.tsx
This allows building the Block component for completeness.
Also fixes a state issue in line tile, where "chartData" updates causes an extra rendering cycle.
=> Add the bare bone for ranking tile

static/js/stat_var_hierarchy/stat_var_group_node.tsx, static/js/stat_var_hierarchy/stat_var_section.tsx
- fix bug where large number of redundant `api/stats/stat-var-summary` and `/api/browser/statvar/group` were being made
=> [tree widget] fix redundant api calls bug

static/css/draw_scatter.scss, static/css/tools/scatter.scss, static/css/topic_page.scss, static/js/chart/draw_scatter.ts, static/js/shared/constants.ts, static/js/tools/scatter/chart.tsx, static/js/tools/scatter/chart_loader.tsx, static/js/tools/scatter/plot_options.tsx, static/js/tools/scatter/util.ts, static/js/topic_page/block.tsx, static/js/topic_page/scatter_tile.tsx, static/js/utils/number_utils.ts, static/js/utils/scatter_data_utils.ts
- added a scatter tile
- tried to move a few files/functions around and added a utils folder
Questions:
- in our config, should scaling and units be instead attached to each statvar? Because in scatter, I think it would make sense for us to want different scaling and units for each axis.
- Also in our config, do we want to allow for log as well? Because I know sometimes log makes the charts look nicer.
Example of scatter tile (just using same config as another tile):
=> [topic page] add scatter tile

static/js/chart/draw_bivariate.ts, static/js/tools/scatter/chart.tsx, static/js/topic_page/bivariate_tile.tsx, static/js/topic_page/block.tsx, static/js/topic_page/map_tile.tsx
- added a bivariate tile
- extracted bivariate chart drawing into its own file
Example of bivariate tile (just using same config as another tile):
=> [topic page] add bivariate tile

server/topic_page.proto, server/topic_page_config.textproto, server/topic_page_pb2.py, static/js/topic_page/bar_tile.tsx, static/js/topic_page/bivariate_tile.tsx, static/js/topic_page/block.tsx, static/js/topic_page/highlight_tile.tsx, static/js/topic_page/line_tile.tsx, static/js/topic_page/map_tile.tsx, static/js/topic_page/ranking_tile.tsx, static/js/topic_page/scatter_tile.tsx, static/js/types/stat_var.tsx, static/js/utils/scatter_data_utils.ts
- attach unit, scaling, and log to each stat var instead of to a list of stat vars
=> [topic page] update config proto

server/__init__.py, server/config/topic_page_pb2.py, server/lib/util.py, server/routes/topic_page.py, server/templates/topic_page.html, static/css/topic_page.scss, static/js/chart/draw.ts, static/js/topic_page/chart_tile.tsx, static/js/topic_page/line_tile.tsx, static/js/topic_page/main_pane.tsx, static/js/topic_page/map_tile.tsx, static/js/topic_page/page_selector.tsx, static/js/topic_page/topic_page.ts
- add selector for place and topic
=> [topic page] topic page selector

static/js/tools/map/stat_var_chooser.tsx
- fix bug where page continuously refreshes when there is no StatVarInfo retrieved for the stat vars needed for the page
=> [map] fix bug with updating sv info

.gitignore, scripts/deploy_gke.sh, server/lib/config.py
Also simplified the deploy script file generation, so it does not mess up with local git versioning.
=> DevOps update for private instance

server/templates/static/homepage.html, static/css/static.scss
Add a section to the homepage highlighting the size of the graph
=> [homepage] add a "by the numbers" section

server/config/topic_page/equity/USA.textproto, server/templates/static/homepage.html
also fix the stat on the homepage
=> [topic] add more maps to equity page

server/routes/api/stats.py
Maybe we can expand this UI interface to be more useful..
=> Fix place list page as data API response has changed

server/routes/api/browser.py, server/routes/api/place.py
=> Use newer version of place stat vars api in website

static/js/tools/map/stat_var_chooser.tsx, static/js/tools/scatter/statvar.tsx, static/js/utils/place_utils.ts
- add curated list of sample places to use for countries in the world
- In map tool, increase the sample size for list of places to pass to the stat var hierarchy to 50
=> [map/scatter] reduce randomness of available statvars in the stat var hierarchy

server/config/topic_page/equity/USA.textproto, server/config/topic_page/poverty/USA.textproto, static/css/topic_page.scss, static/js/topic_page/block.tsx, static/js/topic_page/category.tsx, static/js/topic_page/main_pane.tsx, static/js/topic_page/sidebar.tsx
also:
- add support for blocks without titles
- move health & poverty category to "poverty" topic
- add disability charts and more descriptions to "equity" topic
-
=> [topic] more equity charts

server/routes/api/place.py, server/routes/api/ranking.py, server/services/datacommons.py, static/js/ranking/ranking_page.tsx
The ranking API has been updated to not using payload but a protobuf (json) in mixer: https://github.com/datacommonsorg/mixer/pull/723
=> Update website to use the new ranking API response

server/config/topic_page.proto, server/config/topic_page/poverty/India.textproto, server/config/topic_page/poverty/USA.textproto, server/lib/util.py, server/tests/topic_config_test.py, static/css/topic_page.scss, static/js/topic_page/bar_tile.tsx, static/js/topic_page/bivariate_tile.tsx, static/js/topic_page/ranking_tile.tsx, static/js/utils/scatter_data_utils.ts
Also fixed a few bugs dealing with data holes in scatter/bivariate/ranking
=> [topic] add poverty in india config

static/js/stat_var_hierarchy/stat_var_group_node.tsx, static/js/stat_var_hierarchy/stat_var_group_section.tsx, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx
=> [tree widget] don't reset sv hierarchy when search result cleared

deploy/base/deployment.yaml, server/main.py, server/templates/version.html
- Remove cpu limit in GKE
- And import groups args for mixer container
- Update /version to reflect mixer response change
=> Update deployment and version to match recent mixer import group change

static/js/stat_var_hierarchy/stat_var_search.test.tsx, static/js/stat_var_hierarchy/stat_var_search.tsx
- handle cases where there is only one sv/svg or only one of sv/svg
=> [tree widget] fix result count string

server/routes/api/place.py
with allowlist: 
without allowlist:
=> [place page] add allowlist for rankings on overview page

server/webdriver_tests/shared.py, server/webdriver_tests/tests/map_test.py, server/webdriver_tests/tests/scatter_test.py, server/webdriver_tests/tests/timeline_test.py
- fix test break caused by new "Agriculture" vertical added to stat var widget
=> [webdriver] fix tests

docs/new_deployment.md, run_server.sh, server/configmodule.py, server/lib/config.py, server/routes/static.py, server/templates/static/iitm.html
Also updated the instruction on how to setup a private instance.
We should consider simplify the process as it really involves a lot of config change now.
=> Add IITM specific page setup in website

server/templates/static/homepage.html
Highlight new sustainability datasets
Update DC numbers
=> [homepage] Highlight sustainability datasets

static/css/search2.scss, static/js/search/place_results.tsx
- fix jumpiness on hover
- add tooltip on hover
=> [Search] place result icon updates

server/routes/api/place.py, server/webdriver_tests/tests/scatter_test.py
And I plan to make webdriver tests enforced again.
=> Fix webdriver tests

static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/context.ts, static/js/tools/map/util.test.ts, static/js/tools/map/util.ts
time slider will be enabled with ts=1
=> add url param to display time slider

static/js/stat_var_hierarchy/stat_var_section.test.tsx, static/js/stat_var_hierarchy/stat_var_section.tsx
fixes [issue #1525](https://github.com/datacommonsorg/website/issues/1525)
=> [tree widget] fix prefix bug

static/js/protein/chart.ts, static/js/protein/page.tsx, static/js/protein/protein_chart.test.tsx, static/js/shared/types.ts
@chejennifer , @beets , @shifucun @spiekos 
I added the code for the first chart. However, there is some issue on the formatting end which I'm unable to fix. Any help debugging it, would be greatly appreciated. 
Here's the link to the observable hq version of the notebook on how it should look. Also the chart is found on 'bio/protein/bio/P53_HUMAN' on the local version of the website. 
https://observablehq.com/d/a51755b9159a6baf
=> feat: add chart 1

static/css/tools/map.scss, static/js/tools/map/time_slider.tsx
=> add tick marks to time slider

deploy/overlays/iitm/kustomization.yaml, docs/developer_guide.md
- Update submodule documentation
- Reduce IITM instance
=> Minor update for website deployment

static/js/tools/scatter/statvar.tsx, static/js/tools/scatter/util.test.ts, static/js/tools/scatter/util.ts
=> [scatter] add default denom

server/templates/static/homepage.html, static/css/tools/stat_var_widget.scss
removed fixed denom for map charts
updated filter for some links to match images (fixes #1523)
=> update homepage links

server/__init__.py, server/main.py, server/webdriver_tests/tests/map_test.py, server/webdriver_tests/tests/scatter_test.py, server/webdriver_tests/tests/timeline_test.py
Fix some import issues along the way.
=> Log request when Flask throws error

server/webdriver_tests/tests/scatter_test.py, static/js/tools/map/chart.tsx, static/js/tools/map/util.ts, static/js/tools/scatter/chart.tsx, static/js/tools/scatter/chart_loader.tsx
- when per capita is chosen, add per capita into chart title
=> [map/scatter] add per capita in title

deploy/gke/feedingamerica.yaml, deploy/overlays/feedingamerica/kustomization.yaml, deploy/overlays/feedingamerica/patch.yaml, run_server.sh, scripts/autopush.sh, server/configmodule.py, server/lib/config.py, server/main.py, server/routes/static.py, server/templates/base.html, server/templates/static/feedingamerica.html, server/tests/config_test.py, static/css/base.scss
This is a modified version from https://github.com/datacommonsorg/website/pull/1557.
I have tested and deployed it
=> Deployment config for Feeding America

server/templates/tools/map.html, server/templates/tools/timeline.html, static/css/bq_modal.scss, static/css/timeline.scss, static/css/tools/map.scss, static/js/tools/map/bq_query_utils.ts, static/js/tools/map/chart_loader.tsx, static/js/tools/shared/bq_modal.tsx, static/js/tools/shared/bq_utils.ts, static/js/tools/timeline/chart_region.tsx
=> [BQ] modal for getting bq sql

server/templates/static/homepage.html, static/js/tools/scatter/info.tsx
also includes updated stat var count
=> [homepage] staging launch announcement

server/webdriver_tests/tests/map_test.py, server/webdriver_tests/tests/place_explorer_test.py, server/webdriver_tests/tests/place_landing_test.py, server/webdriver_tests/tests/scatter_test.py, server/webdriver_tests/tests/timeline_test.py
- update the expected chart title for a couple charts to reflect the newer 2020 data vs. original 2019 data
- update some waits to wait for the correct element
=> [webdriver] fix failing tests

server/routes/api/landing_page.py, server/routes/api/place.py
These are found from the GCP error reporting page
=> Fix some key errors

deploy/base/deployment.yaml, deploy/base/kustomization.yaml, deploy/overlays/feedingamerica/kustomization.yaml, deploy/overlays/feedingamerica/memdb.json
This PR tracks the change in mixer: https://github.com/datacommonsorg/mixer/commit/c015dffb0e4669f634a310cfad855205857fe852.
=> Update private instance deployment config to use custom stat var info

deploy/gke/dev.yaml, deploy/overlays/dev/ai.yaml, server/services/ai.py, server/services/datacommons.py, static/css/rich_search.scss, static/js/rich_search/stat_vars.tsx
Updates the new statvar-match API introduced in:
https://github.com/datacommonsorg/mixer/pull/842
=> Updates to new statvar-match API.

deploy/base/deployment.yaml, deploy/gke/dev.yaml, deploy/overlays/dev/ai.yaml, server/__init__.py, server/services/ai.py
- Fixes request deadlock.
- Increase wait time for mixer to 5 minutes.
- Set startupProbe for mixer.
=> Updates model.

deploy/gke/stanford.yaml, deploy/overlays/stanford/kustomization.yaml, deploy/overlays/stanford/patch.yaml, run_server.sh, scripts/autopush.sh, server/configmodule.py, server/lib/config.py, server/tests/config_test.py, static/package-lock.json
Private DC deployment for Stanford. Currently, no custom homepage.
=> Stanford private DC

deploy/base/deployment.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/dev/kustomization.yaml, deploy/overlays/feedingamerica/kustomization.yaml, deploy/overlays/karnataka/kustomization.yaml, deploy/overlays/memdb.json.tpl, deploy/overlays/stanford/kustomization.yaml, deploy/overlays/stanford/memdb.json, deploy/overlays/tidal/kustomization.yaml
The deployment works fine with this change.
=> Fix stanford config

static/js/protein/data_processing_utils.ts, static/js/protein/page.tsx
Fixed the data retrieval for error bar chart and added blurbs for each graph 
Please review @chejennifer !
=> feat: add blurbs and fix error chart data retrieval

static/css/protein.scss, static/js/protein/chart.ts
Added UI tweaks to the protein charts. Some of the issues addressed are:
- Adding tool tips
- Aligning y axes of all charts
- Creating uniform bar widths
- Adding axes labels
- Fixing y axis tick labels for some of the charts 
@chejennifer , please review !
=> style: add UI tweaks

server/__init__.py, server/routes/api/disease.py, static/js/disease/chart.ts, static/js/disease/data_processing_utils.ts, static/js/disease/page.tsx, static/js/protein/page.tsx
I added the .py script for diseases under the api directory and I also added more frontend framework. The config for diseases is ready too, I just have make a CL request for the config and require more guidance on that @shifucun!
It'll be great if you could review it please!
=> feat: pipe in real protein data

static/js/import_wizard/utils/validation.ts
fix validation nit from [PR #1674](https://github.com/datacommonsorg/website/pull/1674)
=> [import wizard] fix validation nit

server/templates/import_wizard.html
- Add instructions about radio buttons
=> [Import Wizard] update instructions

server/webdriver_tests/tests/browser_test.py
- Fix broken webdriver test caused by updated Count_Person data
=> Fix broken webdriver test

static/css/import_wizard.scss, static/js/import_wizard/components/page.tsx, static/js/import_wizard/components/preview_section.tsx, static/js/import_wizard/components/value_map_section.tsx, static/js/import_wizard/types.ts, static/js/import_wizard/utils/file_generation.test.ts, static/js/import_wizard/utils/file_generation.ts, static/js/import_wizard/utils/file_processing.test.ts, static/js/import_wizard/utils/file_processing.ts, static/js/import_wizard/utils/obs_generation.test.tsx, static/js/import_wizard/utils/obs_generation.ts
- add section where user can input value mappings or upload a file. (value mapping as in a mapping from cell value in original csv to that cell's value in the cleaned csv)
user input
file upload
=> [import wizard] Add value mapping section

deploy/terraform-datacommons-website/examples/website_v1/main.tf, deploy/terraform-datacommons-website/examples/website_v1/variables.tf, deploy/terraform-datacommons-website/examples/website_v1/variables.tfvars.tpl, deploy/terraform-datacommons-website/modules/vpc/README.md, deploy/terraform-datacommons-website/modules/vpc/main.tf, deploy/terraform-datacommons-website/modules/vpc/outputs.tf, deploy/terraform-datacommons-website/modules/vpc/variables.tf
VPC related resources. 
TESTED=terraform apply on project "datacom-alexyfchen-tf-test2"
=> [devops] Terraform for DC website part2. Add network resources

build/ci/cloudbuild.webdriver.yaml, build/webdriver-chrome/cloudbuild.yaml
This will use the latest chrome driver
=> update webdriver test docker image

server/webdriver_tests/tests/browser_test.py, server/webdriver_tests/tests/download_test.py, server/webdriver_tests/tests/place_explorer_test.py
- fix a test break caused by updated landing page data from mixer
- add more waiting for download tool and browser tests to fix flakiness
=> webdriver test fixes

static/css/import_wizard2.scss, static/js/import_wizard2/components/info.tsx, static/js/import_wizard2/components/page.tsx, static/js/import_wizard2/components/preview_table.tsx, static/js/import_wizard2/components/upload_page.tsx, static/js/import_wizard2/types.ts
- add relevant files for the upload and info pages
- navigation and integration with the rest of the tool will be in future PR
=> [import wizard 2] Upload and info pages

static/css/import_wizard2.scss, static/js/import_wizard2/components/mapping_page.tsx, static/js/import_wizard2/components/mapping_sections/constant_var.tsx, static/js/import_wizard2/components/mapping_sections/multi_var_col.tsx, static/js/import_wizard2/components/mapping_sections/multi_var_mulit_date_col.tsx, static/js/import_wizard2/components/mapping_sections/single_var_multi_date_col.tsx, static/js/import_wizard2/components/template_selection_page.tsx, static/js/import_wizard2/templates.test.tsx, static/js/import_wizard2/templates.tsx
- add template selection page
- add mapping page that will render a mapping section depending on the templateId
- This is just the skeleton and does not have logic implemented yet
- will add navigation and integration into the tool in future PR
=> [import wizard 2] add templates page

static/js/import_wizard2/components/mapping_page.tsx, static/js/import_wizard2/components/page.tsx, static/js/import_wizard2/components/template_selection_page.tsx
- add navigation between the pages
=> [import wizard 2] add navigation

server/__init__.py, server/services/datacommons.py
Use getters for accessing DC_API_KEY which is only required in dev instances. At the moment only affects data download tool
=> Use getters for DC API key

server/__init__.py, server/services/datacommons.py
Not sure how I missed it, even with local testing.
=> Fix error from #1737

server/routes/api/user.py, server/routes/user.py, server/templates/user/portal.html, static/js/user/page.tsx, static/js/user/user.ts
=> Display import list in user dashboard

static/js/shared/util.ts
=> add temp diffs to no cap rcp svs

server/templates/static/homepage.html, static/js/tools/download/info.tsx, static/js/tools/download/page.tsx
=> Update homepage update section

static/js/import_wizard2/components/shared/mapping_column_input.tsx
Small changes to the option text based on our earlier meeting
=> [wizard2] Small ui text updates

server/routes/tools.py, server/templates/tools/map.html, static/js/tools/map/app.tsx, static/js/tools/map/util.ts
- this allows flask to read the flag and only load the leaflet css if leaflet flag is set
=> [map] update geotiff flag so that it's in the url args instead of the url params

static/js/tools/map/app.tsx, static/js/tools/map/info.tsx, static/js/tools/map/title.tsx, static/js/tools/map/util.ts
When context is changed, App() component get re-rendered, hence the children components including <ChartLoader>. In the same time, <ChartLoader> listens to context change and re-render based on that. This creates extra rendering and does not interact well since <ChartLoader> has lots of async data fetch.
=> Control map tool display state inside each component instead of fetching context from app.js

static/js/tools/map/chart_loader.tsx, static/js/tools/map/chart_store.ts, static/js/tools/map/compute_hooks.ts, static/js/tools/map/fetcher/all_dates.ts, static/js/tools/map/fetcher/all_stat.ts, static/js/tools/map/fetcher/breadcrumb_denom_stat.ts, static/js/tools/map/fetcher/breadcrumb_stat.ts, static/js/tools/map/fetcher/default_stat.ts, static/js/tools/map/fetcher/denom_stat.ts, static/js/tools/map/fetcher/geojson.ts, static/js/tools/map/fetcher/map_point_coordinate.ts, static/js/tools/map/fetcher/map_point_stat.ts, static/js/tools/map/fetcher/stat_var_summary.ts, static/js/tools/map/place_details.tsx, static/js/tools/map/ready_hooks.ts
Add a compute hook to compute the breadcrumb values based on breadcrumbStat and breadcrumbDenomStat data.
=> Refactor breadcrumb values to use the custom hook

static/js/tools/map/d3_map.tsx
- earth has an empty list of parent places so should be checking parent places is not null instead of parent places is not empty
=> [map] fix countries in the world map not drawing

server/routes/api/landing_page.py
Reverts datacommonsorg/website#1789
=> Revert "Always add Overview to the category hash map to display it as a subtitle"

static/js/tools/map/leaflet_map.tsx
- remove spinner when leaflet map drawn
=> fix spinner for leaflet

static/js/tools/map/chart_loader.tsx
fixes github issue: https://github.com/datacommonsorg/website/issues/1807
=> fix spinner for map error state

static/js/disaster_dashboard/ranking_section.test.ts, static/js/disaster_dashboard/ranking_section.tsx
code for the ranking component
This is one part of the changes for the disaster dashboard MVP here on dev:
=> [disaster dashboard] ranking section

static/js/chart/draw_bivariate.ts, static/js/chart/draw_d3_map.ts, static/js/disaster_dashboard/constants.ts, static/js/disaster_dashboard/info_card.tsx, static/js/disaster_dashboard/map_section.tsx, static/js/disaster_dashboard/types.ts, static/js/place/chart.tsx, static/js/tools/map/d3_map.tsx, static/js/topic_page/map_tile.tsx
- code for the map section of the dashboard
- separate functions for getting map projection, drawing base map, and adding map points to a base map
This is one part of the changes for the disaster dashboard MVP here on dev:
=> [disaster dashboard] map section

server/routes/dev.py, server/templates/dev/disaster_dashboard.html, static/css/disaster_dashboard.scss, static/js/disaster_dashboard/data_fetcher.ts, static/js/disaster_dashboard/disaster_dashboard.ts, static/js/disaster_dashboard/page.tsx, static/js/disaster_dashboard/ranking_section.tsx
- add main component that completes the disaster dashboard mvp
This is the last part of the changes for the disaster dashboard MVP here on dev:
=> [disaster dashboard] Main component of disaster dashboard

static/js/disaster_dashboard/data_fetcher.ts
- address nits from previously merged pr
=> [disaster dashboard] address nits

server/routes/api/facets.py, server/routes/api/point.py, server/routes/api/series.py
For repeated params, check both params exist and param is not empty.
=> Check empty params in Flask endpoints

static/css/base.scss
Our footers are missing the background color. Missed this error earlier..
=> Add missing var qualifier from #1838

server/routes/api/place.py
Fixes #1849 
Could not find the root cause of the issue, but a user could also easily play with the URL and we would still need handle it in the API handler.
=> Be resilient to empty place dcids

server/routes/api/protein.py
=> [Protein] protein protein interaction graph bug

server/config/disaster_dashboard/Earth.textproto, server/config/subject_page.proto, server/config/subject_page_pb2.py, static/css/shared/_tiles.scss, static/js/components/tiles/disaster_event_map_filters.tsx, static/js/components/tiles/disaster_event_map_info_card.tsx, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/disaster_dashboard_v0/map_section.tsx, static/js/disaster_dashboard_v0/page.tsx, static/js/disaster_dashboard_v0/ranking_section.test.ts, static/js/disaster_dashboard_v0/ranking_section.tsx, static/js/types/disaster_event_map_types.ts, static/js/types/subject_page_proto_types.ts, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/tests/disaster_event_map_utils.test.ts
- add ability to filter the events that show up by specified props
=> [disaster] add severity filters

server/routes/nl_interface.py, static/js/apps/nl_interface/app.tsx, static/js/components/subject_page/main_pane.tsx, static/js/components/text_search_bar.tsx
* Correctly set search box text from url query string
* Fix duplicate react component key issue
* Check containedPlaceTypes is not undefined
=> Various fixes for NL interface

server/config/disaster_dashboard/Earth.textproto, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/string_utils.test.ts, static/js/utils/string_utils.ts
- add FireEvent event type to list of eventType dcids for Fire
- check that date is valid before using for the dropdown
=> [disaster] Minor fixes/updates

server/__init__.py, server/routes/nl_interface.py, static/css/nl_interface.scss, static/js/apps/nl_interface/app.tsx
Make /nl/data endpoints both GET and POST so it can take the context history.
Turn off AI context to sped up server start.
Set cookie MaxAge to 3600s
=> [NL Interface] Use context in cookie, update table component

static/js/apps/nl_interface/app.tsx
=> [nl] add sidebar to nl results

static/js/components/tiles/disaster_event_map_selectors.tsx, static/js/components/tiles/disaster_event_map_tile.tsx
=> [disasters] update URL when user clicks a region or a breadcrumb

server/lib/nl_detection.py, server/lib/nl_training.py
Currently, this is not being used in nl_interface.py 
Once this is approved and merged, I will edit nl_interface.py to use this interface
=> The interface(s) for detection objects

server/config/disaster_dashboard/Earth.textproto, server/config/subject_page.proto, server/routes/api/disaster_api.py, server/services/datacommons.py, server/tests/api/api_disaster_test.py, static/js/components/tiles/disaster_event_map_filters.tsx, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/disaster_dashboard_v0/constants.ts, static/js/disaster_dashboard_v0/page.tsx, static/js/disaster_dashboard_v0/ranking_section.test.ts, static/js/disaster_dashboard_v0/ranking_section.tsx, static/js/types/disaster_event_map_types.ts, static/js/types/subject_page_proto_types.ts, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/tests/disaster_event_map_utils.test.ts
- update severity filtering to be done using the mixer api update
=> [disasters] update severity filtering

server/__init__.py, server/lib/nl_detection.py, server/routes/nl_interface.py, server/services/nl.py
With this change, we have the following:
1. A consistent detection response (as a Detection object) with PlaceDetection, SVDetection, Classification.
2. Formatting the dictionary response based on the Detection object.
3. Setting up the framework for Correlations detections (not currently returning anything useful).
4. Setting up the framework for Ranking, Temporal, Contained In attributes detection heuristics.
The data() function in nl_interface.py can now move all {SV, Place} -> {SV, Place Expansion} -> Charts logic in a separate function using the Detection object.
I have tested these changes on the local server and compared the responses to the autopush live server using the same embeddings. They are exactly the same.
=> Using the Detection data class.

static/css/nl_interface.scss, static/js/apps/nl_interface/debug_info.tsx, static/js/apps/nl_interface/query_result.tsx, static/js/types/app/nl_interface_types.ts
Moved debug panel into a new component.
=> [NL] zippy for debug

static/css/nl_interface.scss, static/js/apps/nl_interface/app.tsx, static/js/apps/nl_interface/query_result.tsx
=> [NL] add blocks around each answer

static/css/nl_interface.scss, static/js/apps/nl_interface/app.tsx, static/js/apps/nl_interface/query_result.tsx
also updates loading to a more "chatty" one. this is sometimes buggy, and even though charts are not re-rendering, there is sometimes a lag and an over-scroll. adding this in first to add other features..
=> [NL] add scroll to query

server/lib/nl_chart_spec.py, server/lib/nl_page_config.py, static/css/nl_interface.scss, static/js/apps/nl_interface/query_result.tsx, static/js/components/subject_page/block.tsx, static/js/components/subject_page/category.tsx, static/js/components/subject_page/main_pane.tsx, static/js/components/tiles/bar_tile.tsx, static/js/components/tiles/bivariate_tile.tsx, static/js/components/tiles/histogram_tile.tsx, static/js/components/tiles/line_tile.tsx, static/js/components/tiles/map_tile.tsx, static/js/components/tiles/scatter_tile.tsx, static/js/constants/tile_constants.ts
shrink charts down to 160px tall, and 3 charts wide (also removed legends, margins, etc)
also fixes chart / block titles with plurals
=> [NL] smaller charts

static/css/nl_interface.scss, static/js/components/subject_page/main_pane.tsx
last change inadvertently broke scrolling.. sorry!
=> [NL] fix scrollbar

static/js/components/tiles/ranking_tile.tsx
=> sort ranking tiles by value

static/js/apps/nl_interface/app.tsx, static/js/components/text_search_bar.tsx
- autofocus on load
- on search, clear text box
=> [nl] search bar updates

static/js/components/tiles/chart_tile.tsx
address pr comments from exporting charts pr https://github.com/datacommonsorg/website/pull/1961
=> [nl] followup for download pr

server/lib/nl_detection.py, server/routes/nl_interface.py, server/services/nl.py, static/js/apps/nl_interface/debug_info.tsx, static/js/types/app/nl_interface_types.ts
1. Show sentences matched (see screenshot)
2. Enable US SVs from demo (embeddings)
=> [NL Interface] Show sentences matched in debugInfo

server/lib/nl_page_config.py, static/js/components/subject_page/block.tsx, static/js/components/tiles/ranking_tile.tsx
classifier.attributes.ranking_type was changed to List in #1983
=> [NL] fix ranking charts

server/routes/nl_interface.py, static/js/apps/nl_interface/debug_info.tsx
Adds back json under "Chart Spec" in debugging info
=> [NL] Fix missing chart spec

server/lib/nl_page_config.py, static/js/apps/nl_interface/app.tsx, static/js/apps/nl_interface/query_result.tsx
fix missing sv's during chart generation
catch empty categories returned - show an error
also remove scrolling logging
=> [NL] more error handling

server/routes/nl_interface.py, static/js/components/subject_page/block.tsx, static/js/utils/nl_interface_utils.ts
we were adding "tile-hidden" to all tiles by default... :-o
added strict_slashes so it now defaults to `/nl/`
=> [NL] fix ultra-aggressive show more

static/css/shared/_tiles.scss, static/js/components/tiles/place_overview_tile.tsx
=> [nl] add subtopic links

server/lib/nl_detection.py, server/lib/nl_page_config.py, server/services/nl.py
Adds two more ranking types, `BEST` and `WORST`.
This helps improve the logic for stat vars with negative connotations.
Ex:
"Cities with worst crime" -> should show cities with _highest_ crime
"Best cities by crime" -> should show cities with _lowest_ crime.
=> [NL] Improve ranking behavior

server/lib/nl_data_spec.py
=> Topic SVs should look at highlight SVs

server/lib/nl_topic.py
=> Replace a SV in Agriculture nl_topic to avoid time-series gap

static/css/nl_interface.scss
=> [NL] fix place overview styling

server/lib/nl_page_config.py
=> [NL] filter out pc charts for temperature and precipitation sv's

server/lib/nl_data_spec.py
=> Fix primary sv for contained in query

server/lib/nl_page_config.py
specifically, if one is percentage / prevalence, do the same for the other
=> [NL] ensure both scatter axes are comparable

server/__init__.py, server/routes/nl_interface_next.py
A a new forked copy of the NL route handler for next-version prototyping
The route is localhost:8080/nlnext/
=> [NL-2] new endpoint for next version development

static/js/components/tiles/disaster_event_map_selectors.tsx, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/constants/disaster_event_map_constants.ts
=> [disasters] add last year to date filters

static/css/shared/_tiles.scss, static/js/chart/draw_d3_map.ts, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/types/disaster_event_map_types.ts, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/tests/disaster_event_map_utils.test.ts
- add tooltip that shows place name when hovering over a region
- make dot size match severity
=> [disasters] event map updates

static/css/shared/_tiles.scss, static/js/components/tiles/disaster_event_map_filters.tsx, static/js/components/tiles/disaster_event_map_selectors.tsx, static/js/components/tiles/disaster_event_map_tile.tsx
=> [disasters] make filter section an expando

server/config/disaster_dashboard/Earth.textproto, server/routes/api/disaster_api.py, server/templates/custom_dc/stanford/disaster_dashboard.html, static/css/shared/_tiles.scss, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/utils/disaster_event_map_utils.tsx
- More readable maps - updated colors, dot sizes, fixed droughts
- Rename page
- Add dates to map titles
- Sort categories
- Default to 1 year filter
=> [disasters] map and config improvements

server/__init__.py, server/configmodule.py, server/lib/disaster_dashboard.py, server/routes/api/disaster_api.py, server/tests/routes/api/disaster_test.py, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/constants/disaster_event_map_constants.ts, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/tests/disaster_event_map_utils.test.ts
- add new flask endpoint that reads disaster event map data from saved jsons
- add url hash param that will read data from cache if "&cache=1" is set
=> [disasters] read disaster event map data from saved jsons

.vscode/launch.json
=> add debugger config without NL models

deploy/terraform-datacommons-website/examples/setup/main.tf
enable cloud build and BT admin API for BT automation.
=> [Custom DC] More fixes

static/js/components/tiles/disaster_event_map_filters.tsx
=> [disasters] add delay to severity filter inputs

server/config/disaster_dashboard/Earth.textproto, static/js/components/tiles/disaster_event_map_info_card.tsx
- Update link from map info cards to browser
- Move maps above histograms for each disaster section
- Remove unused drought sv's
=> [disaster] small fixes

server/config/disaster_dashboard/Earth.textproto, static/js/components/tiles/top_event_tile.tsx, static/js/utils/string_utils.ts
also drops histograms while we fix data display consistency issues
=> [disaster] add category for wet bulb; drop histograms

server/routes/nl_interface_next.py
Missed it in https://github.com/datacommonsorg/website/pull/2095 because I had auto-merge on and it submitted despite some failures.
=> [NL Next] Fix minor codacy issues

server/routes/api/disaster_api.py, server/tests/routes/api/disaster_test.py, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/tests/disaster_event_map_utils.test.ts
- update date dropdown to differentiate between using cache or not
- fix duplicates and missing dates in dropdown
=> [disasters] Date dropdown updates

static/js/constants/disaster_event_map_constants.ts, static/js/utils/disaster_event_map_utils.tsx
- use param "json=1" to use json data, otherwise, use cache data
=> [disasters] by default, use cache data

nl_server/__init__.py, nl_server/lib/nl_embeddings.py, nl_server/requirements.txt, nl_server/routes.py, run_nl_server.sh, run_test.sh
In this PR, we have the following:
1. Port over the embeddings loading
2. SV search over the embeddings
A major TODO is to add unit tests. For now, this is just a port from the previous server/services/nl.py
=> [NL Model Server] Embeddings + SV Search

server/lib/nl/nl_data_spec_next.py, server/lib/nl/nl_detection.py, server/routes/nl_interface_next.py, server/services/nl.py
Note this is only used in /nlnext but not /nl, so existing scripts should not be affected.
=> Add a very basic compare classification to unblock fulfillment testing

nl_server/loader.py, server/lib/nl/nl_data_spec_next.py, server/routes/nl_interface.py, server/routes/nl_interface_next.py
This also re-uses the populate_charts() framework, but extends it to support multiple places.
Imminent TODO (hopefully tonight):  unit tests for nl_data_spec_next.py
Example: [auto theft in sunnyvale] -> [compare with palo alto]
=> Initial version of COMPARISON fulfillment

server/config/disaster_dashboard/Earth.textproto, server/routes/api/disaster_api.py, server/tests/routes/api/disaster_test.py
also updated api handling to handle cases where upper or lower limits are unspecified.
=> [disaster] add unit back for cold events

server/lib/nl/nl_data_spec_next.py
=> Change large SV comparisons to use bar charts instead of timeline

scripts/install_custom_dc.sh, server/lib/nl/variable.py
Sanity checked with [male population in california] which pulls in peer vars.
=> Make peer variable checks more resilient to custom DC SVG hierarchy

server/lib/nl/constants.py, server/routes/nl_interface_next.py, server/services/nl.py, static/js/apps/nl_interface/debug_info.tsx
This PR:
* Adds more heuristics to the comparison classifier
* Adds comparison classification results to the debug output
Example screenshot:
=> [NL Next] Improve comparison classification

server/routes/disasters.py, static/js/components/tiles/disaster_event_map_tile.tsx
- update European places to use Euronuts as contained place types instead of admin areas. Fixes map problems for a lot of the european places
=> [disasters] fix european maps

server/lib/nl/utterance.py
Adds event classifiers to utterances.py as followup to PR #2158 .
=> [NL Next] Add event classifier to utterances

static/css/nl_interface.scss
Fixes missing maps on place overviews in the NL interface by adding missing CSS.
=> [NL / NL Next] Fix missing maps for place queries

server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/event.py, server/lib/nl/fulfillment_next.py, server/lib/nl/page_config_next.py, server/lib/nl/utterance.py, server/routes/nl_interface_next.py, server/tests/lib/nl/fulfillment_next_test.py, server/tests/lib/nl/page_config_next_test.py, server/tests/lib/nl/test_utterance.py
This approach is convenient, but adds config dependencies on disaster dashboard that can potentially impact NL.  We will eventually fork the config out to be its own thing.
=> Implement event fulfillment by leveraging disaster dashboard configs

static/css/rich_search.scss, static/js/apps/nl_interface/app.tsx, static/js/apps/nl_interface/query_search.tsx, static/js/components/text_search_bar.tsx, static/js/rich_search/app.tsx
to make testing a sequence of prompts easier on our hands.
e.g. using single query param to enter each spaced 2s apart. each query should be separated by semi-colon.
http://localhost:8080/nlnext/#q=tell%20me%20about%20palo%20alto;what%20about%20auto%20theft;compare%20with%20Berkeley
=> [NL] Add a URL param to put in a series of prompts 2s apart

server/services/nl.py, server/tests/lib/nl/heuristics_test.py
Completes TODO of adding unit testing for the heuristics-based event classifier.
=> [NL Next] Add unit tests for event classifier

server/lib/nl/constants.py, server/lib/nl/detection.py, server/routes/nl_interface_next.py, server/services/nl.py, server/tests/lib/nl/heuristics_test.py, static/js/apps/nl_interface/debug_info.tsx
This PR:
* Adds an "overview" classifier to look for "tell me about <place>" and "more about <place>" queries
* Hooks the classifier up to debug info
* Adds unit-tests for the new classifier
Example:
=> [NL Next] Add overview classifier

server/lib/nl/constants.py, server/lib/nl/fulfillment/overview.py, server/lib/nl/fulfillment_next.py, server/tests/lib/nl/fulfillment_next_test.py, server/tests/lib/nl/page_config_next_test.py, server/tests/lib/nl/test_utterance.py
One classification tweak: allow "tell me more about" (to satisfy current script), beyond just "tell me about"
=> Implement a simple overview fulfiller

docs/developer_guide.md, scripts/deploy_latest.sh
This makes it possible to deploy latest version to dev and other demo instances
=> Deploy latest binary/data to any environment

deploy/base/model.yaml, server/lib/nl/topic.py, server/lib/nl/utils.py
=> Add a topic for income

deploy/base/model.yaml, server/lib/nl/topic.py, server/lib/nl/utils.py
=> [NL Next] Update projected temperature extremes topic with new variables and description

server/config/disaster_dashboard/Earth.textproto, server/config/subject_page.proto, server/config/subject_page_pb2.py, server/lib/nl/page_config_next.py, server/tests/lib/nl/page_config_next_test.py, static/js/components/tiles/top_event_tile.tsx, static/js/types/subject_page_proto_types.ts, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/tests/disaster_event_map_utils.test.ts
=> [NL] show end date on top event ranking tile

deploy/base/model.yaml, server/lib/nl/page_config_next.py
=> Prefix "Related" to SECONDARY charts and drop abs temp SVs

deploy/overlays/autopush/kustomization.yaml, deploy/overlays/dev/kustomization.yaml, scripts/deploy_latest.sh
Reduce replica given recent memory increase in NL server.
Fix deploy_latest git sync issue
=> Some deployment update

.dockerignore, .gitignore, nl_server/__init__.py, nl_server/main.py, nl_server/routes.py, nl_server/tests/embeddings_test.py, pytest.ini, server/__init__.py, server/configmodule.py, server/lib/util.py, server/main.py, server/routes/nl_interface_next.py, server/routes/static.py, server/tests/chart_config_test.py
* Use absolute path for configs
* Add pytest config file so it's easier to see log output
* Move all flask app code inside create_app() function
* extract backend check into util functions
* disable "ADMIN" in configmodule as that is not used in any instances
* Only use "POST" for /nlnext/data as the code does not work for "GET"
=> [Flask Server] A bunch of improvement clean up to get read for integration test

deploy/gke/demo.yaml, deploy/gke/feedingamerica.yaml, deploy/gke/stanford-staging.yaml, deploy/gke/stanford.yaml, deploy/gke/tidal.yaml, scripts/deploy_gke.sh, scripts/deploy_latest.sh
added more warnings / comments to deploy scripts
added required `others` cluster info
=> [custom_dc] comments, others

server/routes/disasters.py
- should draw countries for Europe, not EuroNUTS1
=> [disasters] fix europe map

server/routes/api/choropleth.py, server/tests/routes/api/choropleth_test.py
- one of the AA1 regions were not being drawn because we have multiple property values for it.
=> [map] fix bangladesh AA1 map

server/config/disaster_dashboard/Earth.textproto, static/css/shared/_tiles.scss
requested changes:
- add end date for droughts
- remove end date for fires (temporarily)
also added paths and polygons to main map
=> [disaster] display tweaks

server/config/disaster_dashboard/Earth.textproto, server/integration_tests/test_data/demo_feb2023/query_2/chart_config.json, server/routes/disasters.py
Increase fire lower limit further for all places (and override to 500 sq km for Earth)
Update color of droughts
before:
after:
=> [Disasters] reduce fires

deploy/base/model.yaml, server/integration_tests/nlnext_test.py, server/integration_tests/test_data/demo2_cities_feb2023/query_1/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_1/debug_info.json, server/integration_tests/test_data/demo2_cities_feb2023/query_2/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_2/debug_info.json, server/lib/nl/fulfillment/comparison.py, server/lib/nl/topic.py, server/lib/nl/utils.py
Main sheet edit: Removed the prior 5 SVs (that are being added to the topic), and added entry for `dc/topic/WorkCommute`.
Also, while comparing across places, include per-capita.
=> NL: Implement a topic for commute

server/routes/api/place.py, static/js/components/tiles/ranking_tile.tsx, static/js/tools/timeline/data_fetcher.test.ts, static/js/tools/timeline/data_fetcher.ts, static/js/tools/timeline/mock_functions.tsx, static/js/utils/place_utils.ts
add state code when states differ across the list of places:
don't add state code if all places are from the same state:
=> [ranking tile] add state code for USA place name

deploy/base/model.yaml, server/lib/nl/variable.py
Both are >0.5 in the queries we have
=> Update index with two SVs in Magiceye demo

server/__init__.py, server/configmodule.py
=> Only load disaster json data when ENABLE_DISASTER_JSON=true

server/integration_tests/test_data/demo2_cities_feb2023/query_2/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_6/chart_config.json, server/lib/nl/page_config_builder.py, server/lib/nl/utils.py, server/tests/lib/nl/page_config_builder_test.py
=> [NL] add units for percent svs

server/integration_tests/nlnext_test.py, server/integration_tests/test_data/demo_feb2023/query_10/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_10/debug_info.json, server/lib/nl/fulfillment/overview.py, server/lib/nl/fulfillment/simple.py
This translate to:
- For SIMPLE case, either SV or place has to be present in the current query.
- For OVERVIEW case, place has to be present in the current query.
=> In the absence of both SV and place, avoid reading from context

static/js/constants/app/nl_interface_constants.ts, static/js/utils/tile_utils.tsx
=> [nl] update source name from datacommons to google

server/routes/nl.py, server/templates/nl_interface.html, static/css/nl_interface.scss, static/js/apps/nl_interface/app.tsx, static/js/apps/nl_interface/debug_info.tsx, static/js/apps/nl_interface/main.ts
- also fixed an error about `<tr>` can not be a child of a `<td>`
=> [nl] Add feedback link

static/css/nl_interface.scss, static/css/shared/_tiles.scss
=> [nl] fix font color for place overview tile

deploy/base/model.yaml, server/lib/nl/fulfillment/ranking_across_vars.py, server/lib/nl/topic.py
=> Add Climate TRACE Variables to the NL index

server/integration_tests/nlnext_test.py, server/integration_tests/test_data/demo_climatetrace/query_1/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_1/chart_config.json, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/correlation.py, server/lib/nl/fulfillment/time_delta_across_places.py, server/lib/nl/page_config_builder.py
=> Add default places for certain child types; fix min-temp ranking bug

server/integration_tests/test_data/demo2_cities_feb2023/query_1/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_7/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_8/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_9/chart_config.json, server/lib/nl/page_config_builder.py, server/tests/lib/nl/page_config_builder_test.py, static/js/components/tiles/bar_tile.tsx, static/js/components/tiles/line_tile.tsx, static/js/components/tiles/map_tile.tsx, static/js/components/tiles/ranking_tile.tsx, static/js/components/tiles/scatter_tile.tsx, static/js/i18n/i18n.tsx, static/js/utils/string_utils.ts, static/js/utils/tile_utils.tsx
- get units from data fetch for the tiles
=> [tiles] add units for tiles

static/js/components/tiles/histogram_tile.tsx
- Missed a place where formatNumber function needed to be passed to drawHistogram
=> Fix a bug from formatNumber change

static/js/tools/map/chart_loader.tsx
Discovered this in custom DC setup
=> Fix null dom ref for BQ download link

scripts/deploy_gke.sh, scripts/deploy_latest.sh, server/lib/render.py, server/templates/custom_dc/custom/about.html, server/templates/custom_dc/custom/base.html, server/templates/custom_dc/custom/disclaimers.html, server/templates/custom_dc/custom/faq.html, server/templates/custom_dc/custom/homepage.html, server/templates/custom_dc/custom/new.html
deploy_gke.sh is updated with named args, instead of positional args now. All references should be updated.
Added more html template and place holder file for change
=> Updates and fixes for custom DC UI/deployment

server/routes/api/disease.py, server/routes/api/protein.py, server/services/datacommons.py, server/services/discovery.py
Tested locally with charts matching autopush instance.
=> Use V1 API for bio page data fetch

server/integration_tests/test_data/demo_climatetrace/query_1/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_7/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_8/chart_config.json, server/integration_tests/test_data/place_detection_e2e/query_2/chart_config.json, server/integration_tests/test_data/place_detection_e2e/query_6/chart_config.json, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/correlation.py, server/lib/nl/page_config_builder.py, server/lib/util.py, server/tests/lib/nl/page_config_builder_test.py
* Fix a couple of crashes I found on [GCP console](https://pantheon.corp.google.com/errors;service=;version=;time=P7D?project=datcom-website-autopush&mods=-monitoring_api_staging).
* Fix a regression to [floods in the world]
* Add dates for map charts (https://github.com/datacommonsorg/website/issues/2392)
=> NL: Fixes minor crashes and add dates for maps

server/routes/api/node.py, static/js/components/subject_page/data_context.ts, static/js/components/subject_page/main_pane.tsx, static/js/components/tiles/disaster_event_map_info_card.tsx, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/components/tiles/top_event_tile.tsx, static/js/types/disaster_event_map_types.ts, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/geojson_utils.ts, static/js/utils/tests/disaster_event_map_utils.test.ts, static/package-lock.json, static/package.json
- remove unused european places fetch
- don't make node geojson fetch if geojson is already in the event point's prop vals
- only fetch parent places if not already passed as a prop to subject page
bug fixes along the way:
- fix info card properties displayed so that there aren't any duplicates
- use post to get propvals in top event tile (some get requests were getting too long because of too many dcids)
=> [disasters] optimizations part 1

server/routes/nl.py
Previous: used to remove all place strings found even if only some of them got a valid DCID resolution. This was also reported as bug (by @jehangiramjad ) in the NL queries testing for the query: "show me the richest county in California" where NER place detection found "richest county" and "California" as possible places but only found California with a valid DCID. But, "richest county" was also removed from the query for further attribution/classification/SV detection. This meant that the query was not classified as "contained in = COUNTY" because the word "county" was removed.
Now: only removing place strings for which a DCID was found. In the example above, only "California" is removed. See the screenshot below for the debugInfo showing the correct handling + the other screenshot …
=> [NL Interface bug fix] Only remove place strings for which we found a DCID

server/integration_tests/test_data/demo_climatetrace/query_1/chart_config.json, server/lib/nl/fulfillment/base.py, server/lib/nl/page_config_builder.py
=> Fallback from Continent to Earth

server/lib/nl/counters.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/comparison.py, server/lib/nl/fulfillment/containedin.py, server/lib/nl/fulfillment/correlation.py, server/lib/nl/fulfillment/event.py, server/lib/nl/fulfillment/overview.py, server/lib/nl/fulfillment/ranking_across_places.py, server/lib/nl/fulfillment/ranking_across_vars.py, server/lib/nl/fulfillment/simple.py, server/lib/nl/fulfillment/size_across_entities.py, server/lib/nl/fulfillment/time_delta_across_places.py, server/lib/nl/fulfillment/time_delta_across_vars.py, static/js/apps/nl_interface/query_result.tsx
Fix regression introduced in https://github.com/datacommonsorg/website/pull/2409, where if page-config is empty, we don't show up debug info.
Also, Jehangir's review comments from https://github.com/datacommonsorg/website/pull/2409.
=> NL: minor counter fixes and fix debug info regression

server/routes/disasters.py, server/templates/custom_dc/stanford/disaster_dashboard.html, static/js/apps/disaster_dashboard/app.tsx, static/js/apps/disaster_dashboard/child_places.tsx, static/js/apps/disaster_dashboard/main.ts, static/js/chart/draw_d3_map.ts, static/js/components/tiles/disaster_event_map_tile.tsx
- remove child place fetch
- remove unnecessary blocking calculation when adding map points
- remove unnecessary node geojson call
=> [disaster] some more optimizations

server/config/subject_page/events.textproto, server/config/subject_page/sustainability.textproto, server/lib/subject_page_config.py, server/routes/disasters.py, server/routes/event.py, server/routes/sustainability.py
We currently throw an error if there aren't any child place types to fetch (if we are on a leaf page according to the config), introduced in #2448 
Also fixed a couple of strange sounding chart titles
=> [disasters] fix bug with leaf pages

server/lib/subject_page_config.py
- Added more logging to debug flaky sustainability/Earth page (logging lines are quite verbose so these are temporary)
- Fix a small bug
=> [sustainability] add more logging

static/js/components/subject_page/main_pane.tsx, static/js/utils/geojson_utils.ts
- add geojson drawing for cities
- handle when no geojson found
=> [disasters] handle empty geojson

server/lib/util.py, server/services/datacommons.py, server/services/discovery.py, server/tests/routes/api/point_test.py, server/tests/routes/api/series_test.py
=> For unit display, use name if not shortDisplayName

server/routes/topic_page.py, server/templates/topic_page.html, static/js/apps/topic_page/app.tsx, static/js/apps/topic_page/main.ts, static/js/apps/topic_page/page_selector.tsx
This is not the most cleanest way to do this in topic page. If we want to support multiple places for all topic pages, might need to re-structure the data fetch.
=> Show all place names from url params

scripts/deploy_gke.sh
`-i`'s suffix shouldn't have a space.
=> Fix `sed` on linux

deploy/base/custom_bigtable_info.yaml, scripts/deploy_gke.sh
This script allows something like this:
./scripts/deploy_gke.sh -p iqss-gdc  -t import_group1_test_2023_03_24_12_00_04 -h f730596
https://gdc.dataverse.org/tools/statvar#sv=Count_MedicalConditionIncident_Contract_COVID
=> Support modification of custom BT tables in deploy_gke.sh

server/integration_tests/test_data/demo_feb2023/query_9/chart_config.json, server/integration_tests/test_data/multisv/query_1/chart_config.json, server/lib/nl/page_config_builder.py, server/tests/lib/nl/page_config_builder_test.py
Bug: https://github.com/datacommonsorg/website/issues/2548
=> NL: Fix dates in scatter title

static/js/tools/scatter/app.test.tsx
This PR fixes some issues in the scatter plot "all functionalities" test case. Previously, a bug in the test's promise/callback structure was preventing it from actually enforcing some of the nested assertions.
Also:
* Flattened nested promises in "all functionalities" test
* Added SVGElement stubs for methods that only exist in the browser
* Updated axios mocks to reflect current call chain workflow
=> [scatter] Updated scatter app test

.gitignore, deploy/helm_charts/dc_website/templates/service.yaml, deploy/helm_charts/dc_website/values.yaml, deploy/helm_charts/envs/autopush.yaml, deploy/helm_charts/envs/custom.yaml, scripts/deploy_gke_helm.sh
Also remove the IAP gke secret; Updated some constants; Make embedding file in the base config.
=> Add autopush yaml for website helm chart

static/js/chart/draw_d3_map.ts
=> [map] fix color bug when value is 0

deploy/base/deployment.yaml, deploy/helm_charts/dc_website/README.md, deploy/helm_charts/dc_website/values.yaml, deploy/helm_charts/envs/autopush.yaml, deploy/helm_charts/envs/custom.yaml, deploy/helm_charts/envs/dev.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/climate_trace/kustomization.yaml, deploy/overlays/custom/kustomization.yaml, deploy/overlays/custom_kustomization.yaml.tpl, deploy/overlays/dev/kustomization.yaml, deploy/overlays/feedingamerica/kustomization.yaml, deploy/overlays/iitm/kustomization.yaml, deploy/overlays/kustomization.yaml.tpl, deploy/overlays/local/kustomization.yaml, deploy/overlays/magiceye/kustomization.yaml, deploy/overlays/prod/kustomization.yaml, deploy/overlays/staging/kustomization.yaml, deploy/overlays/stanford/kustomization.yaml, deploy/overlays/stanford_staging/kustomization.yaml, deploy/overlays/tidal/kustomization.yaml, deploy/terraform-datacommons-website/modules/helm/main.tf, deploy/terraform-datacommons-website/test/website_v1_test.go, docs/new_deployment.md, scripts/deploy_gke_helm.sh
A follow up change for https://github.com/datacommonsorg/mixer/pull/1111
=> Update mixer project flag in deployment configs

scripts/deploy_gke_helm.sh
- Do not enable mixer ingress
- Specify custom project id for image
=> Fix deploy_gke_helm for custom instances

build/ci/cloudbuild.webdriver.yaml, run_test.sh, server/requirements.txt, server/webdriver_tests/base_test.py, server/webdriver_tests/screenshot/screenshot_test.py, server/webdriver_tests/shared.py, server/webdriver_tests/tests/browser_test.py, server/webdriver_tests/tests/download_test.py, server/webdriver_tests/tests/homepage_test.py, server/webdriver_tests/tests/map_test.py, server/webdriver_tests/tests/place_explorer_i18n_test.py, server/webdriver_tests/tests/place_explorer_test.py, server/webdriver_tests/tests/place_landing_test.py, server/webdriver_tests/tests/ranking_test.py, server/webdriver_tests/tests/scatter_test.py, server/webdriver_tests/tests/timeline_test.py
* Use new syntax for find_elements
* Use "--headless=new"
=> Upgrade selenium to the latest (4.9)

static/css/import_wizard2.scss
- remove scrolling of template options
- update sizing of template options
=> [import wizard] update template page layout

deploy/helm_charts/dc_website/templates/config_maps.yaml, deploy/helm_charts/dc_website/templates/deployment.yaml, deploy/helm_charts/dc_website/values.yaml, deploy/helm_charts/envs/custom.yaml, deploy/helm_charts/envs/prod.yaml, deploy/helm_charts/envs/staging.yaml, server/__init__.py, server/app_env/_base.py, server/app_env/climate_trace.py, server/app_env/production.py, server/app_env/staging.py, server/app_env/stanford.py, server/app_env/stanford_staging.py, server/routes/shared_api/variable_group.py
- Get blocklisted svgs from environment file
- set blocklisted svgs file in each helm chart
=> [stat var hierarchy] separate blocklist svgs for each environment

server/lib/fetch.py, server/lib/nl/topic.py, server/lib/nl/utils.py, server/lib/nl/variable.py, server/lib/shared.py, server/lib/subject_page_config.py, server/lib/util.py, server/routes/browser/api.py, server/routes/disease/api.py, server/routes/event/html.py, server/routes/place_list/html.py, server/routes/protein/api.py, server/routes/shared_api/choropleth.py, server/routes/shared_api/node.py, server/routes/shared_api/observation/point.py, server/routes/shared_api/observation/series.py, server/routes/shared_api/place.py, server/routes/shared_api/stats.py, server/services/datacommons.py, server/tests/lib/shared_test.py, server/tests/routes/api/choropleth_test.py, server/tests/routes/api/landing_page_test.py, server/tests/routes/api/place_test.py
There are quite some duplicate functions to fetch data (and with similar response data structure).
This is to consolidate and have all data fetch functions into one "fetch" module. This makes it easier to test, inspect and do data conversion for API update.
=> Create a fetch module to hold all data fetch functions

static/js/components/tiles/line_tile.tsx
Refactor so the data fetch can be reused by server side rendering too
=> line tile async fetch data

static/js/components/tiles/line_tile.tsx, static/package-lock.json, static/package.json, static/src/server.ts
This does not fully work due to getBBox() function not available on the server side.
Check this in so we have an e2e flow to work on.
=> [Node Server] Render line tile on server side and return svg

static/js/components/google_map.tsx
- fixes map not showing up due to bug in getting lat lng of marker location
=> [browser] fix map not showing up

static/js/components/tiles/chart_tile.tsx, static/js/components/tiles/map_tile.tsx, static/js/utils/tile_utils.tsx
- add the merged (map + legend) svg to the data attribute of map tile if the map is a data tile
=> [tiles] add merged svg in data attribute for map tile

static/js/utils/chart_csv_utils.ts, static/js/utils/tests/chart_csv_utils.test.ts
make the order of the rows in the data csv deterministic (for map and scatter)
=> [tiles] make data csv deterministic

server/lib/fetch.py, server/lib/nl/detection.py, server/lib/nl/utils.py, server/routes/nl/api.py
Fix edge-case return value from api, for:
- (empty string)
Add more types to ContainedInPlaceType, for:
- Which cities in the San Francisco Peninsula have the most parks 
- how many people unemployed in the bay area? 
- income to live comfortably in the bay area 
- auto thefts in Beverly Grove
- how safe is london
- most burglaries in new york state
- what is the crime rate in guatemala
Check existence before map access in API libs, for:
- cities in USA that have seen the biggest shrinking in median income
- where were the major earthquakes in california
=> NL: Fix a few crash bugs triggered by queries in queryset

server/routes/import_wizard/html.py, server/tests/routes/import_wizard_test.py
- enable the new import wizard on prod/staging
- update routes so that new import wizard is at /import & old import wizard is at /import/old
=> enable import wizard on prod

deploy/helm_charts/envs/custom.yaml, deploy/helm_charts/envs/feedingamerica.yaml, deploy/helm_charts/envs/prod.yaml, deploy/helm_charts/envs/staging.yaml, deploy/helm_charts/envs/stanford.yaml, deploy/helm_charts/envs/stanford_staging.yaml, deploy/helm_charts/envs/unsdg.yaml
- update mixer
- add oecd to svg blocklist
=> update mixer at v2.8.3

scripts/deploy_latest.sh
The table could be empty for newly created import group.
=> Check latest bigtable version is not empty for autopush deployment

server/config/subject_page/events.textproto
Also, add Count_WildlandFireEvent to the event-page config.
Validation -
=> Update Mixer submodule

server/app_env/stanford.py, server/templates/custom_dc/stanford/base.html, server/templates/custom_dc/stanford/homepage.html, static/custom_dc/stanford/overrides.css
Change from https://github.com/datacommonsorg/website/pull/2781
=> Stanford DC theme update

server/templates/tools/download.html, server/templates/tools/map.html, server/templates/tools/timeline.html
on map, timeline, and download tool
=> hide BQ button for custom dc

deploy/helm_charts/envs/climate_trace.yaml, deploy/helm_charts/envs/custom.yaml, deploy/helm_charts/envs/custom_dc_template.yaml, deploy/helm_charts/envs/dev.yaml, deploy/helm_charts/envs/prod.yaml, deploy/helm_charts/envs/staging.yaml, deploy/helm_charts/envs/techsoup.yaml
Use remote mixer for climate trace, custom and custom template
Remove unused fields in helm values.
=> Update a bunch custom DC instance deployment config

server/config/topic_page/equity/US_Places.textproto, server/lib/subject_page_config.py, server/routes/topic_page/html.py, server/tests/test_data/existence_expect.textproto
- add climate equity scatter charts
- update topic pages to remove empty charts
North Carolina:
Wayne County:
=> [topic page] Add climate equity charts

server/config/topic_page/equity/US_Places.textproto, static/css/shared/_tiles.scss
- update the sv name for the projected temperature sv
- fix scatter plot tooltip hover
=> [topic pages] equity page update

server/lib/gcs.py, server/requirements.txt, server/routes/screenshot/diff.py, server/routes/screenshot/html.py, server/templates/screenshot.html, server/tests/routes/screenshot_test.py, server/webdriver_tests/screenshot/screenshot_test.py, static/css/screenshot.scss, static/webpack.config.js
Example diff (with minor source order change)
=> Compare screenshot images from two commit

gke/README.md, gke/update_config_cluster.sh, scripts/deploy_latest.sh
to update a cluster's config, need to first get gke credentials for that cluster before applying the config files
=> [node server] update the update config cluster script

experimental/sdg-static/index.html, experimental/sdg-static/styles/index.css
=> Updated styles on static sdg tracker

static/js/place/child_places_menu.tsx
This is found from the screenshot diff
https://autopush.datacommons.org/screenshot/compare/edeb637...5c8c093
=> Sort the place type in place page child places list

server/lib/nl/common/debug_utils.py, server/lib/nl/common/topic.py, server/lib/nl/config_builder/timeline.py, static/js/apps/nl_interface/debug_info.tsx
This is to allow topics to contain other topics.
=> Support recursive topics and fix minor bugs

server/webdriver/screenshot/local/page.json, server/webdriver/screenshot/remote/main.py, server/webdriver/screenshot/runner.py, server/webdriver/shared.py, static/js/browser/app.tsx, static/js/browser/out_arc_section.tsx, static/js/components/tiles/sv_ranking_units.tsx, static/js/components/tiles/top_event_tile.tsx, static/js/tools/stat_var/explorer.tsx
Also fix a stat var page source bug
=> Add more screenshot test case

build/ci/cloudbuild.nl.yaml, build/ci/cloudbuild.push_image.yaml, build/ci/cloudbuild.screenshot.yaml, build/ci/cloudbuild.webdriver.yaml, build/webdriver-chrome/Dockerfile, build/webdriver-chrome/cloudbuild.yaml, nl_server/__init__.py, nl_server/loader.py, run_test.sh, server/integration_tests/nl_screenshot_test.py, server/integration_tests/nlnext_test.py, server/routes/screenshot/html.py, server/webdriver/base.py, server/webdriver/screenshot/local/page.json, server/webdriver/tests/event_page_test.py, shared/lib/test_server.py, static/js/components/ranking_unit.tsx, static/js/place/overview.tsx, static/js/place/ranking.tsx
* Abstract out the test server setup as a base class
* Install default font for ubuntu
=> Add screenshot capture for NL page

experimental/datacommons-js/example.html, static/js/components/tiles/ranking_tile.tsx, static/library/index.ts, static/library/ranking_component.ts
Add a Ranking Chart web component based on the ranking tile
Example screenshot:
=> [Library] Add ranking chart web component

static/src/server.ts
- add timing info for the node server
=> [node server] add timing info

server/routes/nl/api.py, server/services/bigtable.py, static/js/apps/nl_interface/nl_options.tsx, static/js/apps/nl_interface/query_result.tsx
The new MultiVarCandidates can not be dumped by json, using pickle instead.
Also fix some other small issues.
=> Fix json dump bug in NL logging

server/routes/browser/html.py
Add landing page for bio browser
=> Bio browser landing

server/routes/nl/api.py, server/services/bigtable.py, static/css/shared/_tiles.scss, static/js/apps/nl_interface/query_result.tsx, static/js/components/subject_page/column.tsx, static/js/components/tiles/chart_tile.tsx, static/js/types/app/nl_interface_types.ts
=> NL feedback client side support

experimental/sdg-static/stories.html
Add a standalone html page demonstrating how our webcomponents can be integrated into a simple webpage.
Replit: https://replit.com/@JuliaWu7/SDG-Stories-Page
=> [Experimental] Add stand-alone example story page

server/templates/browser/bio_landing.html
=> [bio] landing page updates

experimental/sdg-static/stories.html
=> SDG page visual tweak

server/lib/nl/detection/place.py
This small fix fixes the broken integration test.
The current failure is happening because the Maps API has started to return results in a different order where searching for "new york state" is returning "Staten Island" above "New York State". In this fix, we check the results returned and prefer an exact (lowercase) match instead of the first result.
=> [NL Interface] Integration test failure fix

static/js/components/tiles/map_tile.tsx
This fixes a bug where the map tile wouldn't render properly if it was constructed while hidden from view
=> Added useDrawOnResize to map tile. 

static/css/datacommons.scss, static/webpack.config.js, web-components/README.md, web-components/examples/example.html
Consolidated library css imports
=> Added datacommons.css

static/js/utils/nl_interface_utils.ts
update nl interface to use this shorter feedback form instead that just asks user for their feedback: https://forms.gle/ADxVJzmjid3ynBo26
=> [nl interface] update the feedback form being used

static/src/server.ts
- update chartUrl param so that default returns chartUrl, but &chartUrl=0 will return svg
=> [node server] update chart url param

server/templates/static/homepage.html, static/css/homepage.scss
=> updated homepage styles, swapped tools/partners sections

static/css/base.scss, static/css/homepage.scss
- update the nav bar color by updating dc primary color
- this also updates the color of links, some buttons, etc. which I think is ok and makes sense to do?
=> update dc primary color

server/config/nl_page/chart_titles_by_sv.json, server/integration_tests/test_data/demo_feb2023/query_7/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_8/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_9/chart_config.json
Updating the chart title for SV: Percent_Person_18OrMoreYears_WithHighBloodPressure_ReceivedTakingBloodPressureMedication
=> [NL Interface] Updating SV chart title

static/js/apps/nl_interface/nl_commentary.tsx, static/js/apps/nl_interface/query_result.tsx
=> NL: Drop the click-to-see-charts behavior

static/css/shared/_tiles.scss, static/js/components/nl_feedback.tsx, static/js/utils/nl_interface_utils.ts
=> Added tooltips to feedback buttons

server/__init__.py, server/routes/insights/html.py, server/templates/insights.html, static/css/insights.scss, static/js/apps/insights/app.tsx, static/js/apps/insights/main.ts, static/webpack.config.js
=> Added insights skeleton page

server/routes/nl/api.py, static/js/apps/insights/app.tsx
This is just to debug/see topics that we create.
=> Insights: display chart config given topic and place

static/css/insights.scss, static/js/apps/insights/app.tsx
Now opens up a new browser page for the query result.
=> [Insight Page] Add NL search box

server/routes/nl/html.py, server/templates/nl_interface.html, static/js/apps/nl_interface/app_state.ts
=> [nl] add /nl/sdg route that used sdg_ft index

static/css/insights.scss, static/js/apps/insights/app.tsx
=> Callout the current place

server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_childtype/chart_config.json, server/lib/insights/fulfiller.py, server/lib/nl/common/utils.py, server/lib/nl/detection/detector.py, server/lib/nl/detection/place.py, server/lib/nl/detection/types.py, server/routes/insights/api.py, static/js/apps/insights/parent_breadcrumbs.tsx
Stop using place_metadata() instead piggy-back on existing API calls.
=> Insights: optimize and check parent/child places

server/lib/insights/chart_builder.py, server/lib/insights/fulfiller.py, server/lib/nl/common/topic.py, server/lib/nl/common/variable.py, server/lib/nl/fulfillment/existence.py, server/lib/nl/fulfillment/types.py
The sub-categories of HealthEquity are the 6 topics under it: https://autopush.datacommons.org/browser/dc/topic/HealthEquity
=> Insights: Organize charts by sub-topic categories

static/css/shared/_tiles.scss, static/css/tools/visualization.scss, static/js/apps/visualization/app_context.tsx, static/js/apps/visualization/chart.tsx, static/js/apps/visualization/selected_options.tsx, static/js/components/tiles/line_tile.tsx, static/js/components/tiles/map_tile.tsx, static/js/components/tiles/scatter_tile.tsx, static/js/shared/ga_events.test.tsx, static/js/tools/timeline/__snapshots__/page.test.tsx.snap, static/js/tools/timeline/chart.tsx, static/js/tools/timeline/chart_region.tsx, static/js/tools/timeline/page.test.tsx, static/js/utils/app/timeline_utils.ts, static/js/utils/app/visualization_utils.ts
- render a map, scatter, or timeline tile depending on selections
=> [tools revamp] render simple charts based off selections

server/templates/base.html, server/templates/static/homepage.html
- update links in the nav bar, homepage, and footer to point to the new visualization tool
=> [tools revamp] update tool links to new vis tool

server/config/topic_page/dev/CA.textproto, server/templates/topic_page.html, static/css/shared/_subject_page.scss, static/js/components/subject_page/block.tsx, static/js/components/subject_page/category.tsx, static/js/components/subject_page/stat_var_provider.ts, static/js/components/tiles/bar_tile.tsx, static/js/components/tiles/bivariate_tile.tsx, static/js/components/tiles/gauge_tile.tsx
- UI changes to allow for block level per capita option
=> [subject page] add block level per capita option

static/css/insights.scss, static/css/shared/story_block.scss, static/js/apps/insights/app.tsx
=> Align search box to the RHS section; Make left menu narrower

server/integration_tests/test_data/demo_feb2023/query_6/chart_config.json, server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_comparison/chart_config.json, server/integration_tests/test_data/fulfillment_api_correlation/chart_config.json, server/integration_tests/test_data/sdg/query_3/chart_config.json, server/lib/insights/fulfiller.py, server/lib/insights/page.py, server/lib/insights/page_type/builder.py, server/lib/insights/page_type/fallback.py, server/lib/insights/topic.py, server/lib/nl/common/topic.py, server/lib/nl/detection/detector.py, server/routes/insights/api.py, server/templates/insights.html, static/css/insights.scss, static/js/apps/insights/app.tsx
1. Empty page fallback to place overview
2. Per-capita plumbing
3. Read ordered topics
Life Expectancy is on top for dc/topic/LifeExpectancy:
=> Explore: 3 features

server/__init__.py, server/lib/nl/common/variable.py, server/lib/nl/fulfillment/time_delta_across_places.py, server/lib/nl/fulfillment/time_delta_across_vars.py, server/lib/shared.py, server/routes/insights/api.py, server/routes/nl/helpers.py, server/routes/shared_api/stats.py, server/tests/routes/api/stats_test.py, static/js/apps/visualization/vis_type_configs/map_config.tsx, static/js/apps/visualization/vis_type_configs/scatter_config.tsx, static/js/apps/visualization/vis_type_configs/timeline_config.tsx, static/js/shared/stat_var.ts, static/js/utils/app/visualization_utils.tsx
- extract out the nl check for whether per capita is relevant for a stat var
- use that check to decide whether or not to show the per capita option on a vis tool chart
=> [tools revamp] update when to show the per capita option

static/js/apps/explore/app.tsx, static/js/apps/insights/app.tsx, static/js/apps/insights/sidebar.tsx
* Clear query when clicking on a LHS menu
* Text on topic landing page
* React key issue
=> Fix a bunch of UI bugs

static/js/apps/nl_interface/sidebar.tsx
=> NL: change marketing speak on NL for Camp demo

server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_statvars/chart_config.json, server/lib/insights/page.py, server/lib/insights/page_type/builder.py, server/lib/insights/page_type/default.py
=> Insights: make map+rank as its own block

server/__init__.py, server/integration_tests/test_data/fulfillment_api_statvars/chart_config.json, server/lib/nl/common/topic.py
Make the logic work without the TOPIC_CACHE so we can be more flexible in future.
=> Disable topic cache

server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_statvars/chart_config.json, server/lib/insights/page_type/default.py, server/lib/nl/common/utils.py, server/lib/nl/fulfillment/context.py, server/routes/insights/api.py, server/routes/nl/api.py, server/routes/nl/helpers.py, static/js/apps/insights/app.tsx, static/js/types/subject_page_types.ts
I'm not fully sure why the emojis are bigger than NL. They use the same shared css within tiles.
=> Show emojis on insights pages

server/config/nl_page/topic_cache.json, server/integration_tests/test_data/fulfillment_api_statvars/chart_config.json, server/lib/explore/page_type/default.py, server/lib/nl/fulfillment/handlers.py, static/js/apps/explore_landing/topics.json
1. Add a highlight chart alongside single-var timeline
2. Fix for the [highest gini index in the world] query in NL
3. Fix query wordings per Guha's suggestion
=> NL/Explore: fix some bugs, improve layout

server/templates/base.html
- hide the navigation links for disaster dashboard and sustainability explorer
-
=> hide nav links for dashboards

server/config/nl_page/topic_cache.json, server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_comparison/chart_config.json, server/integration_tests/test_data/fulfillment_api_correlation/chart_config.json
Includes fixes till https://github.com/datacommonsorg/schema/commit/47737793aefd3e383fee40bff64ca56a374fcc79
=> Update topic_cache with fixed sustainability, etc

server/integration_tests/test_data/demo2_cities_feb2023/query_3/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_4/chart_config.json, server/integration_tests/test_data/demo_climatetrace/query_1/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_6/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_7/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_8/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_9/chart_config.json, server/integration_tests/test_data/multisv/query_1/chart_config.json, server/integration_tests/test_data/multisv/query_2/chart_config.json, server/integration_tests/test_data/place_detection_e2e/query_6/chart_config.json, server/integration_tests/test_data/place_detection_e2e_dc/query_6/chart_config.json, server/integration_tests/test_data/sdg/query_1/chart_config.json, server/integration_tests/test_data/sdg/query_3/chart_config.json, server/lib/explore/topic.py, server/lib/nl/common/topic.py, server/tests/lib/nl/page_config_builder_test.py
For improved ordering of results, performance and time-to-build...
=> NL: modify NL to use topic_cache

static/js/apps/explore_landing/topics.json
Add "+" instead of spaces in the url of a query in topics.json
=> Fix query in topics.json

server/templates/explore.html, static/js/utils/app/visualization_utils.tsx
- add footer for explore page
- fix bug in vis tool
=> small updates

static/css/nl_interface.scss, static/js/components/nl_feedback.tsx
=> adjust feedback form appearance

server/templates/explore_landing.html
=> Added byline footer to search/explore page

server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_expansion/chart_config.json, server/integration_tests/test_data/fulfillment_api_statvars/chart_config.json, server/lib/explore/extension.py, server/lib/explore/fulfiller.py, server/lib/explore/page_type/default_main.py, server/lib/explore/params.py, server/lib/nl/common/variable_group.py, server/lib/nl/config_builder/ranking.py, static/js/apps/explore/app.tsx
For example, `/explore/#t=dc/topic/HealthConditions&p=country/AUS&pcmp=&pt=&svg=dc/g/Person_MedicalCondition` will now have a lot more data
=> Param for topic extension + single ranking chart

server/templates/disaster_dashboard.html, server/webdriver/tests/place_explorer_test.py, static/css/draw.scss, static/css/explore.scss, static/css/shared/_subject_page.scss, static/css/shared/_tiles.scss, static/js/components/nl_feedback.tsx, static/js/components/ranking_unit.tsx, static/js/components/subject_page/block.tsx, static/js/components/tiles/bar_tile.tsx, static/js/components/tiles/bivariate_tile.tsx, static/js/components/tiles/chart_footer.tsx, static/js/components/tiles/chart_tile.tsx, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/components/tiles/highlight_tile.tsx, static/js/components/tiles/histogram_tile.tsx, static/js/components/tiles/line_tile.tsx, static/js/components/tiles/map_tile.tsx, static/js/components/tiles/ranking_tile.tsx, static/js/components/tiles/scatter_tile.tsx, static/js/components/tiles/sv_ranking_units.tsx, static/js/components/tiles/top_event_tile.tsx, static/js/utils/tile_utils.tsx
- update font sizing/padding/etc
- move sources
- update tile footers
- update icons
- add source to highlight tile
- update per capita selecotr
- update line tile legend
- stretch map to be the same size as ranking
=> [explore/search] results UI changes round 1

server/templates/nl_interface.html
=> Fix icons on NL tiles

static/css/explore_landing.scss, static/js/shared/topic_queries.tsx
* Increased spacing between topic queries.
* Updated font to Google Sans.
* Removed additional data blob.
* Updated section headers.
[explore-landing-page.webm](https://github.com/datacommonsorg/website/assets/1221814/99965aca-5f38-4449-896a-728cc0d902da)
=> Apply style changes to explore landing pages.

static/css/explore.scss, static/css/explore_landing.scss, static/css/shared/item_list.scss, static/js/apps/explore/item_list.tsx
=> Fixed item list rendering

static/css/homepage.scss
- Fixed tools/learn more text styling
- Added wrapping to partner logos
=> Homepage style fixes

build/ci/cloudbuild.deploy.yaml, build/ci/cloudbuild.push_image.yaml, build/python_node_go_protoc_envoy/Dockerfile, build/python_node_go_protoc_envoy/README.md, build/python_node_go_protoc_envoy/cloudbuild.yaml, build/web_compose/Dockerfile, build/web_compose/compose.sh, build/webdriver-chrome/README.md, docs/developer_guide.md, server/requirements.txt, static/package-lock.json
The website compose container need Python, Node, Golang, Protoc and Envoy. Created a base image for that to make the docker build much simpler. 
Before the change, different base image are combined which have incompatible debian system library.
=> Create a base image for web compose docker container

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, experimental/sdg-tracker/src/components/layout/AppHeader.tsx
Screencast:
https://github.com/datacommonsorg/website/assets/13766/432ff955-582a-4748-8463-60f85247d5da
=> [sdg-tracker] Added lazy web component loading

experimental/sdg-tracker/src/components/layout/AppHeader.css, experimental/sdg-tracker/src/components/layout/AppHeader.tsx, experimental/sdg-tracker/src/components/layout/components.css, experimental/sdg-tracker/src/components/layout/components.tsx, static/.eslintrc.json
* Moving css to a separate file makes it easier to use it in the UN custom DC.
[header-css.webm](https://github.com/datacommonsorg/website/assets/1221814/ddf8a8dd-bd16-4e2f-9fab-8349febf13b6)
=> Move UN tracker css to a separate file.

server/templates/custom_dc/climate_trace/map_examples.json, server/templates/custom_dc/climate_trace/scatter_examples.json, server/templates/custom_dc/climate_trace/timeline_examples.json, server/templates/custom_dc/feedingamerica/base.html, server/templates/custom_dc/iitm/base.html, server/templates/custom_dc/iitm/map_examples.json, server/templates/custom_dc/iitm/scatter_examples.json, server/templates/custom_dc/iitm/timeline_examples.json, server/templates/custom_dc/stanford/base.html, static/css/base.scss, static/custom_dc/feedingamerica/css/overrides.css, static/custom_dc/iitm/style.css, static/custom_dc/stanford/overrides.css
- fix examples missing on the tool pages of custom dcs
- fix footer/header styling/colors for stanford, feedingamerica, iitm, worldbank
https://screenshot.googleplex.com/7VeTFzMd7fDvu57
https://screenshot.googleplex.com/5ss2DzVMhmpWS2v
=> fix custom dc styling

run_test.sh, server/lib/nl/detection/date.py, server/lib/nl/detection/types.py, server/tests/lib/nl/date_parser_test.py
This only covers very basic cases for now. Will need to expand based on the usage.
=> Add a Date classifier

server/routes/explore/api.py
add new endpoint that does detection and fulfillment
=> [explore] make new detect + fulfill endpoint

static/js/apps/explore/app.tsx, static/js/apps/explore/result_header_section.tsx, static/js/apps/explore/search_section.tsx, static/js/apps/nl_interface/app_state.ts, static/js/apps/nl_interface/debug_info.tsx, static/js/apps/nl_interface/nl_commentary.tsx, static/js/apps/nl_interface/query_result.tsx, static/js/types/app/nl_interface_types.ts
Made a bunch of renaming based on object type as we have more data in this page now.
=> Add debug info to explore page

server/lib/fetch.py, server/lib/nl/common/utils.py, server/services/datacommons.py
For query "What are the projected temperature extremes across california", the check goes from 22 seconds to 0.2 seconds.
=> Use observation facet API to check single point observation

static/js/components/subject_page/block.tsx, static/js/components/subject_page/column.tsx, static/js/constants/app/nl_interface_constants.ts
Apparently the length of the HTMLCollection object changes as class list is updated. That causes the issue that only a subset of the divs have class updated.
=> Fix explore more iteration bug

run_test.sh, server/webdriver/screenshot/local/page.json, static/js/apps/explore/success_result.tsx, static/js/apps/nl_interface/query_result.tsx, static/js/components/tiles/highlight_tile.tsx, static/js/constants/app/explore_constants.ts, static/js/utils/subject_page_utils.ts
* Fixed the issue that highlight tile does not have proper setup for async-element markup
* Use 3000px for nl/explore page height universally.
=> Fix screenshot test failure and support setting a maximum block number in results

server/lib/gcs.py, server/routes/screenshot/html.py, server/templates/screenshot/commit.html, server/templates/screenshot/compare.html, server/templates/screenshot/date.html, static/css/screenshot.scss, static/js/apps/screenshot/app.tsx, static/js/apps/screenshot/main.ts, static/webpack.config.js
* Async load each image (image diff) so viewing the result is much faster
*  Do not show diff if the ratio is less than a threshold (0.001)
=> Revamp screenshot capture tool

server/templates/static/about.html, server/templates/static/faq.html, server/templates/static/feedback.html
per approved content from prem
=> Update static content

server/config/nl_page/sdg_topic_cache.json, tools/sdg/topics/README.md, tools/sdg/topics/main.py
* See the generated MCF [here][cns].
+ Will create a CL for g3 after this PR is submitted.
* @pradh - This commit includes the updated topic cache JSON. Let me know if that should be removed.
[cns]: https://cnsviewer-static.corp.google.com/cns/jv-d/home/datcom/keyurs/custom_topics_sdg.mcf?user=
=> Generate SDG topics MCF.

experimental/sdg-tracker/src/components/home/PlaceSection.tsx, experimental/sdg-tracker/src/components/shared/components.tsx, experimental/sdg-tracker/src/state/index.ts, experimental/sdg-tracker/src/utils/DataCommonsClient.ts
- updates homepage to use same place dropdown as countries page
- update the dropdown to include regions
- get regions on app initialization
=> [sdg] add un regions

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, experimental/sdg-tracker/src/utils/types.ts
This is a companion PR to #3445 . It adds the frontend changes that pair with the new varToTopics in fulfillment return.
=> Frontend changes for varToTopics changes

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, experimental/sdg-tracker/src/utils/types.ts
=> [sdg] added proper place type and childPlaceType handling for map results

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, packages/web-components/docs/components/bar.md, packages/web-components/examples/all-charts.html, static/js/components/tiles/bar_tile.tsx, static/library/bar_component.ts
=> [sdg] add variable name regex for bar tile

experimental/sdg-tracker/src/components/home/PlaceSection.tsx, static/css/shared/_tiles.scss, static/js/components/tiles/place_overview_tile.tsx
- add link to place explorer on place overview tile
- update sdg homepage place section according to mocks
=> [SDG/Explore] Some UI updates

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, packages/web-components/docs/components/bar.md, packages/web-components/docs/components/line.md, static/js/components/tiles/bar_tile.tsx, static/js/components/tiles/line_tile.tsx, static/js/utils/tile_utils.tsx, static/library/bar_component.ts, static/library/line_chart_component.ts, static/library/utils.ts
=> [sdg] in legend labels, if no [], make label "Total"

static/css/base/_color.scss, static/css/explore.scss, static/js/apps/explore/user_message.tsx
update user message according to mock
=> [explore] update user message

experimental/sdg-tracker/index.html, experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, packages/web-components/examples/all-charts.html, static/css/shared/_tiles.scss, static/css/tools/visualization.scss, static/js/components/tiles/chart_footer.tsx, static/library/slider_component.ts
Also applied some misc formatting
Screenshot
=> [sdg] Moved map slider component into map component

static/js/components/tiles/map_tile.tsx
Adds the date to tooltips in the map tile
Screenshot:
=> Add date to tooltips in map tile

experimental/sdg-tracker/src/components/countries/Countries.tsx, experimental/sdg-tracker/src/components/goals/Goals.tsx, experimental/sdg-tracker/src/components/shared/AppSidebar.tsx, experimental/sdg-tracker/src/state/index.ts, experimental/sdg-tracker/src/utils/DataCommonsClient.ts, experimental/sdg-tracker/src/utils/types.ts
[dynamic-sidebar.webm](https://github.com/datacommonsorg/website/assets/1221814/fb43830f-91d2-447d-ab21-f81140b2e86a)
=> Hide sidebar goals with no data for countries.

static/css/base.scss, static/js/components/spinner.tsx
=> Add a spinner loading prompt after 3 seconds

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, packages/web-components/docs/components/scatter.md
=> Added scatter plot web component to results

server/templates/custom_dc/stanford/homepage.html
Please accept this updated homepage text provided by the Doerr School Communications team.
Thank you.
=> Update homepage.html with new text from the SDSS Communications team.

server/lib/fetch.py, static/js/utils/tile_utils.tsx
- update complex unit to jsut display the unit part
e.g., unit here used to be "% with base period 2017"
=> [sdg] update complex unit string

server/integration_tests/explore_test.py, server/integration_tests/test_data/fulfillment_api_sdg_centralasia/chart_config.json, server/lib/nl/common/constants.py, server/lib/nl/detection/types.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/handlers.py
=> SDG: Enable maps for UN regions

experimental/sdg-tracker/src/state/index.ts, experimental/sdg-tracker/src/utils/DataCommonsClient.ts, experimental/sdg-tracker/src/utils/constants.ts
[sidebar-regions.webm](https://github.com/datacommonsorg/website/assets/1221814/ed73608f-e66d-4cb9-a222-aab44bab6b0c)
=> Add support for dynamic sidebars for regions.

server/integration_tests/test_data/fulfillment_api_sdg_specialvars/chart_config.json, server/lib/nl/common/commentary.py, static/js/components/tiles/highlight_tile.tsx
=> SDG: tune user message

server/templates/static/about.html
=> add video to about page

build/ci/cloudbuild.website_testing.yaml, run_website_adversarial.sh, run_website_sanity.sh, run_website_snapshot.sh
In the cloudbuild, all 3 tests perform pip install in the same time which causes error. Now have a separate step for python setup.
=> Fix testing cloudbuild pip install issue

experimental/sdg-tracker/src/config/countries.json, server/webdriver/tests/standalone/README.md, server/webdriver/tests/standalone/sdg_sanity.py
* Does not include SDG_* checks.
=> Create SDG sanity test for home, countries and regions.

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/AppSidebar.tsx
[sidebar-spinner.webm](https://github.com/datacommonsorg/website/assets/1221814/1873c65e-c2f1-4a7a-85cb-077a7dd611c3)
=> Show spinner when sidebar is loading.

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/components/molecule/DataCommons/global.js, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/custom.css, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/home/GoalSection.tsx
- remove replace search with dc logo in the header
- update line size
=> [sdg] some homepage updates

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/countries/CountriesContent.tsx
[no-data-found.webm](https://github.com/datacommonsorg/website/assets/1221814/6138688b-5862-4a8e-811f-5054029396ff)
=> Show no data found error message when there is no data.

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/countries/CountriesContent.tsx, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/components.tsx
=> Added separate country / area selector back in, added search caret and rounding back in

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/goals/GoalOverview.tsx, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/config/indicatorText.json, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/utils/constants.ts
* Updated default question: “How many people go hungry in the World?”
* fixed broken 12.2.1 infographic image path
* Updated homepage text to "Explore SDG Data by Countries or Areas"
* Updated goal section header for better responsiveness
Before
After
=> [sdg] Misc UN style fixes

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/countries/CountriesContent.tsx, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/goals/AllGoalsOverview.tsx
[dc-class-name.webm](https://github.com/datacommonsorg/website/assets/1221814/a3516fc8-7d3b-42fe-a23a-62987f36b23e)
=> Add -dc class name to goal content cards for webdriver tests.

server/templates/explore_landing.html, static/js/apps/explore_landing/topics.json
1 - Update suggested query that currently shows low confidence results
2 - Add topic to the page title of Explore landing pages
=> [main site] two small fixes

server/webdriver/tests/standalone/sdg_sanity.py
* Also using `-dc-*` class names now.
=> Check for SDG_ in page content for SDG sanity test.

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/home/GoalSection.tsx, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/home/PlaceSection.tsx
* Fixed country select alignment
* Fixed goal link grid
before
after
=> [sdg] homepage style fixes

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/countries/CountriesContent.tsx, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/components.tsx
=> [sdg] added search page error message when no topics are found

static/js/components/tiles/scatter_tile.tsx
- fix a problem where we are trying to draw a scatter chart in a container that has 0 width. This is a quick fix & I've added a todo to figure out/fix the root cause
=> [sdg] fix "invalid size" error

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/components/DataCommons/DataCommonsHeader.js, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/components/DataCommons/DataCommonsLayout.js, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/custom.css, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/AppLayoutContent.tsx, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/AppSidebar.tsx
=> [sdg] Added sticky header

server/app_env/_base.py, server/app_env/unsdg.py, server/routes/shared_api/choropleth.py
- add new GEO_JSON_PROP to the app config & read that when retrieving geojsons
=> use un geojsons for all maps on unsdg dc

server/routes/disaster/html.py, server/routes/event/html.py, server/routes/sustainability/html.py, server/routes/topic_page/html.py
Thanks @caravansteve for finding this issue in the techsoup DC instance!
=> Deepcopy topic page config before it is mutated

static/js/apps/explore/result_header_section.tsx, static/nodejs_server/bar_tile.ts, static/src/server.ts
https://github.com/datacommonsorg/website/assets/4375037/c11b98bb-a380-4bdb-af2f-f1213fb89a64
=> NL: Link to Place Pages

server/templates/custom_dc/custom/base.html, server/templates/custom_dc/feedingamerica/base.html, server/templates/custom_dc/iitm/base.html, server/templates/custom_dc/stanford/base.html, static/custom_dc/iitm/style.css, static/custom_dc/stanford/overrides.css
- fix headers 
- add missing stylesheet
=> update styling for custom dc

build/ci/cloudbuild.website_testing.yaml, server/routes/screenshot/html.py, server/webdriver/screenshot/local/page.json, server/webdriver/screenshot/remote/dev.datacommons.org/nl.json
Reordered the tests in cloudbuild to be screenshot -> sanity -> adversarial by their running time.
=> Add logging param to screenshot tests url; Make cron job running tests sequentially

deploy/helm_charts/envs/prod.yaml, deploy/helm_charts/envs/staging.yaml, deploy/helm_charts/envs/stanford.yaml, deploy/helm_charts/envs/stanford_staging.yaml
We would add SDG to the base DC for both charting and NL search.
=> Unblock SDG variables in all DC instances

update_git_submodules.sh
I always need to lookup which commands to run to update the submodules of this repo. This PR adds the commands as a script for convenience.
=> Add a convenience script for updating submodules

static/js/components/tiles/map_tile.tsx
- update map tile to be able to calculate geojson for specific place types (this will propagate to map vis tool)
=> [map vis tool] support manual geojson distances

server/app_env/custom.py, server/app_env/floret.py, server/lib/config.py, server/routes/import_wizard/html.py, server/templates/custom_dc/floret/homepage.html
* Do not use memcache for custom DC to catch up for data refresh
* Update import and mixer submodule and update import script execution
* Update Floret homepage based on their request
=> A bunch of updates for RSI and Floret DC

nl_server/embeddings.py, nl_server/requirements.txt
- the nl server uses the package `datasets` which uses the package `fsspec`. The most recent version of `fsspec` causes problems with `datasets` as mentioned here: https://github.com/huggingface/datasets/issues/6333
=> Fix Test Failures

server/templates/explore.html
Removed extra datacommons.js script tag which was preventing the explore page from loading
=> Explore page fix

server/webdriver/shared.py
Verified `./run_test.sh -s` screenshot test succeeds locally
=> fixed geoId/06?wc=true screenshot test

server/routes/shared_api/choropleth.py, server/tests/routes/api/choropleth_test.py
Before: https://screenshot.googleplex.com/Bb5uh6u36FeZuyf
After: https://screenshot.googleplex.com/9P3VzUX8shzGvqU
=> [Maybe] Defensive change to fix buggy BRA geojsons

static/js/tools/stat_var/page.tsx
Currently source filtering result in a large number api call that degrade the performance, especially in custom DC setup. Switch the check from stat var info to existence check, which is much more efficient.
Also no need to fetch the source names as they are already from the property value response.
=> Use existence check to filter sources in stat var explorer page

static/nodejs_server/ranking_tile.ts, static/nodejs_server/types.ts, static/src/server.ts
- add a `dcLink` field that links to the datacommons explore page
- enable ranking results and return place names in the data csv
- hide map results
example for the query "which counties in california have the largest population"
https://paste.googleplex.com/5076381028319232
=> [nodejs] Updates to query results

static/nodejs_server/ranking_tile.ts, static/src/server.ts
- fix ranking bug where ranking charts of the type "rankHighestLowest" were not showing up because they weren't being handled
- add TODO to switch dcUrl to bard.datacommons.org
updated result for "obesity vs poverty of counties in california"
https://paste.googleplex.com/6419230606491648
=> [nodejs] fix ranking bug

server/routes/admin/html.py
* Disabling it temporarily until we have full support for GCS data based embeddings.
=> Temporarily disable creating custom embeddings if data is in GCS.

server/tests/test_data/nodejs_query/disaster/screenshot.json, server/tests/test_data/nodejs_query/map_rank/screenshot.json, server/tests/test_data/nodejs_query/timeline/screenshot.json, server/tests/test_data/nodejs_query/timeline_all/screenshot.json, static/nodejs_server/ranking_tile.ts
fix bug where ranking table csv is in the wrong order
updated response for family earnings in california counties
https://paste.googleplex.com/6309252029743104
=> [nodejs] fix ranking csv bug

server/integration_tests/explore_test.py, server/integration_tests/test_data/demo_feb2023/query_2/chart_config.json, server/integration_tests/test_data/e2e_single_date/lifeexpectancyinusstatesin2018/chart_config.json, server/integration_tests/test_data/e2e_single_date/populationintheusinthelastyear/chart_config.json, server/integration_tests/test_data/e2e_single_date/whataretheprojectedtemperaturesincaliforniain2025/chart_config.json, server/lib/fetch.py, server/lib/nl/common/serialize.py, server/lib/nl/common/utils.py, server/lib/nl/config_builder/bar.py, server/lib/nl/config_builder/builder.py, server/lib/nl/config_builder/highlight.py, server/lib/nl/config_builder/map.py, server/lib/nl/config_builder/ranking.py, server/lib/nl/config_builder/scatter.py, server/lib/nl/detection/date.py, server/lib/nl/detection/types.py, server/lib/nl/fulfillment/basic.py, server/lib/nl/fulfillment/existence.py, server/lib/nl/fulfillment/fulfiller.py, server/lib/nl/fulfillment/time_delta_across_places.py, server/lib/nl/fulfillment/time_delta_across_vars.py, server/lib/nl/fulfillment/types.py, server/lib/nl/fulfillment/utils.py, server/tests/lib/nl/utils_test.py, static/js/components/tiles/bar_tile.tsx
fulfillment logic for a query that asks for a specific date
- prune out time delta queries
- specify date when building chart configs
- note: added for all charts except Event and Timeline 
- update existence check to check for the date 
- Although, this isn't 100% accurate, so have a TODO to fail gracefully on the frontend when a chart doesn't have data 
https://screenshot.googleplex.com/4Si2RJc2xhFyrWQ
https://screenshot.googleplex.com/6yMxFLx7HtoVw6c
https://screenshot.googleplex.com/3hd98GuBM2Kta8R
=> [nl] fulfill single date queries

tools/nl/nodejs_query_differ/README.md, tools/nl/nodejs_query_differ/differ.py, tools/nl/nodejs_query_differ/differ_results.json, tools/nl/nodejs_query_differ/requirements.txt, tools/nl/nodejs_query_differ/run.sh
script to generate and output diffs between results of two nodejs query runs (run as a cronjob on gke)
TODO for future, set this differ up to run automatically and alert if there is a diff
=> [cron tests] Add tool to diff results of nodejs query runs

deploy/helm_charts/envs/bard.yaml, deploy/helm_charts/envs/dev.yaml
update bard and dev deployment yamls to be able to handle cron tests
=> [cron testing] Update dev and bard yamls to handle cron tests

static/js/tools/scatter/chart_loader.tsx
fix bug where scatter plot fetches the same data 3 times
=> [legacy scatter] Fix duplicate API calls

server/integration_tests/test_data/e2e_edge_cases/povertyincaliforniaandcalifornia/chart_config.json, server/integration_tests/test_data/multisv/query_3/chart_config.json, server/integration_tests/test_data/multisv/query_4/chart_config.json, server/integration_tests/test_data/place_detection_e2e_dc/query_6/chart_config.json
This PR Updates the nl integration test goldens from a clean master branch.
=> Update nl test goldens

custom_dc/README.md
Some minor tweaks to the quick start guide to Custom DC to clarify a few details / improve information flow.
=> Update Custom DC Quick Start Documentation.

deploy/nl/embeddings.yaml, server/integration_tests/test_data/detection_api_statvars/correlatewithgdpofcalifornia/chart_config.json, tools/nl/embeddings/data/curated_input/sheets_svs.csv, tools/nl/embeddings/data/preindex/medium/sv_descriptions.csv
- add "population by age" for the AgeDistribution topic
- This was added to promote the AgeDistribution topic to the top in cases like "population by age in the United States". 
- before: https://screenshot.googleplex.com/AW5eV5DXrVD4cDe
- after: https://screenshot.googleplex.com/6MNeE4PDrsuProY
- add "gender of population" for the Gender topic
- This was added to promote the Gender topic to the top in cases like "population by gender in the United States". 
- before: https://screenshot.googleplex.com/4fvN5rk5HbNobh7
- after: https://screenshot.googleplex.com/4yT2P3o86Yq2jHc
validation: https://pantheon.corp.google.com/storage/browser/_details/datcom-embedding-diffs/chejennifer_medium_ft_2023_12_11_22_30_00.html
=> [embeddings] Update descriptions for 2 SVs

server/integration_tests/test_data/demo_feb2023/query_2/chart_config.json, server/integration_tests/test_data/e2e_date_range/lifeexpectancyinusstatesinthelast5years/chart_config.json, server/integration_tests/test_data/e2e_single_date/populationintheusinthelastyear/chart_config.json, server/integration_tests/test_data/sdg/query_3/chart_config.json, server/tests/lib/nl/date_parser_test.py
Tests having to do with date range where the query was along the lines of "in the last year" needed to have the detected year updated from 2022 to 2023
=> [NL] Update the detected year for tests about the previous year 

tools/nl/loadtest/loadtest_results.csv
It's been awhile since we've updated the loadtest results and there have been updates to the endpoint response.
=> Update Nodejs loadtest results

static/js/chart/base.ts, static/nodejs_server/constants.ts, static/nodejs_server/utils.ts, static/src/server.ts
- increase the size of the png image of the chart to improve image quality when consumed by Bard
- add an option to return the chart as an svg to be used by Bard to test consuming our charts as an svg instead of a png
=> [nodejs] Update chart image response

static/js/chart/draw_utils.ts
before: https://screenshot.googleplex.com/6bemXe9UHSzM85c
now: https://screenshot.googleplex.com/7NmatAGb5A7jiiC
=> [nodejs] increase space between legend items

deploy/helm_charts/envs/internal.yaml
Reference: https://pantheon.corp.google.com/bigtable/instances/dc-graph/tables?mods=-monitoring_api_staging&project=datcom-internal
=> DC internal deployment: add BT section to yaml

deploy/helm_charts/envs/internal.yaml
Updates to the yaml file to bring parity with magic-eye instance (except with lower limits for replicas etc)
=> DC internal deployment - Enabling customBigTable

server/integration_tests/test_data/e2e_answer_places/whatistheemissionsinthesecounties/chart_config.json, server/integration_tests/test_data/e2e_answer_places/whichcountiesincaliforniahavemedianageover40/chart_config.json, server/integration_tests/test_data/e2e_edge_cases/numberofheadlessdriversincalifornia/chart_config.json, server/integration_tests/test_data/e2e_edge_cases/povertyincaliforniaandcalifornia/chart_config.json, server/integration_tests/test_data/e2e_edge_cases2/californiacountieswiththebiggestincreaseinincomelevels/chart_config.json, server/integration_tests/test_data/e2e_edge_cases2/countiesincaliforniawhereincomeisover50000/chart_config.json, server/integration_tests/test_data/e2e_edge_cases2/howdoesschoolsizeofurbanschoolscomparetoruralschoolsinus/chart_config.json, server/integration_tests/test_data/e2e_edge_cases2/whatistherelationshipbetweenhousingsizeandhomepricesincalifornia/chart_config.json, server/integration_tests/test_data/e2e_no_default_place_specified/chart_config.json, server/integration_tests/test_data/e2e_us_demo/howdoeshouseholdincomecomparewithratesofdiabetesinusacounties/chart_config.json, server/integration_tests/test_data/fulfillment_api_comparison/chart_config.json, server/webdriver/tests/download_test.py, server/webdriver/tests/map_test.py, server/webdriver/tests/place_explorer_test.py, server/webdriver/tests/scatter_test.py, server/webdriver/tests/vis_map_test.py, server/webdriver/tests/vis_scatter_test.py
Update goldens and webdriver tests. Looks like there's been new census data
=> update goldens and webdriver

server/integration_tests/standalone/adversarial.py, server/integration_tests/test_data/detection_api_context/stateswithhighestphds/chart_config.json, server/routes/nl/helpers.py
Plan to keep this PR outside of today's release.
TODO:  Validate the adversarial run after this is submitted.
=> Switch to Gemini Pro instead of PaLM as default

server/integration_tests/explore_test.py, server/integration_tests/test_data/fulfillment_api_undata/chart_config.json, server/lib/explore/fulfiller_bridge.py, server/lib/explore/params.py, server/lib/explore/topic.py, server/lib/nl/common/commentary.py, server/lib/nl/common/serialize.py, server/lib/nl/config_builder/builder.py, server/lib/nl/fulfillment/basic.py, server/lib/nl/fulfillment/fulfiller.py, server/lib/nl/fulfillment/simple.py, server/lib/nl/fulfillment/types.py, server/lib/nl/fulfillment/utils.py, server/lib/topic_cache.py, server/routes/nl/helpers.py, tools/sdg/topics/README.md, tools/sdg/topics/main.py, tools/sdg/topics/requirements.txt, tools/sdg/topics/run.sh
This is to support UN's upcoming WHO launch.
=> Add new undata DC backend with SDG+WHO datasets

server/templates/static/faq.html
Adding Legal approved FEPRA compliance statement to the FAQ.
=> Adding FAQ about FEPRA Compliance

deploy/nl/embeddings.yaml, server/integration_tests/test_data/e2e_no_default_place_specified/chart_config.json, server/integration_tests/test_data/fulfillment_api_undata/chart_config.json, server/lib/explore/params.py, server/routes/nl/helpers.py, tools/nl/embeddings/data/curated_input/undata/sheets_svs.csv, tools/nl/embeddings/data/preindex/undata/duplicate_names.csv, tools/nl/embeddings/data/preindex/undata/sv_descriptions.csv, tools/nl/embeddings/run.sh, tools/sdg/topics/README.md, tools/sdg/topics/main.py
* Also, drop a couple of variables related to estimate availability from the topics.
* The "poverty" variables in UN topic seems not as good as poverty from SDG, so slightly demote it.
* Also, address comments in https://github.com/datacommonsorg/website/pull/3955
This fixes the query below:
=> Improve UN topic NL descriptions

server/lib/nl/fulfillment/base.py
fixes: https://screenshot.googleplex.com/9ScS7NQoqwSTfPP
=> [nl] bug in counters

deploy/nl/embeddings.yaml, tools/nl/embeddings/data/curated_input/undata/sheets_svs.csv, tools/nl/embeddings/data/preindex/undata/sv_descriptions.csv
=> Undata: Improve triggering for HIV / AIDS

deploy/nl/embeddings.yaml, tools/nl/embeddings/data/curated_input/undata/sheets_svs.csv, tools/nl/embeddings/data/preindex/undata/sv_descriptions.csv
This is to pull in https://github.com/datacommonsorg/mixer/commit/800e6ce7a919ffacd296ab0a674f967331e01c45.
For example, this works now:
=> Sync mixer submodule

server/integration_tests/test_data/e2e_undata/pulmonarydiseasesintheworld/chart_config.json, server/lib/explore/topic.py, server/lib/nl/fulfillment/handlers.py
1.  Improves further on https://github.com/datacommonsorg/website/commit/a820bde8a37f9eb4fc3eeec69b239e2680b55161 by opening more topics, but having an SV-based limit for Special DCs.
2.  Sync mixer to fix the "number of cholera cases" query.
3.  For the edge-case, the following query was failing.  Because "filter_with_single_var" fulfiller would not fallback to place-comparison, rather only to Basic (and basic won't fulfill multi-place query).
=> UNData: increase topic limit and fix edge-cases

server/lib/disaster_dashboard.py, server/lib/log.py, server/lib/nl/common/counters.py, server/lib/nl/common/rank_utils.py, server/lib/nl/common/serialize.py, server/lib/nl/common/utils.py, server/lib/nl/config_builder/base.py, server/lib/nl/config_builder/builder.py, server/lib/nl/config_builder/event.py, server/lib/nl/detection/heuristic_detector.py, server/lib/nl/detection/llm_api.py, server/lib/nl/detection/llm_detector.py, server/lib/nl/detection/place.py, server/lib/nl/fulfillment/containedin.py, server/lib/nl/fulfillment/existence.py, server/lib/nl/fulfillment/filter_with_dual_vars.py, server/lib/nl/fulfillment/filter_with_single_var.py, server/lib/nl/fulfillment/fulfiller.py, server/lib/nl/fulfillment/ranking_across_places.py, server/lib/nl/fulfillment/ranking_across_vars.py, server/lib/nl/fulfillment/superlative.py, server/lib/nl/fulfillment/time_delta_across_places.py, server/lib/nl/fulfillment/time_delta_across_vars.py, server/lib/translator.py, server/routes/explore/api.py, server/routes/nl/api.py, server/routes/nl/helpers.py
And turn a few of them into counter updates.
=> Dropping logging calls from NL

deploy/gke/prod.yaml
remove the domains that are no longer in use
=> Update domains in the prod yaml config

model_server/main.py, shared/model/loader.py, shared/model/vertex_ai_endpoints.yaml
Preliminary PR for reranking support.  I will build docker image and create endpoint after merging.
=> Add CrossEncoder model to Vertex AI Model Server

nl_server/embeddings.py, nl_server/store/lancedb.py, nl_server/store/memory.py, server/lib/nl/common/debug_utils.py, server/lib/nl/detection/detector.py, server/lib/nl/detection/heuristic_detector.py, server/lib/nl/detection/llm_detector.py, server/lib/nl/detection/rerank.py, server/lib/nl/detection/variable.py, server/routes/nl/helpers.py, shared/lib/detected_variables.py, shared/model/vertex_ai_endpoints.yaml, static/js/apps/nl_interface/debug_info.tsx, static/js/types/app/nl_interface_types.ts
Also, turn sv2sentences into a dataclass for easier processing.
=> NL:  Setup plumbing in prep for reranking

nl_server/__init__.py, nl_server/gcs.py
=> NL: some edge case handling when running locally

tools/nl/embeddings/build_custom_dc_embeddings.py, tools/nl/embeddings/testdata/custom_dc/input/embeddings.yaml, tools/nl/embeddings/utils.py, tools/nl/embeddings/utils_test.py
* This should fix the recent docker build failures: https://screenshot.googleplex.com/SEVhMwYnxZeyTRR
* There is a bug in this PR where the default model and embeddings paths don't match what we do in main dc.  I'll address this in a follow-up PR.
=> Adapt building custom dc embeddings to the recent yaml changes.

build/ci/cloudbuild.deploy.yaml, docs/developer_guide.md
Fixed another deploy to autopush error
This should fix things, ran cloud-build-local to test the yaml file
=> [cron testint] fix another deploy error

server/lib/config.py, server/routes/shared_api/observation/point.py
Setting date=HIGHEST_COVERAGE falls back to date=LATEST in SQL custom data commons
=> Disabled HIGHEST_COVERAGE option in SQL custom data commons

.vscode/launch.json, server/routes/disaster/html.py, server/routes/sustainability/html.py, server/routes/topic_page/html.py
GCP error due to this: `UndefinedError: 'None' has no attribute 'CUSTOM'`
=> Fix a few wrong subject page config params when passing to jinja

nl_server/embeddings_map.py, nl_server/loader.py, nl_server/tests/custom_embeddings_test.py, tools/nl/svindex_differ/README.md, tools/nl/svindex_differ/differ.py, tools/nl/svindex_differ/run.sh
More deets in README.
Same index diff: https://storage.mtls.cloud.google.com/datcom-embedding-diffs/shanth_medium_ft_2024_05_02_18_12_18.html
Different index diff: https://storage.mtls.cloud.google.com/datcom-embedding-diffs/shanth_medium_ft_2024_05_02_18_21_37.html
=> SV Differ: compare model and/or store

scripts/deploy_custom_dc_autopush.sh
* #4197 did not work so trying this time with `chmod +x deploy_custom_dc_autopush.sh`.
* Made a synthetic change to the script - without it github won't create a PR with no code change.
=> Try updating script permissions again.

docs/developer_guide.md, nl_server/__init__.py, nl_server/loader.py, nl_server/tests/embeddings_test.py, nl_server/tests/verb_test.py, tools/nl/embeddings/README.md
this removes the local cache from the nl server & is part of the changes for updating the embeddings.yaml structure
The difference in time taken for the server to restart after a change
with cache: 1-2s
without cache: 6-7s
=> [nl server] remove local cache

nl_server/loader.py, nl_server/routes.py
Custom DC crashes here.  This likely won't fix it, but we might know more...
=> NL: avoid NULL access in healthz

deploy/helm_charts/dc_website/templates/config_maps.yaml, deploy/helm_charts/dc_website/values.yaml, deploy/helm_charts/envs/autopush.yaml, deploy/helm_charts/envs/bard.yaml, deploy/helm_charts/envs/biomedical.yaml, deploy/helm_charts/envs/climate_trace.yaml, deploy/helm_charts/envs/dev.yaml, deploy/helm_charts/envs/internal.yaml, deploy/helm_charts/envs/magic_eye.yaml, deploy/helm_charts/envs/prod.yaml, deploy/helm_charts/envs/staging.yaml, deploy/helm_charts/envs/unsdg.yaml, deploy/helm_charts/envs/unsdg_staging.yaml, deploy/helm_charts/envs/worldbank.yaml, nl_server/config.py, nl_server/custom_dc_constants.py, nl_server/embeddings_map.py, nl_server/loader.py, nl_server/routes.py, nl_server/tests/custom_embeddings_test.py, nl_server/tests/embeddings_test.py
Get default index and enabled indexes from deployment because this could be instance specific
=> [nl server] get default and enabled indexes from deployment

server/lib/nl/detection/llm_detector.py
Attempt to fix: https://pantheon.corp.google.com/errors/detail/COjD9qbilefT-gE;time=P30D?project=datcom-website-prod&utm_source=error-reporting-notification&utm_medium=email&utm_content=new-error&e=13803378&mods=-monitoring_api_staging
=> Be flexible with exception handling in llm parsing

run_test.sh, server/routes/nl/html.py, server/templates/eval_rig.html, static/js/apps/eval_rig/app.tsx, static/js/apps/eval_rig/constants.tsx, static/js/apps/eval_rig/eval_section.tsx, static/js/apps/eval_rig/main.ts, static/js/apps/eval_rig/query_section.tsx, static/js/utils/firebase.ts
=> RIG Eval: fetch sheet data and display actual content for 1 query/call

static/css/eval_rig.scss, static/js/apps/eval_rig/app.tsx, static/js/apps/eval_rig/eval_section.tsx, static/js/apps/eval_rig/feedback_form.tsx, static/js/apps/eval_rig/query_section.tsx, static/package-lock.json
=> [RIG EVAL] Implement DC call navigation and eval form

static/js/apps/eval_rig/app.tsx, static/js/apps/eval_rig/context.tsx, static/js/apps/eval_rig/eval_section.tsx, static/js/apps/eval_rig/feedback_form.tsx, static/js/apps/eval_rig/one_question.tsx, static/js/apps/eval_rig/query_section.tsx, static/js/utils/firebase.ts
Next step is to 
- Output the response to gsheet
- Get the query/call status from Firestore and use them for UI display.
=> Update RIG Eval questions and write the response to Firestore

static/js/apps/eval_rig/app.tsx, static/js/apps/eval_rig/constants.tsx, static/js/apps/eval_rig/context.tsx, static/js/apps/eval_rig/data_store.tsx, static/js/apps/eval_rig/eval_section.tsx, static/js/apps/eval_rig/feedback_form.tsx, static/js/apps/eval_rig/query_section.tsx
Also:
- put google sheet client (doc) in context
- Remove try catch so errors should be handled by caller
=> [RIG EVAL] Save rater feedback to google sheet

static/css/eval_rig.scss, static/js/apps/eval_rig/app.tsx, static/js/apps/eval_rig/data_store.tsx, static/js/apps/eval_rig/eval_list.tsx, static/js/apps/eval_rig/eval_section.tsx
https://github.com/datacommonsorg/website/assets/69875368/e0974e8e-234e-4150-a6b4-7d20d2125039
=> [RIG EVAL] add eval list

run_test.sh, static/css/eval_rig.scss, static/js/apps/eval_rig/call_feedback.tsx, static/js/apps/eval_rig/data_store.tsx, static/js/apps/eval_rig/eval_list.tsx, static/js/apps/eval_rig/feedback_navigation.tsx, static/js/apps/eval_rig/query_feedback.tsx, static/js/apps/eval_rig/types.tsx
dc response has no stat:
dc response has stat:
=> [RIG EVAL] some css and feedback updates

server/templates/static/homepage.html
As a followup to #4299, capitalizes the K to match the capital B on the same line.
=> Capitalize K in 260k on homepage

static/css/eval_rig.scss, static/js/apps/eval_rig/app.tsx, static/js/apps/eval_rig/call_feedback.tsx, static/js/apps/eval_rig/eval_list.tsx, static/js/apps/eval_rig/query_feedback.tsx, static/js/apps/eval_rig/query_section.tsx, static/js/apps/eval_rig/util.ts
- move the option “Apply the same evaluation to the next item” [to the bottom of the questions]
- Remove toolbar
- update Q4 to Query 4
- update footnote text font styling
- Move the “Re-eval” button to the left of the “List button”
- update highlight colors
=> [rig eval] fix some bugs

static/css/eval_rig.scss, static/js/apps/eval_rig/app.tsx, static/js/apps/eval_rig/data_store.tsx, static/js/apps/eval_rig/feedback_navigation.tsx
Also anchor "prev" and "next" button in the bottom of the page
=> [NL EVAL] query landing/navigation based on login user

server/integration_tests/test_data/demo2_cities_feb2023/query_3/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_4/chart_config.json, server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_comparison/chart_config.json, server/lib/nl/common/constants.py
Fixes a few more typos in SV display name overrides.
=> Fix more stat var name typos

nl_server/config_reader.py, run_test.sh, tools/nl/svindex_differ/differ.py, tools/nl/svindex_differ/prep/to_vars.py, tools/nl/svindex_differ/queryset_nodejs.csv, tools/nl/svindex_differ/queryset_nodejs_vars.csv
- update to_vars to use a non-deprecated endpoint
- add nodejs queries that can be used by sv differ tool
- update reading catalog for sv differ
=> Sv differ fixes

static/css/eval_retrieval_generation.scss, static/js/apps/eval_retrieval_generation/call_feedback.tsx, static/js/apps/eval_retrieval_generation/query_feedback.tsx, static/js/apps/eval_retrieval_generation/table_pane.tsx, static/js/apps/eval_retrieval_generation/util.ts
https://github.com/datacommonsorg/website/assets/69875368/cf87a224-58c2-4a6c-ad2a-92ac1aa07e0a
=> [rag eval] add table pane component

server/templates/base.html, static/js/apps/diff/app.tsx
With this, when clicking in one side of the iframe, the other iframe can be updated correspondingly based on the url path.
=> DC website compare tool navigation support

deploy/helm_charts/envs/autopush.yaml
Some examples testing locally of calculations: 
Timeline: 
Map:
=> Add cacheSVFormula to autopush.yaml

static/css/eval_retrieval_generation.scss, static/js/apps/eval_retrieval_generation/app.tsx, static/js/apps/eval_retrieval_generation/claim_counter.tsx, static/js/apps/eval_retrieval_generation/constants.tsx, static/js/apps/eval_retrieval_generation/data_store.tsx, static/js/apps/eval_retrieval_generation/eval_list.tsx, static/js/apps/eval_retrieval_generation/feedback_navigation.tsx, static/js/apps/eval_retrieval_generation/rag_ans_feedback.tsx
https://github.com/datacommonsorg/website/assets/69875368/7334d32d-4042-41a8-aca0-c7a8ef75e62f
=> [rag eval] add rag ans section

deploy/helm_charts/envs/staging.yaml, tools/clearcache/clear_staging.sh
Note: after merging, update oncall docs with a step to clear redis after deploying to staging
=> Added redis cache layer for staging.datacommons.org

static/js/apps/eval_retrieval_generation/constants.tsx, static/js/apps/eval_retrieval_generation/feedback_navigation.tsx, static/js/apps/eval_retrieval_generation/query_section.tsx, static/js/apps/eval_retrieval_generation/util.ts
move overall question feedback to before individual question feedback
=> [rag eval] update feedback stage order

static/css/eval_retrieval_generation.scss, static/js/apps/eval_retrieval_generation/app.tsx, static/js/apps/eval_retrieval_generation/call_feedback.tsx, static/js/apps/eval_retrieval_generation/constants.tsx, static/js/apps/eval_retrieval_generation/feedback_navigation.tsx, static/js/apps/eval_retrieval_generation/overall_feedback.tsx, static/js/apps/eval_retrieval_generation/query_section.tsx, static/js/apps/eval_retrieval_generation/rag_ans_feedback.tsx
- fix crashing when a query doesn't have an answer
- add loading when fetching data for the feedback section
- update reading either answer or questions in the LHS
=> [rag eval] fix crashing question, add loading, fix answer showing instead of questions

static/css/eval_retrieval_generation.scss, static/js/apps/eval_retrieval_generation/claim_counter.tsx, static/js/apps/eval_retrieval_generation/rag_ans_feedback.tsx
=> Update RAG eval tool counter layout for easier interaction

static/js/apps/eval_retrieval_generation/data_store.tsx, static/js/apps/eval_retrieval_generation/query_section.tsx, static/js/apps/eval_retrieval_generation/table_pane.tsx, static/js/apps/eval_retrieval_generation/util.ts
- make one call to read mulitple rows instead of making one call per row
- fix table parsing when header contains "," or "₂"
=> [rag eval] make less sheets reads, fix more table parsing

deploy/helm_charts/envs/unsdg_staging.yaml
- Removed sdg table since it's now in covered in `schema_2024_07_03_12_17_40` and `country_2024_07_03_10_18_47`
- Updated ilo tables
=> Updated un staging tables

static/css/eval_retrieval_generation.scss, static/js/apps/eval_retrieval_generation/app.tsx, static/js/apps/eval_retrieval_generation/sxs/app.tsx, static/js/utils/google_signin.tsx
Also show some explanatory text while things are loading.
=> [Eval UI] Trigger sign in on load

server/lib/nl/detection/heuristic_detector.py, server/lib/nl/detection/utils.py
example: https://screenshot.googleplex.com/C3QjzRnnzD9euVc
sv index differ: https://storage.mtls.cloud.google.com/datcom-embedding-diffs/chejennifer_base_uae_mem_2024_07_08_12_11_23.html where test replaces residents with people
=> [toolformer] replace "residents" with "people"

static/nodejs_server/tiles/highlight_tile.ts, static/nodejs_server/types.ts
e.g., what is the percentage of urban population in Tamil Nadu? https://paste.googleplex.com/4946781240819712
=> [nodejs] add highlight field to highlight tile response

tools/nl/embeddings/input/base/sheets_svs.csv
So it can be viewed as a [table on github](https://github.com/datacommonsorg/website/assets/4375037/6f355c58-89da-4708-99dc-eb1061ef771c) and loaded into BQ, etc.
=> Make base/sheets_svs.csv a proper csv

server/config/nl_page/topic_cache.json, server/integration_tests/test_data/demo2_cities_feb2023/query_3/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_4/chart_config.json, server/integration_tests/test_data/detection_api_multivar/comparemalepopulationwithfemalepopulation/debug_info.json, server/integration_tests/test_data/detection_api_multivar/howarefactorslikeobesity,bloodpressureandasthmaimpactedbyclimatechange/debug_info.json, server/integration_tests/test_data/detection_api_multivar/showmetheimpactofclimatechangeondrought/debug_info.json, server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_comparison/chart_config.json
commute time topic updated with mean commute time replacing total commute time
=> update goldens after topic cache update

shared/lib/utils.py, shared/tests/lib/utils_test.py
There are place names with St. like St. Landry Parish and stripping the period from that will prevent the place from being detected.
=> avoid stripping period for "St."

static/css/eval_retrieval_generation.scss, static/js/apps/eval_retrieval_generation/app.tsx, static/js/apps/eval_retrieval_generation/context.tsx, static/js/apps/eval_retrieval_generation/query_section.tsx, static/js/apps/eval_retrieval_generation/sxs/app.tsx, static/js/apps/eval_retrieval_generation/sxs/context.tsx, static/js/apps/eval_retrieval_generation/sxs/data_store.tsx, static/js/apps/eval_retrieval_generation/sxs/eval_list.tsx, static/js/apps/eval_retrieval_generation/sxs/navigation.tsx, static/js/apps/eval_retrieval_generation/sxs/sxs_feedback.tsx, static/js/apps/eval_retrieval_generation/types.tsx, static/js/apps/eval_retrieval_generation/util.ts
Also keep answers in loading state until answer text is processed.
[Demo](https://github.com/user-attachments/assets/ac31ea02-8646-4e32-8a59-12cc85178627)
=> [Eval Sxs] Add an eval list; jump to first incomplete eval on load

static/js/apps/eval_retrieval_generation/util.ts
use formattedValue instead of value to get the actual value that a user sees in the sheet
=> [evals] fix format of values read from sheet

static/css/eval_retrieval_generation.scss, static/js/apps/eval_retrieval_generation/eval_list.tsx, static/js/apps/eval_retrieval_generation/sxs/eval_list.tsx, static/js/apps/eval_retrieval_generation/util.test.ts, static/js/apps/eval_retrieval_generation/util.ts
[Demo](https://github.com/user-attachments/assets/0623d7af-3415-427e-bcc9-02410d15fbed)
=> [Eval UI] Reformat RIG tooltip; Close list modal on esc or external click

build/web_compose/compose.sh, custom_dc/env.list
Decided to make it required in an offline conversation following https://github.com/datacommonsorg/website/pull/4509#discussion_r1687181957
=> Make OUTPUT_DIR required.

tools/nl/nodejs_query_differ/goldens/bard/bar.json, tools/nl/nodejs_query_differ/goldens/bard/scatter_non_bard.json, tools/nl/nodejs_query_differ/goldens/bard/timeline_all.json
Update diffs after pushing most recent changes
=> update bard goldens

static/js/apps/eval_retrieval_generation/util.ts
If there are no tooltips shown, go back to old UI of showing footnotes
=> Update RIG UI to show footnotes if no tooltips

deploy/helm_charts/envs/internal.yaml
Verified on https://dc.corp.goog/version
=> Update internal to use remoteMixerDomain

scripts/build_cdc_services_and_tag_latest.sh
* To fix [build failure](https://screenshot.googleplex.com/9sGn944m5eJmqVc).
=> Build cdc services image with docker buildkit enabled.

.gitignore, deploy/terraform-custom-datacommons/README.md
Fixed some typos in the custom datacommons terraform readme, and added the backend.tf to gitignore
=> minor readme and .gitignore updates to custom dc terraform

deploy/helm_charts/envs/magic_eye.yaml
Verified at https://datcom-magiceye-dev.corp.goog/version
=> Update magic_eye to use remoteMixerDomain

tools/apigee/apigee.py, tools/apigee/prod.env, tools/apigee/staging.env
* The keys are written to a `keys` column in the same sheet. [[Example]](https://docs.google.com/spreadsheets/d/1hxOmST5kLtil8RFfZcwYgeRvSATvvPa3EkduPpvNosc/edit?gid=193373547#gid=193373547&range=F:F)
* Once the keys are in the sheet, the next step is to import them into apigee (next PR).
=> Read projects from Google Sheet and write dc keys back to it.

tools/apigee/README.md, tools/apigee/apigee.py, tools/apigee/prod.env, tools/apigee/run.sh, tools/apigee/staging.env
* Also, added the ability to run the script in multiple modes.
* Did the migration for all staging keys.
- Keys along with the created apps and developers are now in [apigee](https://screenshot.googleplex.com/8cBkUrb6pz69npe).
- Sheet [updated](https://screenshot.googleplex.com/4d68tetAc3iQmxV) to reflect the details.
- Note that none of the staging keys have any developer details, so the script defaults developer and app info.
* Working with @ajaits on some spreadsheet issues with prod keys. Will migrate prod once those are resolved.
=> Add support for importing keys into apigee.

custom_dc/env.list.sample
...to act as a template to avoid users checking in their API keys.
=> [custom_dc] Add env.list.sample

deploy/helm_charts/envs/datagemma.yaml, tools/nl/loadtest/load.py
- updated the config for datagemma to increase qps to about 40 (same as what we have for bard): https://screenshot.googleplex.com/7VTXyFQn78qeZGY
- minor bug fix in the load testing script
=> Update DataGemma environment config

server/webdriver/tests/standalone/sanity.py
Note that once this change is in, sanity against prod will break until the latest changes are deployed to it.
=> Update website sanity to adapt to the new homepage.

static/custom_dc/custom/overrides.css
* Fixes misalignment of the custom dc header following the latest base dc updates.
| Before | After |
|---|---|
| ![Home Page](https://github.com/user-attachments/assets/c4dd908e-41fe-4afe-b844-c9922d41aadd)| ![Home Page](https://github.com/user-attachments/assets/39a5e166-d8b9-4b37-a6ec-5396d73e0205)|
|![Search](https://github.com/user-attachments/assets/a89e7eeb-e8d1-46c6-8ce1-e6f27f78ec0a)| ![Search](https://github.com/user-attachments/assets/5160da48-f0e0-4d35-8fcc-4161d23f1db8)|
=> Fix custom dc header.

tools/screenshot_diff/diff.sh
update the script to use latest version tag as the prod commit because prod tag is a little finicky to pull
=> update screenshot diff script

server/webdriver/screenshot/local/page.json, server/webdriver/screenshot/remote/dev.datacommons.org/nl.json, server/webdriver/screenshot/runner.py
Adds new screenshots to be included. All scenarios added are homepage related. Many are for the explore page, but are one-click scenarios from the home page.
Also adds an optional width parameter on the screenshot config to allow for custom width. Adds one screenshot test for 800px width.
=> Screenshots

tools/nl/analysis/log/dashboard.md
this is to be able to merge pr #3707. Since prashanth is no longer under the CLA, we can't merge that old PR anymore
=> dashboard documentation from prashanth old pr

static/css/stat_var_hierarchy.scss, static/css/tools/visualization.scss
fix vis tools getting cut off:
https://github.com/user-attachments/assets/69cc332d-f7d5-4af5-bb92-69f26930b952
fix stat var widget overflow:
https://github.com/user-attachments/assets/c87a3dbe-90db-4d8a-aadb-ebe864a10ad5
=> fix some css

static/js/components/nl_search_bar/auto_complete_input.tsx, static/js/components/nl_search_bar/auto_complete_suggestions.tsx, static/js/shared/ga_events.ts
Trigger GA Event for tracking autocomplete selections with the selected index.
=> Google Analytics AutoComplete Tracking

static/js/components/nl_search_bar/nl_search_bar_header_inline.tsx
Identifies the environment based on the window.location.hostname parameter.
=> Enable autocomplete for Autopush environment.

.github/workflows/all-commits-in-master.yml
Tested here: https://github.com/hqpho/dc-website/pull/8
=> Fix all-commits-in-master ambiguous argument issue

run_cdc_tests.sh, server/templates/tools/map_examples.json, server/templates/tools/visualization_examples.json, server/webdriver/shared_tests/vis_map_test.py
- Remove some landing page example links that don't work anymore
- Add parallelization for Custom DC autopush tests
- Add some waiting for elements to be ready in tests that were failing on Cloud Build
=> Webdriver test fixes and improvements

server/templates/tools/map_examples.json, server/templates/tools/visualization_examples.json
The previous links were removed in https://github.com/datacommonsorg/website/pull/4719
=> Replace CO2 emissions example links

build/ci/cloudbuild.push_cdc_stable.yaml
- Ensure the whole trigger fails if getting the commit label fails
- Fix comments
=> Tweak CDC stable release trigger config

gke/get_storage_permission.sh
Reduced from roles/bigquery.admin to roles/bigquery.dataViewer
=> Updated website service account bigquery permissions

scripts/update_prod_tag.sh
This is currently available for copy/paste from release documentation but does not take into account that remote names vary.
=> Add script for updating prod tag

deploy/helm_charts/envs/dev.yaml, deploy/helm_charts/envs/staging.yaml, tools/delete_cron_outputs/run.sh
* This is a cron testing job, but it will never run automatically. Instead it can be manually run as part of the release process.
* Also, add a comment on the dev schedule string.
=> Set up "cron" testing job in staging

server/webdriver/shared_tests/vis_map_test.py
Tested with 100 runs by pytest-flakefinder
=> Deflake map tool webdriver tests

server/routes/place/html.py
Per bug bash session, we are removing India and Russia from the new place page experiment group.
=> Remove India and Russia from place page experiment group

static/css/place/dev_place_page.scss, static/js/place/dev_place_main.tsx
When clicking on show metadata in Key Demographics sources: https://screenshot.googleplex.com/AZy3mBZVrvHbewD
=> Revert css I unintentionally modified & add the source sv modal on Place page sources

server/webdriver/shared_tests/place_explorer_test.py, static/js/place/chart.tsx
=> Fixed bug where export csv wasn't working on place page 'snapshot' group bar charts

server/webdriver/shared_tests/ranking_test.py
fix a webdriver test that broke with new population data. 
Update the check to just look for values along the y axis instead of checking the actual value which can change
=> update webdriver test

deploy/terraform-custom-datacommons/README.md, deploy/terraform-custom-datacommons/create_artifact_repository.sh, deploy/terraform-custom-datacommons/modules/main.tf, deploy/terraform-custom-datacommons/modules/variables.tf
* Added script to create custom data commons docker artifact repo in gcp. 
* Updated CDC terraform README.md
* Added terraform variables for adjusting CDC web service instance count.
=> Added script to create custom data commons docker artifact repo in gcp. Added terraform variables for adjusting CDC web service instance count.

server/routes/dev_place/api.py, server/routes/dev_place/utils.py
Fixes guernsey topics: https://screenshot.googleplex.com/4M3tcdjeMurDjga
Also allows Zip codes to be used as children of cities, see LA: https://screenshot.googleplex.com/5ZTyvSuwfPuaEUD
=> [Place Page Revamp] Remove the chart configs when the blocks are empty.

.github/workflows/codeql-analysis.yml
Fix for https://github.com/datacommonsorg/website/actions/runs/12952289311/job/36129286749
=> Permissions fix to codeql-analysis

static/js/apps/explore/app.tsx, static/js/apps/explore/autoplay.tsx
Before: https://screencast.googleplex.com/cast/NjU3NTU1Njg0MDY1MjgwMHw3ZTZiNWY1Yi0wMg
After: https://screencast.googleplex.com/cast/NTQ3MDEzMzc5NDM3MzYzMnxhNDJhZTJiMC0wMA
=> Fixed autoplay queries

static/js/apps/explore/app.tsx, static/js/components/elements/scroll_to_top_button.tsx
Fixes the explore page floating arrow. https://screenshot.googleplex.com/9CugJihN5Fz2cGF
=> Pass in theme provider for emotion styling in explore page

server/routes/dev_place/api.py, server/routes/dev_place/utils.py, server/tests/routes/dev_place/utils_test.py
Cover all the helper methods functionalities with unit tests to ensure no regressions, especially on small features.
Note that with these unit tests we only want to mock the api responses, and the translation responses.
=> [Place Page Revamp] Adds unit tests for a lot more helper functions.

server/templates/dev/datagemma.html, static/css/datagemma.scss, static/js/apps/datagemma/app.tsx, static/webpack.config.js
cleaning up the DataGemma UI a little according to asks from adriana
=> DataGemma UI cleanup

static/css/explore.scss, static/css/place/dev_place_page.scss, static/css/shared/item_list.scss, static/js/apps/explore/item_list.tsx, static/js/apps/explore/result_header_section.tsx, static/js/place/dev_place_main.tsx
https://screenshot.googleplex.com/3V9CbZyWL2r8rZG
=> [Place Page Revamp] Relevant topics bar to wrap around. 

server/lib/nl/common/rank_utils.py
fixes [b/396104577](https://b.corp.google.com/396104577)
=> Fix a key error

server/routes/dev_place/utils.py, server/tests/routes/dev_place/utils_test.py
Bug fix for the type of places to use
=> Bug fix for chart name

docs/feature_flags.md, scripts/update_gcs_feature_flags.sh
Adds the second command for the us west1 cluster for production. 
Fixes doc to put the right command.
=> [Feature Flags] Fix production rollout script.

server/webdriver/tests/place_explorer_test.py, static/js/place/dev_place_overview.tsx, static/js/shared/components.tsx
Tested by [running NodeJS server ](https://github.com/datacommonsorg/website/blob/master/static/src/README.md) and encountered 0 compile errors with this patch.
=> Remove references to Theme in shared/components.tsx

server/lib/nl/explore/params.py, server/lib/nl/explore/topic.py, server/routes/explore/api.py, server/routes/explore/helpers.py, static/js/apps/explore/app.tsx, static/js/constants/app/explore_constants.ts
Parameterize the limits for setting max topics that get opened in fulfill and  the max number of svs from subtopics that get processed when processing topics
=> [NL] add url params for topic limit and subtopic sv limits

build/ci/cloudbuild.push.yaml
- Increased cloudbuild autopush build on push memory.
- Added logging to website image build step
=> Increased cloudbuild autopush build on push memory.

static/js/apps/explore/item_list.tsx, static/js/apps/explore/result_header_section.tsx
Fixed: https://screenshot.googleplex.com/4VPqwSF46DGjU7t
Previously as: https://screenshot.googleplex.com/7o3wGjUFrb3pqXT
=> [Place Page Revamp] Only show relevant topics label based on boolean

build/ci/cloudbuild.update_feature_flags.yaml
Replicating what is described in https://cloud.google.com/build/docs/configuring-builds/pass-data-between-steps#passing_data_using_workspaces
=> [Feature Flags] Pass variable through the workspace

server/config/feature_flag_configs/production.json
Note that this is already enabled in staging!
=> [Dynamic Placeholders] Enable dynamic placeholders experiment in prod

server/lib/nl/explore/topic.py
fixes: https://groups.google.com/a/google.com/g/datacommons-alerts/c/ytLTpOuR3eI/m/hrbHXzF_AAAJ?utm_medium=email&utm_source=footer
=> Fix bug with NL URL parameters

server/requirements.txt, server/routes/experiments/biomed_nl/traversal.py
Also remove unused import in traversal.py
=> Add sentence_transformers to server/requirements.txt.

server/routes/experiments/biomed_nl/api.py, server/routes/experiments/biomed_nl/entity_recognition.py
While the biomed NL api is under development and unstable, we should catch and log exceptions to avoid crashing autopush.
=> [biomed_nl] Catch all exceptions in api to prevent autopush crashes

server/__init__.py, server/routes/experiments/biomed_nl/api.py, server/routes/experiments/biomed_nl/html.py, server/templates/experiments/biomed_nl.html, static/css/biomed_nl.scss, static/js/apps/biomed_nl/app.tsx, static/js/apps/biomed_nl/main.ts, static/webpack.config.js
=> [biomed_nl] Create basic UI based on the datagemma page

server/webdriver/shared_tests/vis_map_test.py
Attempting to resolve a flakey test by removing an element check race condition
=> Updated flakey map viz test

server/routes/experiments/biomed_nl/traversal.py, server/routes/experiments/biomed_nl/utils.py, server/services/datacommons.py, server/tests/services/datacommons_test.py
* Re-ran biomed hero queries to ensure no regressions: https://docs.google.com/spreadsheets/d/1uvL990dvqhes7FoFf-iPuiwc2qGt042K69FYuygZVIc/edit?gid=1335743036#gid=1335743036
=> Move dcid batch logic from v2node to biomed utils.

server/webdriver/shared_tests/place_explorer_i18n_test.py, server/webdriver/tests/place_explorer_i18n_test.py
Moved new place page i18n test out of shared testing folder to avoid CDC test failures  (the new place page is disabled in CDC, which was causing the failure)
=> Moved new place page i18n test out of shared testing folder to avoid CDC test failures

server/config/feature_flag_configs/autopush.json, server/requirements.txt, server/routes/experiments/biomed_nl/traversal.py, server/routes/experiments/biomed_nl/utils.py, static/css/biomed_nl.scss, static/js/apps/biomed_nl/app.tsx
Includes:
* re-implementing cosine-score calculation via numpy
* small ui layout changes
after PR:
before PR:
=> [biomed_nl] Remove sentence_transformers from website server + UI nits

static/js/apps/biomed_nl/app.tsx
Previous url format: 
> https://localhost:8080/experiments/biomed_nl/#q=What%20is%20the%20chembl%20ID%20of%20acetaminophen%3F
then clicking on the citation link would replace the hashParam with the scrollTo:
> https://localhost:8080/experiments/biomed_nl/#biomednl-ref-1
New URL format: 
> http://localhost:8080/experiments/biomed_nl/?query=What+is+the+chembl+ID+of+acetaminophen%3F
clicking on citation: 
> http://localhost:8080/experiments/biomed_nl/?query=What+is+the+chembl+ID+of+acetaminophen%3F#biomednl-ref-1
=> [biomed_nl] migrate from hash param to URL param

server/routes/experiments/biomed_nl/api.py, server/routes/experiments/biomed_nl/entity_recognition.py, server/routes/experiments/biomed_nl/traversal.py, server/routes/experiments/biomed_nl/utils.py, server/tests/routes/experiments/biomed_nl/entity_recognition_test.py, server/tests/routes/experiments/biomed_nl/traversal_test.py, static/css/biomed_nl.scss, static/js/apps/biomed_nl/app.tsx
Examples with answer+ chips:
Example no answer, only chips:
=> [biomed_nl] Add entity chips to final result, timeout final entity fetching after 3 minutes 

static/js/apps/biomed_nl/app.tsx
=> [biomed_nl] Add link to legal agreement

server/config/feature_flag_configs/production.json
Hold off on merging  until new website release is complete
=> Enable new place pages in prod

scripts/update_gcs_feature_flags.sh
I was able to successfully enable the `dev_place_ga` flag in prod with this change
=> Fixed bug where prod feature flags werent updating after validating the production flag file

server/config/feature_flag_configs/custom.json, server/config/feature_flag_configs/dev.json
Hold off on merging until new website release is complete
=> Enable new place page in custom dc and dev

server/integration_tests/test_data/demo_fallback/query_5/chart_config.json, server/integration_tests/test_data/e2e_date_range/populationincaliforniaafter2013/chart_config.json, server/integration_tests/test_data/e2e_edge_cases2/californiacountieswiththebiggestincreaseinincomelevels/chart_config.json, server/integration_tests/test_data/e2e_electrification_demo/howhaspovertyreducedintheseplaces/chart_config.json, server/integration_tests/test_data/e2e_electrification_demo/howhasthegdpgrown/chart_config.json, server/integration_tests/test_data/e2e_us_demo/howdoeshouseholdincomecomparewithratesofdiabetesinusacounties/chart_config.json, server/integration_tests/test_data/textbox_sample/query_1/chart_config.json
NL PR checks are currently blocking a few PRs.
=> Update NL Goldens

server/config/feature_flag_configs/staging.json
Dynamic Placeholders Launch GA in Staging.
Follow up CL to launch in Production.
=> Dynamic Placeholder Launch to GA for STAGING

server/config/feature_flag_configs/production.json
Dynamic Placeholders Launch GA in Production.
Experiment result were overwhelmingly positive with a significant improvement in NL queries executed per page view. 
We will be rolling out the experiment to GA. The experiment ran at 20%. This feature remains limited to English & Desktop traffic.
Verified in staging.
=> Dynamic Placeholder Launch to GA for PRODUCTION

server/webdriver/shared_tests/place_explorer_test.py, static/js/place/dev_place_main.tsx
=> Fixed search bar placeholder in place category pages

static/css/core.scss
- Bug: b/407053284
- Tested this locally in various locales and screen sizes
Before:
After:
=> Fixed word wrap in localized headers

custom_dc/env.list.sample, run_cdc_dev_docker.sh, scripts/update_gcs_feature_flags.sh, server/config/feature_flag_configs/custom.json, server/config/feature_flag_configs/dev.json, server/config/feature_flag_configs/production.json, server/lib/nl/detection/llm_api.py, server/webdriver/shared_tests/place_explorer_i18n_test.py, server/webdriver/shared_tests/place_explorer_test.py, server/webdriver/tests/place_explorer_test.py, static/js/apps/data/data_sources.json, static/js/i18n/compiled-lang/en/place.json, static/js/i18n/i18n_place_messages.ts, static/js/i18n/strings/en/place.json, static/js/place/dev_place_main.tsx
- Add support for facet requests for sql backends. ([#1549](https://github.com/datacommonsorg/mixer/pull/1549))
- Return correct facet info in series facet responses. ([#1550](https://github.com/datacommonsorg/mixer/pull/1550))
=> 2025-04-08 Custom DC stable release

server/routes/place/utils.py, server/tests/routes/place/mock_data.py, server/tests/routes/place/utils_test.py
=> fixed bug in the place page overview table where we were not pulling the latest observation dates

server/webdriver/shared_tests/download_test.py
@ajaits can you confirm that this data change is expected?
Autopush, : Source is www.census.gov ... https://screenshot.googleplex.com/6Kd53TCVUsjwjRh
Prod: source is www2.census.gov ... https://screenshot.googleplex.com/5u8387YziTpJkPe
=> Fixes failing test case in data download tool due to data change

server/webdriver/shared_tests/explore_test.py, static/js/apps/explore/app.tsx
This guarantees that navigating to a different topic/place on click will wipe the highlight chart.
=> [Chart Injection] Use helper function for updating page content

server/config/home_page/partners.json
=> Remove legacy custom instances from homepage

static/js/apps/data/data_sources.json
Dataset documentaion update for release-20250515
=> Release: release-20250515: Dataset update

server/config/feature_flag_configs/production.json
Deprecated unused show_api_modal flag in production
=> Deprecated show_api_modal production flag

.github/workflows/submodule-update.yml, server/webdriver/shared_tests/map_test.py, server/webdriver/shared_tests/scatter_test.py, server/webdriver/shared_tests/timeline_test.py, server/webdriver/shared_tests/vis_map_test.py, server/webdriver/shared_tests/vis_scatter_test.py, server/webdriver/shared_tests/vis_timeline_test.py
=> [Submodule Update] Add fetch-depth: 0

.github/workflows/submodule-update.yml
Previous run showed an issue with the Label creation, this should resolve it!
Also disable the automated runs for now.
=> [Submodule Update] Add permissions for label creation

server/lib/nl/explore/related.py, server/routes/explore/api.py
To reduce the latency of the Follow Up Questions component, a cache was added to the route that is based on the body of the request and the Gemini model used was switched from 2.5 Pro to 2.5 Flash.
=> [Explore] Added Redis cache and switched Gemini model

server/routes/redirects.py
update the redirect to a page that exists
=> update /nlnext redirect

.github/workflows/integration-goldens-update.yml, build/ci/cloudbuild.update_nl_goldens.yaml
Google Org restricts some features that make authentication from github to GCP much harder. Running this action from Cloud Build simplifies things!
=> [Productionization Excellence] Move the Goldens update to be triggered from Cloud Build in order to guarantee access to Vertex AI.

tools/nl/nl_metadata/add_metadata.py
Fixes some small bugs in add_metadata.py relating to reading in the failed attempts file path and exporting statvars
=> Fix bugs in add_metadata.py 

server/webdriver/shared.py
* Increased loading wait time in webdriver tests to reduce flakiness like [this one](https://screenshot.googleplex.com/BoYnVBnmi7nZzmm).
=> Increase loading wait time in webdriver tests

server/config/nl_page/chart_titles_by_sv.json, server/integration_tests/test_data/e2e_date_range/lifeexpectancyinusstatesinthelast5years/chart_config.json, server/integration_tests/test_data/e2e_fallbacks/lifeexpectancyinuscounties/chart_config.json, server/integration_tests/test_data/e2e_single_date/lifeexpectancyinusstatesin2018/chart_config.json, server/integration_tests/test_data/international/query_2/chart_config.json, tools/nl/titles/demo_svs_1.3k_names.csv
Commits:
* [Correct IntentionalSelfHarm as a Rate rather than Percentage.](https://github.com/datacommonsorg/website/commit/501a6995109d8afc97bc6ec7a59f1b033e085e7d)
* [Update tests based on renamed statvar title.](https://github.com/datacommonsorg/website/commit/dd8aaae2a5945a59470bce710f47880f6e58bf45)
=> Correcting SV graph title to match the description

server/config/feature_flag_configs/production.json, server/lib/util.py, server/webdriver/cdc_tests/explore_test.py
To unblock https://github.com/datacommonsorg/website/pull/5483
See http://b/444077626 for details
=> [cdc-webdriver] Read feature flags from custom.json

server/routes/static.py, server/templates/version.html
Demo:
- https://screenshot.googleplex.com/B44WzXARog5vqCy
- https://screenshot.googleplex.com/6SwsbpKM869RaqU
- https://screenshot.googleplex.com/6RKGwkDR7nSE8QL
=> [Mixer Flags] Website /version section for mixer feature flags
