server/__init__.py, server/chart_config.json, server/routes/api/chart.py, server/routes/api/place.py, server/routes/api/stats.py, server/services/datacommons.py, static/js/place_overview.ts, static/js/place_template.tsx, static/js/stats_var.test.ts, static/js/stats_var.ts
- Move chart config generation to server side.
- Do not show chart sections if not available.
- Better handle child and parent places in dropdown menu.
- Remove places types from config since chart display is based on statsvars.
=> Dynamically generate chart config based on place's stats vars

server/lib/translator.py
Schema mapping now does not take bigquery dataset name any more. Remove it in the translation tool as well.
=> Fix translation tool schema mapping

server/routes/api/place.py, static/js/browser/kg.js, static/js/shared/util.js, static/webpack.config.js
Right now for containing places, only one type is selected. When all child places are grouped by the type, child place are grouped randomly. This fix the bug.
=> Use all place types in contained in (child) place relation

static/js/chart/draw.ts, static/js/tools/statsvar_menu.tsx
- fix the problem that the chart cannot be rendered when the statsvar is not available for one of the places
- fix the filtering logic of menu: need to check two levels for value nodes.
=> fix the chart when statsvar is not available

run_test.sh
Test failures on datcom-ci were undetected by cloud build because the error codes weren't propagated from the run_test script.
=> Exit tests upon any failure, and propagate errors from test commands

static/js/chart/draw.ts, static/js/tools/timeline_chart.tsx, static/js/tools/timeline_chart_region.tsx, static/js/tools/timeline_page.tsx, static/js/tools/timeline_util.ts
This eliminates the need of random dom id and tracking them in chart region. It also get rid of the flashing effect when updating places and stats vars.
Some caveats still exists: there are multiple rendering for each place/statsvar update due to redundent props update. place name and stats var name mapping could be simplified throughout.
=> Create a Chart componenet to hold reseources of a single chart

static/js/chart/draw.ts
Current behavior:
With this fix:
=> Fix 0 range in d3 y axis plot

static/js/tools/statsvar_menu.tsx
The statsvar title is not set when:
- (1) select a statsvar 
- (2) unselect the statsvar 
- (3) select a new statsvar.
The reason is that the variable that stores the statsvar title is not reset, so the condition of setting statsvar title based on count is not satisfied.
=> fix the problem of statsvar title not properly set

static/js/tools/mock_functions.tsx, static/js/tools/timeline_chart.tsx, static/js/tools/timeline_chart_region.tsx, static/js/tools/timeline_page.test.tsx, static/js/tools/timeline_page.tsx, static/js/tools/timeline_search.tsx
- pass addPlace/removePlace, and removeStatsVar functions to search bar and chart region
- move the mock functions into a separate file for reusing by different tests
- fix the error of calling api when no statsVar/ places are selected
=> add event propagation in timeline_search and timeline_chart

static/js/chart/draw.ts, static/js/shared/util.js
- Show original number when y tick is less than 1 to avoid showing 0.5 as 500m.
- Make default "show more" height larger so the "show more" box is hidden in chart view.
=> UI fix on d3 chart y axis format and kg chart default height

static/css/draw.scss, static/js/chart/draw.ts
=> fix issue #272 Chart labels too big 

static/js/chart/draw.ts
add the extra space in timeline page chart only
Timeline page:
Place:
=> Fix issue #293, Extra top padding on place page 

server/routes/api/chart.py, static/js/chart/draw.ts, static/js/place/place.ts, static/js/place/place_template.tsx, static/js/shared/data_fetcher.ts, static/js/tools/timeline_chart.tsx
- keeps only latest data unless line charts are required
- client still fills in with stats data if data isn't cached yet
=> Use cached chart data for place explorer

static/js/shared/util.js
Temporary fix for #318 - window.location.host somehow returns "undefined", possibly because we aren't using async XHR and the processing is blocked by the large request. This is a temporary fix to use the prod mixer, which has more resources, until we move to asynchronous calls.
=> Default browser to use prod mixer

static/js/chart/draw.ts
The bug is because the x-axis range and the width for plotting the grids are mismatched. 
Timelines Page after fix:
Place Page
=> Fix "timelines lines extend beyond the chart area"

static/css/tools/choropleth.scss, static/js/tools/choropleth/choropleth.tsx
After investigating for a few hours, I could find no better way of resizing the map to the screen than setting it to a size that is some fraction of the screen size. I suspect there must be a way of telling a React component to "take up as much screen as it can without overstepping other components," but I have not found a way of doing this. 
Below is a picture of the finished product, on a large screen size (such that before it would have taken up a small fraction of the screen):
=> Added map resizing.

server/main.py, server/routes/api/place.py, server/services/datacommons.py, static/js/place/place_template.tsx
Note there are some auto-formatting by yapf on the modified files.
webdriver tests revealed a bug in current children places selection. With new places from wikidata, there are more children place types. For example, California has a village children that has 0 population, thus making the "containing" places chart not showing.
Added a fix to pick the child place type that has the highest average population.
[1] http://staging.datacommons.org/api/place/child/geoId/06
=> Fix key error exception and update children place selection logic

cloudbuild.deploy.yaml
The dep of google-cloud-secret-manager, grpcio, takes about 10min to complete, should add enough buffer for testing, binary push etc.
=> extend timeout to 1 hour for website deploy

static/js/shared/data_fetcher.test.ts, static/js/shared/data_fetcher.ts
When doing per capita calculation, if population is 0, we want to set the result for that calculation to be 0, not NaN.
=> fix dividing by population of 0

server/routes/api/place.py
stopgap fix for related place charts -- we were returning many international places with no data.
=> scope similar places to the same country if possible

static/js/browser/kg.js
Prepare for adding more geoJsonCoordinate* properties for lower resolutions.
=> blacklist geoJsonCoordinatesDPX from browser

server/configmodule.py, server/main.py, server/templates/base.html
I've tried setting up filters within GA but that doesn't seem to apply, and staging data is mixed up with prod. This should keep things much cleaner.
=> Use different Google Analytics account for non-prod instances

server/__init__.py, server/routes/api/place.py, server/routes/place.py, server/routes/ranking.py, server/services/datacommons.py, server/templates/ranking.html, static/css/ranking.scss, static/js/chart/draw.ts, static/js/place/place_template.tsx, static/js/ranking/ranking.ts, static/js/ranking/ranking_histogram.tsx, static/js/ranking/ranking_page.tsx, static/js/ranking/ranking_table.tsx, static/js/ranking/ranking_types.ts, static/js/shared/data_fetcher.ts, static/js/shared/stats_var_labels.test.ts, static/js/shared/stats_var_labels.ts, static/js/shared/stats_var_titles.test.ts, static/js/shared/stats_var_titles.ts, static/webpack.config.js
Adds basic ranking pages, supporting rankings of stat vars from the chart config, grouped by place type and optionally scoped by a containing place. There is support for multiple stat vars as well, though we won't use it for now.
=> Ranking pages v0

static/js/tools/choropleth/choropleth.tsx
In an effort to make the website use types and be more react friendly, I have made some small refactoring changes.
1. function() is unbinded, to remove redundant code, I converted all functions to () => {} which is binded.
2. Added types to the State.
3. Added types to return functions.
4. Converted breadcrumb to use React Component instead of .innerHTML.
5. The map is a bit smaller. I divide by 3.5 instead 3.0. The map's legend was going out of boundaries.
6. Ran linter.
7. Adds public to methods as per Codacy recommendation.
8. Fixes any comments on previous PR.
Screenshot:
=> Small refactor changes to be more react and typescript-friendly

server/routes/api/ranking.py, server/routes/ranking.py, server/services/datacommons.py, server/templates/ranking.html, server/webdriver_tests/screenshot/screenshot_test.py, static/js/ranking/ranking.ts, static/js/ranking/ranking_histogram.tsx, static/js/ranking/ranking_page.tsx, static/js/ranking/ranking_table.tsx
Also adds better error handling and cleans up client lint errors
The Mixer API was updated to get in https://github.com/datacommonsorg/mixer/commit/f6d3c6a61a9450837e00b91bf7289746a78a205a
The change doesn't affect prod since the ranking pages aren't launched yet, but it does break the screenshot tests.
=> [ranking] Add support for per-capita, migrate to get api

static/js/place/chart.tsx
One example would be the health outcome page where there is only data for cdc500 cities.
=> Do not show parent places chart if there is no data for parent places.

server/templates/place.html, static/js/chart/base.ts, static/js/chart/draw.ts, static/js/dev.ts, static/js/place/chart.tsx, static/js/place/chart_block.tsx
* Fix overlapping stack bar charts when there is incomplete stat var data
* Highlight the SVG rect of the current place (it's quite subtle so we might want to tweak it)
* Make place labels clickable again (also applied to stack bar charts)
* Fix label rendering crispness and timelines tool (regression from #472)
=> Some chart rendering fixes

server/routes/api/chart.py, server/tests/chart_test.py, static/js/place/chart.tsx, static/js/place/types.ts
add explore url for choropleth charts which will redirect to timeline tool for the stat var for the current place
Changes:
- updated api/chart/choroplethdata/<dcid> to return the explore url for each stat var
- updated chart.tsx to get explore url for choropleth charts
=> get explore url for choropleth charts

server/routes/api/ranking.py, server/templates/ranking.html, static/css/ranking.scss, static/js/chart/base.ts, static/js/chart/draw.test.ts, static/js/chart/draw.ts, static/js/place/chart.tsx, static/js/place/chart_block.tsx, static/js/place/main.tsx, static/js/place/place.ts, static/js/place/types.ts, static/js/ranking/ranking.ts, static/js/ranking/ranking_histogram.tsx, static/js/ranking/ranking_page.tsx, static/js/ranking/ranking_table.tsx, static/js/shared/stats_var_titles.ts
Also carry over params so the per capita, unit and scaling match the original charts.
=> Add links to ranking pages from stat var chips

server/routes/api/landing_page.py
Overview chart data is filled with "parent" data but is not rendered, thus leaving a sub title only.
=> Fix a bug that same chart reference in overview and topic page

static/js/chart/draw_choropleth.ts
This change should make sure that the tooltip is always above and to the right of the mouse pointer, so it won't get in the way of hovering over the current area
=> fix tooltip positioning

static/js/place/chart.tsx, static/js/place/place.ts
- add check to only call the choropleth APIs if dcid is from USA 
- add check to only draw choropleth if there is geojson data
=> add some checks

server/routes/api/landing_page.py, static/js/place/chart.tsx, static/js/place/types.ts
Previously the statsVars are at Chart Block level. 
In age aggregation, then US age trend chart and US similar places charts could use different aggregated age buckets.
=> Allow per chart stats vars to accommodate aggregation

server/chart_config.json
Use the WDI stat var "Amount_EconomicActivity_GrossDomesticProduction_Nominal_PerCapita" instead. That is USD and only for country level.
Can revisit on using the Amount_EconomicActivity_GrossDomesticProduction_Nominal_AsAFractionOf_Count_Person version instead after some other work.
=> Replace GDP chart with GDP per capita.

static/data/statsvar_path.json, tools/pv_tree_generator/build_tree.py
Only StatVars with an mprop of "count" can be used as denominators. (The diff for `hierarchy_statsvar.json ` can be loaded)
Thanks for reviewing.
=> [PV Tree Generator] restrict mprop to count for denominators

server/app_staging.yaml, server/main.py
Check x-forwarded-proto headers instead for ssl, and use a pre-request handler to redirect if non-ssl
https://stackoverflow.com/questions/32237379/python-flask-redirect-to-https-from-http
secure: always in the yaml file does not work for app engine flex
=> ssl fix take 3

static/js/place/search.ts
fixes #522 
changes:
- if autocomplete object isn't selected (aka user isn't on one of the autocomplete suggestions), get the list of autocomplete predictions for what the user has entered and redirect according to the first prediction in the list.
=> Use first autocomplete result when pressing enter in search

static/js/chart/draw_choropleth.ts, static/js/place/chart.tsx, static/js/place/chart_block.tsx, static/js/place/main.tsx, static/js/place/place.ts
- When clicking on a place in the bar charts or choropleth and opening a new tab for the clicked place, go to the same topic page as the current one
=> Add topic to click url

cloudbuild.deploy.yaml, dispatch.yaml, go/.gcloudignore, go/go.yaml, go/main.go
This is a proof of concept to use go backend together with the current Flask server. This goal is to:
- write new endpoint in golang
- gradually migrate python to golang
- finally deprecate the flask server.
I have done the gcloud app deploy locally and can see the response from go service: https://staging.datacommons.org/go/
=> Proof concept to add GO backend and co-exist with Flask

server/routes/api/chart.py, static/js/chart/draw_choropleth.ts, static/js/place/chart_block.tsx, static/js/place/types.ts, static/package.json
- use package "geo-albers-usa-territories" so puerto rico choropleth charts can be drawn
- use fitSize method from https://bl.ocks.org/HarryStevens/0e440b73fbd88df7c6538417481c9065 for fitting and centering the map
- when getting geoJson for puerto rico, use the highest resolution version of simplified geojsons because lower resolutions will look like a mosaic
=> draw choropleth for puerto rico

README.md
Not sure if you like this idea, but I thought I'd propose it.
Instead of manually downloading the latest Chrome Driver version.
1. Curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE
2. Store the response as **CHROMEDRIVERV**.
3. Download https://chromedriver.storage.googleapis.com/${**CHROMEDRIVERV**}/chromedriver_linux64.zip
=> Automate downloading latest version of Chrome Driver

cloudbuild.py.yaml
I have made flask_test, package_js , and pv_tree_generator run in parallel from the beginning.
flask_webdriver_test will run after package_js has completed.
Times:
Current Behavior Run 1: 324 secs
Current Behavior Run 2: 306 secs
Current Behavior Run 3: 314 secs
Parallel Run 1: 256 secs
Parallel Run 2: 245 secs
Parallel Run 3: 278 secs
=> Parallelizes Testing Steps

server/webdriver_tests/README.md, server/webdriver_tests/place_explorer_test.py, server/webdriver_tests/timeline_test.py
**Only Testing WebDriver tests total time.**
Current Behavior with time.sleep():
Run 1: 124secs
Run 2: 119secs
Run 3: 118secs
Run 4: 117secs
New Behavior with WebDriverWait:
Run 1: 55 secs
Run 2: 69 secs
Run 3: 67secs
Run 4: 61secs
Improvement of 1 minute 👍 
I wrote a README for anyone who wishes to maintain the tests.
=> Improve Test Waiting Time

static/css/tools/choropleth.scss, static/js/tools/choropleth/choropleth.tsx, static/js/tools/choropleth/choropleth_template.tsx
When in the choropleth tool and switching stat vars or changing the current place, update the title and then show loading indicator. Loading indicator not shown when first navigating to the choropleth tool.
=> Loading Indicator for Choropleth Tool

cloudbuild.screenshot.yaml, run_test.sh, server/requirements.txt, server/webdriver_tests/README.md, server/webdriver_tests/base_test.py, webdriver-chrome/Dockerfile, webdriver-chrome/README.md, webdriver-chrome/cloudbuild.yaml
1. Adds pytest-parallel to requirements.txt. It's pytest + parallel plugin.
2. Updates Dockerfile to install Selenium Grid.
3. Adds -t flag in run_tests.sh to run tests in parallel.
4. Adds check to make sure $SELENIUM_SERVER is specified.
5. Increases TIMEOUT to 60 seconds.
6. Updates all documentation and README.md.
Note, PYTEST_PARALLEL is currently an OS variable. I will research to see if we can pass it in as an argument to Pytest.
-t will start selenium grid. Otherwise, run normal test (without parallel and without selenium grid).
=> Webdriver tests in parallel

static/js/tools/scatter2/chart_loader.tsx, static/js/tools/scatter2/util.ts
1. Fix `formatDate` not adding extra zeros before single digit months and days
2. Fix `isDateChosen` not checking if month or day is not set
=> [Scatter2] Fix formatDate and isDateChosen

deployment/config.yaml, deployment/website.yaml.tmpl
See discussion: https://stackoverflow.com/a/61936155.
Basically without startupProbe, the liveness probe can timeout if server starts slow and restart it, making it an infinite loop.
=> GKE does not support startupProbe yet, so only keep readiness probe

server/routes/api/chart.py, server/routes/api/landing_page.py, server/routes/api/place.py, server/routes/api/ranking.py, server/routes/ranking.py, server/tests/api_place_test.py, static/package-lock.json, static/package.json
Make locale a default value in cached_i18n_name, get_i18n_name in case upstream missing it.
Update cached_i18n_name to fall back to name, if there is no nameWithLanguage, which is legitimate for some places.
Switch to use cached_i18n_name or get_i18n_name and have caller pass in locale.
Added unit test
Tested
ranking.py
http://127.0.0.1:8080/api/ranking/Count_Person/Place/geoId/06?hl=zh https://screenshot.googleplex.com/PA4xj69AY3R7b9p
landing_page.py
http://127.0.0.1:8080/api/landingpage/data/geoId/17043 https://screenshot.googleplex.com/5r7C3B2JavYMXDU
chart.py http://127.0.0.1:8080/api/chart/geojson/geoId/06 https://screenshot.googleplex.com/Aa7CqX28LuiLAAj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Switch to i18n name

server/configmodule.py, static/js/shared/util.js, tools/pv_tree_generator/dc_request.py
The staging mixer is re-deployed in a new cluster based on new process: https://github.com/datacommonsorg/mixer/pull/423.
This is to migrate the website to use the new mixer endpoints. Once this is checked in, can remove the old staging mixer cluster.
=> Update staging mixer endpoints

build/ci/cloudbuild.deploy.yaml, deploy/base/deployment.yaml, deploy/base/kustomization.yaml, deploy/base/namespace.yaml, deploy/overlays/dev/kustomization.yaml, deploy/overlays/dev/patch_deployment.yaml, deploy/overlays/dev/patch_esp.yaml, deploy/overlays/dev/service.yaml, deploy/overlays/dev/serviceaccount.yaml, deploy/overlays/prod/kustomization.yaml, deploy/overlays/staging/kustomization.yaml, script/deploy_gke.sh, script/push_image.sh, server/configmodule.py, server/webdriver_tests/place_explorer_test.py, skaffold.yaml
In this new flow, "Kustomize" is used to compose and patch k8s yaml files.
In local dev, Skaffold is used to manage building docker image, kustomize yaml files and deploy to Minikube cluster.
This PR adds the base, dev and staging yaml files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/website/757)
=> Add k8s Kustomize config and Skaffold config dev/staging

gke/create_cluster.sh, gke/setup_robot_account.sh, server/cache.py
- Use --scopes=https://www.googleapis.com/auth/trace.append, so cloud tracing can work in GKE
- Update redis cache environment
=> More fix for production deployment

server/__init__.py, static/js/chart/draw.ts, static/js/i18n/i18n.tsx, static/js/place/chart.tsx, static/js/place/chart_block.tsx, static/js/place/main.tsx, static/js/place/page_subtitle.tsx, static/js/place/parent_breadcrumbs.tsx, static/js/place/ranking.tsx, static/js/place/topic_menu.tsx, static/js/ranking/ranking_page.tsx, static/js/ranking/ranking_table.tsx
- append hl parameter to all flask links that use url_for 
- append hl parameter to relevant js links (added a new react functional component for this)
in both cases, only propagates hl parameter if it's not 'en'.
- also disables 'explore more' link for non-en languages, since it won't be translated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/website/781)
=> [i18n] Propagate hl parameters

.gitmodules, build/ci/cloudbuild.deploy.yaml
Tested locally with cloud-build-local.
=> Cloudbuild can only use https (not ssh) for git submodule update

server/routes/api/browser.py, server/services/datacommons.py, static/js/browser/kg.js
The raw popobs cache for geoId/06 is 9.7Mb, which is not bad. Unzip it on flask server is very slow and leads to timeout. 
This way reduces the memcache object size, also user can leverage the browser cache which also use a smaller object.
Tested this on local instance, California page loads in about 15s, compared with timeout after 40s.
=> Move popobs cache unzip from server to client

build/ci/cloudbuild.deploy.yaml, deploy/base/deployment.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/dev/kustomization.yaml, developer_guide.md, run_server.sh, scripts/deploy_gke.sh, server/__init__.py, server/configmodule.py, server/services/datacommons.py, static/js/shared/util.js, tools/pv_tree_generator/dc_request.py
- Fix some config issues for autopush deploy
- Let local development talking to autopush instance
- Webdriver test still talking to staging. Long term, the webdriver should be a k8s test that uses current code, instead of talking to other services
- Remove autopush from the push step. Now all the autopush is triggered from "deployment" repo "autopush" version update
=> Update webiste config based on mixer autopush/staging deployment

server/routes/api/chart.py, server/routes/api/landing_page.py, server/tests/api_stats_test.py, server/tests/chart_test.py, static/js/chart/draw.ts, static/js/place/chart.tsx, static/js/shared/data_fetcher.test.ts, static/js/shared/data_fetcher.ts, static/js/shared/util.js, static/js/tools/mock_functions.tsx, static/js/tools/scatter2/app.test.tsx, static/js/tools/scatter2/chart_loader.tsx, static/js/tools/scatter2/util.ts
Still shows domain in both place page and timeline page.
This bundles the mixer change that removes provenance domain as well. So client and api changes are within one commit.
=> Use provenance url instead domain for sources

go/template/base.gohtml, server/routes/redirects.py, server/templates/base.html, server/templates/static/homepage.html
Testing: brought up a local server and navigated to "Tutorials" under "Documentation". Also, checked http://localhost:8080/colab.
=> Fix broken links to the tutorials page

static/js/browser/kg.js
The render process terminates for Class node, hence the loading hint erasing should happen before that.
=> Fix loading hint invalidate error

server/routes/api/place.py, server/routes/api/shared.py, server/tests/api_place_test.py, server/tests/api_shared_test.py
- Create a new file for shared flask APIs and functions
- Extract the cached_name function from place api into the new shared file
=> Extract cached_name to a shared library

static/css/browser.scss, static/js/browser2/arc_table_row.tsx, static/js/browser2/in_arc_subsection.tsx, static/js/browser2/observation_chart.tsx
Some small fixes/changes:
- limit height of in-arcs sections and allow scrolling
- only show dots on hover on the observation charts when there are too many dots
- update prefix of links to "/browser/" instead of "/browser2/"
=> [Graph Browser 2] Small fixes/changes

static/js/browser2/arc_section.tsx, static/js/browser2/browser_page.tsx, static/js/browser2/out_arc_section.tsx
For place stat var pages, show the arcs for the stat var by updating BrowserPage to also render the ArcSection for the PLACE_STAT_VAR pageDisplayType.
=> [Graph Browser 2] Show arcs for place stat var pages

server/routes/api/browser.py, server/routes/browser.py, server/tests/api_browser_test.py, static/css/browser.scss, static/js/browser2/observation_chart.tsx, static/js/browser2/observation_chart_section.tsx, static/js/browser2/weather_chart_section.tsx
- update the flask server endpoint to use new statVarObservation table & return a mapping of date to dcids
- update observationChart component to retrieve observation dcids for all the data points on the chart & have it in the state so onClick will open the observation node page right away
=> [Graph Browser 2] Fix/Improve opening observation node page from observation chart

static/css/browser.scss, static/js/browser2/arc_section.tsx, static/js/browser2/arc_table_row.tsx, static/js/browser2/in_arc_section.tsx, static/js/browser2/in_arc_subsection.tsx, static/js/browser2/out_arc_section.tsx, static/js/browser2/util.ts
- Update the ArcTableRows component to take in an array of values. The arc table row will show up to 10 values and be able to expand and collapse. 
- Update OutArcsSection component to group values by predicate and provenance Id & pass a list of values for each combination of predicate and provenance id to the ArcTableRows component
- Also removed the any types
I had also experimented with other ways to separate the list of values in each row:
- vertically aligned dot was confusing, especially when values had dashes: https://screenshot.googleplex.com/33MDP7y6QAGocwP
- comma could be confusing as to whether we are looking at a single value or multiple values: https://screenshot.googleplex.com/NYP2tjv26mPakuX
=> [Graph Browser 2] Make rows in arc table expandable

static/js/browser2/browser_page.tsx, static/js/browser2/image_section.tsx, static/js/browser2/util.ts
- Add new ImageSection component that displays images from the imageUrl property of a node
- Render ImageSection component when the PageDisplayType is BiologicalSpecimen
=> [Graph Browser 2] Show image for biological specimen pages

server/webdriver_tests/place_explorer_i18n_test.py
The position of the GDP comparison chart in Japanese for country/JPN is flaky. Disable this part of the test for now to unblock others.
=> Disable flaky webdriver test

static/js/browser2/arc_section.tsx, static/js/browser2/in_arc_section.tsx, static/js/browser2/out_arc_section.tsx
Observation nodes have no property labels or property values, so in order to get out arcs, fetch data from api/browser/triples
=> [Graph Browser 2] Use triples to get out arcs for observation nodes

static/js/browser2/out_arc_section.tsx
If a node has no out arcs, show message indicating that this is not a node.
=> [Graph Browser 2] Add not a node message

server/routes/api/browser.py, server/tests/api_browser_test.py, static/js/browser2/observation_chart.tsx, static/js/browser2/observation_chart_section.tsx, static/js/browser2/statvar_node.tsx, static/js/chart/draw.ts
- Fix bug where if an observation chart has no measurement method or observation period, clicking on a point on the chart may redirect to the wrong observation node. 
- Fixed by updating the sparql query to return more fields and then filtering on those fields
- Update the table view column name to be the stat var display name instead of the stat var id because the stat var id may be a non human curated string
- Update tooltip to show "N/A" for null values (used to just not show the value)
=> [Graph Browser 2] More observation chart updates/fixes

server/templates/browser/node.html, static/css/browser.scss, static/js/browser2/arc_table_row.tsx, static/js/browser2/browser_page.tsx, static/js/browser2/image_section.tsx, static/js/browser2/observation_chart.tsx, static/js/browser2/observation_chart_section.tsx, static/js/browser2/out_arc_section.tsx, static/js/browser2/statvar_hierarchy_search.tsx
- update page headers
- update each row to show 5 items (instead of 10) when collapsed
- fix weather observations table showing error when clicking on a row (rows for weather observations tables should not be clickable)
- make observation table values look clickable (not just on hover)
- update stat var hierarchy search input box placeholder to be "filter" instead of "search" & add ability to clear input
- filter out observations with measurement method of GoogleKGHumanCurated or HumanCuratedStats
- fix observation charts spinner problem where if we have 2 of the same stat vars expanded in the stat var hierarchy, when expanding the second one, the spinner will appear on the chart that is already expanded 
- fixed this by giving each observation chart section a randomId
the dev instance …
=> [Graph Browser 2] UI updates

gke/mci.yaml.tpl, gke/setup_ssl.sh
This is update on one-time setup and does not have any effect on future deployment.
In current setup, "website-certificate" is Google managed cert and "multi-domain" is the self managed cert. This change is to align the script with actual deployment.
=> Clean up ssl setup steps to be consistent with current deployment

server/lib/statvar_hierarchy_search.py, server/tests/statvar_hierarchy_search_test.py
There was a bug with the stat var hierarchy search where the results returned was an intersection between the results of each of the tokens except for the first token. This happened because the variable used to save all the results for the tokens was set to be the object in the search index for the first token instead of a new object that read in the object in the search index for the first token. Fixed and added a test.
=> [Graph Browser 2] Fix bug with the stat var hierarchy search

server/routes/api/browser.py, static/js/browser2/arc_section.tsx, static/js/browser2/browser.ts, static/js/browser2/browser_page.tsx, static/js/browser2/statvar_group_node.tsx, static/js/browser2/statvar_hierarchy.tsx, static/js/browser2/util.test.ts, static/js/browser2/util.ts
- Before rendering browser page, find out if the page has stat var hierarchy by making call to get all stat vars for current dcid
- Move stat var hierarchy section after out arcs section & add loading spinner
- If a node has a "Variables" child stat var group, move that group to the top of the section
dev instance has been updated with these changes (eg. https://dev.datacommons.org/browser/geoId/12086)
=> [Graph Browser 2] Stat Var Hierarchy Updates

server/routes/api/place.py, static/css/tools/scatter2.scss, static/js/tools/scatter2/app.test.tsx, static/js/tools/scatter2/app.tsx, static/js/tools/scatter2/chart.tsx, static/js/tools/scatter2/chart_loader.tsx, static/js/tools/scatter2/info.tsx, static/js/tools/scatter2/place_options.tsx, static/js/tools/scatter2/plot_options.tsx, static/js/tools/statvar_menu/util.tsx
- swap the order of the place options selection, and populate place types selection depending on the selected place
- move the plot options to below the chart and remove the stats from under the chart
- add source attribution
- get child place names in background to decrease loading time after selecting place and child place type
=> scatter2 various client side updates

static/js/tools/scatter2/chart.tsx, static/js/tools/scatter2/chart_loader.tsx, static/js/tools/scatter2/info.tsx
- revert the change where I updated the axes to not change when switching to logscale
- for landing page examples, replace "foreign born vs unemployment rate" with "covid cases vs african american per capita"
=> [scatter] revert log axis and update landing page examples

run_test.sh, server/requirements.txt, server/routes/api/browser.py, server/templates/browser/node.html, server/templates/dev/dev.html, server/templates/tools/timeline.html, server/templates/tools/timeline_bulk_download.html, server/tests/api_browser_test.py, static/js/browser2/browser_page.tsx, static/js/browser2/statvar_checkbox.tsx, static/js/browser2/statvar_group_node.tsx, static/js/browser2/statvar_hierarchy.tsx, static/js/browser2/statvar_node.tsx, static/js/dev_page.tsx, static/js/shared/context.ts, static/js/shared/types.ts, static/js/tools/scatter2/chart_loader.tsx, static/js/tools/scatter2/context.ts, static/js/tools/scatter2/statvar.tsx, static/package-lock.json
* Stat var hierachy taking multiple places, which is the case for timeline, scatter plot.
* Store stat var hierarchy type in context.
* Check the stat var hierarchy type and render accordingly.
=> Allow stat var hierarchy to display checkbox instead of stat line charts

static/css/tools/scatter.scss, static/js/tools/scatter2/chart.tsx
- make scatter plot chart square
- update scatter log scale axes to not be scientific notation
- make dots smaller
=> [scatter] additional ui changes

deploy/overlays/dev/kustomization.yaml
Right now it takes 5-10 mins for all the pods to be fully updated.
This is to make the dev instance update under 2 mins.
=> Update dev instance rollout strategy

static/js/browser2/statvar_group_node.tsx, static/js/browser2/statvar_group_section.tsx, static/js/browser2/statvar_hierarchy.tsx
fixed bugs:
- when section is expanded and user selects a search result within that section, result won't show up.
- when user clears search result, the expanded section (from the selected search result) is rendered and then closed
=> stat var hierarchy bugs

server/routes/api/choropleth.py, server/routes/tools.py, server/templates/tools/map.html, server/tests/tools_test.py, static/css/tools/map.scss, static/js/chart/draw_choropleth.ts, static/js/place/chart.tsx, static/js/tools/map/app.tsx, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/context.ts, static/js/tools/map/map.ts, static/js/tools/map/place_options.tsx, static/js/tools/map/util.test.ts, static/js/tools/map/util.ts, static/js/tools/scatter/chart_loader.tsx, static/js/tools/scatter/util.test.ts, static/js/tools/scatter/util.ts, static/js/tools/shared_util.test.ts, static/js/tools/shared_util.ts, static/js/tools/timeline/search.tsx, static/package-lock.json, static/webpack.config.js
- rename choropleth to map
- things added: 
- main component for map explorer
- context for map explorer
- fetching chart data & drawing choropleth with that data
- component for choosing the place and place type
- update to draw_choropleth function so that the link that onclick redirects to gets passed into the function
Left the stat var menu out for now, but we can get map to show up by updating the hash link.
dev is updated with these changes & you can go to http://dev.datacommons.org/tools/map#%26sv%3DCount_Person_Female%26svn%3DCount_Person_Female%26pc%3D0 and then select the place and place type to see the choropleth.
=> [map] get basic map explorer view working

static/css/tools/map.scss, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/chart_options.tsx, static/js/tools/map/context.ts, static/js/tools/map/place_options.tsx, static/js/tools/map/util.test.ts, static/js/tools/map/util.ts, static/js/tools/scatter/chart_loader.tsx, static/js/tools/shared_util.ts
added new ChartOptions component that contains the per capita toggle and breadcrumbs
dev is updated with these changes (eg. http://dev.datacommons.org/tools/map#%26sv%3DCount_Person_EducationalAttainmentBachelorsDegree%26pc%3D1)
=> [map] add per capita and breadcrumbs

build/Dockerfile, deploy/overlays/dev/kustomization.yaml, gke/backendconfig.yaml, gke/mcs.yaml, gke/setup_config_cluster.sh
The default timeout is 30s, which prevents a large stat-var-hierarchy cache to serve.
=> Increase Flask worker and GKE load balancer timeout to 60s

server/routes/api/chart.py, server/tests/chart_test.py, static/js/place/chart.tsx
- for date range in title, use "[start date] to [end date]" instead of "[start date] - [end date]" (eg. "2020-03 to 2020-04" vs "2020-03-2020-04")
- the function for getting tooltip html for place pages had a bug causing it to always show "data missing"
=> Place Page Choropleth Fixes

server/routes/api/chart.py, server/tests/chart_test.py
There was a case where the list of dates was empty which caused a list index out of range error. This check will prevent future errors like this when getting date range.
=> Add check when getting date range for choropleth charts

server/__init__.py
Mixer now takes longer time to start due to the increased size of stat var group cache
=> Increase wait time for mixer start up

static/js/chart/draw_choropleth.ts, static/js/tools/map/chart.tsx
Make the legend shorter in map explorer by allowing customization of legend height when using the draw_choropleth funciton.
=> [map] make legend shorter

static/css/draw_choropleth.scss, static/css/tools/map.scss, static/js/chart/draw_choropleth.ts, static/js/place/chart.tsx, static/js/tools/map/app.tsx, static/js/tools/map/chart.tsx, static/js/tools/map/place_options.tsx
- when zooming and panning, disable hover action
- make tooltip stay in map boundary
- show alert when user selects a place we don't have maps for [issue 977](https://github.com/datacommonsorg/website/issues/977)
- on map click, open the page in the same window [issue 978](https://github.com/datacommonsorg/website/issues/978)
- only push hash to history if it's new. With this change, user only has to click back once to get to the last state
dev updated (http://dev.datacommons.org/tools/map#%26sv%3DCumulativeCount_MedicalConditionIncident_COVID_19_PatientDeceased%26pc%3D1)
=> [map] few updates

static/css/tools/map.scss, static/js/chart/draw_choropleth.ts, static/js/place/chart.tsx, static/js/tools/map/chart.tsx
Separate how window resize is handled for the legend from how it's handled for the map. Otherwise, going from small screen to large screen will cause the legend to become too large.
=> [map] resize legend separately from the map

static/css/stat_var_hierarchy.scss, static/css/tools/stat_var_widget.scss, static/js/stat_var_hierarchy/node_header.tsx, static/js/stat_var_hierarchy/stat_var_group_node.tsx, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/stat_var_hierarchy/stat_var_section_input.tsx, static/js/tools/scatter/statvar.tsx, static/js/tools/timeline/__snapshots__/page.test.tsx.snap
- fixed [issue 1005](https://github.com/datacommonsorg/website/issues/1005):  entire path not highlighted. This was actually because a different path that goes to the same variable was being highlighted. Fixed this by making sure the path that user took to get to a stat var is the path that gets highlighted
- fixed [issue 1006](https://github.com/datacommonsorg/website/issues/1006): browser should only show available nodes
- fixed problem where when a tree widget section had been opened and then there was a places change, the contents of the opened section didn't update. 
- fixed problem where when the input in the search box was longer than the width of search box, it would overlay over the clear search button
- removed auto selecting the option user selects from the list of search …
=> [tree widget] Various fixes

server/routes/api/stats.py, server/services/datacommons.py, server/templates/tools/scatter.html, server/templates/tools/timeline.html, static/css/tools/stat_var_widget.scss, static/js/chart/draw.ts, static/js/shared/types.ts, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/stat_var_hierarchy/stat_var_section.tsx, static/js/stat_var_hierarchy/stat_var_section_input.tsx, static/js/stat_var_hierarchy/util.ts, static/js/tools/mock_functions.tsx, static/js/tools/scatter/app.test.tsx
- add an info tooltip to explain the count and the greyed out stat var groups ([issue 1008](https://github.com/datacommonsorg/website/issues/1008))
- add tooltip for greyed out stat vars that gives list of placetypes and/or place names that have data for this stat var
dev updated with these changes
=> [tree widget] Add tooltips

server/routes/api/stats.py, static/js/stat_var_hierarchy/stat_var_section_input.tsx
- don't show certain place types that can't be searched
- show tooltip for stat vars that have data
- rename certain place types (eg. NUTS2) to more recognizable place type
=> [tree widget] tooltip updates

static/css/tools/stat_var_widget.scss, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/stat_var_hierarchy/stat_var_search.tsx, static/js/stat_var_hierarchy/stat_var_section_input.tsx, static/js/tools/map/info.tsx, static/js/tools/map/stat_var_chooser.tsx, static/js/tools/scatter/app.test.tsx, static/js/tools/scatter/info.tsx, static/js/tools/scatter/statvar.tsx, static/js/tools/timeline/info.tsx, static/js/tools/timeline/page.tsx
- standardize to use "statistical variables" everywhere [issue #1020](https://github.com/datacommonsorg/website/issues/1020)
- remove [x] in the search when there is no input and update place holder to "Search Statistical Variables" [issue #1022](https://github.com/datacommonsorg/website/issues/1022)
- prevent tooltip from getting squished [issue #1023](https://github.com/datacommonsorg/website/issues/1023)
- remove svg hierarchy sorting in the client code [issue #1025](https://github.com/datacommonsorg/website/issues/1025)
- bug where when there are no stat vars in the search results, choosing a stat var group will cause the results section to stay open [issue #1028](https://github.com/datacommonsorg/website/issues/1028)
=> [tree widget] various updates

build/Dockerfile
This change https://github.com/datacommonsorg/website/pull/1044/files#diff-540d39fbd8b0774c2d96e42b981dce59d51849ec7878f9cd447ae08f954e286f included test files in tsconfig.json. Some of the test files refer to chart_config.json which resides in "/server" folder.
By swapping the order, we make sure "npm run-script build" can see the "/server" folder
=> Fix website docker image build issue

static/js/shared/data_fetcher.ts
follow up from #1044 - there are cases where a place will not have data for one of the stat vars, e.g.
https://autopush.datacommons.org/tools/timeline#statsVar=Count_Person_Employed__dc%2Fnm9hcklgg5zb3&place=nuts%2FES61%2CgeoId%2F56&chart=%7B%22consumption%22%3Afalse%7D
=> [timeline] fix a few deref errors for null series

static/css/timeline.scss, static/js/chart/draw.ts, static/js/shared/data_fetcher.ts, static/js/tools/timeline/chart.tsx
- plot zero values [issue #1030](https://github.com/datacommonsorg/website/issues/1030)
- link to browser page when click on chip [issue #1032](https://github.com/datacommonsorg/website/issues/1032)
- make tooltip labeling consistent with legend [issue #1032](https://github.com/datacommonsorg/website/issues/1033)
plot zero values:
make tooltip labelling consistent with legend:
=> [timeline] various updates

static/js/place/main.tsx, static/js/place/topic_menu.tsx
* "Overview" tab contains sections of "categories", the order of the section should in the original order.
* "non Overview" tab contains sections of "chart groups", the order of the chart groups should be based on the title.
=> Update chart sorting in place page

static/js/shared/data_fetcher.ts, static/js/tools/timeline/chart.tsx
Right now this link is broken: https://autopush.datacommons.org/tools/timeline#place=wikidataId%2FQ1445%2Ccountry%2FIND,asia&statsVar=Count_Person_Workers__Count_Person_NonWorke&pc=1&chart=%7B%22count%22%3Atrue%7D
As there is no population data for Asia
=> Fix some null data issue

server/routes/api/landing_page.py, server/webdriver_tests/place_landing_test.py, static/js/place/chart.tsx, static/js/shared/data_fetcher.test.ts, static/js/shared/data_fetcher.ts, static/js/tools/timeline/chart.tsx, static/js/tools/timeline/chart_region.tsx, static/js/tools/timeline/page.tsx, static/js/tools/timeline/util.ts
This was removed in recent stat var hierarchy change, where stat var denominator was removed and only Count_Person is used.
However, place page uses specific denominator for stat vars and that carries over in the explore more link. This fixes the broken link. Also fixes the "per capita" checkbox bug
=> Add denominator to timeline page url

static/js/chart/draw_choropleth.ts, static/js/place/chart.tsx, static/js/tools/map/chart.test.ts, static/js/tools/map/chart.tsx, static/js/tools/map/util.ts
eg. counties in USA (country) will have its boundary lines removed
but counties in California (State) will keep its boundary lines
=> [map] remove boundary lines for granularities 2 levels down from the selected place

static/css/tools/scatter.scss, static/js/tools/scatter/chart.tsx, static/js/tools/scatter/chart_loader.tsx, static/js/tools/scatter/context.ts, static/js/tools/scatter/plot_options.tsx, static/js/tools/scatter/util.test.ts, static/js/tools/scatter/util.ts
quadrant lines are plotted based off the mean of both x and y values
adds a new "qd" query parameter, with display option:
=> [scatter] add option for quadrant lines for scatterplots

static/js/chart/draw_choropleth.ts
domain and range must match -- we were setting domain only with extent, but range with 3 values, so the third (darkest color) was ignored. increased the range, making it darker at the end, using the max color for the median instead.
also fixed the legends to always include the min and max values.
=> [map] increase dynamic range of map colors

static/js/stat_var_hierarchy/stat_var_group_node.tsx, static/js/tools/scatter/statvar.tsx
- Use more samples for scatter plot places. This is to allow stat var with sparse data of some place type to work properly.
- Highlight private dc section
=> Website update for scatter and stat var widget

static/css/tools/map.scss
- on hover, make the dots outline and fill colors opposite that of the regular state
=> [map] update hover behaviour for dots

docs/developer_guide.md, static/js/place/chart_block.tsx, static/js/place/main.tsx
We were adding div's around each chart block, which creates an entire row (even if there could be opportunity for a chart on the next row to float up).
Before:
After:
=> [place] fix layout for charts without comparisons

static/css/tools/scatter.scss, static/js/tools/scatter/chart.tsx, static/js/tools/scatter/chart_loader.tsx, static/js/tools/scatter/place_and_type_options.tsx, static/js/tools/scatter/plot_options.tsx
use css to set size of the chart drawing area, to reduce jumpiness on replotting.
also updated container to fluid for some options that were left out with earlier layout fixes.
will work on debouncing next..
=> [scatter] fix jumpiness option changes

static/css/tools/scatter.scss, static/js/chart/draw_choropleth.ts, static/js/tools/scatter/chart.tsx, static/js/tools/scatter/draw_scatter.ts, static/js/tools/scatter/statvar.tsx
- add text wrap for tooltip
- on dot click, go to place page
- when switching to new stat var, reset per capita and scale log for that axis
=> [scatter] various updates/fixes

static/js/tools/scatter/plot_options.tsx, static/js/tools/scatter/statvar.tsx
- revert resetting options when switching sv
- if log is picked for an axes that can't have log, un-choose log
- disable log options instead of hiding them
=> [scatter] don't reset options when switching sv

static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/stat_var_hierarchy/stat_var_section_input.tsx, static/js/tools/scatter/chart.tsx
- update bivariate map legend so that the min and max doesn't change when using log scale
- fix flashing of points when switching stat vars in scatter explorer
- original: ![screen-recording-_34_](https://user-images.githubusercontent.com/69875368/139941016-d713a919-a146-4833-ad26-3abb4b59bcfc.gif)
- with fix: ![screen-recording-_35_](https://user-images.githubusercontent.com/69875368/139940860-f5bace3d-26a3-4e96-8e4b-2ac0851ca3cd.gif)
- fix tooltip in the tree widget
- original:  
- with fix:
=> [tools] various fixes

server/templates/static/homepage.html
* Drop wet-bulb number-of-months, pending average computation
* Clarify that Max Temperature charts are actually change in max temperature
* Use projection statvar for difference across models
=> Homepage tweaks

static/css/browser.scss, static/js/browser/arc_table_row.tsx
made it even lighter, and added dcid: prefix
=> [browser] small change in dcid refs

static/js/i18n/i18n.tsx
2 digits round up temperature values in the following case:
=> Change max significant digits to 3 in number formatting

static/js/tools/map/chart_loader.tsx
- map facilities weren't showing up due to the changes to the `/stat/set/within-place/` API. Updated so that we can show facilities on the map again
=> [map] fix map facilities not showing up bug

server/webdriver_tests/browser_test.py
- webdriver tests failed because with the series ranking update for `stat/set/series/all` API endpoint ([from this pr](https://github.com/datacommonsorg/mixer/pull/665)), the order of series shown on the browser page changed & so the redirected page also changed
=> [browser] fix webdriver test

docs/iap.md, docs/new_deployment.md, docs/redis.md, gke/README.md, gke/add_policy_binding.sh, gke/backendconfig.yaml, gke/backendconfig_iap.yaml, gke/config.yaml.tpl, gke/create_all_clusters.sh, gke/create_api_key.sh, gke/create_ip.sh, gke/get_storage_permission.sh
Some manual steps and inconsistencies have accumulated since last version.
Clean up and update the doc to reflect the latest steps. This will help for simplify private Data Commons deployment.
=> Clean up GCP/GKE setup guide

static/js/stat_var_hierarchy/stat_var_group_node.tsx, static/js/stat_var_hierarchy/stat_var_section_input.tsx
- include stat var name in tooltip
- expand tree for pre-selected stat var for Map [(issue #1036)](https://github.com/datacommonsorg/website/issues/1036)
=> [tree widget] small fixes/updates

server/configmodule.py, server/main.py, server/routes/api/landing_page.py, static/js/place/place.ts
The entire cache data is still load once in the web server, however only the data for the current category is processed.
This also removes the previous behavior that merges all the categories into overview when total number of charts is too small.
Some other updates:
- Removes the new stat vars for place page as they are already in cache.
=> [Place Page] Only process data for the current topic

server/webdriver_tests/scatter_test.py, static/css/tools/scatter.scss, static/js/tools/scatter/chart.tsx, static/js/tools/scatter/chart_loader.tsx, static/js/tools/scatter/context.ts, static/js/tools/scatter/statvar.tsx, static/js/tools/scatter/util.test.ts, static/js/tools/scatter/util.ts
- Add date url param to control the date for the data for each axis in the plot. (param keys are "datex" and "datey")
- If date is specified, include it in the title
Notes
- not sure if including the dates in the title is useful or confusing (would love some thoughts)
- Could be useful to quickly see that all the data will be from this specific date. Otherwise, will need to hover over the points on the graph to see the date of the data in the tooltip.
- Could be confusing if sometimes there is a date in the title and sometimes there isn't
=> [scatter] Add date param

server/__init__.py, server/main.py, server/templates/topic_page.html, static/js/topic_page/block.tsx, static/js/topic_page/line_tile.tsx, static/js/topic_page/main_pane.tsx, static/js/topic_page/map_tile.tsx, static/js/topic_page/tile.tsx, static/js/topic_page/topic_page.ts
Page config is stored in initial page load as an html data field. Then each block (tile) renders async with their own data fetching.
Things to add later:
- real css
- ranking tile
- bar tile
- better config for place type, child place type and similar place type; place based stat vars..
=> Add Block componenet and get topic page working end to end

static/js/topic_page/block.tsx, static/js/topic_page/ranking_tile.tsx, static/js/topic_page/tile.tsx
I fetch the raw stat and do the ranking instead of calling the ranking API as this involves computation between stat vars. Speed wise fairly good. This PR has minimal css layout just to get the data in.
=> Implement ranking tile with highest and lowest comparison

server/webdriver_tests/place_explorer_i18n_test.py, static/css/place/place.scss, static/css/shared/story_block.scss, static/js/place/main_pane.tsx, static/js/place/menu.tsx, static/js/place/page_subtitle.tsx, static/js/topic_page/block.tsx
guha requested that we show income first for equity category pages. i think keeping the ordering from the config allows us the most flexibility to configure this.
also picking up our old todo of displaying the topics on the place page so the ordering isn't confusing..
the strings for the topics still need to be sent for translation.
=> [place] use topic ordering from config, display topics on place pages

static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/context.ts, static/js/tools/map/stat_var_chooser.tsx, static/js/tools/map/util.test.ts, static/js/tools/map/util.ts
- add a url param to set the stat var used for the installations on a map. If no stat var set, will default to using the same stat var as being shown for the map regions.
- URL params to show glaciers: &mapsv=SurfaceArea&ppt=Glacier
- Now that installations can show a different stat var than the rest of the map, remove the dateParam when retrieving installations data because it can be hard to make the date work for both the map stat var and the installations stat var. For example, RCP stat vars use 2050 as the date, but not many other stat vars have data for 2050.
=> [map] url param to set the stat var for installations on a map

static/js/chart/draw_choropleth.ts
- the min size of the installations on the map is calculated depending on the sizes of the regions on the map. For IPCCPlace50 placetype, the size of each region causes the installations to become too small to see. Therefore, we want to set a minimum size for map installation points
=> [map] add a min size for map installations

deploy/overlays/karnataka/kustomization.yaml, server/__init__.py, server/configmodule.py
As private instance will have frequent data refresh, disable caching so it won't have stale data in the frontend.
To bring up a local private instance, run
`run_server.sh -e private`
=> Do not cache for private instance and update local private instance API_ROOT

static/js/tools/scatter/statvar.tsx
- fix bug causing scatter chart to not show up when one of the chosen stat vars doesn't have StatVarInfo
=> [scatter] Fix bug when there is no StatVarInfo available

server/config/topic_page.proto, server/config/topic_page/equity/USA.textproto, server/config/topic_page/poverty/USA.textproto, server/config/topic_page_pb2.py, static/js/chart/draw_scatter.ts, static/js/topic_page/block.tsx, static/js/topic_page/constants.tsx, static/js/topic_page/main_pane.tsx, static/js/topic_page/scatter_tile.tsx, static/js/topic_page/string_utils.ts, static/js/topic_page/tile.tsx, static/js/topic_page/topic_page.ts
Config updates
- Flip ordering of scatter stat vars (y first, then x)
- Add support for contained_place_types (and added a tile-level override)
Scatter updates
- Removed extra top-margin (and it looks fine on scatter tool)
- Add support for configured stat var names
Equity updates
- Added health scatters
=> Topic page scatter updates

server/templates/tools/timeline_bulk_download.html
there is a display-flex on #main-pane which caused the weird column layout
=> [timeline] fix bulk download formatting

static/js/ranking/ranking.ts, static/js/ranking/ranking_histogram.tsx, static/js/ranking/ranking_page.tsx, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx
- when there is a date specified for the ranking page, get data using within-places endpoint and do on the fly ranking calculation
- if map tool has a date set, "explore ranking" link will redirect to ranking page with that specified date
=> Add date param for ranking page

static/css/stat_var_hierarchy.scss, static/css/tools/stat_var_widget.scss, static/js/stat_var_hierarchy/stat_var_search.tsx
- add additional information in stat var group results about what stat vars are contained in that stat var group
- widen search results section
- make font smaller
- show loading as soon as user starts typing
- close results dropdown when user clicks outside the search area
=> [tree widget] various search result ui updates

server/webdriver_tests/tests/browser_test.py
- the update to the stat var search mixer result caused the stat vars to be nested under stat var groups, so selecting the first result was not giving a chart
=> fix webdriver test

server/requirements.txt
- flask depends on jinja2 which depends on markupsafe and the latest markupsafe version has a [breaking change](https://github.com/pallets/markupsafe/issues/286) causing an error to be thrown when trying to run flask locally because [Jinja2 depends on the latest version of markupsafe](https://github.com/pallets/jinja/issues/1585)
=> Pin markupsafe version

deploy/base/deployment.yaml
Need to remove the cpu limit as the mixer would restart a few times currently when processing the stat var hierarchy cache.
=> Remove GKE cpu limit

scripts/deploy_gke.sh, static/js/browser/browser_page.tsx
In import group mode, subject name is added to all triples. In the the "Provenance" triples data, when "Provenance" is subject, its name "Provenance" is used as URL and lead to errors. This makes the check more robust.
=> Better check of browser page provenance triples

static/js/stat_var_hierarchy/stat_var_search.test.tsx, static/js/stat_var_hierarchy/stat_var_search.tsx
- there was a bug where searching for mortality in the tree widget threw an error. This was because one of the matching tokens returned for this query was "mortality)" and the ")" at the end was causing an invalid regex error.
=> [tree widget] fix invalid regex problem

static/js/translator/constants.ts, static/js/translator/page.tsx, static/js/translator/translator.ts
This is also to verify that we can build BigQuery links from raw query string.
Tested and works ([link](https://pantheon.corp.google.com/bigquery;create-new-query-tab=SELECT%20_datcom_store_dc_kg_latest_Place_0.id%20AS%20node%2C%20_datcom_store_dc_kg_latest_StatVarObservation_1.value%20AS%20life_expectancy%2C%20_datcom_store_dc_kg_latest_StatVarObservation_2.value%20AS%20median_age%20FROM%20%60datcom-store.dc_kg_latest.StatVarObservation%60%20AS%20_datcom_store_dc_kg_latest_StatVarObservation_1%20JOIN%20%60datcom-store.dc_kg_latest.Place%60%20AS%20_datcom_store_dc_kg_latest_Place_0%20ON%20_datcom_store_dc_kg_latest_StatVarObservation_1.observation_about%20%3D%20_datcom_store_dc_kg_latest_Place_0.id%20JOIN%20%60datcom-store.dc_kg_latest.StatVarObservation%60%20AS%20_datcom_store_dc_kg_lates …
=> Use BigQuery query API for /translator page

server/routes/api/place.py
- some non english place pages were erroring out (caught by webdriver) because of trying to get cached_i18n_name for an empty list of dcids
=> [place] handle empty dcids when getting i18n name

server/configmodule.py, server/templates/base.html
Also made some corresponding changes to tag manager. I'm not sure if that's why the stats dropped, since the diff from the release seems benign except for the new settings.
https://github.com/datacommonsorg/website/compare/v1.13.1...v1.14.0
Disabling client_storage should turn off cookies too. Will test this post release (also added back our existing GA to staging for testing).
=> [analytics] disable consent manager (and just disble client storage)

server/requirements.txt, server/services/ai.py
I will discuss later with @nopper and see if can remove "numpy" deps as it is only used for one function.
This will fix the deployment error for now.
=> Add missing library for AI model service

deploy/base/kustomization.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/dev/kustomization.yaml, deploy/overlays/prod/kustomization.yaml
Environment does not need to create empty ai.yaml if NLP is not used.
=> Create default config map for ai-config

server/configmodule.py, server/routes/api/landing_page.py, server/routes/api/place.py, static/js/place/main_pane.tsx, static/js/place/place_autocomplete.ts
- Borrow category data from all categories into Overview page.
- For a set of India cities, use the District place as search result.
- [Bonus]: remove additional stat vars for place page data fetch.
=> Fix data sparsity issue in place page

static/js/browser/browser_page.tsx
Now an invalid URL will make the entire provenance section not showing up.
=> Do not fail on invalid url in browser page data fetch

scripts/autopush.sh
As the instance is used as production use. The deployment should be done manually.
=> Do not auto release feeding america instance

server/routes/api/choropleth.py, server/routes/api/shared.py, server/tests/api_shared_test.py
- when getting map points, sometimes error thrown because longitude/latitude string was not a float. Should skip those map points
=> [map] fix non float string error in getting map points data

server/webdriver_tests/tests/browser_test.py, static/js/browser/observation_chart.tsx, static/js/browser/out_arc_section.tsx
Fetching observation triples requires BQ query which is very costly as the new table is not keyed by observation id.
=> Temporarily disable observation page to reduce BQ cost

static/css/rich_search.scss, static/js/rich_search/app.tsx, static/js/rich_search/stat_vars.tsx, static/js/utils/place_utils.ts
This change properly handles and shows errors when no places were specified in the query. We also add support for displaying generic debug messages.
=> Handle the case no places returned by the API

server/webdriver_tests/tests/map_test.py, server/webdriver_tests/tests/scatter_test.py, static/css/_search_place.scss, static/css/place_selector.scss, static/css/shared/chip.scss, static/css/tools/map.scss, static/css/tools/scatter.scss, static/js/shared/chip.tsx, static/js/tools/timeline/__snapshots__/page.test.tsx.snap
- clean up class names for the chip component because no longer need to maintain the "mdl-chip" naming
- fix place selector component overflow by adding flex-wrap and hiding input area once place has been chosen
=> Chip component cleanup and place selector fixes

server/routes/api/choropleth.py, static/js/place/chart_block.tsx, static/js/place/place.ts, static/js/place/util.ts
For the visualization part, it turns out that only the chart fig that has complete data can be rendered. So I was only able to render the choropleth for the population under demographics. And there are many sources listed under the chart as well.
=> Add choropleth map to the earth page

static/css/tools/download.scss, static/js/shared/types.ts, static/js/stat_var_hierarchy/stat_var_group_node.tsx, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/stat_var_hierarchy/stat_var_section_input.tsx, static/js/tools/download/page.tsx, static/js/tools/download/stat_var_chooser.tsx, static/js/tools/map/stat_var_chooser.tsx, static/js/tools/mock_functions.tsx, static/js/tools/scatter/statvar.tsx, static/js/tools/shared/stat_var_widget.tsx, static/js/tools/stat_var/page.tsx, static/js/tools/timeline/__snapshots__/page.test.tsx.snap, static/js/tools/timeline/page.test.tsx, static/js/tools/timeline/page.tsx
- Add alert when place changes and chosen stat vars are unavailable
- Refactored stat var widget to do this so that all tools are consistent in behavior
- This also fixes: [issue #1522 ](https://github.com/datacommonsorg/website/issues/1522)
- Add modal that pops up when more than 5 stat vars are chosen for download tool
=> [download] Add stat var selection alerts

deploy/overlays/memdb.json.tpl, deploy/overlays/sample_data.csv.tpl, deploy/overlays/sample_tmcf.tmcf.tpl, deploy/overlays/stanford/memdb.json, docs/new_deployment.md
Note: the corresponding "template" style csv, tmcf and manifest.json file is here: https://console.cloud.google.com/storage/browser/datcom-stanford-resources/stanford?project=datcom-stanford&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false
=> Adding template style memdb file for Stanford private DC instance

server/routes/api/place.py, server/tests/api_place_test.py
1. Restrict the parent place type and keep consistent with the rule of place filtering in [getParentPlaces](https://github.com/datacommonsorg/mixer/blob/master/internal/server/placepage/place_page.go) in mixer.
2. Add a population filter so that API won't return data points of places with populations less than 1000. Keep consistent with the rules of the population filtering of the [ranking page](https://source.corp.google.com/piper///depot/google3/datacommons/prophet/related_places/calculator_svobs.cc;l=309-321).
=> Ranking chart API: Restrict parent place type and add population filter 

static/js/tools/map/chart_loader.tsx
- fixed bug where legend calculation did not take the correct min and max resulting in 0 contrast in the map.
original: 
fixed:
=> [map] fix per capita legend bug

server/webdriver_tests/tests/timeline_test.py
- Webdriver test failure was caused by change in stat var name. Make webdriver test more reliable by finding element based on ID.
- Also realized the test is named "check statvar and uncheck" but the test only tested for checking statvar and not unchecking statvar, so added that part
=> fix broken webdriver test

static/js/place/menu.tsx, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx, static/js/tools/timeline/chart.tsx
We set the object key by variable. In order to let the key be the value of the variable, we need to use bracket notation. e.g.,
const GA_PARAM_PLACE_DCID = "place_dcid";
triggerGAEvent(GA_EVENT_TOOL_CHART_PLOT, {
[GA_PARAM_PLACE_DCID]: Object.keys(this.props.placeNames),
});
Without brackets, the key will be "GA_PARAM_PLACE_DCID" instead of "place_dcid"
The following is the document for this syntax:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names
=> Fix bugs where GA event parameters are not surrounded by brackets.

static/js/biomedical/disease/chart.ts, static/js/biomedical/disease/data_processing_utils.ts, static/js/biomedical/disease/page.tsx, static/js/biomedical/protein/data_processing_utils.ts
I added the disease symptom association chart. For the disease of interest, the x axis has the symptoms and the y axis has the association score.
=> [Disease Browser] Add second chart for the disease browser 

server/services/datacommons.py
Include `property-values` function from [this commit](https://github.com/shifucun/website/blob/79046d4923e7fd1b027cfcf0c24ea92b5249cdc6/server/services/datacommons.py#L156) by @shifucun, updated to use the new V1 endpoint format.
=> datacommons.py property-values function

static/js/tools/map/chart_loader.tsx
If user has set values for the domain through the URL params, we should use that domain when generating the legend
=> [map] domain set in URL should take priority

server/routes/api/protein.py
Bug: I do a type check for `type(center_protein_dcid) == str` and return an error response if this does not hold.  However, I then added `center_protein_dcid = escape(center_protein_dcid)` to mitigate an XSS vulnerability, which changes the type of `center_protein_dcid` to `markupsafe.Markup`, and now this check never holds.
Fix: Use `isinstance(center_protein_dcid, str)` instead.
=> [Protein browser] Fix type error caused by escaping protein dcid

server/__init__.py, server/configmodule.py, server/services/datacommons.py, static/package-lock.json
We plan to enforce API key for the V1 mixer API. 
This won't affect website deployment in GKE as the the mixer is an internal service within pod, so it does not need API key restriction. However, local website development requires talking to an instance of mixer. For example, regular local dev talks to the autopush mixer instance.
This PR allows a local website instance to fetch the API key from the corresponding mixer project and use it when sending requests.
A prerequisite of this is to creating the API key and store it in the secret manager. I have done this manually for the two mixer projects involved in this PR.
=> Use mixer API key for local development

.gitignore, deploy/terraform-datacommons-website/README.md, deploy/terraform-datacommons-website/examples/website_v1/.terraform.lock.hcl, deploy/terraform-datacommons-website/examples/website_v1/README.md, deploy/terraform-datacommons-website/examples/website_v1/main.tf, deploy/terraform-datacommons-website/examples/website_v1/variables.tf, deploy/terraform-datacommons-website/examples/website_v1/variables.tfvars.tpl, deploy/terraform-datacommons-website/examples/website_v1/versions.tf, deploy/terraform-datacommons-website/modules/iam/README.md, deploy/terraform-datacommons-website/modules/iam/main.tf, deploy/terraform-datacommons-website/modules/iam/outputs.tf, deploy/terraform-datacommons-website/modules/iam/variables.tf, deploy/terraform-datacommons-website/modules/iap/README.md, deploy/terraform-datacommons-website/modules/iap/main.tf, deploy/terraform-datacommons-website/modules/iap/outputs.tf, deploy/terraform-datacommons-website/modules/iap/variables.tf
This is part 1 of converting one time set up to terraform.
This PR handles 
1) Enabling services
2) IAM binding
3) IAP setups.
Tested: tested using the following variables.tfvars file.
```
project_id = "datacom-alexyfchen-tf-test2"
storage_project_id = "datcom-store"
brand_support_email = "alexyfchen@google.com"
web_user_members = [ "alexyfchen@google.com"]
```
=> [Devops] Terraform config for the website part1

server/routes/import_wizard.py, server/templates/import_wizard2.html, server/tests/import_wizard_test.py, static/css/import_wizard2.scss, static/js/import_wizard2/components/page.tsx, static/js/import_wizard2/import_wizard.ts, static/js/import_wizard2/types.ts, static/webpack.config.js
- added the changes to have V2 appear at /import/new
- types.ts is copied from V1 - static/js/import2 will have all the files needed for V2 (even if they're duplicate files from V1) so that when we do the flip, we can just rename the folder and delete the V1 folder
=> [import wizard] Set up the skeleton for V2

static/js/chart/draw_choropleth.ts
- Update legend domain for dc aggregate temp diffs to range from -30 to 30
=> [map] update legend domain for dc aggregate temp diffs

static/css/import_wizard2.scss, static/js/import_wizard2/components/mapping_page.tsx, static/js/import_wizard2/components/mapping_preview_section.tsx, static/js/import_wizard2/components/mapping_templates/constant_var.tsx, static/js/import_wizard2/components/shared/mapping_column_input.tsx, static/js/import_wizard2/components/shared/mapping_place_input.tsx, static/js/import_wizard2/templates.tsx, static/js/import_wizard2/types.ts, static/js/import_wizard2/utils/detection.test.tsx, static/js/import_wizard2/utils/detection.ts, static/js/import_wizard2/utils/file_generation.test.ts, static/js/import_wizard2/utils/tmcf_generation.test.tsx, static/js/import_wizard2/utils/tmcf_generation.ts, static/js/import_wizard2/utils/validation.test.tsx, static/js/import_wizard2/utils/validation.ts
- add a generic column selector component & use it in constant var mapping section
- add a place selector component that has place type and property selecting
- while doing this, reverted MappingVal to only having a single placeType and placeProperty. We had made MappingVal take multiple placeType and placeProperties in import wizard v1 because as the user goes through each column, they could potentially assign multiple columns to be place & have a different place type/property for each chosen column. In import wizard 2, users currently can not get to that state of having multiple place types and properties, so I decided to simplify the MappingVal structure for now.
- add another constant mapping in templates.tsx which is a mapping between templateId and function for getting userMapping …
=> [wizard 2] Add dropdown selectors for mapping section

server/routes/api/browser.py, server/services/datacommons.py, static/js/browser/browser_page.tsx, static/js/browser/out_arc_section.tsx
The name of a provenance triple is changed from url to the import name. Browser fetches all provenance and url, so the logic needs to be updated to fetch the url.
This PR also updates to use V1 API for triples fetch. This is only used in browser page.
=> Fix and refactor browser page provenance issue

static/js/tools/map/app.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/geojson.ts
This is a start of efforts to simplify and speed up map tool by having multiple data fetch components. 
The rendering will be based on needed data instead of all data ready.
Also removed "showChart" check for <ChartLoader> in app.js. This turns out reducing the network request from around 60 to 30 for the first chart load (duplicated data request). The checking is moved into chart_loader.tsx. This also reduces extra geojson fetch when geo types do not change.
=> Separate geojson data fetch into a separate module

static/js/shared/stat_types.ts, static/js/tools/map/chart_loader.tsx, static/js/tools/map/chart_store.ts, static/js/tools/map/context.ts, static/js/tools/map/fetcher/all_stat.ts, static/js/tools/map/fetcher/breadcrumb_denom_stat.ts, static/js/tools/map/fetcher/breadcrumb_stat.ts, static/js/tools/map/fetcher/default_stat.ts, static/js/tools/map/fetcher/denom_stat.ts, static/js/tools/map/fetcher/european_countries.ts, static/js/tools/map/fetcher/geojson.ts, static/js/tools/map/fetcher/map_point_coordinate.ts, static/js/tools/map/fetcher/map_point_stat.ts, static/js/tools/map/geojson.ts, static/js/tools/map/ready_hook.ts, static/js/tools/map/util.ts
This is a no-op change to existing code and prepares for future updates of chart_loader.
The goal is to remove the dependency of data fetch and processing. Ideally, the tool only needs to fetch the needed data and will render the map when all necessary data is ready. The other data can be loaded on the background or on-demand, which can be controlled independently without touching the component logic.
Some design thoughts:
- Each data load should be in a separate module, which fetches data and sends the raw data to the desired component. These modules are put in /fetcher folder. New data fetcher should be created in the same pattern.
- All the raw data are used in various ways to construct the chart data, the construction depends on context (user input) and is dependent on data …
=> [map refactor] Add data fetcher modules and a chart store

static/js/shared/ga_events.test.tsx, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/compute_hooks.ts, static/js/tools/map/d3_map.tsx, static/js/tools/map/fetcher/european_countries.ts, static/js/tools/map/ready_hooks.ts
The map point loading is effectively in the background.
This is a show case of how to migrate the current code to be React hook based.
=> Use fetch hook for map points and european countries

static/js/shared/ga_events.test.tsx, static/js/tools/map/chart.tsx, static/js/tools/map/chart_loader.tsx, static/js/tools/map/d3_map.tsx, static/js/tools/map/leaflet_map.tsx, static/js/tools/map/place_details.tsx
All the map children components can directly access the context instead of getting them through the props.
=> Use context directly in map sub components

static/js/tools/map/d3_map.tsx
There was a bug where redirect was throwing an error. i.e., we're on a States in USA page and try to click California.
The error was being thrown because placeInfo.values.parentPlaces was not done populating before calling it
=> [map] fix redirect bug

server/routes/api/landing_page.py
Always add Overview to the category hash map. This ensures that is displayed as a subtitle and translated to other languages.
Fixes the bug introduced by https://github.com/datacommonsorg/website/pull/1754
Bug: b/206032102
=> Always add Overview to the category hash map to display it as a subtitle

server/routes/api/csv.py, server/routes/api/place.py, server/routes/api/shared.py, server/routes/browser.py, server/routes/disease.py, server/routes/protein.py, server/tests/api/api_csv_test.py, server/tests/api/api_place_test.py, server/tests/api/api_shared_test.py, server/tests/browser_test.py
Since dc.property_values() supports cache already, there is no need for a wrapper function to cache names. This is to gradually migrate to use V1 API and simplify existing code.
=> Use new property values API to fetch names

server/routes/dev.py, server/templates/dev/disaster_dashboard.html, static/css/disaster_dashboard.scss, static/js/disaster_dashboard/constants.ts, static/js/disaster_dashboard/disaster_dashboard.ts, static/js/disaster_dashboard/page.tsx, static/js/disaster_dashboard/types.ts, static/webpack.config.js
set up skeleton for the new disaster dashboard page (so future PRs can be submitted in parallel)
This is one part of the changes for the disaster dashboard MVP here on dev:
=> [disaster dashboard] initial page set up

server/__init__.py, server/configmodule.py, server/lib/disaster_dashboard.py, server/routes/api/disaster_dashboard.py, server/tests/api/api_disaster_dashboard_test.py
add flask endpoints for getting date range and getting data
This is one part of the changes for the disaster dashboard MVP here on dev:
=> [disaster dashboard] add flask endpoints

server/routes/api/place.py, server/routes/api/point.py, server/routes/api/series.py, server/services/datacommons.py, server/tests/api/api_place_test.py, static/js/tools/download/mock_functions.ts, static/js/tools/timeline/mock_functions.tsx, static/js/utils/place_utils.ts
* These errors are found from Error Reporting in GCP. We should set up alerts for such errors.
* All Flask endpoint should do "try/catch" to handle any errors from mixer response. This PR updates one such case from error reporting logs.
* Changed "dcid" to "dcids" in name fetch endpoint for better readability and consistency.
=> Fix a few key/value error issues

docs/developer_guide.md
- Re-structure the docs by environment: local, dev GCP instance. This makes it straightforward to start the local development without jumping around.
- Remove local Minikube development instruction: it's very lengthy process, easier to fail due to local resource constraints and thus bare used. Deploying to dev instance could serve the same purpose.
=> Update website development doc

deploy/terraform-datacommons-website/examples/base_storage_permissions/README.md, deploy/terraform-datacommons-website/examples/base_storage_permissions/main.tf, deploy/terraform-datacommons-website/examples/base_storage_permissions/variables.tf
This step is to be run by the storage project owners to allow the custom DC service account to access base storage layers directly.
=> Custom DC: Terraform for storage project IAM

server/configmodule.py, server/lib/disaster_dashboard.py
On server start up, if the ENV is stanford, local-stanford, or autopush, we need to read disaster data files from the GCS bucket
=> [stanford] add gcs bucket to stanford config

deploy/gke/stanford.yaml
The Stanford IT admin has now mapped this subdomain (datacommons.stanford.edu) to our Stanford static ip.
=> pointing to the stanford subdomain for stanford custom DC

server/configmodule.py
It is easy to make mistakes if the staging config is inherited from prod config. For example, the staging instance is currently trying to read the prod GCS bucket because the GCS bucket is not set explicitly in config.
=> Stanford Staging: Do not inherit Stanford prod config

build/Dockerfile, build/ci/cloudbuild.deploy.yaml, build/ci/cloudbuild.push_image.yaml, scripts/push_image.sh, server/requirements.txt
This PR removes things that can be removed without changing functionality. 
Debate of where to put the language model and the torch library aside, there are immediate improvements that can be made to reduce the compressed image size from 5.5G to 2.1G (over 60% reduction). This saves both build and deploy time. Cloud build now runs in ~9min, which is an improvement from ~14min. It is further observed that 8CPU machine and 32CPU machine doesn't seem to make a difference.
Pip cache takes 2.7G: 
Nvidia takes 1.4G:
Note that this is still not ideal as our image size is still > 3times larger than before and this has a noticeable difference in both build and deploy times. Next steps would be to discuss whether we can move nlp features to a separate container, and launched together like mixer and …
=> Reduce image size by removing pip cache and nvidia lib

server/routes/nl_interface.py, server/templates/nl_interface.html, static/js/apps/nl_interface/app.tsx, static/js/apps/nl_interface/main.ts, static/package-lock.json, static/package.json
* The cookie is used within the /nl page only.
* The html data is not needed since the data is fetched from the client after page loads now.
=> Add cookies support in NL interface; Clean up page data

deploy/terraform-datacommons-website/examples/setup/main.tf, deploy/terraform-datacommons-website/examples/setup/variables.tf, deploy/terraform-datacommons-website/examples/website_v1/main.tf, scripts/install_custom_dc.sh
Clone tools repo and call BT automation Terraform module. Also copy from the reference folder in datcom-public bucket into a folder called "reference" in custom dc resource bucket. 
Note that the reference bucket is currently empty and will be filled with actual sample tmcf shortly.
=> Custom DC: Add BT automation and initial reference data to install script

static/js/components/tiles/disaster_event_map_info_card.tsx, static/js/components/tiles/disaster_event_map_tile.tsx
This PR:
1. Adds a "More info" link to the bottom of tooltips on the disaster dashboard
2. Changes behavior of tooltips to only close when the "x" is clicked, or when a different dot is selected.
=> Add link to event pages to tooltips

docs/developer_guide.md, server/__init__.py, server/requirements.txt
This would save a ton of time for local development. Right now each change would download and build the model from scratch.
=> NL: cache model in disk for local dev

static/css/place/place.scss, static/css/shared/_chart_embed.scss, static/css/shared/_tiles.scss, static/css/shared/modal.scss, static/js/chart/base.ts, static/js/components/tiles/bar_tile.tsx, static/js/components/tiles/bivariate_tile.tsx, static/js/components/tiles/chart_tile.tsx, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/components/tiles/histogram_tile.tsx, static/js/components/tiles/line_tile.tsx, static/js/components/tiles/map_tile.tsx, static/js/components/tiles/ranking_tile.tsx, static/js/components/tiles/scatter_tile.tsx, static/js/place/chart.tsx, static/js/place/chart_embed.tsx, static/js/tools/scatter/chart_loader.tsx, static/js/utils/chart_csv_utils.ts, static/js/utils/tests/chart_csv_utils.test.ts
- allow downloading svg and csv data for each chart in a tile
some bug fixes along the way:
- fix data fetch for bivariate tile (param was missing a plural)
- fix "download chart image" only showing up the second time the export button is clicked (here and place charts)
=> [nl] add exporting charts for nl

server/lib/nl_training.py, server/routes/nl_interface.py, server/services/nl.py, static/js/apps/nl_interface/debug_info.tsx, static/js/types/app/nl_interface_types.ts
This PR adds:
1. Basic clustering-based correlation detection. It mostly only works when the query matches two very distinct set of SVs, e.g. "median income and auto theft California". 
2. The Detection object has all the attributes set.
3. Increased the number of SV matches we get from the embeddings matcher (from 10 to 20). The reason is that we now have a growing number of sentence alternatives for each SV and as a result the matching produces many duplicates. 
4. For the debugInfo rendered on the website, I have concatenated everything in a string. It is not the best rendering but for now, actual detection is perhaps more important than the formatting of the debugInfo. See attached image for now the debugInfo looks like:
=> [NL Interface] Correlation Detection - First Version

server/lib/nl_chart_spec.py, server/services/nl.py, static/js/apps/nl_interface/debug_info.tsx
1. Returning from charts config function when there are no svs in the list (currently it results in an error from API call to dc)
2. Ensure too low scores for SVs matched do not get passed to the clustering.
=> [NL Interface] Fixing some query detection bugs

server/lib/nl_detection.py, server/routes/nl_interface.py, server/services/nl.py
Changes the ranking query classification to use heuristics instead of a ML-model.
Note that this also:
(1) Changes the spec of `RankingClassificationAttributes`
(2) Changes query preprocessing to replace punctuation with spaces.
=> [NL Interface] Use heuristics-based ranking query classifier

server/routes/nl_interface.py, server/services/nl.py, server/test_nlp_manual.py
Since the flow is fixed and we have fast merging PRs, it would be nice to have a way to verify the flow end to end with a script. This PR only verifies Palo Alto is correctly detected. The rest of the flow will be followed.
The goal is to test: query -> nl/data API response, with contexts in between.
=> Add a script to manually verify the flow of NLP features

static/js/components/tiles/ranking_tile.tsx
When NaN is present,  javascript array sort does not work at all.
Before Fix:
After Fix:
=> Fix ranking sort issue when NaN is present

server/lib/nl/nl_data_spec.py, server/lib/nl/nl_page_config.py, server/lib/nl/nl_variable.py, server/routes/nl_interface.py
* Remove unused codes: related places, other commented codes
* Use "extended_sv_maps" as how topic branch works. The major change is to find extended svs robustly by inspecting direct siblings or remote siblings.
* Simplify context by using `data_spec` directly
=> [NL] Display extended stat vars as comparison charts

server/config/disaster_dashboard/Earth.textproto, server/routes/disasters.py, static/js/apps/disaster_dashboard/main.ts, static/js/components/disaster_dashboard/parent_breadcrumbs.tsx, static/js/components/subject_page/main_pane.tsx
- for the maps that are rendered, render AA2 for AA1 places
- in the breadcrumbs, prefer to show "State" or "County" over "AdministrativeArea" as the place type
=> [disasters] render AA2 maps for AA1 places

server/routes/api/series.py, static/js/components/tiles/histogram_tile.tsx
This PR:
* Adds a server endpoint that filters observation series to data for a specific year.
* Use that endpoint to have histogram tiles only show data from 2022.
This allows us to pre-bin the data used in the histogram tile to a specific year, as a quick workaround to the rendering issues seen when trying to show histograms for long historical timeseries.
Allowing for multiple types of binning (by decade, year, month) and either allowing this to be set in a config or dynamically chosen based on the data can come in a future PR.
Current:
Proposed:
=> [Disaster Dashboard] Binning histogram to latest year

server/routes/api/disaster_api.py
- update flask side event filtering to filter out events that don't have the filter props
=> [disasters] filter out events without props

server/config/disaster_dashboard/Earth.textproto, static/js/components/subject_page/category.tsx, static/package-lock.json, static/package.json
This PR:
- Adds a short description for each category on the disaster dashboard
- **adds [react-markdown](https://www.npmjs.com/package/react-markdown?activeTab=readme)** npm package to add support for links in descriptions via markdown. This adds a `<ReactMarkdown>` component for rendering markdown into html.
Preview:
=> [Disaster Dashboard] Add descriptions with markdown

static/js/components/subject_page/category.tsx
Quick fix for the `<p>` descriptions error.
=> Fix for "<p> cannot be descendant of <p>" errors

static/js/chart/draw_d3_map.ts, static/js/components/subject_page/block.tsx, static/js/components/subject_page/category.tsx, static/js/components/subject_page/main_pane.tsx, static/js/components/tiles/disaster_event_map_filters.tsx, static/js/components/tiles/disaster_event_map_selectors.tsx, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/components/tiles/top_event_tile.tsx, static/js/utils/disaster_event_map_utils.tsx
- event ranking tile embed
- event ranking tile use url params
- updates to allow multiple disaster event maps on one page (config changes to show the multiple event maps will be in a separate PR in case we don't want to include those changes because it slows down the page)
=> [disasters] various updates

static/js/components/tiles/disaster_event_map_filters.tsx
- when updating filter on key press, only update if "enter" is pressed
=> [disaster] filter delay fix

server/__init__.py, server/lib/disaster_dashboard.py
- made heat and cold event data available to be used, but NOT added to config
- don't read disaster data from GCS bucket if running lite server
=> [disaster] make heat and cold event data available

static/css/shared/_tiles.scss, static/js/chart/draw_d3_map.ts, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/components/tiles/top_event_tile.tsx, static/js/utils/disaster_event_map_utils.tsx
- for disaster event map tile, when a place doesn't have a specified contained place type (e.g., counties), render the parent map and highlight the selected place (like map explorer)
=> [disasters] render parent map for places with no enclosedPlaceType

deploy/terraform-datacommons-website/examples/setup/main.tf, deploy/terraform-datacommons-website/examples/website_v1/main.tf, scripts/install_custom_dc.sh
- Save Terraform state to gcs (create a terraform state bucket if it does not exist already).
- Only clone if repo does not exist. This makes the script retryable.
=> [Custom DC] Save terraform state to gcs

docs/developer_guide.md, server/__init__.py, server/lib/nl/nl_place_detection.py, server/requirements.txt, server/routes/nl_interface.py, server/routes/nl_interface_next.py, server/services/nl.py, server/tests/lib/nl/nl_place_detection_test.py
This PR replaces the previous SV search (on embeddings) and NER place search with the new NL models server API calls. 
Note: for now, the dependence on the embeddings models and builds is not completely removed. This will need one more API end point first (returning the embeddings vector for individual queries). This will be done in the next PR.
=> [NL Interface] Replacing SV search and NER place search with the new server API endpoints

deploy/base/deployment.yaml
NL server restarts a few times now due to the lack of startup probe.
Removes initialDelaySeconds=10 as it is default value.
=> Add startupProbe for NL server; Update all the Kubernetes probers

server/lib/nl/nl_page_config_next.py
Currently, it only shows "Total" or "Per Capita".
Instead, if the ChartSpec attr sets a title use that. Otherwise, if this is a multi-SV chart, point out SV comparison.
=> [NL Next] Set appropriate title for bar charts

server/lib/nl/constants.py, server/lib/nl/detection.py, server/routes/nl_interface_next.py, server/services/nl.py, static/js/apps/nl_interface/debug_info.tsx
Adds a classifier for "time-delta" queries to the NL interface.
This would identify queries that ask for a change in a statvar over time, e.g. "Which places have seen the most increase in population?"
This is an initial classifier to unblock downstream tasks, improved classifiers to follow in future PRs.
Example Screenshots:
=> [NL Next] Add Time-Deltas classifier

server/lib/nl/detection.py, server/lib/nl/utterance.py
This PR:
1. Adds Time-Delta classifiers to utterances, as followup to [this PR comment](https://github.com/datacommonsorg/website/pull/2150#pullrequestreview-1280041268)
2. Makes quick fix for JSON serializability errors for the TimeDeltaType object.
=> [NL Next] Add time-delta classifiers to utterances

server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/comparison.py, server/lib/nl/fulfillment/containedin.py, server/lib/nl/fulfillment/correlation.py, server/lib/nl/fulfillment/ranking_across_places.py, server/lib/nl/fulfillment/ranking_across_vars.py, server/lib/nl/fulfillment_next.py, server/lib/nl/utils.py
Bo had the right intuition earlier today to break up ranking into by places and vars.  With the addition of "time delta" for ranking across vars, this is better.
Also, often times when the ranking, correlation and contained-in fails on a SV a better choice is to show the place rather than attempt some poor fallback of population in county, which invariably also fails.
=> Fork ranking into by place and by var. Also improve fallback

server/lib/nl/constants.py, server/lib/nl/detection.py, server/routes/nl_interface_next.py, server/services/nl.py, static/js/apps/nl_interface/debug_info.tsx
Adds the event classifier to query detection
Supports rudimentary heuristics for:
* Fires
* Floods
* Drought
* Cyclones
* Extreme heat
* Extreme cold
* Wetbulb temperatures
Examples:
=> [NL Next] Add event classifier

server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/comparison.py, server/lib/nl/fulfillment/containedin.py, server/lib/nl/fulfillment/correlation.py, server/lib/nl/fulfillment/simple.py, server/lib/nl/fulfillment/time_delta.py, server/lib/nl/fulfillment_next.py, server/lib/nl/utils.py, server/tests/lib/nl/fulfillment_next_test.py, server/tests/lib/nl/page_config_next_test.py, server/tests/lib/nl/test_utterance.py
1. Downgrade single point time-series to bar charts
2. Open up topics in correlation, and include multiple SVs from current utterance and past context
3. Show contained-in maps for peer-group SVs
4. Sprinkle more debug logs
This improves on Jan script, in these ways:
(1) [agriculture in california] contained single-dot timeline charts
(2) There used to be only one correlation chart
=> [NL Next] A few fulfillment fixes

deploy/helm_charts/dc_website/templates/deployment.yaml, deploy/helm_charts/dc_website/values.yaml, deploy/terraform-datacommons-website/README.md, deploy/terraform-datacommons-website/examples/website_v1/main.tf, deploy/terraform-datacommons-website/examples/website_v1/variables.tf, deploy/terraform-datacommons-website/examples/website_v1/variables.tfvars, deploy/terraform-datacommons-website/modules/apikeys/main.tf, deploy/terraform-datacommons-website/modules/apikeys/variables.tf, deploy/terraform-datacommons-website/modules/esp/main.tf, deploy/terraform-datacommons-website/modules/helm/main.tf, deploy/terraform-datacommons-website/modules/helm/variables.tf, scripts/install_custom_dc.sh
This PR adds the following improvements
- Website, mixer, and tools repo now are fetched from a tagged version of the code
- Docker images now match the version of the code with the install script.
- api key secret: global resource -> regional resource
- For re-runs, the script is no longer stuck trying to fetch non existent tmp files. We force a file fetch.
- Small fixes: BIGQUERY -> BIG_QUERY, always force mixer to be fetched for re-runs.
Tested using a [test tag](https://github.com/Fructokinase/website/releases/tag/test-custom-dc-v0.1.1). The current tag the script references to (custom-dc-v0.1.0) does not exist, and will be created in website repo and tools repo after this PR is committed.
Result: https://custom-dc-tag-based-launch-datacommons.com/
=> [Custom DC] improvements for re-runs

server/lib/nl/constants.py, server/tests/lib/nl/heuristics_test.py
Add support for 'major' triggering a high ranking classification, including test cases. This allows for queries like "which were the major earthquakes in california?"
Similar additions like "large", "big", "small", "minor" were tested, but prone to false positives, so leaving those out for now.
=> [NL Next] Add support for 'major' in rankings

server/lib/nl/constants.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/correlation.py, server/lib/nl/fulfillment/ranking_across_places.py, server/lib/nl/fulfillment/ranking_across_vars.py, server/lib/nl/fulfillment/time_delta.py, server/lib/nl/page_config_next.py, server/lib/nl/topic.py, server/lib/nl/utils.py, server/tests/lib/nl/page_config_next_test.py, static/js/shared/util.ts
(1) Support fulfillment of ACROSS contained-in type by resolving to a place-type based on the place considered
(2) Support fulfillment of EXTREME ranking type by deciding whether to show lowest based on SV name
(3) Prune some SV names per Guha request (a hack for now)
(4) Modify the RANKING chart display to always show an adjoining map on the same row
(5) Drop a weird jobs SV from topic
(6) Make and use helper functions for getting {ranking-type, contained-in, time-delta-types} from utterance
(7) Fix the temperature hack properly to avoid pinned max dates
Sorry that (6) is in this PR.  I have tested both the old and new scripts with this though.
For the main UI change of ranking-across-places results, here is an example screenshot.
=> Miscellaneous fixes for new script

static/js/chart/draw.ts
for the example query on nl interface (family earnings in california)
on autopush: https://screenshot.googleplex.com/7i8eTxghosJG6yC
with this fix: https://screenshot.googleplex.com/8CZA5A3QA8FsdZM
=> [NL] fix line tile

static/css/nl_interface.scss, static/js/apps/disaster_dashboard/app.tsx, static/js/apps/nl_interface/query_result.tsx, static/js/apps/topic_page/app.tsx, static/js/chart/draw_bivariate.ts, static/js/chart/draw_d3_map.ts, static/js/components/subject_page/block.tsx, static/js/components/subject_page/category.tsx, static/js/components/subject_page/disaster_event_block.tsx, static/js/components/subject_page/main_pane.tsx, static/js/components/subject_page/sidebar.tsx, static/js/components/tiles/bivariate_tile.tsx, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/components/tiles/map_tile.tsx, static/js/constants/subject_page_constants.ts, static/js/place/chart.tsx, static/js/tools/map/d3_map.tsx, static/js/tools/scatter/chart.tsx, static/js/utils/subject_page_utils.ts
- get unique id for each component when there are multiple subject pages
- update draw_d3_map to take a ref element instead of an element id
small css fix:
- update font color for severity filters (for disaster event tiles) on nl interface to white
=> [subject page] Add support for multiple pages

deploy/base/deployment.yaml, deploy/overlays/dev/kustomization.yaml
Decreasing this changes memory requirement from 15G -> 14G per pod. Nodes currently have ~29G of memory and this allows 2 pods to fit in a node as opposed to 1.
=> [Devops] ESP 2G -> 1G memory to fit another pod in a node

server/config/disaster_dashboard/Earth.textproto, static/js/components/tiles/top_event_tile.tsx
Adds dates to the top event tile for storms
Screenshot:
Also confirmed changes don't break any of the other top event tiles:
=> [Disaster Dashboard] Add dates to storm top events

static/js/components/tiles/histogram_tile.tsx
Removes logic that truncates histogram to the last date we have data for. This makes the histograms show bars for every month in the range. As a nice side effect, all histogram bars will have the same width if the same time setting is used.
Before ("last year" setting):
After ("last year" setting):
=> Show full date range in histogram tile

server/config/disaster_dashboard/Earth.textproto, static/css/shared/_tiles.scss, static/js/components/tiles/disaster_event_map_info_card.tsx, static/js/components/tiles/top_event_tile.tsx, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/string_utils.ts
top event tile:
- add links to dates if place & name are not available
- don't show NaN
event map info card:
- add box shadow
- only show 3 significant digits
- don't show NaN
- TODO: bring in event spec so we can use display name & units
=> [disaster] small ui fixes

static/css/shared/_tiles.scss, static/js/components/google_map.tsx
After PR #2189, google map tiles with KML coordinates drawn don't let the user scroll or pan.
This PR removes the listener added as a quick-fix, and instead fixes a CSS bug that caused map heights to sometimes be set to 0.
Before:
https://user-images.githubusercontent.com/4034366/219223889-0125501a-70d1-42c0-b91a-a4750ed525bb.mov
After:
https://user-images.githubusercontent.com/4034366/219223926-39c46b17-2ead-406e-a728-f0d7d05d4121.mov
Also tested the changes on the following pages:
Place pages:
* San Francisco City
* California
* USA (no maps expected)
* India (no maps expected)
Browser pages:
* Mountain View
* Santa Clara County
* Alaska
* India
NL interface:
* "Tell me about palo alto"
* "Tell me about Santa Clara County"
* "Tell me about Nebraska"
* "Tell me about USA"
=> Fix google maps scrolling issue

nl_server/tests/ner_place_model_test.py, server/lib/nl/constants.py
NER does an Ok job in recognizing continent names. But to guard against any missed detection (for such important places like continents), adding continent names to special cases.
=> [NL Interface] Adding continent names to special cases

server/lib/nl/constants.py, server/lib/nl/detection.py, server/services/nl.py
This PR does the following:
1. Adds the following types to contained in detection (singular + plural):  
"School"
"PublicSchool"
"PrivateSchool"
"PrimarySchool"
"ElementarySchool"
"MiddleSchool"
"HighSchool"
Note: these all exist in the KG today and "pre school" does not (so that has not been added).
2. These are added in ranked order for contained in so all previous contained in attributes are given preference. For example, see the screenshot below for "what about private schools in counties in New York State" and the contained in classification says "COUNTY".
3. There are some cases where unintended consequences will also happen. For example "high schools" will also trigger the RANKING.HIGH attribution/classification. See example below of "what about high schools in San Mateo County" …
=> [NL Interface] Adding schools to contained in

server/routes/api/choropleth.py, server/tests/routes/api/choropleth_test.py, static/js/components/subject_page/data_context.ts, static/js/components/subject_page/main_pane.tsx, static/js/components/tiles/disaster_event_map_tile.tsx, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/geojson_utils.ts
- If a place doesn't have geojson for its children, use its own geojson as the base map
autopush: 
with the change:
=> [disasters] use own place geojson if children are missing

server/lib/nl/constants.py, server/lib/nl/detection.py, server/routes/nl.py, server/services/nl.py, static/js/apps/nl_interface/debug_info.tsx, static/js/types/app/nl_interface_types.ts
Detects "big" and "small" query type. The generic name is called SizeType. Plumbs it all the the way to debugInfo and adds the right types to debugInfo javascript object too (some were missing even though it worked fine).
Tested locally + on the previous demo script. All work. Some screenshots of the latest changes are below (note this "big" and "small" do not automatically trigger the RANKING.HIGH and RANKING.LOW attributes which is good):
=> [NL Interface] Size type (big/small) attribution/classification

server/integration_tests/nlnext_test.py, server/integration_tests/test_data/demo2_cities_feb2023/query_1/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_1/debug_info.json, server/integration_tests/test_data/demo2_cities_feb2023/query_2/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_3/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_3/debug_info.json, server/integration_tests/test_data/demo2_cities_feb2023/query_4/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_4/debug_info.json, server/lib/nl/constants.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/handlers.py, server/lib/nl/fulfillment/size_across_entities.py, server/lib/nl/page_config_builder.py, server/lib/nl/utils.py, server/lib/nl/utterance.py, server/services/nl.py
The new SIZE_ACROSS_ENTITIES fulfiller just maps "size" to set of SVs depending on the ContainedInPlaceType, and thereon pretends like a RANKING_ACROSS_PLACES fulfiller.
There is some page_config_builder tweaks needed to put all the charts in a single block and avoid showing map charts.
Also, extend the integration tests to include the working demo script.
=> Implement a size_across_entities fulfiller

server/__init__.py
The config should really be split out
=> When model is enabled, should register stanford routes to get disaster config

static/js/apps/nl_interface/app.tsx
- update running prompts from url to only automatically run if there is `&a=true` in the url. Otherwise, wait for enter to be pressed after each prompt
Note: This is kind of hacky and not very clean, added TODO to clean up the code
=> [nl] Add mode where enter has to be clicked to move on to next url prompt

server/integration_tests/test_data/demo_climatetrace/query_1/chart_config.json, server/lib/nl/constants.py, server/lib/nl/page_config_builder.py, server/lib/nl/topic.py, server/lib/nl/utils.py
For descriptions, only the following scenarios are supported now:
(1) If an SVPG has a description, for comparison bar charts.  (That's the case where an SVPG is in a single block.)
(2) If an SV has a description, for ranking chart.
(3) If an SV has a description, for time-delta charts.
These are the scenarios where we explicitly control the block boundary.  In other cases, a block could be shared by multiple SVs.
Screenshots from Climate Trace below:
=> Support SV descriptions and add descriptions for Climate Trace vars

deploy/base/kustomization.yaml, deploy/git/kustomization.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/climate_trace/kustomization.yaml, deploy/overlays/custom/kustomization.yaml, deploy/overlays/dev/kustomization.yaml, deploy/overlays/feedingamerica/kustomization.yaml, deploy/overlays/iitm/kustomization.yaml, deploy/overlays/kustomization.yaml.tpl, deploy/overlays/magiceye/kustomization.yaml, deploy/overlays/prod/kustomization.yaml, deploy/overlays/staging/kustomization.yaml, deploy/overlays/stanford-staging/kustomization.yaml, deploy/overlays/stanford/kustomization.yaml, deploy/overlays/tidal/kustomization.yaml
Kustomize currently adds a suffix to all config maps deployed. It seems like there are some rationales for doing this (link below) but so far I'm not sure if it helped us. Since it is difficult for helm to match this, let's get rid of the configmap suffix?
https://pauldally.medium.com/why-is-kustomize-adding-a-bunch-of-characters-to-my-secret-configmap-names-b1572741c846
=> [Custom DC] Fix helm/kustomize diff: remove kustomize config suffix

static/js/chart/draw.ts
Fixes #2333 
Culprit was that the check to see if x-axis labels overflow the margins was not working as intended, so axis location wasn't updated as necessary.
Pair programmed with @chejennifer 
Before:
After:
=> Fix diagonal x-axis labels being cut off

static/css/nl_interface.scss
fix nl interface layout on small window sizes (width < 992px). The problem was that nl interface css depends on the styling for the containing divs from here: https://github.com/datacommonsorg/website/blob/master/static/css/tools/base_tools.scss#L50-L66, but this styling is only applied when page size is lg which is when min-width = 992px
autopush:
with the change:
=> [nl] fix small window size css

deploy/base/kustomization.yaml, deploy/git/kustomization.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/climate_trace/kustomization.yaml, deploy/overlays/custom/kustomization.yaml, deploy/overlays/dev/kustomization.yaml, deploy/overlays/feedingamerica/kustomization.yaml, deploy/overlays/iitm/kustomization.yaml, deploy/overlays/kustomization.yaml.tpl, deploy/overlays/magiceye/kustomization.yaml, deploy/overlays/prod/kustomization.yaml, deploy/overlays/staging/kustomization.yaml, deploy/overlays/stanford/kustomization.yaml, deploy/overlays/stanford_staging/stanford-staging/kustomization.yaml, deploy/overlays/tidal/kustomization.yaml
Reverts datacommonsorg/website#2335
Going to revert the removal of config map suffix. I don't have a deep enough understanding of the k8s resource chain to know what field triggers the recreation of what resources.  Configmap change  + deployment referencing the config map seems like it should obviously update the upstream deployment but it doesn't. For helm/kustomize divergence, config map naming shouldn't affect anything because the name changes everytime anyways.
This solution is also worth looking into, but for later.
https://blog.questionable.services/article/kubernetes-deployments-configmap-change/
=> Revert "[Custom DC] Fix helm/kustomize diff: remove kustomize config suffix"

server/integration_tests/test_data/place_detection_e2e/query_2/chart_config.json, server/integration_tests/test_data/place_detection_e2e/query_3/chart_config.json, server/integration_tests/test_data/place_detection_e2e/query_4/chart_config.json, server/integration_tests/test_data/textbox_sample/query_1/chart_config.json, server/lib/nl/constants.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/containedin.py, server/lib/nl/page_config_builder.py, server/lib/nl/utils.py
1. Make default child types for "Earth" work right
2. Make contained-in ACROSS work right (regressed with map_type check)
3. Drop per-capita for a couple of more cases
=> NL: Fix a few bugs related to guessing place types and per-capita

server/integration_tests/nlnext_test.py, server/integration_tests/test_data/demo_fallback/query_4/chart_config.json, server/integration_tests/test_data/demo_fallback/query_4/debug_info.json, server/lib/nl/constants.py, server/lib/nl/detection.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/correlation.py, server/lib/nl/page_config_builder.py, server/lib/nl/utils.py, server/lib/nl/variable.py, server/services/datacommons.py, server/tests/lib/nl/fulfiller_test.py
1. We may fallback to parent places... eg, jobs in sunnyvale -> SC county
2. We may fallback to parent contained-in types... eg, cities with highest agricultural production in california -> counties of CA
3. Collect SVs and batch existence check... this is done using a tracker class
Fallback is implemented in common code so it works for all query-types (except correlation and comparison, which is v custom rn).
TODO: Providing user feedback about the fallback
=> Implement place fallback and optimize existence checks

static/js/apps/nl_interface/app.tsx
Removing query history from the NL page, especially while we push the boundaries of the app in testing
=> [nl] remove query history

static/js/utils/place_utils.ts
This reverts commit d919ad939e440df208d1cc123dbb3f4a48252793.
Since it breaks Map Explorer
=> Revert "[sv widget] show sv that have data for at least 10 countries"

server/integration_tests/nlnext_test.py, server/integration_tests/test_data/place_detection_e2e/query_2/chart_config.json, server/integration_tests/test_data/place_detection_e2e/query_2/debug_info.json, server/lib/nl/constants.py, server/routes/nl.py, server/services/nl.py
(1) Avoid matching places within a word (e.g., "us" in "houses")
(2) Set the country for default place so default-place queries get the right child-type (https://github.com/datacommonsorg/website/issues/2518)
(3) Match "where" as ACROSS (https://github.com/datacommonsorg/website/issues/2506)
One working screenshot for each:
=> NL: Fix a few fulfillment bugs

server/__init__.py, server/services/bigtable.py
Now server/services/bigtable.py is always imported hence require bigtable client is always created. This gives GCP auth error for 3P developers that do not have corresponding access.
=> Only load bigtable module when LOG_QUERY is enabled

deploy/helm_charts/dc_website/templates/config_maps.yaml, deploy/helm_charts/envs/autopush.yaml, deploy/helm_charts/envs/custom.yaml, deploy/helm_charts/envs/dev.yaml
When deploying mixer pods, the serviceGroup in deploy/helm_charts/envs/<ENV>.yaml is merged with the base values in mixer repo, hence "null" values should be added to prevent creating unwanted pods.
=> More update on service group config

static/js/chart/draw_scatter.ts, static/js/utils/chart_csv_utils.ts, static/js/utils/scatter_data_utils.ts, static/js/utils/tests/chart_csv_utils.test.ts
- scatter tiles sometimes will have null populationData causing an error when trying to access populationData during the data processing
=> [scatter] fix population bug in scatter tile

.vscode/launch.json, server/routes/place/api.py, server/routes/place/html.py, server/routes/ranking/api.py, server/routes/shared_api/choropleth.py, server/routes/shared_api/place.py, server/services/datacommons.py, server/services/discovery.py, server/tests/routes/api/landing_page_test.py, static/js/shared/ga_events.test.tsx, static/js/tools/download/mock_functions.ts, static/js/tools/download/page.test.tsx, static/js/tools/scatter/app.test.tsx, static/js/tools/shared/stat_var_widget.tsx, static/js/tools/timeline/data_fetcher.test.ts, static/js/tools/timeline/mock_functions.tsx, static/js/tools/timeline/page.test.tsx, static/js/utils/place_utils.ts, static/js/utils/tests/disaster_event_map_utils.test.ts
* Use /info/place API to get parent places instead of using get_prop_value a few times.
* Get rid of "cached" version of some data fetch functions. The dc.Fn() call result is already cached, and/or there is cache for flask endpoints response.
=> [V2 API] Migrate place stat var union/existence and place name related APIs

static/js/chart/draw_bivariate.ts, static/js/components/tiles/chart_tile.tsx
- When a chart tile has mulitple svgs (e.g., map which has the map and the legend), in the export functionality, package the svgs together into 1 svg to be exported
- also fix a bug in the bivariate tile where multiple legends were showing up
=> [tiles] merge all svgs in chart tile container and export

server/lib/fetch.py, server/lib/nl/utils.py, server/lib/subject_page_config.py, server/routes/shared_api/observation/existence.py, server/routes/shared_api/place.py, server/services/datacommons.py, server/services/discovery.py, server/tests/lib/subject_page_config_test.py, server/webdriver_tests/tests/stat_var_hierarchy_test.py, static/js/tools/download/mock_functions.ts, static/js/tools/shared/stat_var_widget.tsx, static/js/tools/timeline/mock_functions.tsx
Follow the new file layout pattern:
* Create data fetch function in fetch.py, with response simplification
* Remove v1/v2 observation existence REST call wrapper in datacommons.py
=> [V2 API] Migrate and clean up usage of observation existence API

server/lib/nl/scraper.py
- instead of always waiting 5 seconds for charts to load, wait for loading placeholders to disappear, then wait for svgs to be drawn
comparing the time spent waiting between the old and new methods (look for time_taken & the time is in seconds):
old method: https://paste.googleplex.com/5697023377408000
new method: https://paste.googleplex.com/5627238262243328
=> [nl] update how scraper waits for charts to be loaded

server/integration_tests/test_data/demo_feb2023/query_9/chart_config.json, server/lib/nl/page_config_builder.py
- some stat var names no longer contain key words that indicate per capita, so should also check the dcid to tell if a stat var is per capita or not. 
e.g.,
sv dcid: Percent_Person_WithHighBloodPressure
sv name: High Blood Pressure
=> [nl] update determining if sv is per capita

static/js/stat_var_hierarchy/node_header.tsx
Format the count of stat vars in the sidebar of our explorer tools to the user's locale. In the US, this adds commas to numbers larger than 1k. This improves readability of the sidebar.
Before:
After:
=> Format the count of SVs in the sidebar

server/lib/subject_page_config.py, server/routes/disaster/html.py, server/routes/event/html.py, server/routes/shared_api/place.py, server/routes/sustainability/html.py, server/templates/disaster_dashboard.html, server/templates/event.html, server/templates/sustainability.html
* Do now show Earth in place page ranking table
* Move disaster, sustainability html template from stanford to base
* Use subject_config instead of config in jinja template, as config represents the global app.config
=> A few website bug fixes

server/routes/shared_api/choropleth.py, server/webdriver_tests/tests/map_test.py, server/webdriver_tests/tests/stat_var_hierarchy_test.py, static/js/tools/map/util.ts
This PR:
* Adds support for selecting zip codes (ZCTAs) as a place type in the map tool
* Allows for map tiles to use ZCTAs as an enclosed place type
* Allows for map tiles to use cities as an enclosed place type.
Sample map tool screenshots:
Sample map tiles:
Note that ZCTAs and cities currently render poorly -- borders and some rescaling would improve readability. These improvements will come in future PRs.
Testing:
Confirmed these changes don't break the NL interface, place pages, disaster dashboard, and sustainability explorer.
=> [Maps] Add support for zip codes

static/js/components/google_map.tsx
- instead of having the page break due to improperly formatted json string, just hide the map
autopush fire event page which has an improperly formatted json string as the geojson string:
with the fix:
=> [google map] handle when geojson is not a properly formatted json string

static/js/chart/draw_d3_map.ts, static/js/tools/map/d3_map.tsx
- allow drawing map points even if they don't have associated data values
e.g., map point place type is SuperfundSite, no map point sv, and there is no data on median income for superfund sites
=> [map] draw map points without data values

static/js/chart/draw_d3_map.ts
currently on autopush:
with this change:
=> [map] make dots smaller

server/routes/shared_api/choropleth.py, static/js/chart/draw_d3_map.ts, static/js/tools/map/d3_map.tsx, static/js/tools/map/fetcher/map_point_coordinate.ts
- Fixed a bug where map points size kept changing. This was because we were trying to get the min region diagonal without actually calling Math.min
- Reverted the dot size logic to use minDotSize * 2 when there is no dot size scale & increased minimum dot size from 1.1 to 1.25
- Additional bug fixed: infinite loading when there are no map points. This is because of a check for non empty map points data even though there just may not be map points for the chosen place type
=> [map] fix dot size

static/js/apps/event/app.tsx
Fix a bug where the "observation date" entry on the property table in the event pages has an incorrectly formatted value. 
Before:
After:
=> [Event Pages] Fix "observation date" value rendering.

static/js/apps/event/app.tsx
Fixes a bug where the negative sign in a property value shows up as a unit instead of being in front of the digits.
Before (see SPI value in table):
After:
=> [Event Pages] Fix negative numbers bug

static/js/components/tiles/top_event_tile.tsx
=> [disaster] remove NA from top event tiles

static/js/components/tiles/disaster_event_map_tile.tsx
Fixes a bug where the (+)/(-) zoom buttons on the individual disaster maps don't do anything on click. This PR makes the ids of each button div unique, which fixes the issue.
https://github.com/datacommonsorg/website/assets/4034366/e9cc526f-29a8-4e98-b1e0-34a4a9244aea
=> [Disaster Dashboard] Fix zoom buttons on disaster specific maps

server/config/subject_page.proto, server/config/subject_page_pb2.py, server/config/topic_page/equity/US_States.textproto, server/lib/subject_page_config.py, server/lib/util.py, server/routes/shared_api/choropleth.py, server/routes/topic_page/html.py, server/tests/lib/subject_page_config_content_test.py, server/tests/routes/api/choropleth_test.py, server/webdriver_tests/tests/event_page_test.py
- add list of allowed place groups in the subject page config
- allow equity page for all states in USA
bug fixes along the way (caused by updates in accepted parameter type and return value of parent_places):
- fix bug in getting parent place type in choropleth API
- fix bug in returned parent place list from subject page config place metadata
=> [subject page] allow place groups for a topic page config

deploy/gke/feedingamerica.yaml, deploy/gke/stanford.yaml, deploy/gke/tidal.yaml, deploy/helm_charts/dc_website/values.yaml, docs/developer_guide.md, gke/README.md, gke/add_policy_binding.sh, gke/config.yaml.tpl, scripts/install_custom_dc.sh
mem cache has been deprecated in mixer: https://github.com/datacommonsorg/mixer/pull/1155
=> Remove tmcf+csv mem cache support in website config

static/js/apps/event/app.tsx, static/js/components/tiles/disaster_event_map_info_card.tsx, static/js/components/tiles/histogram_tile.tsx, static/js/components/tiles/top_event_tile.tsx, static/js/types/disaster_event_map_types.ts, static/js/utils/disaster_event_map_utils.tsx, static/js/utils/property_value_utils.tsx, static/js/utils/tests/disaster_event_map_utils.test.ts
This PR enables property value units to be displayed on the disaster dashboard.
More specifically, the following changes are made:
* Extract out the util functions in `event/app.tsx` to a dedicated utils file, that way these general functions can be reused.
* Edit `displayProps` interface to map to strings instead of numbers, to keep the unit stored.
* Remove stripping the unit in the main `disaster_event_map_utils`.
* Pass that unit to the info card so it can also be displayed.
* Update property value processing in `histogram_tile` and `top_event_tile` which expect numbers instead of a number with unit.
* Update `disaster_event_map_utils_test` to reflect changes
Before:
After:
Dashboard page itself remains unchanged:
=> [Disaster Dashboard] Add units to info cards

deploy/helm_charts/envs/stanford.yaml
There are data shared between s3l and magic labs. Add the stat var schema hierarchy mcf to s3l lab import group
=> Add s3l lab import group in stanford DC

server/requirements.txt, server/routes/screenshot/html.py, server/templates/screenshot_landing.html, static/css/screenshot.scss
This page pulls the github commits from the past month, list them with screenshot links, including current, diff with previous, and diff with a base commit.
=> Add a screenshot landing page

docs/developer_guide.md, run_test.sh, server/routes/event/html.py, server/templates/event.html, server/webdriver_tests/base_test.py, server/webdriver_tests/screenshot/screenshot_test.py, server/webdriver_tests/screenshot/test_page.json, server/webdriver_tests/shared.py, server/webdriver_tests/tests/timeline_test.py, static/js/apps/event/main.ts, static/js/chart/draw.ts, static/js/chart/draw_d3_map.ts, static/js/chart/draw_scatter.ts, static/js/components/tiles/chart_tile.tsx, static/js/components/tiles/highlight_tile.tsx, static/js/components/tiles/place_overview_tile.tsx, static/js/components/tiles/ranking_tile.tsx, static/js/components/tiles/sv_ranking_units.tsx, static/js/components/tiles/top_event_tile.tsx, static/js/constants/css_constants.ts, static/js/place/chart.tsx, static/js/place/chart_embed.tsx, static/js/place/main_pane.tsx, static/js/ranking/ranking_histogram.tsx, static/js/tools/map/chart.tsx, static/js/tools/scatter/chart.tsx, static/js/tools/timeline/__snapshots__/page.test.tsx.snap, static/js/tools/timeline/chart.tsx
A lot of charts, widgets are fetched async by using react effect and state. For example on place page, there are tens of charts that show up at different times. This makes screenshot unstable.
This PR adds a framework to wait for all the charts/widgets loading before taking a screenshot. The idea is simple, add a class for the holder element that are initially rendered and add a class for the chart/widget element that are updated asynchronously. The tests first gather all the holder elements and check when each holder element has the desired element present.
We should use in other web driver tests as well.
=> Add a framework to get stable screenshot result

server/routes/topic_page/html.py, server/templates/topic_page.html
- base.html uses "config" assuming it is the app config, but topic page was passing in the page config as "config" causing the page to fail to load: https://autopush.datacommons.org/topic/poverty/country/USA
=> [topic page] fix bug

server/__init__.py, server/app_env/autopush.py, server/config/nl_page/palm_prompt.txt, server/lib/nl/common/utterance.py, server/lib/nl/detection/heuristic_detector.py, server/lib/nl/detection/llm_detector.py, server/lib/nl/detection/palm_api.py, server/lib/util.py
This is a straightforward PR that maps json enums from LLM to Classification enums.
Now LLM supports queries like:
* commute in california vs. nevada (COMPARISON)
* what are some bad USA counties for asthma (RANK, SUB_PLACE_TYPE)
* fires in california (DISASTER_EVENT)
* poverty vs. income in california cities (CORRELATION, SUB_PLACE_TYPE)
* countries where gdp has grown the most (GROWTH, SUB_PLACE_TYPE, RANK)
* how big is nevada (SIZE)
=> PaLM API: support 7 additional classification types

static/js/apps/nl_interface/app.tsx
- fix bug with running the url prompts when the data fetch takes too long where the input will get cleared because the completed data fetch re-renders the search box. Fixed by inputting the next prompt once the previous data fetch is completed.
=> [nl] fix url prompts bug

server/lib/nl/detection/llm_detector.py
For example, sometimes the returned json object will have the key but value `None`.  So don't assume key existence => list.
=> Minor bug fix to cope with LLM misbehavior

experimental/datacommons-js/example.html, static/library/map_component.ts
Update the properties of the map web component to bring in line with other components
Specifically:
(1) Remove "statVarName", it is unused
(2) Rename "statVarDcid" to "variableDcid" to match convention of other components
As a result, a minimal example of embedding a datacommons map now looks like:
```
<script src="https://autopush.datacommons.org/datacommons.js"></script>
<datacommons-map
title="Population Below Poverty Level Status in Past Year in States of United States (2020)"
placeDcid="country/USA"
enclosedPlaceType="State"
variableDcid="Count_Person_BelowPovertyLevelInThePast12Months"
></datacommons-map>
```
=> [Library] Update map web component properties

experimental/datacommons-js/example.html, static/library/bar_component.ts
Add support for the user to select specific places to plot in the bar chart
With this change, users can also now use
```
<script src="https://datacommons.org/datacommons.js"></script>
title="Population in States of United States"
variableDcid="Count_Person"
comparisonPlaces='["geoId/01", "geoId/02", "geoId/04"]'
></datacommons-bar>
```
to create the bar chart below:
=> [Library] Add support for comparing specific places to Bar Chart

static/src/server.ts
- just dividing big ints causes decimals to be lost. So instead, convert ns to ms, convert to number type & then divide by 1000 to get s with decimals
=> [node server] add more precision to node server timing

experimental/datacommons-js/example.html, static/library/map_component.ts
Added back `datacommons-map` attributes `placeDcid`, `statVarDcid`, and `enclosedPlaceType` for backwards compatibility. 
@pradh FYI
=> Added datacommons-map deprecated attributes for backwards compatibility

server/cache.py, server/routes/browser/api.py, server/routes/disaster/api.py, server/routes/disease/api.py, server/routes/event/html.py, server/routes/place/api.py, server/routes/place_list/html.py, server/routes/protein/api.py, server/routes/screenshot/html.py, server/routes/shared_api/choropleth.py, server/routes/shared_api/observation/point.py, server/routes/shared_api/observation/series.py, server/routes/shared_api/place.py, server/routes/shared_api/stats.py, server/routes/sustainability/html.py, server/services/datacommons.py
After a deployment, only branch cache is updated which can cause data update. Since only covid is in branch cache and it's of low interest, we would increase the cache expiration from 1 day to 7 days. This would improve the latency a lot.
=> Extend flask cache expiration from 1 day to 7 days

static/js/apps/nl_interface/app.tsx, static/js/apps/nl_interface/data_app/app.tsx, static/js/apps/nl_interface/query_result.tsx, static/js/components/nl_feedback.tsx, static/js/components/tiles/chart_tile.tsx, static/js/components/tiles/ranking_tile.tsx, static/js/components/tiles/top_event_tile.tsx, static/js/utils/nl_interface_utils.ts
Includes the following changes:
* Ranking tile and top-events tile includes thumbs-down
* TODO: the top-events tile might need some css tweaks
* When LOG_QUERY is False, no query-level thumbs-down shown (chart-level already doens't show)
* With `enable_demo=True` url param, no thumbs-down shown
Screenshots:
=> Improve feedback UI

static/js/components/tiles/map_tile.tsx, static/library/map_component.ts
Allow users to specify a specific date to display on a map component.
Example usage:
```
<datacommons-map
title="Population"
place="country/USA"
childPlaceType="State"
variable="Count_Person"
date="2010"
></datacommons-map>
```
=> [Library] Add date attribute to map component

experimental/datacommons-js/example.html, static/library/bar_component.ts, static/library/utils.ts, static/tsconfig.json
<br />
This PR:
* Adds support for grouped bar charts to the existing bar chart component. 
* Removes the quirk of requiring users to use double quotes within lists by adding a custom attribute converter
* Switches "ES2021" in tsconfig to lowercase so `replaceAll()` can be loaded properly
The above charts were created with:
```
title="Median income by gender"
variables='["Median_Income_Person_15OrMoreYears_Male_WithIncome", "Median_Income_Person_15OrMoreYears_Female_WithIncome"]'
comparisonPlaces='["geoId/01", "geoId/02", "geoId/04"]'
></datacommons-bar>
title="Median income by gender for counties in Alaska"
variables="['Median_Income_Person_15OrMoreYears_Male_WithIncome', 'Median_Income_Person_15OrMoreYears_Female_WithIncome']"
place="geoId/02" …
```
=> [Library] Add grouped bar charts

nl_server/__init__.py, nl_server/routes.py, server/services/bigtable.py, server/services/datacommons.py
To validate, I added a log statement in write_row() locally.
```
【11:55:34】【INFO】【 bigtable.py:89 】 {'website_hash': None,
'mixer_hash': 'f32cb9d',
'table': ['dcbranch_2023_06_28_18_34_13', 'auto1d_2023_06_28_21_07_45', 'frequent_2023_06_28_20_02_43', 'auto1w_2023_06_25_21_05_05', 'auto2w_2023_06_27_10_30_37', 'ipcc_2023_06_22_12_08_25', 'biomedical_2023_06_27_16_09_49', 'disaster_2023_06_25_21_29_58', 'country_2023_06_28_22_33_14', 'experimental_2023_06_04_03_44_11', 'infrequent_2023_06_26_11_53_15', 'place_2023_06_12_21_08_19'],
'embeddings': {
'small': 'embeddings_small_2023_05_24_23_17_03.csv',
'medium': 'embeddings_medium_2023_05_24_22_15_24.csv'
}}
```
=> NL: log embeddings versions to BT

server/lib/nl/detection/palm_api.py, server/requirements.txt, server/tests/lib/nl/detection/palm_api_test.py
JSON5 is a lot more lenient in parsing JSON strings that LLM returns.
The docs say JSON5 can be 1000-3000x slower.  I did some benchmarking ([code](https://gist.github.com/pradh/63e5b9085505a7906062575314d1365a)), it is ~600x slower.
=> LLM: Use JSON5 to parse LLM response

nl_server/gcs.py
This bug was preventing the local nl_server from starting. 
Issue: on OS X any folders/files under the `/tmp/` folder are deleted if unused for some time (ref thanks to @pradh : https://apple.stackexchange.com/questions/438930/does-macos-delete-files-in-tmp-periodically). But looks like this cleanup does not properly remove a parent folder if there is an empty folder contained in it. This resulted in our nl_server's initialization to think the model is already downloaded (because we were only checking for path existence) but when loading the model it threw an error.
Fix is to check at startup time if the model can actually be loaded successfully. If not, remove the path entirely and then re-download the model folder and files.
=> [NL Interface] Bug fix: check if the predownloaded model can successfully be loaded

experimental/datacommons-js/example.html, static/js/chart/draw.ts, static/js/components/tiles/bar_tile.tsx, static/js/dev_page.tsx, static/js/place/chart.tsx, static/library/bar_component.ts
=> [library] Added stacked bar chart support to datacommons-bar web component

server/lib/nl/common/variable.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/correlation.py, server/lib/nl/fulfillment/event.py, server/tests/lib/nl/test_utterance.py, static/js/apps/nl_interface/debug_info.tsx, static/js/apps/nl_interface/query_result.tsx
If we retrieve a place or variable from context and also do place fallback, provide a unified message.
Before this PR we would not report place fallback when we fallback from a place in context. [asthma in california] -> [what about blood pressure?]
Now we'll say, `Tried looking up relevant statistics for "California" based on your prior queries, but found no results.   Here are results for "United States" instead.`
[How long do workers in Maryland live] from earlier today
These come about because we were expanding a "main SV" even when it doesn't pass existing check, so fix that.
This is a temporary thing until we have [chart controls for per-capita](https://github.com/datacommonsorg/website/issues/2917).
=> NL: misc fulfillment fixes

static/js/chart/draw.ts, static/js/components/tiles/bar_tile.tsx, web-components/docs/README.md, web-components/examples/example.html
This PR adds the ability to draw stacked and horizontal lollipop charts, and updates the docs/examples.
Examples (compare to bar version):
```
title="Median income by gender for counties in Alaska (horizontal, stacked, lollipop)"
comparisonVariables="Median_Income_Person Median_Income_Person_15OrMoreYears_Male_WithIncome Median_Income_Person_15OrMoreYears_Female_WithIncome"
place="geoId/02"
childPlaceType="County"
lollipop
horizontal
stacked
></datacommons-bar>
```
```
title="Median income by gender of select US states (stacked, lollipop)"
comparisonVariables="Median_Income_Person_15OrMoreYears_Male_WithIncome Median_Income_Person_15OrMoreYears_Female_WithIncome"
comparisonPlaces="geoId/01 geoId/02 geoId/04 geoId/05"
stacked
lollipop
></datacommons-bar> …
```
=> [Library] Stacked and Horizontal Lollipop Charts

static/js/constants/app/nl_interface_constants.ts
... to account for map tile no longer defaulting to a height of 200
=> Bumped nl default chart height to 200

nl_server/loader.py, nl_server/tests/embeddings_test.py
We are now exceeding the local cache default size (1Gb) which meant that the local development caching was not working. Fixing this issue by increasing the cache size.
This PR also ensures that if an Embeddings object was not found in the local cache (used in the server/embeddings_test.py) then the finetuned model is downloaded/loaded and associated with the embeddings index in a new Embeddings object.
=> [NL Interface] Fixing the local cache bug

nl_server/gcs.py, server/__init__.py, server/integration_tests/nlnext_test.py, server/integration_tests/test_data/demo2_cities_feb2023/query_7/chart_config.json, server/integration_tests/test_data/inappropriate_query/query_1/chart_config.json, server/integration_tests/test_data/place_detection_e2e_dc/query_6/debug_info.json, server/lib/config.py, server/lib/nl/common/bad_words.py, server/lib/nl/common/utils.py, server/lib/nl/detection/utils.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/size_across_entities.py, server/routes/nl/api.py, shared/lib/constants.py, shared/lib/gcs.py, shared/lib/utils.py, shared/tests/lib/utils_test.py, static/js/apps/nl_interface/query_result.tsx
* The initial bad-word list is located [here](https://storage.mtls.cloud.google.com/datcom-website-config/nl_bad_words.txt).
* Also, avoid school types from being considered as stop-words.  There were two other ripple effects to this change:
1. It also requires special-handling for fallback logic (to not say "schools in sunnyvale" => "sunnyvale")
2. It also requires not regressing the demo query [how big are public schools in sunnyvale]
Note: making the schools change also uncovered https://github.com/datacommonsorg/website/issues/2953.   This whole stop-word removal business needs streamlining!  Post fishfood maybe, and as part of fixing 2853.
Screenshot
=> NL: reject inappropriate words and improve schools

static/package-lock.json, static/package.json, static/src/server.ts
- have the endpoint /nodejs/chart serve a png instead of a svg
=> [node server] serve png instead of svg

server/integration_tests/nlnext_test.py, server/integration_tests/test_data/usa_map_types/query_3/chart_config.json, server/lib/nl/detection/place.py, server/routes/nl/api.py, shared/lib/utils.py, static/js/apps/nl_interface/app.tsx, static/js/apps/nl_interface/nl_options.tsx, static/js/apps/nl_interface/query_search.tsx
Also, remove the check-box from frontend.  The diffs are pretty clean (except for an underlying bug - https://github.com/datacommonsorg/website/issues/2962).
Finally, check for bad-words also from punctuation-removed query.
=> NL: Switch NL place-detector default to `dc`

server/lib/insights/chart_builder.py
Stop using `ranking_chart_multivar` which existed in a prior version but later got dropped.
=> Insights: fix brokenness

static/js/apps/insights/app.tsx, static/js/types/subject_page_types.ts
In a page with a combination of <topic, place>, user can issue a query with totally different place and topic. In this case, we don't want to store conflicting topic, place and query on the url. Instead, first call "detect" API to retrieve the desired topic and place, update the url hash (also erase the query). So the page would refresh based on the detected topic and place.
=> Solve conflict state from topic, place and query and only rely on <topic,place> from url hash

static/css/tools/visualization.scss, static/js/apps/visualization/app_context.tsx, static/js/apps/visualization/chart.tsx, static/js/apps/visualization/stat_var_selector.tsx, static/js/utils/app/timeline_utils.ts
- add per capita and log options
note: 
- the render chart function is getting a little out of hand. To make it easier to see the actual logic/code changes, I will do the clean up in a separate PR
=> [tools revamp] add per capita and log options

static/js/apps/visualization/app_context.tsx, static/js/apps/visualization/place_type_selector.tsx, static/js/apps/visualization/selected_options.tsx, static/js/apps/visualization/selector_wrapper.tsx, static/js/apps/visualization/stat_var_selector.tsx
- if there are no allowed child place types, render a message telling user to select a different place so that user doesn't get into a bad state
- update the place label for timeline vis type to say "plot places" instead of "plot places in"
=> [tools revamp] handle when there are no child places

static/js/shared/place_search_bar.tsx
- when new place search components are rendered, it adds another pac-container to the html. To get the current pac-container, we want the last one in the list, not the first
=> fix hardcoded place search

static/js/apps/visualization/selector_pane.tsx, static/js/apps/visualization/stat_var_selector.tsx
- change "continue" to "display"
- if going from map to scatter, make the selector header say "Select 1 more variable"
- on scatter or map, only show stat vars that are available for at least 10 places
=> [tools revamp] stat var selector updates

static/js/apps/explore/app.tsx, static/js/apps/explore/topics.json
Add the rest of the /explore/<vertical> pages to the new homepage.
More example links for each vertical, and the number of datapoints will be added in a followup PR.
https://github.com/datacommonsorg/website/assets/4034366/e149cff2-b568-4da7-847b-bc9bd73b5895">
=> Add landing pages for all verticals

server/integration_tests/test_data/demo_feb2023/query_1/chart_config.json, server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_comparison/chart_config.json, server/lib/insights/page_type/builder.py, server/lib/insights/related.py, server/lib/insights/topic.py, server/routes/insights/api.py, server/templates/insights.html, static/js/apps/insights/app.tsx, static/js/apps/insights/parent_breadcrumbs.tsx, static/js/shared/child_places.tsx
1.  Do not show a category for the display topic (i.e., Economy -> Economy)
2. Use the immediate sub-topic, rather than some further descendent sub-topics, as categories
3. Avoid showing "Places in X" when things are empty.
4. Instead of "Places in X Counties" say "Counties in X"
5. For parent places, say "Located in".... its weird to see "County in USA" for SC county when there's no state-level data.
6. Avoid showing "Statistics" (aka dc/topic/Root) in Broad topics.
7. Change the title from Insights -> Explore
=> Insights: Fix a bunch of minor things

server/__init__.py, server/integration_tests/test_data/fulfillment_api_statvars/chart_config.json, server/lib/fetch.py, server/lib/topic_cache.py, server/lib/util.py, server/services/datacommons.py, server/tests/routes/api/point_test.py, server/tests/routes/api/series_test.py, server/tests/routes/api/stats_test.py
Essentially undo https://github.com/datacommonsorg/website/pull/3072, and instead of API key plumb through the context.  That way, it will work on prod and local.
=> Revert previous mixer-api-key change and don't require it in prod

static/js/apps/nl_interface/debug_info.tsx, static/js/apps/nl_interface/query_result.tsx, static/js/components/ranking_unit.tsx, static/js/components/text_search_bar.tsx
2 digits gives inaccurate result as we use M, K (1000 step) as unit. Also it makes per capita value very weak (all 0.1 or all 0)
Fix some lint issues as well.
=> Use default 3 digits precision for ranking tile; Do not auto focus explore query box

server/integration_tests/explore_test.py, server/integration_tests/test_data/detection_api_basic/chart_config.json, server/integration_tests/test_data/detection_api_context/comparewithnevada/chart_config.json, server/integration_tests/test_data/detection_api_context/correlatewithasthma/chart_config.json, server/integration_tests/test_data/detection_api_context/countrieswithgreenhousegasemissions/chart_config.json, server/integration_tests/test_data/detection_api_context/medianincomeinsantaclaracountyandalamedacounty/chart_config.json, server/integration_tests/test_data/detection_api_statvars/correlatewithgdpofcalifornia/chart_config.json, server/integration_tests/test_data/detection_api_statvars/incomeininformationindustryinnevada/chart_config.json, server/lib/explore/detector.py, server/lib/nl/detection/detector.py, static/js/apps/explore/app.tsx
1. Make [Median income in Sunnyvale and San Francisco] be treated as comparison query
2. Infer world, without relying on context, for [countries with highest GHG] query
3. Allow for just [california] query to not return failure
4. Allow for server-side crashes to more gracefully throw error
5. Move School type detection hack from last night from `/fulfill` to `/detect` where it should belong
=> A few parity bugs for NL vs. Explore

packages/web-components/examples/all-charts.html, static/css/shared/story_chart.scss, static/js/components/tiles/chart_tile.tsx
Adds a slot to the web components to add an optional subtitle.
Note that based on the inline comment in `chart_tile.tsx`, it looks like intended behavior was for space for the header to remain even if a title is not provided. The CSS changes are to maintain this behavior, while avoiding awkward blank space between the title and subtitle.
Also confirmed these changes don't change the way our tiles are rendered in our Search/Chat interfaces.
Example:
```
title="Most populous states in the US"
parentPlace="country/USA"
childPlaceType="State"
variables="Count_Person"
maxPlaces="15"
>
<p slot="subtitle" style="text-align:center; color: grey; font-size: 0.85rem">(top 15 places)</p>  
</datacommons-bar>
```
=> [library] Add subtitle slot to web components

packages/web-components/examples/all-charts.html, static/css/shared/_tiles.scss, static/js/components/tiles/chart_footer.tsx, static/js/components/tiles/chart_tile.tsx
Add the ability for users to add a custom source attribution as a chart footer, replacing our default "Data from <domain>" text.
More concretely, this adds a "footer" slot to our web components, so users can use syntax like this:
```
<datacommons-pie
title="California Farms by Size"
place="geoId/06"
variables="Count_Farm_1To9.9Acre Count_Farm_10To49.9Acre Count_Farm_50To179Acre Count_Farm_180To499Acre Count_Farm_500To999Acre Count_1000OnwardsAcre"
>
<div slot="footer">
<ul>
<li>custom footer item 1</li>
<li>custom footer item 2</li>
</ul>
</div>
</datacommons-pie>
```
To create a chart like:
Another example, for what happens when the provided footer is very long:
```
title="Most populous states in the US"
parentPlace="country/USA"
childPlaceType="State" …
```
=> [library] Add optional custom footer with slots

server/integration_tests/explore_test.py, server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_comparison/chart_config.json, server/integration_tests/test_data/fulfillment_api_correlation/chart_config.json, server/integration_tests/test_data/fulfillment_api_expansion/chart_config.json, server/integration_tests/test_data/fulfillment_api_explore_more/chart_config.json, server/integration_tests/test_data/fulfillment_api_sdg/chart_config.json, server/integration_tests/test_data/fulfillment_api_statvars/chart_config.json, server/lib/explore/extension.py, server/lib/explore/fulfiller.py, server/lib/explore/params.py, server/lib/explore/related.py, static/css/explore.scss, static/js/apps/explore/app.tsx, static/js/types/subject_page_types.ts
This is enabled by `em=`.
The frontend needs more work.  For now just listing the URLs at the bottom of the charts for debugging.
=> Implement Explore More for single-SV charts

deploy/gke/autopush.yaml, deploy/gke/dev.yaml, deploy/gke/staging.yaml, deploy/helm_charts/envs/autopush.yaml, docs/developer_guide.md
us-west1 is not co-located with the BT cache, and could have longer mixer->web server latency.
it also makes deployment longer as the deployment need to happen sequentially for two clusters.
=> Do not deploy to us-west1 for dev and autopush

static/js/components/tiles/highlight_tile.tsx
=> [highlight tile] add space between number and unit

static/js/chart/draw_bar.ts, static/js/chart/types.ts, static/js/components/tiles/bar_tile.tsx
This PR allows setting `sort="ascending"` and `sort="descending"` to sort bars/lollipops by variable when there is only 1 place.
Currently, we only sort by place, so when a single place but multiple variables are passed to the bar tile, no sorting happens even though there are multiple bars. With this change, we'll sort by variable when there is only 1 place available. This allows `sort` to behave more intuitively for users.
Screenshots:
=> Allow bar tiles to sort by variable when there is only one place

static/js/components/tiles/highlight_tile.tsx
- remove the space between number and % when the unit starts with %
=> [highlight tile] fix units that start with %

server/templates/tools/download.html, server/templates/tools/map.html, server/templates/tools/stat_var.html, server/templates/tools/timeline_bulk_download.html
After the homepage revamp, the sidebar icons are not rendering properly on some of the pages. This PR is a quick fix to re-add the necessary stylesheets to those pages.
Before:
After:
=> [Custom DC] Quick fix for icons misrendering

server/integration_tests/test_data/demo2_cities_feb2023/query_2/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_7/chart_config.json, server/integration_tests/test_data/demo_fallback/query_3/chart_config.json, server/integration_tests/test_data/demo_fallback/query_4/chart_config.json, server/integration_tests/test_data/demo_fallback/query_5/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_4/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_6/chart_config.json, server/integration_tests/test_data/international/query_1/chart_config.json, server/integration_tests/test_data/international/query_3/chart_config.json, server/integration_tests/test_data/international/query_4/chart_config.json, server/integration_tests/test_data/sdg/query_1/chart_config.json, server/integration_tests/test_data/sdg/query_3/chart_config.json, server/integration_tests/test_data/textbox_sample/query_1/chart_config.json, server/integration_tests/test_data/usa_map_types/query_2/chart_config.json, server/integration_tests/test_data/usa_map_types/query_3/chart_config.json, server/lib/explore/fulfiller.py, server/lib/nl/common/utterance.py, server/lib/nl/config_builder/base.py, server/lib/nl/config_builder/builder.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/basic.py, server/lib/nl/fulfillment/existence.py, server/lib/nl/fulfillment/fulfiller.py, server/lib/nl/fulfillment/handlers.py, server/lib/nl/fulfillment/ranking_across_places.py, server/lib/nl/fulfillment/simple.py, server/lib/nl/fulfillment/size_across_entities.py, server/lib/nl/fulfillment/types.py, server/tests/lib/nl/test_utterance.py
This change adds a new fulfillment handler called "basic" which encompasses:
* simple
* containedin
* ranking_across_places
* ranking_across_vars
(the names need some tweaking, like what's basic vs. simple, but that's in followup)
The "basic" handler, depending on whether it is explore vs. chat, will route to one or more of these components appropriately.
Also, for every single-line timeline (in both modes), add a highlight, and demote a single-bar barchart to highlight.
IMPORTANT NOTE:  This change makes all of the existence checks to require "is it single point", so that makes things a LOT more expensive, esp for [What are the projected temperature extremes across california].
REGRESSION NOTES:
1.  After this change, chat will show a bunch more charts.  As an example, for query [asthma …
=> Add Explore Chart Layout, based on a flag

server/integration_tests/test_data/demo_fallback/query_3/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_2/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_4/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_6/chart_config.json, server/integration_tests/test_data/international/query_5/chart_config.json, server/integration_tests/test_data/international/query_6/chart_config.json, server/lib/explore/page_type/builder.py, server/lib/nl/common/rank_utils.py, server/lib/nl/config_builder/bar.py, server/lib/nl/config_builder/builder.py, server/lib/nl/fulfillment/basic.py, server/lib/nl/fulfillment/fulfiller.py, server/lib/nl/fulfillment/ranking_across_vars.py, server/lib/nl/fulfillment/types.py, server/tests/lib/nl/fulfiller_test.py
This does two main things:
1.  Enables event charts in Explore, and blends in SV stuff along with event charts.
2.  Drops custom ranking logic of vars across bar chart and relies on the bar-chart-spec option Julia added.
=> Parity: Enable event charts and ranking-across-vars

static/css/nl_interface.scss, static/js/components/subject_page/block.tsx, static/js/components/subject_page/column.tsx, static/js/constants/app/nl_interface_constants.ts, static/js/constants/subject_page_constants.ts
With the recent layout change, there is only one tile per column. So the expando should be at block level instead of column level now.
=> Enable expando at block level

run_test.sh, server/routes/shared_api/choropleth.py, server/webdriver/screenshot/local/page.json, server/webdriver/screenshot/local/test_run.py, server/webdriver/screenshot/remote/main.py, server/webdriver/screenshot/runner.py
* Right now facilities fetch parent place via place info cache. In USA map, this involves around 10K facilities and result in server error. Use regular name instead.
* Refactor the screenshot a bit to allow parallel run.
=> Fix a performance issue for fetching map point names; Run screenshot test in parallel

static/js/apps/explore/app.tsx, static/js/apps/explore/result_header_section.tsx
- don't use context when fetching data for topic + place
- filter out empty topic names in the relevant topics section in the header
- autopush: https://screenshot.googleplex.com/6mYfHPZqXeTxY54
- new: https://screenshot.googleplex.com/6kWSd6cXkEXfdDs
=> [explore] fix bugs

server/integration_tests/test_data/e2e_electrification_demo/howdothesecountriescomparewiththeusandgermany/chart_config.json, server/integration_tests/test_data/e2e_electrification_demo/howhaspovertyreducedintheseplaces/chart_config.json, server/integration_tests/test_data/e2e_electrification_demo/howhasthegdpgrown/chart_config.json, server/integration_tests/test_data/e2e_electrification_demo/whichcountriesinafricahavehadthegreatestincreaseinelectricityaccess/chart_config.json, server/integration_tests/test_data/e2e_india_demo/howdoestheliteracyratecompare/chart_config.json, server/integration_tests/test_data/e2e_india_demo/howhasthenumberofsecondaryschoolsincreased/chart_config.json, server/integration_tests/test_data/e2e_india_demo/howhavethewageschangedovertimeinthesestates/chart_config.json, server/integration_tests/test_data/e2e_india_demo/howmuchhasinfantmortalityreduced/chart_config.json, server/lib/nl/common/rank_utils.py, server/lib/nl/config_builder/builder.py, server/lib/nl/config_builder/timeline.py, server/lib/nl/fulfillment/ranking_across_places.py, server/lib/nl/fulfillment/time_delta_across_places.py, server/lib/nl/fulfillment/time_delta_across_vars.py, static/js/constants/app/nl_interface_constants.ts
1. Demo queries hack to threshold country population to 10M to ensure Kenya and Ghana show prominently ([screencast](https://screencast.googleplex.com/cast/NTMxNzk3OTM4NTM2NDQ4MHxjZjllYjJkYS00Yw)).
2. Disable the Show More feature which still apparently seems buggy.
3. Add support for multi-place timeline (see screenshot below)
=> NL: Add demo queries hack, disable Show More, implement multi-place timeline

server/config/subject_page.proto, static/js/components/subject_page/stat_var_provider.ts, static/js/shared/types.ts
Adds a `noPerCapita` attribute to statVarSpecs, which when set, will prevent the per capita toggle on subject pages from dividing their value by population. This is helpful for (1) allowing the per capita toggle to only change one of the axes on a scatter plot (by preventing the change on an axis that doesn't need it) and (2) preventing per capita on variables that are already per capita.
Note, this still needs the following backend changes to show up in explore results:
(1) We should enable the per capita toggle on comparison pages with scatter plots
(2) Fulfillment needs to emit "noPerCapita = true" in the statVarSpecs we wish to prevent from toggling per capita for.
=> Add setting to prevent per-capita toggle from affecting some variables

server/integration_tests/test_data/demo2_cities_feb2023/query_3/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_4/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_8/chart_config.json, server/integration_tests/test_data/demo_climatetrace/query_1/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_1/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_4/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_6/chart_config.json, server/integration_tests/test_data/e2e_edge_cases/povertyincaliforniaandcalifornia/chart_config.json, server/integration_tests/test_data/e2e_electrification_demo/howdothesecountriescomparewiththeusandgermany/chart_config.json, server/integration_tests/test_data/e2e_india_demo/whichstatesinindiahavethehighestpovertylevelspercapita/chart_config.json, server/integration_tests/test_data/international/query_3/chart_config.json, server/integration_tests/test_data/international/query_5/chart_config.json, server/integration_tests/test_data/sdg/query_1/chart_config.json, server/integration_tests/test_data/sdg/query_3/chart_config.json, server/lib/explore/topic.py, server/lib/nl/detection/detector.py, server/lib/nl/fulfillment/basic.py, server/lib/nl/fulfillment/containedin.py, server/lib/nl/fulfillment/ranking_across_places.py, server/lib/nl/fulfillment/simple.py
1. Prefer to show timeline/bar before ranking/map even if query had ranking, and only when the user asks for place-type show ranking+map on top.  That way, [top jobs in Nevada] will show the top jobs bar chart and [top jobs in Nevada Counties] will show per-county SVs on top.
2.  Fix a few deepcopy bugs causing [top jobs in Placer County] to regress.
3. Open more topics.  I saw that often for poverty stuff dc/topic/SDG_x and others come on top, so opening more topics should help with richer results.
4. Avoid escaping query before passing into embeddings index.  This was found while triaging [Ratio of people in Denver who have an associate's degree] which doesn't match the right SV on top.
=> NL: Fix a few bugs

server/app_env/dev.py, server/app_env/unsdg.py
The SecretManager setups for palm-api-key exist in both:
* https://pantheon.corp.google.com/security/secret-manager/secret/palm-api-key/versions?mods=-monitoring_api_staging&project=datcom-recon-autopush
* https://pantheon.corp.google.com/security/secret-manager/secret/palm-api-key/versions?mods=-monitoring_api_staging&project=datcom-website-dev
=> Enable PaLM on dev and unsdg

run_test.sh, server/integration_tests/test_data/e2e_answer_places/whatistheemissionsinthesecounties/chart_config.json, server/webdriver/screenshot/remote/autopush.datacommons.org/page.json, server/webdriver/screenshot/remote/datacommons.org/page.json, server/webdriver/screenshot/remote/dev.datacommons.org/page.json, static/js/apps/screenshot/app.tsx
All main DC site uses the same page.json as /local, Here created symbolic links.
Now there is two saving issue:
1. Some images are saved in the wrong name
2. Some images are corrupted and not fully saved.
These are very likely from the pytest parallel run. Disabling that.
=> Add prod/autopush/dev as remote screenshot target; Try to fix image corruption issue

server/integration_tests/test_data/demo2_cities_feb2023/query_3/chart_config.json, server/integration_tests/test_data/demo2_cities_feb2023/query_4/chart_config.json, server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/integration_tests/test_data/fulfillment_api_comparison/chart_config.json, server/lib/nl/common/constants.py
Add an override for the title and description for the variable `dc/e9gftzl2hm8h9` to make its meaning more clear in explore results.
Before:
After:
=> Override descriptions for commute time variable

server/webdriver/tests/standalone/sanity.py
* Prior to this change, running sanity on linux workstations took ~3 hours.
* With this change, it takes ~30 mins.
=> Speed up sanity test on linux workstations.

static/css/shared/_subject_page.scss, static/css/shared/item_list.scss
- fix left/right nudging by decreasing the min width of tiles
- fix list items being cut off by using a combination of padding + text-indent
regular desktop:
mobile:
[screen-recording - 2023-09-05T170005.795.webm](https://github.com/datacommonsorg/website/assets/69875368/4dfd2802-2a51-47bb-bb03-4f7ff9229767)
=> [explore] mobile fixes

static/js/apps/explore/success_result.tsx
This is so that we can test SDG index independently on our site with context.
=> Show search box for SDG on DC site

experimental/sdg-tracker/src/components/shared/components.tsx
Quick fix for breadcrumbs overflowing the headers on mobile. We should go back and clean this up after demos are done.
Screenshot:
=> Quick fix: cut off breadcrumbs that are too long with overflow: hidden

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, experimental/sdg-tracker/src/components/home/GoalSection.tsx, experimental/sdg-tracker/src/components/home/PlaceSection.tsx, experimental/sdg-tracker/src/components/search/Search.tsx, experimental/sdg-tracker/src/components/shared/AppSidebar.tsx, experimental/sdg-tracker/src/components/shared/components.tsx, experimental/sdg-tracker/src/components/shared/goals/AllGoalsOverview.tsx, experimental/sdg-tracker/src/components/shared/goals/GoalOverview.tsx
All classes start with the prefix `-dc-`
```
-dc-place-search
-dc-goal-item-all
-dc-goal-item-1
-dc-goal-item-2
-dc-goal-item-3
...
-dc-goal-item-17
-dc-search-bar
```
```
-dc-sidebar-submenu
-dc-sidebar-submenu-<dcid>
-dc-sidebar-menu-item
-dc-sidebar-menu-item-<dcid>
```
```
-dc-place-search
-dc-goal-overview (all goal overviews tagged with this)
-dc-goal-overview-all
-dc-goal-overview-1
-dc-goal-overview-2
...
-dc-goal-overview-17
-dc-target-header
-dc-target-header-target-1.1.1
-dc-chart-tile
-dc-chart-tile-BAR
-dc-chart-tile-MAP
-dc-chart-tile-HIGHLIGHT
-dc-chart-tile-BAR
-dc-chart-tile-LINE
```
```
-dc-search-bar
-dc-search-example
```
=> [sdg] Added class names to sdg components for sanity check tests

server/integration_tests/test_data/e2e_electrification_demo/whichcountriesinafricahavehadthegreatestincreaseinelectricityaccess/chart_config.json, server/lib/nl/common/bad_words.py, server/tests/lib/nl/bad_words_test.py, server/tests/test_data/bad_words.txt
1.  Support phrases
2. Support multi-word matching, where every word has to appear in the query (in any order), with `:` separation.
3. Add tests and prod file validation
Note: Using regex as input might be very flexible but since it is easy to get wrong or eye-ball, I chose this simpler config of just `:` separated values.
=> NL: Improve bad-words matching

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, packages/web-components/docs/components/line.md, packages/web-components/examples/all-charts.html, static/js/components/tiles/line_tile.tsx, static/js/utils/tile_utils.tsx, static/library/line_chart_component.ts
- do this by adding a new regex property to the line web component that allows processing of stat var names using regex.
=> [sdg] Use text in [ ] for line chart legend labels 

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, experimental/sdg-tracker/src/components/shared/components.tsx
This PR:
1. Only show goal overviews and indicator blurbs/infographics if the page has the World as the place. The content of those overviews/blurbs is written only for the world, so showing them on country pages/search results does not make sense.
2. Makes the background color of infographics white
With this change...
=> [UN SDG Tracker] Only show goal overviews and indicator blurbs for the world + make infographic backgrounds white

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx
Adds filtering logic so that only charts related to the selected topic get shown. This prevents charts for goal 1 showing up when clicking goal 11 on the sidebar (currently happens because some statvars are part of multiple goals).
Screenshot:
=> [UN SDG Tracker] Filter charts by topic

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, experimental/sdg-tracker/src/components/shared/components.tsx
Adds a disclaimer to the page about map borders, and an asterisk at the end of map titles
Example of a page scrolled all the way down:
See asterisk in map chart title and disclaimer at the bottom.
=> [UN SDG tracker] Add asterisk to maps and show disclaimer at bottom

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx
Sorts the goals/targets/indicators so that the goals, cards, and tiles show up in lexical order by indicator number.
Before:
After:
=> [UN SDG] Bug fix: show target cards in order

static/js/chart/draw_d3_map.ts
Updates the projection scaling for maps of Europe so that the borders are no longer cut off when the chart is much wider than its height.
Before:
After:
What Map tool now looks like:
What explore tiles now look like:
=> Fix maps of Europe being cut-off

server/integration_tests/explore_test.py, server/integration_tests/test_data/demo_fallback/query_3/chart_config.json, server/integration_tests/test_data/e2e_fallbacks/autotheftsintractsofsantaclaracounty/chart_config.json, server/integration_tests/test_data/e2e_fallbacks/autotheftsintractsofsunnyvale/chart_config.json, server/integration_tests/test_data/e2e_fallbacks/lifeexpectancyinuscounties/chart_config.json, server/integration_tests/test_data/e2e_fallbacks/tamilspeakersinuscounties/chart_config.json, server/lib/explore/related.py, server/lib/nl/fulfillment/base.py, server/lib/nl/fulfillment/basic.py, server/lib/nl/fulfillment/types.py
Today, we do not have any message for queries with place-types like:
- [life expectancy in US counties]
- [tamil speakers in US counties]
- [auto thefts in tracts of sunnyvale]
When we don't have any data at the requested place-type.  Because, post Explore-style rewrite, contained-in and simple were clubbed into a single "query handler".  That is, this `basic` query handler produces some charts (at US/sunnyvale level but not maps), so fallback, which works at query-handler granularity, does not kick in.  And unless fallback kicks in, we don't report fallback message.
Address this by having a custom child-type fulfillment tracker for `basic`.  And when that tells us, report fallback message.
Upcoming PR will actually do further place-type fallback.
**Screenshots**
=> PR1:  Improve messaging on place-type fallbacks

experimental/sdg-tracker/src/components/countries/CountriesContent.tsx, experimental/sdg-tracker/src/components/shared/components.tsx
Some charts were not showing up in search results because of filtering by `mainTopic`.
This PR changes the search results pages:
* results are all in one card with all tiles displayed
* tiles are no longer ordered by goal/target/indicator
* target headings have been taken out
* Adds topic name to the header behind the place name using mainTopics (this approach matches what's currently used on our explore pages)
=> [UN SDG] Fix missing charts in search results

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/countries/Countries.tsx, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/AppHeader.tsx, experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/components.tsx
* `Countries / Regions` to `Countries / Areas`.
* Default to Africa instead of Ireland.
* Alphabetize country / area names in dropdown.
[sdg-countries.webm](https://github.com/datacommonsorg/website/assets/1221814/20c2cebc-7b48-4a83-98cc-f43762b5ef7f)
=> Implement minor country related changes.

static/css/shared/_tiles.scss, static/js/components/subject_page/block.tsx, static/js/components/subject_page/category.tsx, static/js/components/subject_page/disaster_event_block.tsx, static/js/components/tiles/bar_tile.tsx, static/js/components/tiles/chart_footer.tsx, static/js/components/tiles/chart_tile.tsx, static/js/components/tiles/donut_tile.tsx, static/js/components/tiles/gauge_tile.tsx, static/js/components/tiles/line_tile.tsx, static/js/components/tiles/map_tile.tsx, static/js/components/tiles/scatter_tile.tsx, static/library/component_attributes.ts
This PR:
* Displays the block footnote inline in tile footers on the explore pages.
* Removes unused footnote props from disaster event tiles (footnotes are displayed as part of the block container instead for those pages)
=> Add footnotes to tiles in main DC

experimental/sdg-tracker-un/frontend-tester/UNSD-Website-skeleton/UNSD.Website/ClientApp/src/templates/DataCommons/components/shared/components.tsx
=> [sdg] added rounded corners back to search bar

server/integration_tests/explore_test.py, server/integration_tests/nl_test.py, server/integration_tests/test_data/demo_climatetrace/query_1/chart_config.json, server/integration_tests/test_data/detection_api_basic/chart_config.json, server/integration_tests/test_data/e2e_superlatives/listschoolsinsunnyvale/chart_config.json, server/integration_tests/test_data/e2e_superlatives/richestcountiesincalifornia/chart_config.json, server/integration_tests/test_data/fulfillment_api_basic/chart_config.json, server/lib/explore/params.py, server/lib/nl/common/utterance.py, server/lib/nl/detection/palm_api.py, server/lib/nl/detection/utils.py, server/routes/explore/api.py, server/routes/nl/api.py, server/routes/nl/helpers.py, static/js/apps/explore/app.tsx, static/js/constants/app/explore_constants.ts
This PR makes 3 fixes:
1. Logs to BT when we abort a query (for bad-words or otherwise).
2. Supports `explore` to specify a url param `test=<type>`, which gets plumbed into the response which is logged.
3. Drops a few signal words in LLM response to avoid false positive blocks.
To validate (1), I ran tests locally and was able to find it in BT (see screenshot)
=> NL: Improve logging, etc

deploy/helm_charts/envs/stanford.yaml
Changed the stanford.yaml file to include the Center for Ocean Solutions' first dataset in future deployments.
=> Stanford - adding first dataset to yaml file

server/lib/fetch.py
API results:
[non-place-descendants.webm](https://github.com/datacommonsorg/website/assets/1221814/03d54559-00aa-45b8-b97e-9ba040a11446)
With this change, we can now do scatter plots for non-place entities:
=> Add support for fetching descendant names for non-place entities.

static/js/utils/tile_utils.tsx
- fix bug when svSpec.scaling was undefined, we were trying to multiply undefined by 100 for per capita
=> [tiles] fix per capita scaling bug

server/webdriver/screenshot/runner.py, static/js/components/tiles/sv_ranking_units.tsx
Removed duplicated ASYNC_ELEMENT_CLASS tagging, which exist twice in ranking tile.
=> Increase element wait timeout for screenshot tests

static/js/components/subject_page/block.tsx, static/js/utils/tile_utils.tsx, static/nodejs_server/bar_tile.ts, static/nodejs_server/line_tile.ts
url used to get this: http://localhost:3030/nodejs/chart-info?config={%22comparisonPlaces%22:[%22self%22,%22geoId/06%22],%22title%22:%22Prevalence%20of%20Health%20Conditions%20in%20Placer%20County%20(${date})%22,%22type%22:%22LINE%22}&place=geoId/06061&svSpec=[{%22name%22:%22Chronic%20Kidney%20Disease%22,%22statVar%22:%22Percent_Person_WithChronicKidneyDisease%22,%22unit%22:%22%25%22},{%22name%22:%22Chronic%20Obstructive%20Pulmonary%20Disease%22,%22statVar%22:%22Percent_Person_WithChronicObstructivePulmonaryDisease%22,%22unit%22:%22%25%22},{%22name%22:%22Coronary%20Heart%20Disease%22,%22statVar%22:%22Percent_Person_WithCoronaryHeartDisease%22,%22unit%22:%22%25%22},{%22name%22:%22Diabetes%22,%22statVar%22:%22Percent_Person_WithDiabetes%22,%22unit%22:%22%25%22}]
=> [node server] enable multiple places for line chart

deploy/helm_charts/envs/dev.yaml, deploy/helm_charts/envs/magic_eye.yaml
DEV: Reduce web server replicas as launch as complete; Increase NodeJs replicas for large scale offline charts generation.
MagicEye: Reduce SVG replicas as it's the least needed. Update Bigtable version. Note this cache substantially increased the SVG in-memory cache built time due to the large amount of stat vars added.
=> Update dev and magiceye replicas

static/js/browser/out_arc_section.tsx
This change hides the `geoJsonCoordinateUN` and `geoJsonCoordinateUNDP<N>` properties in the graph browser, so that their values don't overwhelm the page.
=> Remove geoJsonCoordinateUN* properties from graph browser

deploy/nl/embeddings.yaml, tools/nl/embeddings/data/curated_input/sheets_svs.csv, tools/nl/embeddings/data/preindex/medium/sv_descriptions.csv
diff_report: https://gist.githubusercontent.com/chejennifer/46aba5cb393e634774afff3e8829349c/raw/c6c89983c3a346df32ea587953c52294f01c3068/diff_report.html
Note: not sure if we want ALL the veterans topics to be showing up under veteran unemployment ..?
=> add veterans topic to index

server/integration_tests/test_data/demo_climatetrace/query_1/chart_config.json, server/integration_tests/test_data/e2e_default_place/howtoearnmoneyonlinewithoutinvestment/chart_config.json, server/integration_tests/test_data/e2e_default_place/whatdoesadietfordiabeteslooklike/chart_config.json, server/integration_tests/test_data/sdg/query_2/chart_config.json, server/lib/nl/common/commentary.py, server/lib/nl/common/constants.py, server/lib/nl/detection/context.py, server/routes/nl/helpers.py
This fixes the issue where `Earth` would show up as the title instead of World.
Also, avoid logging test queries.
=> NL: Fix Earth title bug and don't log test queries

build/nodejs_server/Dockerfile
* Added docker image dependencies to allow building on M1 mac
* Updated build logic to copy over and build entire web components folder before installing dependencies in `website/static`
=> fixed nodejs docker image build error

nl_server/__init__.py, nl_server/config.py, nl_server/embeddings.py, nl_server/embeddings_store.py, nl_server/loader.py, nl_server/routes.py, nl_server/tests/embeddings_test.py, nl_server/tests/ner_place_model_test.py, nl_server/tests/verb_test.py
This is to make follow on custom DC specific changes cleaner.
There is no intentional logic change other than using a single cache entry (instead of one per index) in test environment.
A key simplification is to more directly rely on the embeddings name to extract the base / tuned-model (see `config._parse()`) instead of the current code which uses `models.yaml` and also relies on the naming partially.
=> Refactor NL Server bootstrap code for readability

packages/web-components/src/main.ts, server/webdriver/shared.py, static/library/index.ts
Updated `charts_rendered` helper to wait for the web components as well as charts. The original check wasn't working for web components because selenium's element selectors can't reach into the web component shadow root
=> Added support for web components in screenshot test

build/ci/cloudbuild.npm.yaml, static/js/components/subject_page/block.tsx, static/js/components/subject_page/category.tsx, static/js/components/tiles/bar_tile.tsx, static/js/components/tiles/donut_tile.tsx, static/js/components/tiles/line_tile.tsx, static/js/utils/subject_page_utils.ts, static/library/bar_component.ts, static/library/slider_component.ts, static/library/text_component.ts
The `website-pull-request-npm` can pass even when lint tests fail, causing some badly formatted code to be successfully merged. This PR fixes the test, and corrects the files with lint issues.
Root cause was that `website-pull-request-npm` did not exit when the lint test fails and instead silently proceeded, passing if client tests passed. Added `set -e` so that bash exits on a test failure.
=> Fix Lint Tests

static/js/components/tiles/scatter_tile.tsx
**Problem:** The "See per-capita" toggle fails on some scatter plots because the scatter tile sends out a duplicate API call for "Count_Person", one for each axis, which can overwhelm mixer when making concurrent fetches because there are too many places to fetch data for.
**Fix:** Remove duplicate denom dcids in the data fetch.
**Testing:** Verified changes locally on explore pages and scatter plot explorer.
| Per Capita Off | Per Capita On |
--- | --- |
| ![Screenshot 2023-10-31 at 11 20 35 AM](https://github.com/datacommonsorg/website/assets/4034366/ae964ff5-5a20-4f9c-a5f4-a3cf155968f6) |  ![Screenshot 2023-10-31 at 11 29 00 AM](https://github.com/datacommonsorg/website/assets/4034366/47c344c2-c63e-4540-95fd-c412d57c87ff) |
=> Bug quick fix: Fix per-capita toggle for US counties scatter plots

static/nodejs_server/bar_tile.ts, static/nodejs_server/line_tile.ts, static/nodejs_server/map_tile.ts, static/nodejs_server/ranking_tile.ts, static/nodejs_server/types.ts, static/src/server.ts
- add `unit` field for all charts
- add `highlight` field for single line line charts
- only return first 3 charts (use `&allCharts=1` to show all charts)
updated response:
https://paste.googleplex.com/5876459951357952
updated response w/ `&all=1`:
https://paste.googleplex.com/5318110008573952
=> [nodejs] update query response

packages/web-components/package-lock.json, static/library/ranking_component.ts, static/package-lock.json
Reverted change from https://github.com/datacommonsorg/website/pull/3712/files#diff-c2a36ba6cf48741c18a3d860061b77d19b8245d55643936f5dc778c210b573daL164
that was preventing ranking component from rendering
Fixes: <img width="1249" alt="Screenshot 2023-11-08 at 7 46 30 AM" src="https://github.com/datacommonsorg/website/assets/13766/7dde47d7-d308-4b67-9b90-f88b0bd72311">
=> Fixed ranking component rendering bug. Updated web components package-lock version

gke/cron_testing_job.yaml.tpl
- increase history limit to save the logs of more runs
=> [testing cronjob] increase history limit

server/integration_tests/explore_test.py, server/integration_tests/test_data/explore_strict_default_place/howmanydaybeijingsnowindecember/chart_config.json, server/lib/nl/common/debug_utils.py, server/lib/nl/detection/heuristic_detector.py, server/lib/nl/detection/types.py, server/lib/nl/fulfillment/fulfiller.py, shared/lib/constants.py, shared/lib/utils.py, shared/tests/lib/utils_test.py
In strict mode, when we know we don't specially handle certain temporal words (like december), better to to not continue processing.
=> In strict mode, bail on finding temporal words

server/webdriver/tests/scatter_test.py, server/webdriver/tests/vis_scatter_test.py
Fix is https://github.com/datacommonsorg/mixer/pull/1305
=> Enable scatter webdriver tests now that mixer place info performance issue is fixed

docs/iap.md, gke/README.md, gke/setup_config_cluster.sh, gke/update_config_cluster.sh, gke/website_mcs.yaml, gke/website_nodejs_mcs.yaml
Update multi cluster setup scripts to have control over whether or not nodejs service gets added in the setup
- new "-n" flag to denote whether or not to set up the nodejs service
- split the yaml definitions for the nodejs service and website service into their own separate yaml files
=> [nodejs] Update multi-cluster setup

server/templates/place.html, static/css/place/place.scss, static/js/place/place.ts, static/js/shared/ga_events.ts
As followup to https://github.com/datacommonsorg/website/pull/3825, this PR replaces the tiny "Graph Browser" link on the place pages with the NL search bar on top of the page, following the design set in our figma mocks.
Updating the UI treatment for switching places, tabbing sections, and chart styling will come in future PRs.
Before:
After:
=> [Place Page] Add nl search bar to place page

server/integration_tests/test_data/demo_feb2023/query_2/chart_config.json, server/integration_tests/test_data/e2e_single_date/lifeexpectancyinusstatesin2018/chart_config.json, server/integration_tests/test_data/e2e_single_date/populationintheusinthelastyear/chart_config.json, server/lib/nl/common/utils.py, server/lib/nl/config_builder/builder.py, server/lib/nl/config_builder/timeline.py, server/lib/nl/fulfillment/existence.py, server/lib/nl/fulfillment/types.py
Fix a problem with date handling where only a specific series has data for specified date, but the LINE tile may use a different series. This fix makes NL pass the facet id of the series that we want used (if it matters) to the config.
before: https://screenshot.googleplex.com/4LGnpRH3x9FsULs (notice that the line chart starts after 2001)
after: https://screenshot.googleplex.com/9cgjkFrcUCEEtcN
=> [nl] Use facetId in timeline config

server/routes/event/html.py, server/tests/nodejs_e2e_test.py, server/tests/test_data/nodejs_query/disaster/screenshot.json, server/tests/test_data/nodejs_query/rank_top_only/screenshot.json, server/tests/test_data/nodejs_query/scatter/screenshot.json, server/tests/test_data/nodejs_query/scatter_non_bard/screenshot.json, server/tests/test_data/nodejs_query/timeline/screenshot.json, server/tests/test_data/nodejs_query/timeline_all/screenshot.json, server/webdriver/tests/event_page_test.py
update goldens for latest nodejs response update (from last week) where:
- scatter plots re-enabled
- ranking table can show top ... bottoms ranks
Also:
- fix webdriver tests by updating the events tested for on the events page are not autogenerated events (because autogenerated events may sometimes be modified). 
- update event page to handle when no location found
=> Fix repo tests

server/integration_tests/explore_test.py, server/integration_tests/test_data/explore_strict_multi_var/chart_config.json, server/integration_tests/test_data/fulfillment_api_sdg_specialvars/chart_config.json, server/lib/nl/fulfillment/base.py
When there are no svs detected because the scores were too low, we should still try to populate charts for multi sv candidates (if there are any detected)
This fixes the empty result in strict mode for the query 'Does obesity correlate with lack of sleep in US counties' (it returns results in regular mode).
Example: nodejs/query?q=Does%20obesity%20correlate%20with%20lack%20of%20sleep%20in%20US%20counties
currently: empty result
with this change: https://paste.googleplex.com/5581611641339904
=> [nl] Allow fulfillment when there are only multi svs detected

static/js/utils/stat_metadata_utils.ts
scaling factor can be 100, 100.0, 100.00, etc. We should set the unit to % for all variations.
=> Set unit to % for all variations where scaling factor equals 100

custom_dc/README.md
Docker cache images and prevents users to use the latest docker image. This PR fixed that.
=> Use docker run --pull=always in custom DC documentation

static/js/chart/draw_bar.ts, static/js/chart/draw_line.ts, static/js/chart/draw_scatter.ts, static/js/chart/draw_utils.ts, static/js/chart/types.ts, static/js/components/tiles/bar_tile.tsx, static/js/components/tiles/line_tile.tsx, static/js/components/tiles/scatter_tile.tsx, static/nodejs_server/bar_tile.ts, static/nodejs_server/line_tile.ts, static/nodejs_server/scatter_tile.ts
Note: Ideally would like to use larger font for the chart title, but the hack for getting bbox to work on node server depends on the text within a chart to be all the same size ..
=> [nodejs] Add chart titles as part of returned image

server/routes/shared_api/facets.py
This fixes the source selector for the timelines on vis tool (https://screenshot.googleplex.com/kX3735zMTDF7uFR). The problem was that the endpoint for fetching the facets enforced strict slashes, but the client was not passing in a slash and so the client was being redirected to a location it could not access.
=> [vis tool] fix source selector on timeline

server/routes/place/html.py, server/templates/place.html
Adds a [canonical link](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#rel-canonical-link-method) to the header of our place pages, following the [guidance to consolidate duplicate URLs](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls). This change will help us fix "Duplicate without user-selected canonical" indexing errors. The canonical urls were chosen to match the entries in our sitemaps.
=> [Place Page SEO] Add canonical link to header

server/integration_tests/test_data/e2e_answer_places/howabouttheuninsuredpopulation/chart_config.json, server/integration_tests/test_data/fulfillment_api_comparison/chart_config.json, server/integration_tests/test_data/fulfillment_api_correlation/chart_config.json, server/webdriver/shared.py, server/webdriver/tests/vis_map_test.py, server/webdriver/tests/vis_scatter_test.py, server/webdriver/tests/vis_timeline_test.py
Fix webdriver tests and improve source selector checking by:
- picking the source by source name
- checking that the source has in fact changed in the chart
Also update NL goldens. The diffs all have to do with new commute data that was recently imported which caused svgs to get dropped from consideration when fetching related topics.
=> fix webdriver tests

build/python_node_go_protoc_envoy/Dockerfile, build/python_node_go_protoc_envoy/cloudbuild.yaml
* Applied some of the [best practices][practices] for building docker images for the base custom dc docker image.
* Although the overall image size did not change by much, it reduced number of layers with non-zero size in the base image from 18 to 1. Since the base image won't change often, collapsing it into a single layer should help in the future.
* Ran cloud build and pushed the new image to the [cloud directory][directory].
+ Will use this image with the custom DC docker image locally and verify it works before pushing the latter to the cloud.
[practices]: https://www.ecloudcontrol.com/best-practices-to-reduce-docker-images-size
[directory]: gcr.io/datcom-ci/python-node-go-protoc-envoy
=> Apply best practices to base custom dc docker image.

static/nodejs_server/constants.ts, static/nodejs_server/types.ts, static/nodejs_server/utils.test.ts, static/nodejs_server/utils.ts, static/src/server.ts
Sometimes chartUrl that is returned in the response is too long to send a GET request to. Use compression to shorten the URL
For example, "Which industries have grown the most in California" chartUrls:
current (5810 characters): https://screenshot.googleplex.com/4WUDYVS5N2MQsVj
with compression (1513 characters): https://screenshot.googleplex.com/8HAWVmq7Yef9BQE
=> [nodejs] use compression to shorten chartUrl

run_test.sh, server/routes/place/html.py, server/tests/routes/place_test.py
This PR adds:
* A [`rel="canonical"` link](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls?sjid=16312852956349874621-NC#rel-canonical-header-method) as an HTTP response header. This fix the "duplicate without user selected canonical" errors on the place pages.
* A [`rel="alternate"` link](https://developers.google.com/search/docs/specialty/international/localized-versions#http) to the HTTP response header. This will help the crawler understand we have translated versions of the same page, which will also help reduce "duplicate" errors.
* Tests for both
* Fixes a bug where the summary text is not actually limited to the English locale.
=> [Place Page SEO] Add Canonical and Localization HTTP headers

nl_server/routes.py
This fixes the NL server to not suppress faults.  Also, add a real health-check.
Context:
* This is in response to an outage (b/323064085) where a BAD machine caused embeddings to return empty on a small subset of servers, and redis then caches the empty results and always returns it
* With this fix, the website flask cache won't cache the faulty value (if any). To confirm, this [code here](https://github.com/pallets-eco/flask-caching/blob/a367b9f13109d35c1e3df069f5da4c29110a689c/src/flask_caching/__init__.py#L878-L882) in Flash-Caching only caches the return value, not exceptions.
=> NL Server: When at fault, admit it

server/routes/place/html.py, server/templates/place.html, static/package-lock.json
This PR adds `<meta name="robots" content="noindex">` as to place pages when not on the main `https://datacommons.org` domain to [prevent search crawlers from indexing](https://developers.google.com/search/docs/crawling-indexing/block-indexing).
This means only the `https://datacommons.org/place/` pages will get indexed, and the crawler will ignore Custom DCs and alternate domains like `browser.datacommons.org` and `dev.datacommons.org`. This will reduce the spurious indexing error alerts for pages that shouldn't be indexed.
=> [Place Page SEO] Add meta tag to prevent indexing on non-prod place pages

deploy/nl/embeddings.yaml, nl_server/routes.py
This is suspected to cause rollout failures in prod.
One plausible theory why this was not seen in autopush/staging, in discussion with Bo and Natalie, is that we maybe pounding HF to download base model, which might be getting throttled.
So, remove the `small` model which is unused now and is the only reason to download from HF.
=> Disable NL server healthz and remove small index

deploy/helm_charts/dc_website/templates/deployment.yaml, deploy/nl/embeddings.yaml, nl_server/routes.py
Turns out the prod push failures were because the default health check timeouts (1s) was too small, so increasing it to 5s, and rolling forward the original healthz fix.
=> Rollforward healthz and increase timeouts

run_test.sh
Updates the lint fix test `run_test.sh -f` to avoid linting files in python envs nested in subdirectories.
The scripts under `tools/summaries` and `tools/sitemap` use their own python `.env` virtual environment which sometimes contain packages that yapf can't parse.
=> Don't lint nested python virtual envs

static/src/server.ts
Handle cases in node server where the per capita specification comes from the block
example results:
query: What is the GDP per capita in Switzerland?
response: https://paste.googleplex.com/4980846865416192
query: What is the GDP in Switzerland?
response: https://paste.googleplex.com/6015469654376448
=> [node server] Handle block level per capita

nl_server/loader.py, shared/lib/gcs.py
Found a bug when deploying a custom dc with a GCS path where the yaml did not exist yet:
With this fix, if the yaml is not found, it logs a message and does not load the yaml but starts the server:
In PR #3946 we were doing this check for the embeddings CSV but not for the YAML. This PR fixes that.
Also updating submodules in this PR.
=> Do not load custom embeddings yaml from gcs if not found.

deploy/gke/dev.yaml, gke/mci.yaml.tpl
This PR checks in the changes made during the redeployment of dev.datacommons.org on Feb 21, 2024:
Changes:
* The dev instance now lives on a new IP address. `dev.yaml` is updated with the new IP address.
* The ssl cert generated by `setup_ssl.sh` uses a different name for the created cert than is expected by `mci.yaml`. Updated `mci.yaml.tpl` to use the correct cert name.
=> Update deployment YAMLs: dev instance IP and certificate name

static/js/place/place.ts
Updates the place pages to not show the "Sorry, there was an error loading charts for this place." message if summary text is being shown (i.e., there is content on the page). 
This addresses the hypothesis that our "Soft 404" errors come from the crawler picking up our "sorry" message when the crawler cancels our data fetch for being too slow.
Addressing the data fetch latency is a larger change that will come in future PRs.
Before (what crawler sees):
After (what crawler sees):
Behavior when no summary is present:
=> [Place Page SEO] Suppress "sorry" message if summary is present

run_sdg_sanity.sh
* The script now loads a file relative to itself from the file system so `cd`-ing into it from the shell script so it can load it.
=> cd into sanity script folder before running it.

static/js/apps/explore/app.tsx, static/js/apps/explore/entity_pv_section.tsx, static/js/apps/explore/success_result.tsx, static/js/types/app/nl_interface_types.ts
Minimum frontend changes to be able to display the response from a simple entity pv query (biomed nl query).
Uses backend changes from: https://github.com/datacommonsorg/website/pull/3998
https://github.com/datacommonsorg/website/assets/69875368/624e081d-4ec4-47ac-be22-2011cae79665
=> [biomed NL] fe changes for basic working version

build/web_server/Dockerfile
Introduced when adding `@datacommonsorg/client` as a dependency to the frontend code in #4000 
This fix properly installs the npm dependencies (like with the `@datacommonsorg/web-components` dependencies) in the web server docker image
=> Fixed web server build issue with @datacommonsorg/client

deploy/helm_charts/dc_website/values.yaml, deploy/helm_charts/envs/autopush.yaml, deploy/helm_charts/envs/bard.yaml, gke/cron_testing_job.yaml.tpl, gke/setup_cron_testing.sh
Update autopush website-app to deploy in default-pool. This fixed deploying autopush when trying manually
Background:
- autopush deployments have been failing since website cron tests have been added
- there are 2 different node pools used in the autopush instance, one with 4 CPU and one with 8 CPU
- I noticed that a lot of website-app pods were deployed in the 8 CPU node pool and they seemed to have a lot of restarts. In a past experiment, we've learned that website-app pods have trouble starting in node pools that have more CPU than 4.
- So I tested moving all the cron jobs to the 8 CPU node pool and all the website-app pods to the 4 CPU node pool and it seemed to work. (Will see how well it does once this PR is in though)
=> fix autopush deployment

server/config/nl_page/chart_titles_by_sv.json, tools/nl/titles/demo_svs_1.3k_names.csv
This is to address one of the World Bank Issues "Fix Inaccurate labeling of per 100K StatVars as percentages" 
I reverted the curated name to the original SV name (e.g. https://datacommons.org/browser/Count_Death_IntentionalSelfHarm_AsFractionOf_Count_Person)
=> Update some curated SV titles to remove %

server/integration_tests/explore_test.py
Should re-enable this when the failure is solved.
=> Comment out consistently failed NL case due to mixer failure; Unblock PR submission.

static/js/chart/base.test.ts, static/js/chart/base.ts, static/js/chart/draw_scatter.ts
Fixes issue where large y axis labels cut off the chart in mobile
Before:
After:
Just before breakpoint:
=> fixed scatter plot y axis label wrapping issue and overlapping density legend

build/website_cron_testing/run_website_cron_tests.sh
adversarial logs were going into a separate folder because of extra line that gets the date string a second time
=> [cron testing job] fix bug

nl_server/config.py, nl_server/embeddings.py, nl_server/embeddings_store.py, nl_server/loader.py, nl_server/tests/custom_embeddings_test.py, nl_server/tests/embeddings_test.py, tools/nl/svindex_differ/differ.py
Avoid keeping unnecessary data frames in memory after load in `embeddings.py`.  This change drops the memory usage from [745MB to 200MB](https://gist.github.com/pradh/43148b72b74d1c5022eb36c4602ef020).
Also, fix a bug in Custom Index using base-model instead of tuned-model on live reload.
=> Load models once on NL server bootup

nl_app.py, nl_server/__init__.py, server/__init__.py, shared/lib/gcp.py
Should not call `logging.info` before `logging.basicConfig` otherwise the config won't take effect.
Also updated logging format a bit.
=> Fix logging config setup in local env

build/nl_server/Dockerfile, build/web_compose/Dockerfile, run_test.sh, tools/nl/embeddings/finetuning/run.sh, tools/nl/embeddings/run.sh, tools/nl/embeddings/run_custom.sh, tools/nl/svindex_differ/run.sh
Note torch 2.2.2 is released in 3/27: https://pypi.org/project/torch/2.2.2/. This corresponds to our docker image size blow up.
=> Upgrade torch to 2.2.2; Otherwise pip tries to ignore the torch-cpu and downloads cuda torch 2.2.2

tools/nl/embeddings/build_custom_dc_embeddings.py, tools/nl/embeddings/utils.py
Currently, all embeddings specified in embeddings.yaml (default, biomed, UN) are loaded in Custom DCs. We only need the default in them.
When building a custom DC docker image, we [run a script](https://github.com/datacommonsorg/website/blob/3112669701480bc5fe9c1e42051445d631cecace/build/web_compose/Dockerfile#L120) to download and save the default model in the docker image. With this change, we additionally save embeddings.yaml with just the default embeddings in it.
Before:
After:
=> Save embeddings.yaml with only default embeddings for custom DCs.

tools/nl/embeddings/build_custom_dc_embeddings.py, tools/nl/embeddings/build_custom_dc_embeddings_test.py
* This fixes a bug where the NL server uses the base model instead of the FT model.
* It also improves startup and load performance since while the FT model is included in the docker image, the base model is not. Which results in the latter being downloaded on every server startup (or at first load) which makes for longer startup times esp on slow networks.
Before:
After:
In the above case, the load time went down from 13s to 5s = an 8s or 60% improvement overall. While the absolute improvement here (tiny embeddings file, fast Google network) is not significant, the difference can be substantial on slower networks (where we have seen timeouts before).
=> Create custom dc embeddings file name with model version in it.

static/js/components/tiles/bar_tile.tsx
Fixed bar chart CSV export error for multi-place charts
Example:
http://localhost:8080/explore/#client=ui_query&q=How+does+the+GDP+of+USA+compare+with+that+of+China
=> fixed bar chart csv export error

static/sitemap/PriorityPlaces.0.txt, tools/sitemap/main.py, tools/sitemap/requirements.txt
Removes the place page for West Berlin (nuts/DE301) from our sitemap. This place page does not have any charts on it, and because this city no longer exists, we won't be adding new charts to it. This PR removes it from our sitemaps so it doesn't get indexed.
Also removes the unused `yapf` in requirements.txt which was causing some version conflict errors.
=> Remove place page for West Berlin (nuts/DE301) from sitemap

deploy/gke/biomedical.yaml, deploy/helm_charts/envs/biomedical.yaml, server/__init__.py, server/app_env/biomedical.py, server/routes/biomedical/html.py, server/routes/disease/html.py, server/routes/protein/html.py, server/templates/disease/landing.html, server/templates/protein/landing.html, static/js/biomedical/landing/app.tsx, static/js/biomedical/landing/header_and_search_section.tsx
Biomedical DC will now be hosted in its own instance, at https://biomedical.datacommons.org.
This PR:
* Adds deployment yamls used to deploy the biomedical pages to the `datcom-biomedical` GCP project
* Sets the biomedical landing page as the homepage when in biomedical DC
* Removes "/bio" from protein and disease browser paths for a simpler URL structure
* Updates the search bar in biomedical DC to include "&dc=bio" to enable biomedical searches
With this change, local development of biomedical DC can be done with
```
./run_server.sh -e biomedical -m
```
And changes can be deployed to biomedical.datacommons.org with
```
./scripts/deploy_gke_helm.sh -e biomedical
```
Changes are now live!
* homepage: https://biomedical.datacommons.org
* search result: …
=> Create new biomedical DC instance.

nl_server/config.py, shared/lib/gcs.py, tools/nl/embeddings/build_custom_dc_embeddings.py, tools/nl/embeddings/utils.py
* This fixes the bug mentioned in #4124 with the downloaded model and embeddings paths.
* It also makes local paths of downloaded GCS files consistent with downloaded GCS folders - in that the former is also prefixed with the bucket name now like the latter.
* Finally, the embeddings are downloaded using an anonymous client like they were [previously](https://github.com/datacommonsorg/website/blob/master/nl_server/gcs.py#L31).
=> Fix downloaded model and embeddings paths for custom DC.

server/config/nl_page/prop_titles.json, server/integration_tests/test_data/e2e_triple/howaboutcoryluscornutamarshall/chart_config.json, server/integration_tests/test_data/e2e_triple/whatgenesareassociatedwiththegeneticvariantrs13317andrs7903146/chart_config.json, server/integration_tests/test_data/e2e_triple/whatisbetacoronavirus1thespeciesof/chart_config.json, server/integration_tests/test_data/e2e_triple/whatisthephylumofvolvox/chart_config.json, server/integration_tests/test_data/e2e_triple/whatstrandorientationdoesfgfr1have/chart_config.json, server/integration_tests/test_data/e2e_triple/whattypeofgeneisit/chart_config.json, server/integration_tests/test_data/e2e_triple/whatvirusspeciesarers13317andrs7903146/chart_config.json, server/lib/nl/config_builder/answer.py, server/lib/nl/config_builder/base.py, server/lib/nl/fulfillment/triple.py
- add chart title for entity overview charts
autopush: https://screenshot.googleplex.com/8URapF9YZabLWb5
local: https://screenshot.googleplex.com/8KC75DLA3PbmVUw
- update "and <n> more other" -> "and <n> more others"
- updates property names in table headers to be an actual name
- updates the entity string to only show unique entity names
autopush: https://screenshot.googleplex.com/3s9BQHG3xavYQXm
local: https://screenshot.googleplex.com/3FPMc4KEdb8UagP
naming/messaging that still need to be improved & will come in a separate PR:
- the template for the message (i.e., right now it's `the <property> for <entity> is:`)
- how the table heading should differentiate between in and out arcs
=> [biomed nl] some naming updates

static/css/base.scss, static/css/tools/base_tools.scss, static/css/tools/scatter.scss, static/css/tools/visualization.scss, static/js/apps/visualization/stat_var_selector.tsx, static/js/apps/visualization/vis_type_configs.ts, static/js/apps/visualization/vis_type_configs/map_config.tsx, static/js/apps/visualization/vis_type_configs/scatter_config.tsx, static/js/apps/visualization/vis_type_configs/timeline_config.tsx, static/js/apps/visualization/vis_type_selector.tsx, static/js/tools/scatter/app.test.tsx, static/js/tools/scatter/statvar.tsx, static/package-lock.json
- remove icon from vis tool tabs & decrease height of the footer
- local: https://screenshot.googleplex.com/6EWutpp37WhMEtH
- autopush: https://screenshot.googleplex.com/AiHbRJW6wkLkRqh
- update the text in the scatter modal that pops up when extra sv is selected to be more action oriented
- local new tool: https://screenshot.googleplex.com/9obiAC6X4Z3gUVs
- autopush new tool: https://screenshot.googleplex.com/5FKEwYxcpJ6Vjq2
- local old tool: https://screenshot.googleplex.com/xQh7amGkDkkRz6a
- autopush old tool: https://screenshot.googleplex.com/867pNcRkaqJAvJe
=> [fixit] increase chart realestate in vis tools and update stat var modal

tools/nl/embeddings/build_custom_dc_embeddings.py
* Fixes [timeouts](https://screenshot.googleplex.com/BqFXuiQv67dru5J) when downloading default embeddings when building the docker image by using an anonymous client.
=> Fix gcs timeout with custom dc docker build.

server/routes/shared_api/variable_group.py, server/services/datacommons.py, server/tests/routes/api/varable_group_test.py
Calling this endpoint without dcid will overload the mixer and internal server error. Only POST request is used in the client, hence removing GET to reduce its exposure even more.
=> Restrict flask /api/variable-group/info to only use POST and ensure 'dcid' exists in request

tools/screenshot_diff/README.md, tools/screenshot_diff/diff.sh
This tool gets the link to see the diffs between screenshots taken against autopush.datacommons.org between the last autopush that was pushed to prod & the current autopush
=> add script for getting the screenshot diffs between prod and autopush

tools/delete_cron_outputs/README.md, tools/delete_cron_outputs/run.sh
A script to delete old outputs from cron testing jobs.
I set this script to delete files older than 30 days, but have not run it to completion yet (tested by just deleting the earliest file and breaking out of the loop), so I can still increase or decrease this number as you guys see fit!
=> Add script to GC old cron testing job outputs

static/js/components/subject_page/block.tsx
Before: 20 extra calls
After: Extra calls removed
=> Removed empty calls to named_typed endpoint from explore page

scripts/deploy_custom_dc_autopush.sh
* The cloudbuild indicates a permission error with the script.
* Trying to address it by running `git update-index --chmod=+x scripts/deploy_custom_dc_autopush.sh`.
* Also added a restart timestamp env var to easily identify the restart time of a given revision.
=> Update permission of custom dc autopush deployment script.

build/web_compose/nginx.conf
* The fix is to use `$http_host` instead of `$host` in `nginx.conf` so that both host and port are used for redirects.
```
$ curl -H "Host: foo.com" -is http://localhost:8080/admin | grep "Location" 
Location: http://foo.com/admin/
$ curl -H "Host: foo.com:9090" -is http://localhost:8080/admin | grep "Location"
Location: http://foo.com/admin/
```
```
$ curl -H "Host: foo.com" -is http://localhost:8080/admin | grep "Location"     
Location: http://foo.com/admin/
$ curl -H "Host: foo.com:9090" -is http://localhost:8080/admin | grep "Location"
Location: http://foo.com:9090/admin/
```
=> Fix nginx redirects.

static/css/base.scss, static/css/tools/base_tools.scss
Adds alternate body fonts to the tools, because Google Sans is not an open source font. This will allow other fonts to render in custom DC instead of the default serif font of the browser.
=> Fix Google Sans font breaking in Custom DC

server/webdriver/screenshot/local/page.json
when I was deleting the /nl screenshot tests last week, missed some urls that were in a different part of the page.
=> Remove more nl screenshot tests

static/js/tools/stat_var/page.tsx
Fixes a bug in the stat var explorer on custom DC, where clicking on a custom stat var seems to do nothing.
The root cause turned out to be because custom loaded stat vars don't provide a provenance, and the stat var explorer doesn't update state if no provenances were found. This PR adds a state update even if no provenances are provided.
Screenshot:
=> Fix stat var explorer for custom DC data

deploy/helm_charts/dc_website/templates/config_maps.yaml, deploy/helm_charts/dc_website/values.yaml, deploy/helm_charts/envs/autopush.yaml, deploy/helm_charts/envs/dev.yaml, deploy/nl/embeddings.yaml, nl_server/config.py
We want each environment to be able to use different project/location/endpoints for each vertex ai model so move the specification of those values to the deployment yamls. When running locally, read from autopush values
=> move vertex ai model info to deployment values

nl_server/embeddings_map.py, server/lib/nl/common/commentary.py, server/lib/nl/detection/heuristic_detector.py, server/lib/nl/detection/utils.py, server/lib/nl/detection/variable.py, server/lib/nl/explore/params.py, shared/lib/constants.py
Reason:  turns out that the bigger models have a shorter range of scores, and having a % based higher confidence threshold makes "Low confidence" message more common, and could hurt Bard recall.
=> NL: Use fixed higher thresholds

static/css/shared/_tiles.scss
This PR fixes the issue where clicking the NL feedback icons in the charts no longer appears to do anything. This happens because the feedback box got hidden by the chart container for being "out of bounds". 
Before:
After:
=> Fix bug in NL feedback

server/config/nl_page/topic_cache.json, server/integration_tests/test_data/e2e_correlation_bugs/chart_config.json, server/integration_tests/test_data/e2e_correlation_simple_place/foreignbornvs.nativeborninsunnyvale/chart_config.json, server/integration_tests/test_data/e2e_correlation_simple_place/nativebornvs.medianincomeinsunnyvale/chart_config.json, server/integration_tests/test_data/e2e_india_demo/howdoesliteracyratecomparetopovertyinindia/chart_config.json, server/integration_tests/test_data/e2e_us_demo/howdoeshouseholdincomecomparewithratesofdiabetesinusacounties/chart_config.json, server/integration_tests/test_data/e2e_us_demo/howdoobesityratescomparewithratesofdiabetesinusacounties/chart_config.json, server/integration_tests/test_data/explore_strict_multi_var/chart_config.json, server/integration_tests/test_data/international/query_2/chart_config.json, server/integration_tests/test_data/sdg/query_3/chart_config.json, server/lib/nl/explore/topic.py, server/tests/lib/subject_page_config_content_test.py
In multi-var fulfillment, when we have pairs of SVs like:  `([LHS1], [RHS1, RHS2, RHS3, RHS4])`, previously, RHS2-4 go unused.  In the case of [poverty vs. literacy rate], the topic on the RHS got pushed down with the recent model changes, and this bug gets triggered.
This PR fills the empties with the first topic/SV on the shorter side, so that every var on the longer side is considered.  This may still not be ideal, and the other extreme is to do a full-cross, but that might lead to a lot more candidates.
Testing:  notice that this change restores the scatter diff in server/integration_tests/test_data/e2e_india_demo/howdoesliteracyratecomparetopovertyinindia/chart_config.json
=> Improve multi-var fulfillment with uneven #matches

build/ci/cloudbuild.nl.yaml, server/integration_tests/explore_test.py
Previous test split reduces the time from ~10m to ~6m. This tries to split the 2 most long running test. The whole run should then be around 4-5min.
=> Speed up NL cloudbuild even more

nl_server/flask.py
The prediction call right after the registry constructor consistently throws out error during integration test. This can be found from locally as well.
It's not clear why this happens and this brings up a lot of flakiness during test.
```
ERROR    nl_server.flask:app.py:1414 Exception on /api/search_vars/ [POST]
Traceback (most recent call last):
File "/workspace/.env/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
return callable_(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/.env/lib/python3.11/site-packages/grpc/_channel.py", line 1181, in __call__
return _end_unary_response_blocking(state, call, False, None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Do not check nl server registry with prediction call on app creation

build/ci/cloudbuild.screenshot.yaml, build/ci/cloudbuild.sdg_sanity.yaml, build/ci/cloudbuild.webdriver.yaml, build/ci/cloudbuild.website_testing.yaml, build/webdriver-chrome/Dockerfile, build/webdriver-chrome/cloudbuild.yaml, build/website_cron_testing/Dockerfile, nl_server/flask.py, server/__init__.py, server/webdriver/tests/map_test.py, shared/lib/utils.py, web_app.py
A few things changed here:
* Build a new webdriver docker image with newer chrome webdriver also new linux patches.
* Do not use cloud logging for webdriver tests.
* Remove the warmup requests since they are very limited, never updated and do no contribute much. They incur extra threading in flask.
* Add back skipped webdriver tests.
=> Try to fix webdriver tests flakiness

server/templates/static/homepage.html
Updates the country count on our homepage from 256 to 193.
The original 256 comes from the fact that our KG includes data on disputed regions like the [Republic of Artsakh](https://en.wikipedia.org/wiki/Republic_of_Artsakh) ([dcid: wikidataId/Q244165](https://datacommons.org/place/wikidataId/Q244165)) or [Hong Kong](https://en.wikipedia.org/wiki/Hong_Kong) ([dcid: country/HKG](https://datacommons.org/place/country/HKG)).
This same issue is mentioned in https://github.com/datacommonsorg/docsite/issues/380 and https://github.com/datacommonsorg/website/pull/3921
=> Update country count on homepage

static/css/eval_rig.scss, static/js/apps/eval_rig/app.tsx
Currently, for certain window sizes, the navigation buttons will be hidden, updated so that the navigation buttons are always visible
https://github.com/datacommonsorg/website/assets/69875368/ed89719d-50dd-40e6-9ca9-5e278752740a
=> [rig eval] make feedback buttons always visible

server/lib/nl/detection/llm_detector.py, server/lib/nl/detection/types.py, server/lib/nl/detection/variable.py, server/lib/nl/explore/params.py, server/routes/explore/helpers.py, server/routes/nl/api.py, server/services/datacommons.py, static/js/apps/eval_embeddings/index_score_box.tsx
NL server now allows a list of indexes. With this change, we don't need to merge index during embedding build time, but rather include them in the runtime.
This allows not replicate the same embeddings in multiple indexes and makes embedding build atomic for each source folder.
=> [NL param] Use a list of index types everywhere

static/js/apps/eval_retrieval_generation/app.tsx, static/js/apps/eval_retrieval_generation/call_feedback.tsx, static/js/apps/eval_retrieval_generation/constants.tsx, static/js/apps/eval_retrieval_generation/context.tsx, static/js/apps/eval_retrieval_generation/eval_list.tsx, static/js/apps/eval_retrieval_generation/feedback_navigation.tsx, static/js/apps/eval_retrieval_generation/overall_feedback.tsx, static/js/apps/eval_retrieval_generation/query_section.tsx, static/js/apps/eval_retrieval_generation/types.tsx, static/js/apps/eval_retrieval_generation/util.ts
- Add a new FeedbackStage enum to be used when deciding what to display in the query section and feedback sections
- Changes to make RIG eval tool work with this new concept
- only change made for RAG was displaying the rag calls in the query section when feedback stage is the CALLS stage. Actual navigation for RAG will come later
=> [rag eval] add concept of feedback stage

static/js/apps/eval_retrieval_generation/call_feedback.tsx, static/js/apps/eval_retrieval_generation/claim_counter.tsx, static/js/apps/eval_retrieval_generation/constants.tsx, static/js/apps/eval_retrieval_generation/data_store.tsx, static/js/apps/eval_retrieval_generation/eval_list.tsx, static/js/apps/eval_retrieval_generation/feedback_navigation.tsx, static/js/apps/eval_retrieval_generation/overall_feedback.tsx, static/js/apps/eval_retrieval_generation/rag_ans_feedback.tsx
update claim counter page to have 2 sections w/ 3 counters each:
1. statistical claims
- total claims
- false claims
- unique tables
3. inferred claims
- total claims
- false claims
- unsubstantiated claims
=> [rag eval] add claims counters

static/js/utils/tile_utils.tsx
Gives web component users ability to hide and style the 'show metadata' link
=> Added 'part' selectors to 'show metadata' link

server/routes/explore/html.py, server/templates/base.html, server/templates/custom_dc/iitm/base.html, server/templates/custom_dc/stanford/base.html
the redirect from /explore landing pages caused a downgrade from https to http.
also fix a few http:// links to docsite.
follow up to #4392
=> remove redirect for missing trailing slashes on explore links

static/js/apps/eval_retrieval_generation/call_feedback.tsx, static/js/apps/eval_retrieval_generation/util.ts
- fix bug with empty call response being saved to firestore when "apply to next" is selected
- fix table parsing issue when header contains "-"
=> [eval] Fix empty feedback recorded, table parsing

scripts/build_and_deploy_custom_dc_autopush.sh
- Actually initialize submodules so that checkout + pull has an effect.
- Make a temporary commit so that HEAD:import and HEAD:mixer are updated.
=> Fix submodule treatment in custom DC build script

docs/developer_guide.md
When I was onboarding, I found the versioning for protoc confusing, and it also took me a while to figure out where I could download the required version. Adding a direct link for convenience for future readers/contributors.
=> Add a direct link to the required version of protoc

server/webdriver/tests/browser_test.py
skipping broken webdriver test because looks like it is caused by somewhere upstream in mixer/data
=> skip a broken webdriver test

static/custom_dc/stanford/overrides.css
=> Fixed css bug that was hiding the stanford custom dc navbar

server/lib/nl/detection/heuristic_detector.py
ran goldens without the `if (params.is_toolformer_mode(dargs.mode))` & there were no diffs
=> [toolformer] replace "global" with "world" in queries in toolformer mode

server/integration_tests/explore_test.py, server/integration_tests/test_data/cdc_nl/chart_config.json, server/webdriver/cdc_tests/autopush_test.py
* Adds a simple sanity test that asserts that the detect-and-fulfill response includes a Custom DC SV.
* This PR will only be submitted after this one: https://github.com/datacommonsorg/website/pull/4473
+ Without that PR, custom embeddings will not load on startup, which will cause this test to fail.
+ Ironically, in the future, the failure of this test will be an indicator of a Custom DC NL regression.
=> Add Custom DC NL sanity test.

static/js/tools/shared_util.ts
there was a bug in picking the denominator observation where when comparing if next denom is better, it was comparing with the earliest denominator & not the previous denominator. This caused weird behavior for per capita timelines
autopush: https://screenshot.googleplex.com/6gh9Nyjr7kg638C
local: https://screenshot.googleplex.com/BHUsQPMih5X27Hy
=> [timeline] fix ratio bug

nl_requirements.txt
https://github.com/datacommonsorg/website/pull/4487 introduced frozendict import in shared lib.  The NL server requirements was missing it ([Web server requirements has it](https://github.com/datacommonsorg/website/blob/e868bcc8a374fb72106d52cf7fd55a9d8a58f7bb/server/requirements.txt#L9)).
=> Add frozendict to nl_server

static/js/apps/eval_retrieval_generation/util.ts
cell values of type number wasn't fetched when using getCell().stringValue
=> [evals] use value instead of stringValue when getting cell content

scripts/build_custom_dc_and_tag_latest.sh
Allow an empty commit when pulling in latest submods in case they're already up-to-date. This should fix current autopush build failures.
=> [CDC Autopush] Fix submod pull no-op case

build/web_compose/Dockerfile, build/web_compose/compose.sh, custom_dc/env.list, tools/nl/embeddings/utils.py
* Consolidates CDC env vars into a single file (`env.list`).
* See [go/cdc-env-file-consolidation](http://go/cdc-env-file-consolidation) for more details.
* As part of the consolidation `sqlite_env.list` and `cloudsql_env.list` need to be removed.
+ We'll remove them from the code once @kmoscoe has removed their mention from the docs.
* `Dockerfile` changes:
+ `lancedb` deps were moved to a different requirements file a few weeks ago. Adapting Dockerfile to that move.
+ Uses `npm ci` vs `npm install` for faster builds. See [this thread](https://stackoverflow.com/a/74068335) for more details.
* The Dockerfile changes are not related to env consolidation so I can do it in a separate PR if needed. LMK.
* Built docker image (`gcr.io/datcom-ci/datacommons-website-compose:keyurs-test`) with …
=> Consolidate CDC env file.

server/integration_tests/nl_test.py, server/lib/nl/common/bad_words.py
This PR removes the assertion that in the bad words test, in `multi` mode, lines should not contain spaces. This assertion breaks when creating cross products that include place names like "united states of america" or "united kingdom". 
This PR also updates the "headless drivers" NL test case to look for the correct detection type.
This should unblock the python and nl test failures seen in unrelated, already approved PRs.
=> Update bad words python test

.dockerignore
Updates .dockerignore to exclude the sanity.py file (in **/tests) to fix a cron-testing docker build failure.
=> Update .dockerignore to fix docker build

static/js/apps/eval_retrieval_generation/util.ts
- Require table divider to be at least three dashes long. This prevents sequences of 1 or 2 dashes in values from getting parsed as dividers.
- Allow any character other than a pipe in a table header value.
=> [Eval UI] Tweak table parsing

run_server.sh, server/routes/shared_api/stats.py, static/js/shared/ga_events.test.tsx, static/js/utils/search_utils.tsx
Fixes b/356689537 where variable search in the new map tool when plotting countries on earth resulted in an error "Request line is too large".
Since the error only reproduces when running the website server with Gunicorn, also added a mode to run_server.sh for ease of reproing.
I've moved all request params to the request body, but if we want to only move places (maybe for the sake of analytics), I can modify this.
=> Fix map tool stat var search with many places

build/cdc_services/Dockerfile, build/cdc_services/nginx.conf, build/cdc_services/run.sh, build/cdc_services_runtime/Dockerfile, build/cdc_services_runtime/cloudbuild.yaml, build/ci/cloudbuild.push_cdc_services_image.yaml, scripts/push_cdc_services_image.sh
* Currently this new image only includes mixer. NL and website servers will be added in the next PR.
* A key difference from the existing web compose image is that the final image only includes runtime dependencies and no build only dependencies.
+ The runtime deps are limited to python, envoy and nginx.
+ Build only deps that are no longer in the final image include go, protoc, node and gcloud. This makes a significant difference in the size of the final image.
* Another major difference is that mixer is built as a self contained library vs previously where it required go at runtime.
* The runtime dependencies are encapsulated in its own image and pushed to this registry: [gcr.io/datcom-ci/datacommons-services-runtime](https://gcr.io/datcom-ci/datacommons-services-runtime)
* The services …
=> Create initial multi stage CDC services docker image.

build/cdc_services/Dockerfile, build/cdc_services/nginx.conf, build/cdc_services/run.sh, build/cdc_services_runtime/Dockerfile, build/cdc_services_runtime/cloudbuild.yaml
* This PR creates the full multi-stage services image.
* The new image is more than 50% smaller to download - [1 GB](https://screenshot.googleplex.com/5qum85dSxSxUieq) vs [2.3 GB](https://screenshot.googleplex.com/767mwgPEqk3es35)
+ On-disk decompressed size is [3.77 GB vs 7.69 GB](https://screenshot.googleplex.com/Bxw7rvUJcdJXmJd)
* It is also about 3x faster to build in the cloud - [6 min](https://screenshot.googleplex.com/747AAifhDVKGUi3) vs [18 min](https://screenshot.googleplex.com/3ta43Yd9yUEwy2z)
* The new image bundles the embeddings in the image thereby improving the startup time (20 sec vs 30 sec on my machine).
* Verified by running it both locally and in the [cloud](https://screenshot.googleplex.com/6bEjV3Eer4sJCvb).
* Also disabled the web admin in the new services image so …
=> Create smaller, faster building services docker.

scripts/build_cdc_services_and_tag_latest.sh, scripts/deploy_cdc_services_latest_to_autopush.sh
* The deployment script deploys to a new [dc-autopush2](https://pantheon.corp.google.com/run/detail/us-central1/dc-autopush2/revisions?e=13803378&mods=-monitoring_api_staging&project=datcom-website-dev) cloud run service.
+ @hqpho - decided to use a dedicated service vs using the existing `dc-dev` one so we can continue using the latter for ad hoc testing.
* Once this PR is in, the [autopush yaml](https://source.cloud.google.com/datcom-ci/deployment/+/master:cloudbuild-compose-autopush.yaml) will be updated to trigger these scripts.
=> Create scripts to auto build / deploy the new services docker.

build/cdc_services/Dockerfile
* Instead of copying everything from the static build stage, we only copy artifacts under `/server`.
+ Could've copied only `/server/dist` but being flexible in case it produces other server artifacts in the future.
* This reduces the download size from [1GB to 856 MB](https://screenshot.googleplex.com/6QqSBHdSpwEapBx).
* And the on-disk decompressed size from [3.77GB to 2.79 GB](https://screenshot.googleplex.com/33q5PNapfNEpV7J).
* Cloud build time also improved from [6 mins](https://screenshot.googleplex.com/747AAifhDVKGUi3) to [4 mins](https://screenshot.googleplex.com/9nkrqBLq266CrMd).
* Verified by deploying in the cloud [here](https://screenshot.googleplex.com/3Uojhdv7D2z3g6d).
=> Copy only static dist artifacts to further reduce docker image size.

build/cdc_services/Dockerfile, server/webdriver/cdc_tests/autopush_test.py
* When building the new services image locally, @kmoscoe ran into an error that said buildkit was required when building this image.
* The only statement in the Dockerfile that requires buildkit is [this one](https://github.com/datacommonsorg/website/blob/2f0779132258148b217aa3e9b9356e2fd48e2a01/build/cdc_services/Dockerfile#L156) where chmod is run as part of COPY.
* Separating it out into its own command gets rid of this requirement so partners don't need to worry about enabling it.
* However, I've still kept it enabled for both [manual](https://github.com/datacommonsorg/website/blob/2f0779132258148b217aa3e9b9356e2fd48e2a01/build/ci/cloudbuild.push_cdc_services_image.yaml#L28) and [auto](https://github.com/datacommonsorg/website/blob/2f0779132258148b217aa3e9b9356e2fd48e2a01/scripts/build …
=> Run chmod as a separate step when building docker image.

.gitignore, build/cdc/dev/.env.sample, build/cdc/dev/docker-compose.yaml
Fixes when running `./run_cdc_dev_docker.sh` :
- Updated FLASK_ENV from local to custom to show the custom_dc homepage
- Added IS_CUSTOM_DC true to load only custom dc embeddings
- Added `OUTPUT_DIR` to env configuration, which:
- Loads the custom topic cache in dc-website
- Configures the `ADDITIONAL_CATALOG_PATH` (`custom_catalog.yaml`) which contains custom dc embeddings and index definitions
- Mounts local sqlite database for the `dc-mixer`
=> Fixed local cdc docker compose setup to use custom embeddings and configured a local data path

packages/web-components/examples/all-charts.html, static/js/chart/draw_bar.ts, static/js/chart/types.ts, static/js/components/tiles/bar_tile.tsx, static/library/bar_component.ts
(UN ask)
Adds `disableEntityLink` option to bar chart web components to remove the entity link from x-axis:
=> Added disableEntityLink option to bar chart web component

build/cdc_services/Dockerfile
* The `FLASK_ENV` value seldom changes, so setting it to a default value alleviates partners from having to provide one themselves.
* Ran into an issue with a partner yesterday where this was not set and it resulted in a startup error.
* Setting a default will get rid of this error.
=> Set default value for FLASK_ENV.

static/js/components/content/tools.tsx
Updated the new homepage's "Scatter Plot Tool" button to read "Scatter Plot Explorer" to align with the link name in the header.
=> Updated scatter plot explorer copy

server/templates/custom_dc/feedingamerica/base.html, server/templates/custom_dc/iitm/base.html, server/templates/custom_dc/stanford/base.html, server/templates/metadata/routes.html, static/css/core.scss, static/js/apps/about/app.tsx, static/js/apps/base/components/footer.tsx
- Reduced height to match old homepage (49px)
- Removed disclaimers link from footer
- Removed disclaimers link from /about page
New footer height on the homepage homepage
About page
New footer height in stat var explorer
New footer height in data download tool
Scatter plot explorer
Map explorer
Timeline
=> Footer updates for new homepage

server/templates/static/faq.html
=> Remove feedback Q since it's now prominent on the website.

.gitignore
The instructions for running a custom datacommons include creating a file (`custom_dc/env.list`) which is likely to contain API keys. Add it to .gitignore to avoid accidental checkins.
=> Add custom_dc/env.list to .gitignore

static/css/stat_var_hierarchy.scss, static/css/tools/stat_var_widget.scss
View screenshots:
https://screenshot.googleplex.com/ACMikc5N3iotPJ6
https://screenshot.googleplex.com/4PmospyvmAUciQ9
And in Scatterplot:
https://screenshot.googleplex.com/AuP4ukWJuoTSXC9
Based on Mocks from Adriana: https://www.figma.com/design/bK4jZkyB0FqfMhA1AUZVuu/2024-%E2%80%A2-Data-Commons?node-id=1776-75&node-type=frame&t=uNasymbV149qi8ze-0
=> StatVar Hierarchy - Allow wrapping SV names

static/js/components/nl_search_bar/auto_complete_input.tsx
Likely introduced when with my autocomplete FE PR. The result of this bug was that once on the explore page, you would see the previous query in the input bar, but whenever you clicked on it, the query would disappear as it was only set as a placeholder, not the input text.
With this PR, we bring it back to the same state as prod.
=> Fixes bug that sets the query parameter as placeholder only.

server/routes/shared_api/autocomplete/helpers.py
Negates the "score", best match has lowest score. This allows us to sort with the first results being the best matches, but preserves the Google Maps ordering for same score responses.
Cleans up the logic a bit to remove dupes at the end. The new sorting requires computing all scores, so this deduping at the end doesnt lead to useless processing.
When computing score, take into account the ordering of the words.
This significantly improves the results from my testing.
=> Modify the autocomplete processing logic to improve results

static/js/components/nl_search_bar/auto_complete_input.tsx
Modifies the autocomplete query trigger to take into account the last selection.
Before: https://screencast.googleplex.com/cast/NTIzMzU4Njg3NjcxMDkxMnw5MTBiMjA5OS1lYg
After: https://screencast.googleplex.com/cast/NTkyNDU3NjgzNDg3OTQ4OHw2MzIzMTFiMi1kMg
With this change, we only send to autocomplete the part of the last query selection.
=> Autocomplete Trigger Improvements

build/cdc_services/run.sh
This makes startup errors in Mixer or NL servers more obvious.
Bug: b/374820494
Reference: https://docs.docker.com/engine/containers/multi-service_container/#use-a-wrapper-script
=> Exit cdc_services/run.sh when any background process exits

deploy/terraform-custom-datacommons/README.md
Updated custom dc terraform deployment instructions
* Updated API key link to use apikeys.datacommons.org instead of the legacy google form
* Added instructions for using web service & data job `latest` containers.
=> Updated custom dc terraform deployment instructions

server/routes/shared_api/autocomplete/helpers.py, server/webdriver/tests/event_page_test.py, static/css/core.scss
https://github.com/datacommonsorg/website/pull/4684
Changes in the PR above ended up breaking styling for autocomplete. See autopush: https://screenshot.googleplex.com/77CCATTzB2domBv
I believe these 2 lines are the only ones needed to recover the autopush styling. Verified locally.
=> Reintroduce css styling for search autocomplete

server/templates/custom_dc/custom/base.html
The height attribute has not been applied since https://github.com/datacommonsorg/website/pull/4683 changed `#main-header-logo` to `.main-header-logo`.
=> Fix size of Custom DC default logo

static/nodejs_server/types.ts
This came up because Kara is adding documentation about the nodejs/query endpoint & wanted clarification about some of the fields in the response. Thought this information could be useful to have here
=> Add comments for fields in the response for nodejs/query endpoint

.github/workflows/all-commits-in-master.yml
This will be used to make sure no commits get merged into customdc_stable that aren't already in master.
=> Add a GitHub workflow that verifies all commits are already in master

.github/workflows/all-commits-in-master.yml
As well as the the repo and branch of the PR.
Third time's the charm! [Example run](https://github.com/datacommonsorg/website/actions/runs/11691607809/job/32559153338?pr=4710) successfully showing what commits were not in master on a PR opened against datacommonsorg/website/customdc_stable.
=> Properly reference master branch on central repo

server/routes/shared_api/autocomplete/helpers.py
Places like Curaçao, España, or Algérie were being unfairly demoted in scoring due to the non-ascii character. This PR replaces all special characters before determine the match score.
Screencast with the fix: https://screencast.googleplex.com/cast/NDkzOTc5NTE5MjA4NjUyOHw1N2FlYTVmMC00Zg
=> Replaces accents and more into ascii equivalents for matching algorithm.

scripts/create_customdc_stable_update_pr.sh
- Fix head branch ref
- Add options to make rerunning quicker
- Don't directly create the PR, open web browser instead
- Seed the PR description with instructions and reference links
=> Improve custom DC stable release PR creation script

run_cdc_tests.sh, server/integration_tests/test_data/cdc_nl/chart_config.json, server/templates/custom_dc/custom/browser_landing.html, server/webdriver/shared_tests/browser_test.py, server/webdriver/shared_tests/ranking_test.py, server/webdriver/tests/homepage_test.py, static/js/apps/browser_landing/app.tsx
- In one file, don't reference h1 by a selector only present in main DC
- In another file, add some CSS selectors specifically for tests to use
- Add option to run_cdc_tests for regenerating goldens
To prevent failures from recurring, we should make custom DC tests run before merge instead of just after autopush.
=> Fix custom DC tests (NL goldens, shared tests)

build/ci/cloudbuild.webdriver.yaml
Seeing some timeouts recently: https://pantheon.corp.google.com/logs/query;query=textPayload%3D%22ERROR:%20context%20deadline%20exceeded%22%20resource.labels.build_trigger_id%3D%225048c6dd-76b1-4f0e-a6be-f772acf71633%22;cursorTimestamp=2024-11-18T18:10:08.718263864Z;duration=P7D?referrer=search&e=13803378&mods=-monitoring_api_staging&project=datcom-ci&inv=1&invt=Abh1kQ
=> Increase webdriver test timeout to 45 minutes

server/routes/static.py, shared/lib/test_server.py
Routes ending with "z" are reserved by Cloud Run: https://cloud.google.com/run/docs/known-issues#ah
=> Add alternate health check route for website server

build/cdc_data/Dockerfile
Previously, conflicting deps between importer requirements and NL requirements could result in runtime errors.
=> [CDC Data] Create Python venv in a single step

.github/workflows/release-branch-checks.yml
The final check looks at the branch after merge, which includes merge commits added by GitHub when merging PRs. These are the only merge commits that should be allowed in the final release branch commit history.
=> Ignore merge commits on final release branch check

scripts/get_commits_label.sh
Otherwise the length is determined based on what's required for uniqueness based on the commits fetched, which can be different when only a single branch is fetched.
=> Specify length of short hashes for custom DC image labels

tools/nl/nodejs_query_differ/differ.py
Right now, failures in different environments are lumped into the same thread in the Google Groups UI. b/253630058 explains that this is because anything in square brackets at the start of the subject line is ignored.
=> Reformat NodeJS failure email subject

packages/client/src/data_commons_web_client_types.ts, server/routes/dev_place/api.py, server/routes/dev_place/types.py, server/routes/dev_place/utils.py, server/tests/routes/api/dev_place_test.py, static/js/place/dev_place_main.tsx, static/js/place/util.ts
The Geometry coordinates for detailed Google maps boundaries is only available for places contained in the USA (not even the USA country), so we only want to show that component for the places contained within the USA.
=> Only show the Google Map widget on Place pages for places contained within the US

tools/sdg/topics/README.md, tools/sdg/topics/generate_topic_cache.py, tools/sdg/topics/generate_topic_cache.sh, tools/sdg/topics/sdg_topic_cache.json, tools/sdg/topics/sdg_topics.mcf, tools/sdg/topics/sheets_svs.csv
* The MCF is the latest MCF provided by the UN.
* The topic cache json and sentence CSV are generated by the script.
=> Create script to generate topic cache from mcf.

server/templates/dev_place.html, static/css/place/dev_place_page.scss
* Fixed dev place page to have `padding-top: 48px;`
* Removed extra tag with id="main" which was adding to the padding
=> Fixed padding on dev place page

server/webdriver/shared_tests/place_explorer_test.py, static/js/components/tiles/chart_footer.tsx, static/js/place/dev_place_main.tsx
Adds the "explore in [timeline/map] tool" to chart footers in the dev place pages.
Also sorts fields alphabetically for codacy code quality.
Example:
=> Enable "explore in tool" on dev place pages

build/ci/cloudbuild.py.yaml, nl_server/tests/embeddings_test.py, server/integration_tests/test_data/demo_fallback/query_5/chart_config.json, server/integration_tests/test_data/demo_feb2023/query_2/chart_config.json, server/integration_tests/test_data/detection_api_multivar/comparemalepopulationwithfemalepopulation/debug_info.json, server/integration_tests/test_data/e2e_correlation_simple_place/nativebornvs.medianincomeinsunnyvale/chart_config.json, server/integration_tests/test_data/e2e_date_range/femalepopulationincaliforniacountiesbefore2020/chart_config.json, server/integration_tests/test_data/e2e_date_range/femalepopulationincaliforniasinceapr2019/chart_config.json, server/integration_tests/test_data/e2e_date_range/lifeexpectancyinusstatesinthelast5years/chart_config.json, server/integration_tests/test_data/e2e_edge_cases2/povertyvs.unemploymentrateindistrictsoftamilnadu/chart_config.json, server/integration_tests/test_data/e2e_india_demo/howdoesliteracyratecomparetopovertyinindia/chart_config.json, server/integration_tests/test_data/e2e_india_demo/whichstatesinindiahavethehighestpovertylevelspercapita/chart_config.json, server/integration_tests/test_data/e2e_single_date/lifeexpectancyinusstatesin2018/chart_config.json, server/integration_tests/test_data/e2e_single_date/populationintheusinthelastyear/chart_config.json, server/integration_tests/test_data/e2e_toolformer_rag_mode/foreignbornvs.nativeborninsunnyvale/chart_config.json, server/integration_tests/test_data/international/query_1/chart_config.json, server/integration_tests/test_data/international/query_5/chart_config.json, server/integration_tests/test_data/place_detection_e2e_dc/query_5/chart_config.json, shared/lib/gcs.py
python tests were failing in cloudbuild and was throwing a file already exists error when trying to make a new directory which was probably a race condition. Fixed by using exist_ok when making the directory.
=> Fix python cloudbuild test

server/routes/dev_place/utils.py, server/routes/place/html.py, static/css/place/dev_place_page.scss, static/js/place/dev_place_main.tsx, static/js/utils/tile_utils.tsx
Sorts the parent places according to the parent place type in both old and new place page.
Before: https://screenshot.googleplex.com/73zetb4iETK6D7p
After: https://screenshot.googleplex.com/4KQ4baSMN64ZNS6
Adds source tile to the bottom of the key demographics in the overview:
https://screenshot.googleplex.com/57gfbASDD62Jx5y
Replaces the source tile from "Source" to "Sources" when there are multiple.
Before: https://screenshot.googleplex.com/8i94e76fpnWRStE
After: https://screenshot.googleplex.com/HfKwv3zrbDsHxK9
=> Place revamp - minor bug fixes

run_website_sanity.sh, server/webdriver/tests/standalone/sanity.py, static/js/apps/explore_landing/components/query_link.tsx, static/js/apps/homepage/components/sample_questions.tsx, static/js/components/elements/link_box.tsx, static/js/components/elements/link_chip.tsx
The sanity tests started failing after [migrating the homepage to use emotion](https://github.com/datacommonsorg/website/pull/4756)
* Added validation to run_website_sanity.sh to error gracefully if no $domain arg is passed in
* Allow setting the protocol along with $domain arg to allow testing from localhost
* Added `data-testid` attribute to LinkChip, LinkBox, and QueryLink element to allow test cases to select dom elements without a fixed class name
* Updated sanity.py test to use `data-testid` attribute to select elements
=> Fixed sanity test issue to account for homepage redesign

server/webdriver/base_utils.py, server/webdriver/shared_tests/place_explorer_test.py, server/webdriver/tests/place_explorer_test.py
The revampled place page experiment should not be tested against CDC autopush. Extracting that test back out to the Based DC tests only.
Once the revampled place page is fully enabled, we should update all the place page tests to be for the new page.
=> Moving place revamp test to Base DC only.

static/js/apps/explore_landing/components/stat_var_queries.tsx, static/js/apps/homepage/app.tsx, static/js/apps/homepage/components/home_hero.tsx, static/js/components/content/link_chips.tsx, static/js/components/elements/link_chip.tsx
Move variant to be a property of the LinkChip to allow different chips, within one LinkChips group to have different styles.
Move the see all datasources chip to be part of the LinkChips
Before: https://screenshot.googleplex.com/C6nx5vJgmeFB2Tn
After: https://screenshot.googleplex.com/3thzGojXK8xAzZ5
=> Move the see all data sources chip into the link chip group

server/templates/base.html, server/templates/custom_dc/custom/base.html, server/templates/custom_dc/feedingamerica/base.html, server/templates/custom_dc/floret/base.html, server/templates/custom_dc/iitm/base.html, server/templates/custom_dc/iitm/place_landing.html, server/templates/custom_dc/stanford/base.html, server/templates/custom_dc/unsdg/base.html, server/templates/place.html, server/templates/place_landing.html, server/templates/ranking.html, server/templates/topic_page.html, server/webdriver/shared_tests/place_explorer_i18n_test.py, server/webdriver/shared_tests/place_explorer_test.py, static/js/apps/base/components/header_bar/header_bar_search.tsx, static/js/apps/base/main.ts, static/js/apps/explore/app.tsx, static/js/apps/explore/main.ts, static/js/i18n/i18n.tsx, static/js/place/chart.tsx, static/js/place/chart_block.tsx, static/js/place/dev_place.ts, static/js/place/place.ts, static/js/place/place_landing.ts, static/js/ranking/ranking.ts, static/js/shared/ga_events.test.tsx
Fixes issue where searching from a localized place page (like https://datacommons.org/place/country/USA?hl=fr) always sends you to a place page in English
* Updated website "base" app to load locale for the header and footer components
* Updated flask templates to set locale in base.html's `#metadata-base[data-locale]` to make locale setting consistent with other metadata props.
* Added locale loading to dev place page
* Added place, units, and stat var labels locale files to explore page. These locale files keep the explore page from showing errors about missing translations during the place page redirect.
=> Updated place page redirect so it keeps the user's locale

build/cdc_data/Dockerfile
Previously during local development, code changes would for pip dependencies to be reinstalled. With this change, pip dependencies are only reinstalled if the actual requirements.txt files change.
=> Updated cdc data Dockerfile to install dependencies before copying over source files

tools/nl/embeddings/build_embeddings.py
- Removed duplicate log messages
- Updated the log format to match that in https://github.com/datacommonsorg/import/pull/355
Before:
```
I1202 18:24:38.316821 140552371297152 utils.py:72] Loading model
Loading model
I1202 18:24:38.317865 140552371297152 SentenceTransformer.py:66] Load pretrained SentenceTransformer: /tmp/datcom-nl-models/ft_final_v20230717230459.all-MiniLM-L6-v2
Load pretrained SentenceTransformer: /tmp/datcom-nl-models/ft_final_v20230717230459.all-MiniLM-L6-v2
I1202 18:24:40.600165 140552371297152 SentenceTransformer.py:105] Use pytorch device: cpu
Use pytorch device: cpu
```
After:
```
[2024-12-18 23:47:08,350 INFO utils.py:72] Loading model
[2024-12-18 23:47:08,350 INFO SentenceTransformer.py:66] Load pretrained SentenceTransformer: …
```
=> Update build embeddings logger to match format from the stats importer

server/routes/ranking/api.py, server/webdriver/shared_tests/place_explorer_i18n_test.py, server/webdriver/shared_tests/ranking_test.py
* Updated tests to account for data removed from `GrowthRate_Count_Person` and `Amount_Consumption_Energy_PerCapita` stat vars
* Updated `/api/ranking` endpoint to return a 404 when no data is available for a place rather than a 500
=> Fixed webdriver tests that stopped working due to data changes

build/cdc_data/Dockerfile
* Previously, pip dependencies were installed in Stage 2 and copied to Stage 3, causing them to be stored in two layers and doubling their size in the final image.
* Combined Stages 2 and 3 into a single layer to eliminate the duplication of pip dependencies and to reduce the final image size.
=> Removed stage from CDC data dockerfile to reduce image size

.run_cdc_dev.env, run_cdc_dev.sh
* This allows devs to have multiple env files referencing different custom dc backends and then run a local setup connecting to those backends quickly.
* This also fixes a bug where a curl command in the script failed due to an unescaped url character.
=> Parameterize the env file used to run the custom dc dev script.

server/webdriver/cdc_tests/autopush/cdc_base_webdriver.py, server/webdriver/cdc_tests/autopush/place_explorer_i18n_test.py, server/webdriver/cdc_tests/autopush/place_explorer_test.py
* Certain place explorer tests are failing on custom DC autopush. This PR skips those tests for now.
* The failures are likely due to recent place explorer page changes that have probably not been ported to custom DC.
* Filed b/386405593 to fix and unskip them subsequently.
* Also filed b/386405338 to run these tests on each PR so they are caught at the outset.
=> Skip failing custom dc tests.

server/integration_tests/test_data/demo_feb2023/query_2/chart_config.json, server/integration_tests/test_data/detection_api_multivar/comparemalepopulationwithfemalepopulation/debug_info.json, server/integration_tests/test_data/detection_api_multivar/showmetheimpactofclimatechangeondrought/debug_info.json, server/integration_tests/test_data/e2e_date_range/lifeexpectancyinusstatesinthelast5years/chart_config.json, server/integration_tests/test_data/e2e_date_range/whichcountriesinafricahavehadthegreatestincreaseinelectricityaccessoverthelast10years/chart_config.json, server/integration_tests/test_data/e2e_single_date/populationintheusinthelastyear/chart_config.json, server/integration_tests/test_data/e2e_single_date/whatwastheaveragehousepricefor2brhouseinmountainviewdecadeago/chart_config.json, server/lib/util.py, server/tests/lib/nl/date_parser_test.py, server/tests/lib/util_test.py
Tests started failing because our NL goldens hardcode exact year that rely on the real date. So tests like "Population over the last 5 years" now excludes the year 2020. 
A couple of the python unit tests also did the same thing, now they have the date mocked.
=> Update NL Goldens

server/templates/dev_place.html, static/css/place/dev_place_page.scss, static/js/place/dev_place_main.tsx
Hides the Overview panel when in another category (other than Overview): [screenshot](https://screenshot.googleplex.com/NanbV29seswndcw)
Hides the Overview panel when there is no summary. [before](https://screenshot.googleplex.com/5GHepNWgPWom9QZ), [after](https://screenshot.googleplex.com/7jaqgBeeRqdJavY)
Hides the child places when there are no child places. [after](https://screenshot.googleplex.com/BuniXa4CBeA6zFu)
Shows error message for invalid DCID: [after](https://screenshot.googleplex.com/AtVVbfJkFM3bZhB)
Shows missing data message when there is no data: [before](https://screenshot.googleplex.com/9mjJsnVZGq9v8x9) [after](https://screenshot.googleplex.com/573nHshTCnt8YfG)
Adds a loading spinner while the charts are loading: [after](https://screenshot.googleplex.com/7c6zo9Csw9ScGmE)
=> Tweaks to new place page for the no data state

nl_server/embeddings.py, nl_server/flask.py, nl_server/registry.py, nl_server/store/memory.py
* Some custom DCs may not have SVs or topics, hence the embeddings file will be empty.
* Prior to this fix, starting up a service with such files failed.
* With this fix, in custom DC mode, we'll log a warning in such instances and skip that index.
* In base DC mode, it will continue to fail.
=> Skip empty embeddings in custom DC

build/ci/cloudbuild.cdc_autopush.yaml, build/ci/cloudbuild.sdg_sanity.yaml, build/ci/cloudbuild.webdriver.yaml, build/ci/cloudbuild.website_sanity.yaml, build/ci/cloudbuild.website_testing.yaml, build/webdriver-chrome/README.md, build/website_cron_testing/Dockerfile, build/website_cron_testing/README.md
This might resolve an issue where website-cron-testing is running with a vulnerable image (e.g. b/390115448)
=> Update webdriver-chrome Docker image

packages/web-components/package.json
I saw bootstrap in the web components (5.0.0) was out of sync with bootstrap in the website (4.5.2). When i tried to upgrade the website to 5.0.0, i saw some errors:
```
ERROR in ./css/about.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: var(--link-color) is not a color.
╷
185 │     "r": red($color),
│          ^^^^^^^^^^^
╵
node_modules/bootstrap/scss/_functions.scss 185:10  luminance()
node_modules/bootstrap/scss/_functions.scss 174:8   contrast-ratio()
node_modules/bootstrap/scss/_functions.scss 159:22  color-contrast()
node_modules/bootstrap/scss/_variables.scss 846:42  @import
node_modules/bootstrap/scss/bootstrap.scss 8:9      @import
css/base.scss 66:9                                  @import …
```
=> Reverted bootstrap back to 4.5 to align with website version

packages/web-components/package-lock.json
Follow-up to #4854 to fix custom DC autopush build. Generated with `cd packages/web-components` then `npm i --package-lock-only`.
=> Update package lock file for web-components to reflect downgraded bootstrap

nl_server/store/memory.py
The python cloudbuild has been seeing transient errors having to do with embeddings file being empty ([example](https://pantheon.corp.google.com/cloud-build/builds;region=global/eaf1afc5-d2cd-4625-b650-2ed1bf7dc6a6;step=1?e=13803378&inv=1&invt=AbnIfg&mods=-monitoring_api_staging&project=datcom-ci)). However, I have not been able to trigger the error after re-building the cloudbuild multiple times: https://screenshot.googleplex.com/6TBMmvmyLCUT8fA
Adding an extra line in the logging to use to debug if the transient error shows up again.
=> Add logging to understand flaky python test

server/routes/dev_place/api.py, server/routes/dev_place/utils.py, server/webdriver/tests/place_explorer_test.py, static/css/place/dev_place_page.scss, static/js/place/dev_place_main.tsx
* Adds world to list of places to highlight.
* Makes the place name in the title a link back to the overview page
* Removes the overview from the topics
* Makes the tests check the ordering of the topics.
=> [Place Page Revamp] Removes Overview from topics, Adds link to overview from Title, Adds world to parent places to highlight.

deploy/terraform-custom-datacommons/modules/main.tf, deploy/terraform-custom-datacommons/modules/variables.tf, nl_server/requirements.txt
Requires "gcr.io/datcom-ci/datacommons-data:latest" to run since the input bucket won't have a config file yet.
I'll switch it back to gcr.io/datcom-ci/datacommons-data:stable after the next release.
=> [custom dc] Added resource to run the schema init job on terraform apply operations before deploying the web service

server/templates/base.html, server/templates/dev_place.html, server/templates/place.html
New place page:
```
<script>
window.dataLayer = window.dataLayer || [];
function gtag() { dataLayer.push(arguments); }
gtag('js', new Date());
gtag('config', '123', {
client_storage: 'none',
anonymize_ip: true,
new_place_page: true,
place_category: '',
});
</script>
```
Old plage page:
```
<script>
window.dataLayer = window.dataLayer || [];
function gtag() { dataLayer.push(arguments); }
gtag('js', new Date());
gtag('config', '123', {
client_storage: 'none',
anonymize_ip: true,
new_place_page: false,
});
</script>
```
Other pages
```  <script>
window.dataLayer = window.dataLayer || [];
function gtag() { dataLayer.push(arguments); }
gtag('js', new Date());
gtag('config', '123', {
client_storage: 'none',
anonymize_ip: true,
});
</script>
```
=> Added new place page dimension tracking to google analytics

server/config/feature_flag_configs/production.json
About to run the script to update the files in prod. The file checked in has to match staging feature flags.
This will allow me to launch autocomplete, place page experiment and scroll to top button.
=> Launch place page experiment, autocomplete and scroll to top

build/cdc_services/nginx.conf
This change enables cross-origin requests for the Custom DC mixer api endpoint. This allows customers like the UN to make api requests from their static site. 
(The website api endpoint already has CORS enabled)
=> Enabled Cross-Origin Resource Sharing (CORS) for Custom DC mixer api endpoint (/core/*)

deploy/terraform-custom-datacommons/modules/locals.tf, deploy/terraform-custom-datacommons/modules/main.tf, deploy/terraform-custom-datacommons/modules/outputs.tf, deploy/terraform-custom-datacommons/modules/variables.tf
Once https://github.com/datacommonsorg/import/pull/364 is merged (and import submod is updated), Redis will be cleared whenever data is reloaded.
Also:
- Clean up a TODO about using `stable` instead of `latest` data management image
- Remove unused VPC connector config
- Format edited *.tf files (hide whitespace changes in diffs for easier reviewing)
=> [Custom DC] [Terraform] Allow data management job to connect to Redis

server/config/feature_flag_configs/custom.json, server/lib/util.py, server/routes/place/html.py, server/templates/custom_dc/custom/base.html
Creates a local file with the feature flags to be used in Custom DC.
Sets autocomplete and place page flags to be disabled (note that the screenshot had place experiment enabled, but it's now disabled).
Starts reading the flags for custom DC from the local file, and injects them in the custom DC base.html file.
See how local custom DC now has the scroll to top button:
https://screenshot.googleplex.com/7dk4eim4LALCuVL
=> [Feature Flags] Give custom DC their own checked in flags.

deploy/helm_charts/dc_website/templates/deployment.yaml, deploy/helm_charts/dc_website/values.yaml, deploy/helm_charts/envs/autopush.yaml, run_server.sh, server/__init__.py, server/app_env/_base.py, server/app_env/autopush.py, server/app_env/local.py
* The current approach configures this variable in code. Making it an env variable makes it configurable at runtime.
* Also, custom dcs [inherit](https://github.com/ONEcampaign/one-datacommons-website/blob/master/server/app_env/one.py#L29) from some of the base configs, so enabling it in base level configs like `local.Config` is problematic for custom dcs.
* Another approach could be to explicitly disable it for custom DCs. However, we want to slowly phase out python based configs over time so that they can be a pure runtime artifact. So implementing this as an env variable.
=> Enable datagemma based on an env variable.

server/config/feature_flag_configs/autopush.json, server/config/feature_flag_configs/custom.json, server/config/feature_flag_configs/dev.json, server/config/feature_flag_configs/local.json, server/config/feature_flag_configs/production.json, server/config/feature_flag_configs/staging.json, static/js/apps/explore/success_result.tsx, static/js/place/dev_place_main.tsx, static/js/shared/feature_flags/util.ts
This PR removes references in the code to gate the scroll to top button behind a feature.
I also mark the feature flag in all environments as deprecated in order to highlight that it can be removed. But I do not remove it yet because we need this PR to be included in a release first.
If we remove the flags right now, we would end up disabling the feature until this PR makes it to production. So we ll keep the flags in for just a couple more weeks.
=> [Feature Cleanup] Remove references in the code to the scroll to top button

run_cdc_tests.sh, server/webdriver/shared_tests/download_test.py, server/webdriver/shared_tests/scatter_test.py
Adds the ability to run a single test file at a time in cdc test. 
I think this change deflaked a test a little but not too sure why...
=> Reduce flake in cdc test that blocked autopush

README.md, server/config/base/header.json, server/config/base/header_v2.json, server/routes/redirects.py, server/routes/static.py, server/templates/custom_dc/stanford/base.html, server/templates/metadata/routes.html, static/js/apps/about/components/stay_in_touch.tsx, static/js/apps/homepage/app.tsx, static/js/apps/homepage/components/home_hero.tsx, static/js/biomedical/landing/data_sources_section.tsx, static/js/biomedical/landing/header_and_search_section.tsx
* Removed links to https://docs.datacommons.org/datasets/ and replaced them with links to https://datacommons.org/data
* Updated legacy https://datacommons.org/datasets/ redirect to point to https://datacommons.org/data
=> Updated data sources link to point to datacommons.org/data

server/webdriver/tests/standalone/sanity.py
Fixes issue where website sanity test was failing when it landed on the new data sources (datacommons.org/data) page.
Updates sanity check to continue skipping the data sources page using its new URL.
=> Updated standalone 'sanity' test to skip data sources page

server/webdriver/tests/place_explorer_test.py, static/js/place/dev_place_overview.tsx
The theme issues have been fixed in https://github.com/datacommonsorg/website/pull/4992
This PR just removes the logic to hide the icon. I ran the command to start the Node JS server and it worked.
=> [Place Page Revamp] Re-adds the AI Icon previously disabled due to Theme issues

server/webdriver/shared_tests/place_explorer_test.py
Custom DC is still using the old place page, so autopush tests started failing since this part of the test assumed it would use the new place page.
=> [Place Page] Reverting test to use logic from legacy place page

deploy/terraform-custom-datacommons/modules/main.tf, deploy/terraform-custom-datacommons/modules/variables.tf
Tested in my local gcp account with a 5s timeout, and the job 'successfully' failed with a timeout error
=> Added cdc data loading job timeout variable

server/lib/nl/explore/params.py, server/lib/nl/fulfillment/base.py, server/routes/explore/helpers.py, static/js/apps/explore/app.tsx, static/js/constants/app/explore_constants.ts
(a) end of the page with default number of charts (10): https://screenshot.googleplex.com/58VcfK6gRud3YhA
(b) the last charts in (a) appear halfway down the page when maxCharts is set to 200: https://screenshot.googleplex.com/Bu3wJUt6TXJ4fef
=> Add NL param for max charts

static/js/components/nl_search_bar/dynamic_placeholder_helper.ts, static/js/i18n/i18n_place_messages.ts, static/js/i18n/strings/en/place.json
Rollback of quote fix from https://github.com/datacommonsorg/website/pull/5035 - it was causing a literal "\\" to show up in the page.
=> rollback of i18n quote fix

deploy/helm_charts/dc_website/templates/deployment.yaml
Verified that autopush and prod node pools have enough memory to support this increase.
=> Increase website container memory from 3G to 4G

static/js/apps/base/components/header_bar/header_bar_search.tsx, static/js/components/nl_search_bar.tsx, static/js/components/nl_search_bar/auto_complete_input.tsx, static/js/components/nl_search_bar/dynamic_placeholder_helper.ts, static/js/shared/ga_events.ts
Make a new event for rendering the search bar with dynamic placeholders since the text value matters on whether it's enabled.
This way we can actually compare the # of events for the search bar being rendered , and the number of events being rendered with dynamic placeholders. And we can compare that ratio to the number of explore_search_q events.
This also propagates whether the dynamic placeholders are enabled all the way to the onSearch trigger such that we don't miscount when the placeholder is hidden due to the query.
=> [Dynamic Placeholder] Improve Google Analytics for dynamic placeholders

server/app_env/_base.py, server/app_env/dev.py, server/routes/static.py
Adds a new config variable (DISABLE_CRAWLERS) which disables all crawlers access to content within the entire site. 
This is set to False by default in the Base Config and only set to True for the Dev Config.
Screenshots of robots.txt when running locally: 
DISABLE_CRAWLERS == False: 
DISABLE_CRAWLERS == True:
=> Disable web crawlers (GoogleBot) on dev

server/routes/experiments/biomed_nl/api.py, static/js/apps/biomed_nl/app.tsx
=> [biomed_nl] Add error messages for no entities detected or traversal error.

server/routes/static.py
Tested with LocalConfig.USE_MEMCACHE=True with DISABLE_CRAWLERS both True and False to ensure both options work with this new approach.
=> Fix caching issue for robots.txt

server/webdriver/shared_tests/place_explorer_i18n_test.py
Legacy place page test fix for a data update. I removed the check since we'll be deprecating the legacy place page soon.
Before data update (prod):  https://screenshot.googleplex.com/A6q3L72gcK9UpBZ
After data update (autopush): https://screenshot.googleplex.com/8KTCBm57pqemY2r
=> Updated legacy place page test to account for new wikidata updata

server/lib/nl/detection/llm_api.py
The llm api call started getting this error complaining about the model version we were trying to use: https://screenshot.googleplex.com/B9gXbaNpz2FqCuT
=> Update model version used for llm fallback

server/webdriver/tests/place_explorer_test.py, static/js/place/dev_place_main.tsx
=> Fixed bug where place page header link was keeping the category param instead of redirecting to the overview page

server/config/base/footer.json, server/config/base/header.json, server/routes/place/html.py, server/templates/custom_dc/stanford/base.html, server/templates/dev_place.html, server/templates/metadata/routes.html, server/templates/place_landing.html, server/tests/routes/place_test.py, server/webdriver/shared_tests/place_explorer_i18n_test.py, server/webdriver/shared_tests/place_explorer_test.py, static/js/place/dev_place_main.tsx
- Added a new route to handle the place explorer landing page and google search redirects
- Updated logic flow handle new place page rendering first, and legacy place page by exception
- Added redirect handling to new place page to:
- strip trailing slashes (`/place/Earth/` redirects to `/place/Earth`)
- redirect legacy categories to new categories (`?category=Climate` redirects to `?category=Environment`)
- to redirect legacy 'topic' param to use new 'category' param (we still get quite a bit of traffic using the legacy `topic=` param in prod - @beets any idea why?)
- Strip out invalid `category=abcdefg` params and redirect to the overview page
- Updated place_test.py redirect test case to use the new dev place page
- Fixed issue where place page "category" wasn't showing up in the …
=> Refactor place page routes, various redirect fixes

packages/client/src/data_commons_client.ts, packages/client/src/data_commons_web_client.ts, server/lib/nl/common/utterance.py, server/lib/nl/config_builder/base.py, server/lib/nl/explore/params.py, server/lib/nl/fulfillment/comparison.py, server/routes/explore/helpers.py, static/js/apps/explore/app.tsx, static/js/apps/explore/highlight_result.tsx, static/js/apps/explore/success_result.tsx, static/js/components/subject_page/block_container.tsx, static/js/components/subject_page/category.tsx, static/js/constants/app/explore_constants.ts, static/js/utils/app/explore_utils.ts, static/js/utils/url_utils.ts
https://github.com/datacommonsorg/website/pull/5114 was reverted in https://github.com/datacommonsorg/website/pull/5141 following a bug being noticed where the query was correct processed but the results were no longer displayed. This was a bug tied to the changes in processFulfillData which is now resolved. I made the SetPageMetadata parameter non-optional to ensure it doesn't happen again.
This PR uses the URL Hash Params to add the ability to pass in multiple places, and pass in one statistical variable.
We inject the chart for the one stat var, and issue a second call to fetch the Topic of said SV, then issue another fulfill call to with the associated topic.
Adds support for multiple StatVars, and multiple Topics on the fulfill call.
Does a very basic merging of the responses.
In …
=> [Attribution] Re-adds ability to inject chart to highlight, with the query fix. 

static/nodejs_server/query.test.ts, static/nodejs_server/query.ts, static/src/server.ts
Update the nodejs endpoint to allow users to specify the detector type for NL detection.
This came up because "What is the most populous state in the US" works on Data Commons website which uses detector=hybrid, but does not work through the nodejs endpoint which uses detector=heuristic. We want to keep the default behavior, but allow a user to specify if they want to use the hybrid detection.
With this change:
- default: [/nodejs/query?q=what%20is%20the%20most%20populous%20state%20in%20the%20us](https://screenshot.googleplex.com/4B6nP8cqA5JznGD)
- with hybrid detection: [/nodejs/query?q=what%20is%20the%20most%20populous%20state%20in%20the%20us&detector=hybrid](https://screenshot.googleplex.com/3ofpz3qK6yHL2mo)
=> update nodejs endpoint to be able to specify detector

deploy/helm_charts/envs/datagemma.yaml, server/app_env/datagemma.py
Recently made a change to allow the nodejs api to use hybrid/llm mode in the NL search (https://github.com/datacommonsorg/website/pull/5145). However, in order to actually use the llm mode, the instance needs to have a secret project defined and need to turn on the flag USE_LLM
=> Update datagemma instance flask config

server/webdriver/shared_tests/explore_test.py
Use the Base component's title string to differentiate between Custom & Base DC.
=> CDC Autopush Webdriver test fix.

server/routes/nl/api.py, server/services/datacommons.py, server/tests/services/datacommons_test.py
* The `search-vector` endpoint currently returns a mix of topics and SVs. This change is to support a param that returns only the latter.
* Verified locally by bringing up the website and NL servers and making the `search-vector` call with and without `skip_topics`.
=> Add support for a skip_topics param to the search-vector endpoint.

docs/feature_flags.md, static/js/shared/feature_flags/util.test.ts, static/js/shared/feature_flags/util.ts
Added ability to manually enable feature flags using a new `enable_feature` URL parameter.
From the updated `docs/feature_flags.md`:
Feature flags can be enabled manually on any datacommons.org page using the `enable_feature` URL parameter.
For example, to enable the "autocomplete" feature:
- Enable: https://datacommons.org/explore?enable_feature=autocomplete
To enable both the autocomplete and metadata_modal features:
- Disable: https://datacommons.org/explore?enable_feature=autocomplete&enable_feature=metadata_modal
These URL overrides take precedence over the environment-specific feature flag settings defined in server/config/feature_flag_configs/<environment>.json
=> Added feature flag URL override

server/lib/nl/fulfillment/basic.py, static/js/apps/explore/app.tsx, static/js/apps/explore/explore_utils.ts, static/js/utils/app/explore_utils.ts, static/js/utils/explore_utils.ts
This PR does two main things for improving the chart injection work:
For single chart injection, it would show the proper chart + a chart for the contained in places. This PR removes that part of the code. Whenever we have that chartType URL parameter, we filter out any additional contained_in logic for chart generation.
For all charts, since we duplicated the call to fulfill while restricting to a single stat var, that chart will appear in the highlight chart + the regular response. so I implemented the logic to remove any duplicate blocks from the non-highlight block.
Examples:
Before: https://screenshot.googleplex.com/BtvrNX3hHEGaBjv
After: https://screenshot.googleplex.com/9WF3EDSQLVtEZn9
Note the contained in block is gone, and the duplicate first chart is gone.
=> [Chart Injection] Make the highlight Response only show the highlighted chart + Remove the matching chart from the non-highlight response.

static/js/shared/ga_events.test.tsx, static/js/shared/ga_events.ts, static/js/stat_var_hierarchy/stat_var_group_node.tsx, static/js/stat_var_hierarchy/stat_var_hierarchy.tsx
Adds Google Analytics events to track user browsing StatVar. 
- One event is fired when the user clicks on any toggles in the StatVar hierarchy. Note that this fires both when the toggle is opened OR closed (I thought it would be relevant to track both opening and closing the toggle since they both reflect user browsing, but lmk if you disagree with this). 
- The other change updates the existing event `GA_EVENT_TOOL_STAT_VAR_CLICK` which currently fires whenever a stat var is selected. I added a parameter here to track whether the stat var was selected directly from the hierarchy or through searching. 
- While testing this change I also noticed that the event is currently also fired whenever the user clears the current search query …
=> Add usage metrics for StatVar browsing

server/webdriver/shared_tests/vis_timeline_test.py, static/js/components/tiles/line_tile.tsx, static/js/utils/data_fetch_utils.ts
This PR re-adds the facetIds parameter for fetching source series. these are still used by the web components from the viztools. Removing it previously broke the facet selection. 
Added a webdriver test to prevent future breakages.
=> [VisTool Fix] Fix facet selection in vis tools

server/webdriver/shared_tests/explore_test.py, static/js/apps/explore/app.tsx
Allow the hashparams to be provided as URL parameters. The "?" separator is the preferred standard today, we plan on supporting both for now and trying to migrate everything to the using URL params over hash params in the future.
=> [Chart Injection] Adds support for "?" as URL parameter separator

server/webdriver/shared_tests/timeline_test.py
We used to check the exact chart count which may be subject to changes on dataset updates. Changed it for this test to just ensure charts are present.
=> [Autopush CDC webdriver fix] Minor update to test

server/webdriver/shared_tests/explore_test.py, static/js/apps/explore/app.tsx, static/js/apps/explore/highlight_result.tsx, static/js/apps/explore/success_result.tsx, static/js/tools/shared/metadata/citations.ts, static/js/tools/shared/metadata/metadata_fetcher.ts, static/js/tools/shared/metadata/tile_metadata_modal.tsx, static/js/tools/shared/metadata/tile_metadata_modal_content.tsx
Adds the provenance name, source name and some text about DC processing on the Block description for the highlight chart.
This refactors some of the code to fetch the metadata from the show Metadata modal to make it shareable.
http://localhost:8080/explore#sv=LifeExpectancy_Person&p=country%2FITA___country/FRA&client=ui_related_topic&chartType=TIMELINE_WITH_HIGHLIGHT&unit=Euro&imp=WorldDevelopmentIndicators ([screenshot](https://screenshot.googleplex.com/7DbYaBYFLvzoRvM))
=> [Chart Injection] Add Metadata Text on chart highlight

static/js/components/subject_page/block.tsx
I noticed this updated logic caused a regression where some queries default to using the per capita value when they should not have. Reverting for now, will find proper way forward later.
Verified fix locally.
=> [Revert Per Capita Change] 

static/css/explore.scss, static/js/apps/explore/follow_up_questions.tsx, static/js/apps/explore/result_header_section.tsx, static/js/apps/explore/success_result.tsx
It is the initial version of the Follow Up Questions Component, displaying up to 10 generated questions at the bottom of the explore page. 
Before: https://screenshot.googleplex.com/87kBdiichniHvtu
After: https://screenshot.googleplex.com/428GmoCvvrzL2ZZ
=> [Explore] Implement the Follow Up Questions Component

tools/nl/nl_metadata/Dockerfile, tools/nl/nl_metadata/add_metadata.py
Add `--maxStatVars` and `--gcsFolder` flags to the `add_metadata.py` script. Also updates the `language` flag to use double dashes instead of single for consistency
=> Add command line flags to metadata script

server/config/feature_flag_configs/autopush.json, server/config/feature_flag_configs/local.json
Updates the `standardized_vis_tool` feature flag to be turned on by default for autopush and local.
Changes made following discussion in PR #5294.
=> Enable standardized visualization tool UI on autopush and local

server/config/feature_flag_configs/autopush.json, server/config/feature_flag_configs/custom.json, server/config/feature_flag_configs/dev.json, server/config/feature_flag_configs/local.json, server/config/feature_flag_configs/staging.json
adds a feature flag. If enabled, relevance threshold for Vertex AI search will be set to MEDIUM.
=> Add feature flag to set MEDIUM relevance threshold for Vertex AI search

static/js/apps/explore/follow_up_questions.tsx, static/js/apps/explore/result_header_section.tsx, static/js/shared/ga_events.test.tsx, static/js/shared/ga_events.ts
- Added a GA event trigger to the initial view of the Related Topics in the Result Header
- Modified the FOLLOW_UP_QUESTIONS_VIEW event to RELATED_TOPICS_VIEW with a support for different modes (Follow Up Questions and Header Related Topics).
=> [Explore] Add component view to the Header Related Topics

server/lib/feature_flags.py, server/routes/shared_api/stats.py, server/tests/routes/api/stats_test.py
Adds the logic for using a feature flag to decide whether to set the Vertex AI search relevance threshold to LOW or MEDIUM. I tested locally and it works, and decided to hold off on adding a unit test for this change since we can't test that the results are filtered without calling the actual VAI endpoint, and being able to fetch/pass in the feature flag seems trivial to test in the stats module.
=> Added controlling relevance threshold for Vertex AI using feature flag

docs/feature_flags.md, server/lib/feature_flags.py, server/tests/lib/feature_flag_test.py, static/js/shared/feature_flags/util.test.ts, static/js/shared/feature_flags/util.ts
Adds a URL override param to manually disable a feature flag.
This is currently necessary to keep tests for production code that have features disabled, while keeping new features enabled by default in autopush.
This PR also:
* Updates the feature flag page in our development guide with changes, a typo fix, and some linting
* Updates the names of some helper functions and constants for clarity.
Testing strategy:
* Added tests for server side feature flag functions
* Added to the current client side tests
* Manually tested locally using `http://localhost:8080/tools/map?disable_feature=standardized_vis_tool`
=> [Feature flags] Add ability to disable flags

static/js/apps/explore/follow_up_questions.tsx, static/js/constants/app/explore_constants.ts
Adds a new client type to help track which queries succeed or fail from the Follow Up Questions component. This helps compile the types of failing queries Gemini would generate which can then be used to fine tune the prompt.
=> [Explore] Add new client type for generated questions

tools/nl/nl_metadata/Dockerfile, tools/nl/nl_metadata/add_metadata.py, tools/nl/nl_metadata/gemini_prompt.py
Makes some adjustments to the Gemini prompt for generating alternative sentences. A full log of improvements can be found in [this doc](https://docs.google.com/document/d/1QuwijuhD2ah-_VxYfz30C-YeDliGVTCi_47HBdr5pJY/edit?usp=sharing&resourcekey=0-mtKPiRpOQwe2ISzS29WcBQ). 
Also separately defines the prompt that includes translating the metadata. This was done in hopes that by giving Gemini a single task to focus on (I.e. generating the sentences), we may see better results since translated metadata is not a priority for now.
=> Improve Gemini prompt for generating alt sentences

static/js/components/elements/button/button.tsx, static/js/tools/shared/tool_header.tsx
Update the "switch tool version" button to use the shared button component instead of custom anchor styling. This allows for the button to follow set theming and standardizes the look with the rest of the buttons on the site.
Screenshot:
=> [Vis Tools] Code Cleanup: refactor switch tool button

nl_server/search.py, nl_server/tests/embeddings_test.py
* The current topic checks were based on a `dc/topic/` prefix.
* However, for custom DCs, topic DCIDs won't be prefixed with that but will *contain* `/topic/`.
+ e.g. one.org's topics are prefixed with `ONE/topic/`
* This PR updates the logic from a prefix match to a contains check.
=> Update topic dcid check so it works for custom DCs

server/config/feature_flag_configs/production.json
Adds the Follow Up Questions feature flags to the production JSON. Specifically, it adds:
- follow_up_questions_experiment: True
This enables the feature in 20% of the pages to begin collecting data for the experiment.
- follow_up_questions_ga: False
This guards the feature for general audience, and it is included to match the feature flags in staging.
=> [Explore] Enable Follow Up Questions experiment

server/webdriver/shared_tests/place_explorer_test.py
Added "Energy" category back to CA place page test to account for EIA data now being back in autopush.
=> fixed ca place page test to account for data update

static/js/apps/explore/page_overview.tsx, static/js/shared/feature_flags/util.ts, static/js/shared/ga_events.test.tsx
Adds a check to the Link feature flag when generating the elements of the page overview. This allows us to control if links are enabled in the experiment without having to wait for a prod release.
Flag enabled:
https://screenshot.googleplex.com/8nAoytMTyMxMndv
Flag disabled:
https://screenshot.googleplex.com/AUHVWd7YfCpuscY
=> [Explore] Check Link Feature Flag for Page Overview

server/lib/gcs.py, server/routes/screenshot/html.py, server/templates/screenshot/home.html
The `server/lib/gcs.list_folder` function uses `end_offset` which is exclusive in the GCS API. This caused an issue in the screenshot viewer where items from the specified end date (which defaults to today) were not being included in the results.
This change addresses the issue by modifying the screenshot endpoint and `list_folder` to make `end_offset` optional and omit it from the call to GCS when it's not provided explicity.
=> Include current day's results in screenshot endpoint by default

deploy/helm_charts/envs/autopush.yaml, deploy/helm_charts/envs/dev.yaml, deploy/helm_charts/envs/prod.yaml, deploy/helm_charts/envs/staging.yaml, docs/redis.md, gke/create_redis.sh, scripts/deploy_gke_helm.sh, tools/clearcache/README.md, tools/clearcache/run.sh
- Update Redis creation and clearing scripts for mixer
- Set traffic mirroring fractions per environment
- Use Redis hosts returned by creation script for each environment
Tested in datcom-website-dev. IAM permissions for datcom-store have been updated so that all environments can access the test Spanner instance.
=> Enable mixer metrics, mirroring, Redis, and V3 + Spanner Graph

server/config/feature_flag_configs/autopush.json, server/config/feature_flag_configs/custom.json, server/config/feature_flag_configs/dev.json, server/config/feature_flag_configs/local.json, server/config/feature_flag_configs/staging.json
Flag is defined as `enable_stat_var_autocomplete` here: https://github.com/datacommonsorg/website/blob/45c417f3b3e0d842f1e2a25fecbf7422b2f83fda/server/lib/feature_flags.py#L29
=> [sv-autocomplete] Rename flag to match definition

server/routes/shared_api/stats.py
Productionized a new [Vertex AI Search App](https://pantheon.corp.google.com/gen-app-builder/locations/global/engines/full-statvar-search-prod-p_1757437817854/overview/system?e=13803378&mods=-monitoring_api_staging&project=datcom-nl) which is connected to periodic updates from added BigQuery statVars.
This new Vertex AI Search app is connected to a datastore with periodic ingestion on my Cloud Storage bucket. There is a weekly GCP Workflow which triggers a series of Cloud Run Job to run the BigQuery Diff mode of the NL Metadata Generator and output it in the GCS bucket that has periodic ingestion from the data store.
Evals ran against this new VAI App show similar results to the old VAI app.
=> [Vertex AI Search] Change the StatVar Explorer to use the new Vertex AI App with Periodic Updates

static/js/components/nl_search_bar/auto_complete_input.tsx, static/js/components/nl_search_bar/auto_complete_suggestions.tsx, static/js/shared/ga_events.ts
This adds metrics for things such as SV autocompletion selection and trigger. And gives the breakdown with the correct parameters to better understand usage including query at selection, selected stat var and more.
=> [StatVar Autocomplete] Adds Google Analytics events for StatVar autocompletion

static/js/apps/explore_landing/components/stat_var_queries.tsx, static/js/apps/explore_landing/topics.json
Fixes the broken timeline tool links on /explore/equity by:
(1) Switching to new links to the map tool, with more interesting/clear stat vars.
(2) Updating the heading of the section to say "Visualization tool" instead of the Timeline tool.
With this change, the links now go to:
* Gini Index: https://datacommons.org/tools/visualization#visType%3Dmap%26place%3DEarth%26placeType%3DCountry%26sv%3D%7B%22dcid%22%3A%22GiniIndex_EconomicActivity%22%7D
* Electricity Access: https://datacommons.org/tools/visualization#visType%3Dmap%26place%3DEarth%26placeType%3DCountry%26sv%3D%7B%22dcid%22%3A%22sdg%2FEG_ACS_ELEC%22%7D
* Internet Access: https://datacommons.org/tools/visualization#visType%3Dmap%26place%3DEarth%26placeType%3DCountry%26sv%3D%7B%22dcid%22%3A%22sdg%2FIT_USE_ii99%22%7D
* Access to basic …
=> Fix Equity Page Chart Links

static/js/apps/explore/debug_info.tsx
Updates the styling of the "show more" button in our explore debug info to use the standard Data Commons Button component for better readability. The current button is very long and low contrast, so it's unclear it is clickable.
Before:
After:
=> Update debug info button

static/js/apps/base/header_app.tsx, static/js/apps/explore/debug_info.tsx
As a follow up to #5551, moves the theme provider to the application level, and uses the old class name for spacing instead of custom css.
Screenshots:
=> Debug info modal button adjustments

server/webdriver/shared_tests/vis_scatter_test.py, static/js/apps/visualization/main.ts, static/js/apps/visualization/redirect_constants.ts, static/js/apps/visualization/redirect_utils.ts, static/js/apps/visualization/vis_type_selector.tsx, static/js/tools/scatter/app.tsx
This PR implements a redirect from `/tools/visualization#visType=scatter to the equivalent /tools/scatter#` page when the `standardized_vis_tool` flag is enabled.
1. Checkout these changes and spin up a local instance of the website repo
1. Go to `http://localhost:8080/tools/visualization` and click on the 'Scatter Plot` tab. See that you are redirected to the old scatter tool at /tools/scatter.
1. Go to `http://localhost:8080/tools/visualization#visType=scatter` and see that you are redirected to the old scatter tool at /tools/scatter.
1. Go to the original visualization tool landing page by going to `http://localhost:8080/tools/visualization?disable_feature=standardized_vis_tool`
1. Click on the 'Scatter Plot' tab
1. Click through each of the links on the page. If you remove …
=> [Vis Tools] Redirect from /tools/visualization to /tools/scatter
